// bank_gre_quant2.js - Original GRE Quantitative items GQ025-GQ044.
// Second Quantitative increment, weighted toward the harder end so a routed-up section has
// a deep enough pool, and toward Quantitative Comparison, which is the type most students
// have never met before.
const QC2 = ['Quantity A is greater','Quantity B is greater','The two quantities are equal',
             'The relationship cannot be determined from the information given'];
const BANK_GRE_QUANT2 = [
{id:'GQ025',section:'Q',type:'QC',sub:'Quantitative comparison, algebra',skill:'gre_alg',diff:4,
 stem:'x > 1\n\nQuantity A: x + 1 over x\nQuantity B: 2',
 choices:QC2,answer:0,
 expl:'For any positive x other than 1, x plus its reciprocal exceeds 2, because x plus 1 over x minus 2 equals (x minus 1) squared over x, which is positive when x is greater than 1. Quantity A is greater.',
 wrong:'Testing only x equal to 1 gives equality, but the condition excludes it. Test a value strictly inside the allowed range.'},
{id:'GQ026',section:'Q',type:'QC',sub:'Quantitative comparison, averages',skill:'gre_data',diff:3,
 stem:'Set S consists of 5 consecutive even integers.\n\nQuantity A: the mean of S\nQuantity B: the median of S',
 choices:QC2,answer:2,
 expl:'Any evenly spaced set has its mean equal to its median, because the values are symmetric about the middle term. The two quantities are equal.',
 wrong:'Choosing "cannot be determined" misses that the structure fixes the relationship regardless of which five consecutive even integers are chosen.'},
{id:'GQ027',section:'Q',type:'MC',sub:'Exponents',skill:'gre_arith',diff:3,
 stem:'If 2 to the power of x equals 32, what is the value of 2 to the power of (x + 2)?',
 choices:['34','64','96','128','256'],answer:3,
 expl:'2 to the x is 32, so 2 to the (x plus 2) is 32 times 2 squared, which is 32 times 4, or 128.',
 wrong:'Choosing 34 adds 2 to the value rather than to the exponent. Adding to an exponent multiplies the result.'},
{id:'GQ028',section:'Q',type:'MC',sub:'Inequalities',skill:'gre_alg',diff:3,
 stem:'If -3 < x < 5 and 1 < y < 4, which of the following must be true of x - y?',
 choices:['-7 < x - y < 4','-4 < x - y < 1','-2 < x - y < 9','0 < x - y < 20','-7 < x - y < 9'],answer:0,
 expl:'The smallest difference uses the smallest x and the largest y: -3 minus 4 is -7. The largest uses the largest x and the smallest y: 5 minus 1 is 4. So the range is -7 to 4.',
 wrong:'Subtracting the bounds in matching order gives -4 to 1, which misses the extremes. For a difference, pair the smallest with the largest.'},
{id:'GQ029',section:'Q',type:'MC',sub:'Percents',skill:'gre_arith',diff:4,
 stem:'The price of an item rises by 20 percent and then falls by 20 percent. Compared with the original price, the final price is',
 choices:['20 percent lower','4 percent lower','the same','2 percent lower','4 percent higher'],answer:1,
 expl:'1.2 times 0.8 is 0.96, which is 4 percent below the original. The fall applies to a larger base than the rise did.',
 wrong:'Choosing "the same" assumes the percentages cancel, but they are taken on different bases.'},
{id:'GQ030',section:'Q',type:'MC',sub:'Circles',skill:'gre_geo',diff:4,
 stem:'A circle is inscribed in a square of side 10. What is the area of the region inside the square but outside the circle?',
 choices:['25 pi minus 100','50 minus 25 pi','100 minus 25 pi','100 minus 10 pi','100 minus 100 pi'],answer:2,
 expl:'The square has area 100. The inscribed circle has diameter 10, so radius 5 and area 25 pi. The remaining region is 100 minus 25 pi.',
 wrong:'Using 10 as the radius gives 100 pi, which is larger than the square and impossible. The side of the square is the diameter, not the radius.'},
{id:'GQ031',section:'Q',type:'NE',sub:'Numeric entry, ratios',skill:'gre_arith',diff:3,answerType:'spr',
 stem:'A mixture contains water and alcohol in a ratio of 7 to 3. How many litres of alcohol are in 40 litres of the mixture?',
 answer:'12',accept:['12.0'],
 expl:'The mixture is 10 parts, so each part is 4 litres. Alcohol is 3 parts, which is 12 litres.',
 wrong:'Taking 3 tenths of 40 is exactly right; taking 3 sevenths treats the ratio as part to whole rather than part to part.'},
{id:'GQ032',section:'Q',type:'MC',sub:'Probability',skill:'gre_data',diff:4,
 stem:'A fair coin is flipped 3 times. What is the probability of getting exactly two heads?',
 choices:['5 over 8','1 over 8','1 over 4','3 over 8','1 over 2'],answer:3,
 expl:'There are 8 equally likely outcomes and 3 of them have exactly two heads (HHT, HTH, THH), so the probability is 3 over 8.',
 wrong:'Choosing 1 over 4 counts only one arrangement. Exactly two heads can occur in three different orders.'},
{id:'GQ033',section:'Q',type:'QC',sub:'Quantitative comparison, geometry',skill:'gre_geo',diff:4,
 stem:'A triangle has sides of length 5, 12 and x, where x is an integer.\n\nQuantity A: x\nQuantity B: 17',
 choices:QC2,answer:1,
 expl:'The third side must be less than the sum of the other two, so x is less than 17, and greater than the difference, so x exceeds 7. Since x is strictly less than 17, Quantity B is greater.',
 wrong:'Choosing "cannot be determined" misses that the triangle inequality bounds x strictly below 17 for every allowed value.'},
{id:'GQ034',section:'Q',type:'MC',sub:'Sequences',skill:'gre_alg',diff:3,
 stem:'In a sequence, each term after the first is 3 more than the previous term. If the first term is 4, what is the 20th term?',
 choices:['58','61','64','67','70'],answer:1,
 expl:'The nth term is 4 plus 3 times (n minus 1). For n equal to 20 that is 4 plus 57, which is 61.',
 wrong:'Choosing 64 uses 3 times 20 and forgets that only 19 steps separate the first term from the twentieth.'},
{id:'GQ035',section:'Q',type:'MC',sub:'Statistics',skill:'gre_data',diff:4,
 stem:'A set of 6 numbers has a mean of 15. If a seventh number is added and the mean becomes 16, what is the seventh number?',
 choices:['16','18','20','22','24'],answer:3,
 expl:'Six numbers averaging 15 sum to 90. Seven averaging 16 sum to 112. The new number is 112 minus 90, which is 22.',
 wrong:'Choosing 16 assumes the added value equals the new mean, which is only true if the mean does not change.'},
{id:'GQ036',section:'Q',type:'MC',sub:'Coordinate geometry',skill:'gre_geo',diff:3,
 stem:'A line passes through (1, 2) and (5, 14). What is its slope?',
 choices:['2','2.5','3','3.5','4'],answer:2,
 expl:'The change in y is 12 and the change in x is 4, so the slope is 3.',
 wrong:'Reversing the order to get 4 over 12 inverts the slope. Rise goes on top.'},
{id:'GQ037',section:'Q',type:'QC',sub:'Quantitative comparison, arithmetic',skill:'gre_arith',diff:3,
 stem:'n is a positive integer.\n\nQuantity A: the remainder when 5n is divided by 5\nQuantity B: 0',
 choices:QC2,answer:2,
 expl:'5n is a multiple of 5 for every positive integer n, so the remainder is always 0. The quantities are equal.',
 wrong:'Choosing "cannot be determined" treats the presence of a variable as automatic uncertainty, but every allowed value gives the same result.'},
{id:'GQ038',section:'Q',type:'MC',sub:'Word problems',skill:'gre_alg',diff:4,
 stem:'A train travels from A to B at 60 km per hour and returns along the same route at 40 km per hour. What is its average speed for the round trip, in km per hour?',
 choices:['45','48','50','52','55'],answer:1,
 expl:'For equal distances, the average is the harmonic mean: 2 times 60 times 40 divided by 100, which is 48.',
 wrong:'Choosing 50 averages the speeds. More time is spent at the slower speed, so the true average is below the midpoint.'},
{id:'GQ039',section:'Q',type:'NE',sub:'Numeric entry, geometry',skill:'gre_geo',diff:3,answerType:'spr',
 stem:'A square has an area of 49. What is its perimeter?',
 answer:'28',accept:['28.0'],
 expl:'A square of area 49 has side 7, so the perimeter is 4 times 7, which is 28.',
 wrong:'Reporting 49 or 14 confuses area with perimeter or uses only two sides.'},
{id:'GQ040',section:'Q',type:'MC',sub:'Counting',skill:'gre_data',diff:4,
 stem:'How many distinct arrangements can be made from the letters of the word LEVEL?',
 choices:['20','30','60','120','240'],answer:1,
 expl:'LEVEL has 5 letters with L repeated twice and E repeated twice, so the count is 5 factorial divided by 2 factorial times 2 factorial, which is 120 over 4, or 30.',
 wrong:'Choosing 120 treats every letter as distinct and counts identical arrangements more than once.'},
];
