// bank_gre_quant.js - Original GRE Quantitative Reasoning items GQ001-GQ024.
// Four content areas ETS names: Arithmetic, Algebra, Geometry, Data Analysis. Question
// types: Quantitative Comparison (four fixed choices), multiple choice select one (five),
// and Numeric Entry, which reuses the engine's student-produced-response grading so that
// equivalent forms of the same value all count. A basic on-screen calculator is provided on
// the real exam, so items here reward setup rather than arithmetic grinding.
// Numeric answer choices are written in their natural order on purpose and are never
// rotated by src/balance_key.py; answer positions are varied by hand instead.
const QC = ['Quantity A is greater','Quantity B is greater','The two quantities are equal',
            'The relationship cannot be determined from the information given'];
const BANK_GRE_QUANT = [
// ---------- Arithmetic ----------
{id:'GQ001',section:'Q',type:'MC',sub:'Percents',skill:'gre_arith',diff:1,
 stem:'A jacket priced at $80 is discounted by 25 percent, and the discounted price is then reduced by a further 20 percent. What is the final price?',
 choices:['$48','$50','$56','$60','$44'],answer:0,
 expl:'After 25 percent off, the price is 0.75 times 80, which is 60. A further 20 percent off gives 0.8 times 60, which is 48.',
 wrong:'Choosing $44 comes from adding the discounts to 45 percent and taking 55 percent of 80. Successive discounts multiply, they do not add.'},
{id:'GQ002',section:'Q',type:'MC',sub:'Remainders',skill:'gre_arith',diff:3,
 stem:'When the positive integer n is divided by 7, the remainder is 4. What is the remainder when 3n is divided by 7?',
 choices:['1','2','4','5','6'],answer:4,
 expl:'Write n as 7k plus 4. Then 3n is 21k plus 12, and 21k is divisible by 7, so the remainder is the remainder of 12 divided by 7, which is 5.',
 wrong:'Choosing 4 keeps the original remainder unchanged. Multiplying n by 3 multiplies the remainder by 3 before reducing modulo 7.'},
{id:'GQ003',section:'Q',type:'QC',sub:'Quantitative comparison, exponents',skill:'gre_arith',diff:3,
 stem:'Quantity A: 2 to the power of 30\nQuantity B: 3 to the power of 20',
 choices:QC,answer:1,
 expl:'Write both with exponent 10: 2 to the 30 is (2 cubed) to the 10, which is 8 to the 10. 3 to the 20 is (3 squared) to the 10, which is 9 to the 10. Since 9 is greater than 8, Quantity B is greater.',
 wrong:'Choosing "cannot be determined" misses that a common exponent makes the comparison exact. There are no variables here, so the relationship is always determinable.'},
{id:'GQ004',section:'Q',type:'MC',sub:'Ratios',skill:'gre_arith',diff:2,
 stem:'In a club, the ratio of members who play chess to those who do not is 3 to 5. If 24 members play chess, how many members are in the club?',
 choices:['40','48','56','64','72'],answer:3,
 expl:'Three parts correspond to 24 members, so one part is 8. The club is 3 plus 5, which is 8 parts, so 8 times 8 is 64.',
 wrong:'Choosing 40 treats the 5 part alone as the total. The ratio 3 to 5 is part to part, so the whole is 8 parts.'},
{id:'GQ005',section:'Q',type:'NE',sub:'Numeric entry, percents',skill:'gre_arith',diff:2,answerType:'spr',
 stem:'A quantity increases from 250 to 320. By what percent does it increase? Enter your answer as a number without the percent sign.',
 answer:'28',accept:['28.0','28%'],
 expl:'The increase is 70. Divide by the original 250 to get 0.28, which is 28 percent.',
 wrong:'Dividing by the new value 320 gives about 21.9, which answers a different question. Percent change always divides by the original.'},
{id:'GQ006',section:'Q',type:'QC',sub:'Quantitative comparison, number properties',skill:'gre_arith',diff:4,
 stem:'x is an integer and x squared is less than 16.\n\nQuantity A: x\nQuantity B: 0',
 choices:QC,answer:3,
 expl:'x squared less than 16 allows x to be any integer from -3 to 3. Some of those are greater than 0, some are less, so the relationship cannot be determined.',
 wrong:'Choosing "Quantity A is greater" assumes x is positive. The condition permits negative values, and a single counterexample settles it.'},
// ---------- Algebra ----------
{id:'GQ007',section:'Q',type:'MC',sub:'Linear equations',skill:'gre_alg',diff:1,
 stem:'If 4(x - 3) = 2x + 10, what is the value of x?',
 choices:['5','8','11','14','22'],answer:2,
 expl:'Expand to 4x minus 12 equals 2x plus 10. Subtract 2x to get 2x minus 12 equals 10, add 12 to get 2x equals 22, so x is 11.',
 wrong:'Choosing 22 stops at 2x equals 22 and forgets the final division.'},
{id:'GQ008',section:'Q',type:'MC',sub:'Simultaneous equations',skill:'gre_alg',diff:2,
 stem:'If a + b = 10 and a - b = 4, what is the value of ab?',
 choices:['16','21','24','25','40'],answer:1,
 expl:'Adding the equations gives 2a equals 14, so a is 7 and b is 3. Their product is 21.',
 wrong:'Choosing 24 comes from a equals 6 and b equals 4, which satisfies the sum but not the difference.'},
{id:'GQ009',section:'Q',type:'MC',sub:'Quadratics',skill:'gre_alg',diff:3,
 stem:'If x squared minus 7x plus 12 equals 0, what is the sum of the possible values of x?',
 choices:['3','4','7','12','19'],answer:2,
 expl:'The expression factors as (x minus 3)(x minus 4), so the roots are 3 and 4 and their sum is 7. The sum of roots also equals the negative of the x coefficient, which is 7.',
 wrong:'Choosing 12 gives the product of the roots rather than the sum.'},
{id:'GQ010',section:'Q',type:'QC',sub:'Quantitative comparison, inequalities',skill:'gre_alg',diff:4,
 stem:'0 < y < 1\n\nQuantity A: y squared\nQuantity B: y cubed',
 choices:QC,answer:0,
 expl:'For a value strictly between 0 and 1, each further multiplication by y makes the result smaller, so y cubed is less than y squared. Quantity A is greater.',
 wrong:'The intuition that a higher power is larger holds only for values above 1. Testing y equal to one half gives 0.25 against 0.125.'},
{id:'GQ011',section:'Q',type:'MC',sub:'Word problems',skill:'gre_alg',diff:3,
 stem:'A tank is filled by one pipe in 6 hours and by a second pipe in 3 hours. With both pipes open, how many hours does it take to fill the tank?',
 choices:['1','1.5','2','4.5','9'],answer:2,
 expl:'The rates add: one sixth plus one third is one half of the tank per hour, so the tank fills in 2 hours.',
 wrong:'Choosing 4.5 averages the two times. Rates add, times do not.'},
{id:'GQ012',section:'Q',type:'NE',sub:'Numeric entry, functions',skill:'gre_alg',diff:3,answerType:'spr',
 stem:'The function f is defined by f(x) = 2x squared minus 3x plus 1. What is the value of f(4)?',
 answer:'21',accept:['21.0'],
 expl:'2 times 16 is 32, minus 3 times 4 which is 12, plus 1. That gives 32 minus 12 plus 1, which is 21.',
 wrong:'Squaring after multiplying, as in (2 times 4) squared, gives 64 and a wrong result. The exponent applies to x before the coefficient.'},
// ---------- Geometry ----------
{id:'GQ013',section:'Q',type:'MC',sub:'Triangles',skill:'gre_geo',diff:2,
 stem:'A right triangle has legs of length 9 and 12. What is the length of the hypotenuse?',
 choices:['13','14','15','18','21'],answer:2,
 expl:'9 squared plus 12 squared is 81 plus 144, which is 225, and the square root of 225 is 15. This is the 3-4-5 triangle scaled by 3.',
 wrong:'Choosing 21 adds the legs. The hypotenuse is always shorter than the sum of the other two sides.'},
{id:'GQ014',section:'Q',type:'MC',sub:'Circles',skill:'gre_geo',diff:3,
 stem:'A circle has an area of 36 pi. What is its circumference?',
 choices:['6 pi','12 pi','18 pi','36 pi','72 pi'],answer:1,
 expl:'Area pi r squared equals 36 pi gives r squared equals 36, so r is 6. Circumference is 2 pi r, which is 12 pi.',
 wrong:'Choosing 6 pi uses the radius in place of the diameter. Circumference uses 2 pi r, not pi r.'},
{id:'GQ015',section:'Q',type:'QC',sub:'Quantitative comparison, area',skill:'gre_geo',diff:3,
 stem:'A rectangle and a square each have a perimeter of 20.\n\nQuantity A: the area of the square\nQuantity B: the area of the rectangle',
 choices:QC,answer:3,
 expl:'The square has side 5 and area 25. A rectangle with perimeter 20 could be 5 by 5, which is the same square with area 25, or 4 by 6 with area 24. Since equality is possible and so is a smaller rectangle, the relationship cannot be determined.',
 wrong:'Choosing "Quantity A is greater" uses the rule that a square maximises area for a given perimeter, but a square is itself a rectangle, so equality is allowed and the comparison is not strict.'},
{id:'GQ016',section:'Q',type:'MC',sub:'Coordinate geometry',skill:'gre_geo',diff:3,
 stem:'What is the distance between the points (2, 3) and (7, 15) in the xy-plane?',
 choices:['5','12','13','17','25'],answer:2,
 expl:'The horizontal difference is 5 and the vertical difference is 12, so the distance is the square root of 25 plus 144, which is the square root of 169, or 13.',
 wrong:'Choosing 17 adds the differences rather than using the Pythagorean relationship.'},
{id:'GQ017',section:'Q',type:'MC',sub:'Volume',skill:'gre_geo',diff:4,
 stem:'A cylindrical tank has radius 3 and height 10. If its radius is doubled and its height halved, the new volume is what multiple of the original?',
 choices:['one half','the same','twice','three times','four times'],answer:2,
 expl:'Volume is pi r squared h. Doubling the radius multiplies volume by 4, halving the height divides by 2, and 4 divided by 2 is 2.',
 wrong:'Choosing "the same" assumes the two changes cancel, but the radius is squared in the formula and the height is not.'},
// ---------- Data Analysis ----------
{id:'GQ018',section:'Q',type:'MC',sub:'Mean and median',skill:'gre_data',diff:2,
 stem:'The list 4, 7, 7, 10, 22 has a mean of m and a median of d. What is m minus d?',
 choices:['0','1','2','3','5'],answer:3,
 expl:'The sum is 50, so the mean is 10. The middle value of the sorted list is 7, so the median is 7. The difference is 3.',
 wrong:'Choosing 0 assumes mean and median coincide. The large value 22 pulls the mean above the median.'},
{id:'GQ019',section:'Q',type:'MC',sub:'Probability',skill:'gre_data',diff:3,
 stem:'A bag holds 4 red and 6 blue marbles. Two marbles are drawn at random without replacement. What is the probability that both are red?',
 choices:['1 over 5','8 over 45','2 over 5','2 over 15','4 over 25'],answer:3,
 expl:'The first draw is red with probability 4 over 10. With one red gone, the second is red with probability 3 over 9. Multiplying gives 12 over 90, which is 2 over 15.',
 wrong:'Choosing 4 over 25 treats the draws as if the marble were replaced, using 4 over 10 twice.'},
{id:'GQ020',section:'Q',type:'MC',sub:'Counting',skill:'gre_data',diff:3,
 stem:'How many different committees of 3 people can be chosen from a group of 6?',
 choices:['18','20','36','120','216'],answer:1,
 expl:'Order does not matter, so this is 6 choose 3, which is 6 times 5 times 4 divided by 3 times 2 times 1, or 20.',
 wrong:'Choosing 120 counts ordered arrangements. A committee is unordered, so divide by the number of orderings of the 3 chosen.'},
{id:'GQ021',section:'Q',type:'QC',sub:'Quantitative comparison, standard deviation',skill:'gre_data',diff:4,
 stem:'List A: 5, 5, 5, 5\nList B: 2, 4, 6, 8\n\nQuantity A: the standard deviation of List A\nQuantity B: the standard deviation of List B',
 choices:QC,answer:1,
 expl:'Every value in List A is identical, so its standard deviation is 0. List B has spread, so its standard deviation is positive. Quantity B is greater.',
 wrong:'Both lists have a mean of 5, which is irrelevant. Standard deviation measures spread around the mean, not the mean itself.'},
{id:'GQ022',section:'Q',type:'NE',sub:'Numeric entry, averages',skill:'gre_data',diff:3,answerType:'spr',
 stem:'The average of five numbers is 12. If one of the numbers is removed, the average of the remaining four is 10. What was the number removed?',
 answer:'20',accept:['20.0'],
 expl:'Five numbers averaging 12 sum to 60. Four averaging 10 sum to 40. The removed number is 60 minus 40, which is 20.',
 wrong:'Subtracting the averages to get 2 confuses a difference of means with a difference of totals. Convert averages to sums first.'},
{id:'GQ023',section:'Q',type:'MC',sub:'Reading a table',skill:'gre_data',diff:2,
 stem:'A store recorded sales of 120 units in April, 150 in May and 180 in June. June sales were what percent greater than April sales?',
 choices:['60 percent','66 percent','150 percent','33 percent','50 percent'],answer:4,
 expl:'The increase is 60 units on a base of 120, and 60 divided by 120 is 0.5, which is 50 percent.',
 wrong:'Choosing 150 percent reports June as a percent of April rather than the percent increase above it.'},
{id:'GQ024',section:'Q',type:'QC',sub:'Quantitative comparison, rates',skill:'gre_data',diff:4,
 stem:'A car travels 60 miles at 30 miles per hour, then 60 miles at 60 miles per hour.\n\nQuantity A: the average speed for the whole trip\nQuantity B: 45 miles per hour',
 choices:QC,answer:1,
 expl:'The first leg takes 2 hours and the second takes 1 hour, so 120 miles take 3 hours and the average speed is 40 miles per hour. Quantity B is greater.',
 wrong:'Averaging 30 and 60 to get 45 is the trap. Average speed is total distance over total time, and more time is spent at the slower speed.'},
];
