// bank_gre_easy.js - Original GRE items GE001-GE016 at difficulty 1 and 2.
// The GRE routes the second section of each measure up or down on first-section
// performance. A routed-down section still needs a full 15 items, so the easier end of the
// pool has to be deep enough to fill one without repeating. These are genuinely easier
// items, not padding: short sentences with one clear signal word, and quantitative work
// that tests a single step.
const QC_E = ['Quantity A is greater','Quantity B is greater','The two quantities are equal',
              'The relationship cannot be determined from the information given'];
const BANK_GRE_EASY = [
// ---------- Verbal, easier ----------
{id:'GE001',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:1,
 stem:'The road was closed for repairs, so the driver had to find an ______ route.',
 choices:['alternate','expensive','ancient','identical','uneven'],answer:0,
 expl:'A closed road forces a different way around, which is an alternate route.',
 wrong:'Identical would mean the same road, which is closed. The other choices describe the road rather than its relationship to the original.'},
{id:'GE002',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:1,
 stem:'Because the evidence was overwhelming, the jury reached its verdict with unusual ______.',
 choices:['reluctance','speed','difficulty','secrecy','expense'],answer:1,
 expl:'Overwhelming evidence makes the decision easy, so the jury would decide quickly. Because signals agreement, not contrast.',
 wrong:'Reluctance and difficulty fit a weak case, not an overwhelming one, and would need a contrast word like although.'},
{id:'GE003',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:2,
 stem:'Although the museum is small, its collection is remarkably ______, covering four centuries of printmaking.',
 choices:['local','fragile','comprehensive','modern','expensive'],answer:2,
 expl:'Although sets up a contrast with small, and the clause after the blank describes four centuries of coverage. Comprehensive captures that breadth.',
 wrong:'Modern contradicts four centuries. Local and expensive do not contrast with small.'},
{id:'GE004',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:2,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nThe instructions were so ______ that even first-time users finished without help.',
 choices:['lucid','convoluted','plain','lengthy','technical','optional'],answer:[0,2],
 expl:'First-time users finishing unaided means the instructions were easy to follow. Lucid and plain both mean clear.',
 wrong:'Convoluted and technical reverse the meaning. Lengthy and optional have no partner and do not explain the result.'},
{id:'GE005',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:2,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nHer response to the criticism was ______: she neither defended herself nor acknowledged the complaint.',
 choices:['heated','impassive','detailed','unruffled','apologetic','immediate'],answer:[1,3],
 expl:'Neither defending nor acknowledging is showing no reaction. Impassive and unruffled both describe that composure.',
 wrong:'Heated and apologetic are reactions, which the colon rules out. Detailed and immediate have no partner.'},
{id:'GE006',section:'V',type:'RC',sub:'Main idea',skill:'gre_rc',diff:1,
 passage:'Honeybees communicate the location of food by dancing. A returning forager traces a figure-eight pattern on the comb, and the angle of the straight run encodes the direction of the food relative to the sun, while the duration of that run encodes the distance. Other bees follow the dancer closely, then leave the hive and fly directly toward the source.',
 stem:'The passage is primarily concerned with',
 choices:['describing the structure of a honeycomb','comparing honeybee navigation with that of other insects','questioning whether bees can perceive the position of the sun','explaining how honeybees convey the location of food','arguing that bee dances are more precise than once believed'],answer:3,
 expl:'The passage describes the dance and says what its angle and duration encode, then notes other bees fly to the source. That is an explanation of how location is communicated.',
 wrong:'It makes no comparison with other insects and raises no doubt about the bees perceiving the sun.'},
{id:'GE007',section:'V',type:'RC',sub:'Detail',skill:'gre_rc',diff:2,
 passage:'Honeybees communicate the location of food by dancing. A returning forager traces a figure-eight pattern on the comb, and the angle of the straight run encodes the direction of the food relative to the sun, while the duration of that run encodes the distance. Other bees follow the dancer closely, then leave the hive and fly directly toward the source.',
 stem:'According to the passage, the distance to a food source is indicated by',
 choices:['the number of times the figure eight is repeated','how many bees follow the dancer','the position of the dance on the comb','the angle of the straight run','how long the straight run lasts'],answer:4,
 expl:'The passage states that the duration of the straight run encodes the distance, while the angle encodes direction.',
 wrong:'The angle is explicitly assigned to direction, not distance. Repetitions and follower counts are never mentioned.'},
{id:'GE008',section:'V',type:'RC',sub:'Inference',skill:'gre_rc',diff:2,
 passage:'Until the 1960s, museums routinely cleaned old paintings with solvents strong enough to remove the artist\'s final glazes along with the dirt. The practice was defended on the grounds that the brighter surface revealed the original colors. Conservators now use gentler methods and accept a duller result, on the view that a layer the painter applied is part of the painting.',
 stem:'The passage suggests that conservators today and their predecessors differ mainly in',
 choices:['what they consider part of the work itself','the range of solvents available to them','their opinions about which painters are worth restoring','how brightly museums light their galleries','how much dirt they are willing to leave on a painting'],answer:0,
 expl:'The earlier practice removed the artist\'s glazes for brightness; today those glazes are treated as part of the painting. The disagreement is about what counts as the work.',
 wrong:'Availability of solvents is not raised, and the difference is not about which painters matter.'},
// ---------- Quantitative, easier ----------
{id:'GE009',section:'Q',type:'MC',sub:'Percents',skill:'gre_arith',diff:1,
 stem:'What is 15 percent of 240?',
 choices:['24','30','36','40','48'],answer:2,
 expl:'10 percent of 240 is 24 and 5 percent is 12, so 15 percent is 36.',
 wrong:'Choosing 24 stops at 10 percent.'},
{id:'GE010',section:'Q',type:'MC',sub:'Integers',skill:'gre_arith',diff:1,
 stem:'If the sum of three consecutive integers is 48, what is the largest of them?',
 choices:['15','16','17','18','19'],answer:2,
 expl:'Three consecutive integers summing to 48 centre on 16, so they are 15, 16 and 17 and the largest is 17.',
 wrong:'Choosing 16 gives the middle value, which is the average rather than the largest.'},
{id:'GE011',section:'Q',type:'MC',sub:'Linear equations',skill:'gre_alg',diff:1,
 stem:'If 3x - 7 = 20, what is the value of x?',
 choices:['6','7','8','9','13'],answer:4,
 expl:'Add 7 to both sides to get 3x equals 27, then divide by 3 to get x equals 9.',
 wrong:'Choosing 13 divides 20 by 3 and rounds, or adds 7 without dividing. Undo the subtraction first, then the multiplication.'},
{id:'GE012',section:'Q',type:'MC',sub:'Ratios',skill:'gre_alg',diff:2,
 stem:'A recipe uses flour and sugar in a ratio of 5 to 2. If 15 cups of flour are used, how many cups of sugar are needed?',
 choices:['2','4','6','7','10'],answer:2,
 expl:'15 cups of flour is 3 times the 5 part, so sugar is 3 times the 2 part, which is 6 cups.',
 wrong:'Choosing 2 uses the ratio number directly without scaling to the actual quantity.'},
{id:'GE013',section:'Q',type:'MC',sub:'Triangles',skill:'gre_geo',diff:2,
 stem:'Two angles of a triangle measure 45 degrees and 65 degrees. What is the measure of the third angle?',
 choices:['60','65','70','80','110'],answer:2,
 expl:'The angles of a triangle sum to 180, and 45 plus 65 is 110, so the third angle is 70.',
 wrong:'Choosing 110 gives the sum of the two known angles rather than what remains.'},
{id:'GE014',section:'Q',type:'MC',sub:'Area',skill:'gre_geo',diff:1,
 stem:'A rectangle has a length of 12 and a width of 5. What is its area?',
 choices:['17','34','48','60','120'],answer:3,
 expl:'Area is length times width, which is 12 times 5, or 60.',
 wrong:'Choosing 34 computes the perimeter. Choosing 17 adds the two sides.'},
{id:'GE015',section:'Q',type:'MC',sub:'Averages',skill:'gre_data',diff:1,
 stem:'What is the average of 8, 12, 15 and 21?',
 choices:['12','13','14','15','16'],answer:2,
 expl:'The sum is 56 and there are 4 values, so the average is 14.',
 wrong:'Choosing 15 picks a value from the list rather than computing the mean.'},
{id:'GE016',section:'Q',type:'QC',sub:'Quantitative comparison, arithmetic',skill:'gre_data',diff:2,
 stem:'Quantity A: the median of 3, 8, 9, 14, 16\nQuantity B: the mean of 3, 8, 9, 14, 16',
 choices:QC_E,answer:1,
 expl:'The median of the sorted list is 9. The sum is 50, so the mean is 10. Quantity B is greater.',
 wrong:'Assuming mean and median always match is the trap. Compute both; they coincide only for symmetric data.'},
];
