// bank_sat_math5.js - Original SAT Math items SM123-SM136. Fourth increment: takes Math past
// three non-repeating sections and grid-ins to roughly the share the real Math section carries.
const BANK_SAT_MATH5 = [
{id:'SM123',section:'M',type:'SPR',answerType:'spr',sub:'Linear equations in two variables',skill:'m_alg',diff:3,
 stem:'The graph of the line y = mx + 7 passes through the point (3, 1). What is the value of m?',
 choices:[],answer:'-2',
 expl:'Substitute the point: 1 = 3m + 7, so 3m = -6 and m = -2.',
 wrong:'Grid-ins accept a negative sign, so there is no reason to drop it. The line falls from 7 at x = 0 to 1 at x = 3, which confirms the slope is negative.'},
{id:'SM124',section:'M',type:'MC',sub:'Linear inequalities',skill:'m_alg',diff:4,
 stem:'A delivery van can carry at most 1,800 pounds. It is loaded with 340 pounds of equipment plus boxes weighing 55 pounds each. What is the greatest number of boxes it can carry?',
 choices:['26','26.5','27','32'],answer:0,
 expl:'The boxes may weigh at most 1,800 - 340 = 1,460 pounds, and 1,460 divided by 55 is about 26.5. Since a box cannot be split, the greatest whole number is 26.',
 wrong:'Choice C rounds 26.5 up, which puts the van over its limit. When a quantity must be whole and a maximum is in play, always round down.'},
{id:'SM125',section:'M',type:'MC',sub:'Systems of two linear equations',skill:'m_alg',diff:5,
 stem:'A theater sold 240 tickets and collected 3,120 dollars. Adult tickets cost 18 dollars and student tickets cost 8 dollars. How many student tickets were sold?',
 choices:['72','108','120','132'],answer:2,
 expl:'With a adult and s student tickets, a + s = 240 and 18a + 8s = 3,120. Substituting a = 240 - s gives 4,320 - 18s + 8s = 3,120, so 10s = 1,200 and s = 120.',
 wrong:'Choice C is right here, but the standard error is solving for a and reporting it. Label each variable in words before writing the equations, then reread the question.'},
{id:'SM126',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:4,
 stem:'The function f is linear. If f(2) = 11 and f(6) = 3, what is the value of f(0)?',
 choices:['13','15','17','19'],answer:1,
 expl:'The rate of change is (3 - 11)/(6 - 2) = -2 per unit. Going back two units from f(2) = 11 adds 4, so f(0) = 15.',
 wrong:'Choice A moves back only one unit. Count the steps from the point you have to x = 0, and remember that a negative slope means going left raises the value.'},
{id:'SM127',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:4,
 stem:'If (x + 4)^2 = 49 and x is positive, what is the value of x?',
 choices:[],answer:'3',
 expl:'Taking square roots gives x + 4 = 7 or x + 4 = -7, so x = 3 or x = -11. The positive value is 3.',
 wrong:'Expanding first gives x^2 + 8x - 33 = 0, which works but costs time. When a squared binomial is already isolated, take the root and keep both branches.'},
{id:'SM128',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:5,
 stem:'The function f is defined by f(x) = a(x - 3)^2 + k. If f(1) = f(5) = 12 and f(3) = 4, what is the value of a?',
 choices:['1','2','4','8'],answer:1,
 expl:'The vertex is at x = 3, so f(3) = k = 4. Then f(5) = a(2)^2 + 4 = 12 gives 4a = 8 and a = 2. The equal values at x = 1 and x = 5 confirm the vertex sits halfway between them.',
 wrong:'Choice D comes from forgetting to subtract k before dividing. Find k from the vertex first; it is the value the squared term cannot change.'},
{id:'SM129',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:4,
 stem:'Which expression is equivalent to (2x^3 y)^3?',
 choices:['2x^9 y^3','8x^9 y^3','6x^9 y^3','8x^6 y^3'],answer:1,
 expl:'Every factor inside the parentheses is raised to the third power: 2^3 = 8, (x^3)^3 = x^9, and y^3.',
 wrong:'Choice C multiplies the coefficient by 3 instead of cubing it, and choice A leaves it alone entirely. The outer exponent applies to the number as well as the variables.'},
{id:'SM130',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear functions',skill:'m_adv',diff:5,
 stem:'The function g is defined by g(x) = 2x^2 - 12x + 23. What is the minimum value of g?',
 choices:[],answer:'5',
 expl:'The vertex sits at x = -b/(2a) = 12/4 = 3. Then g(3) = 18 - 36 + 23 = 5. Because the leading coefficient is positive, the parabola opens upward and that value is the minimum.',
 wrong:'Answering 3 gives the input where the minimum occurs, not the minimum itself. The question asks for the value of g, which is an output.'},
{id:'SM131',section:'M',type:'MC',sub:'Probability and conditional probability',skill:'m_psda',diff:4,
 stem:'A bag holds 5 red, 7 blue, and 8 green marbles. One marble is drawn at random. What is the probability that it is not green?',
 choices:['3/5','2/5','8/20','12/8'],answer:0,
 expl:'There are 20 marbles in all and 12 that are not green, so the probability is 12/20 = 3/5.',
 wrong:'Choice C is the probability that it is green, which is what the word not exists to reverse. Computing the complement and subtracting from 1 is the safer route.'},
{id:'SM132',section:'M',type:'SPR',answerType:'spr',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:4,
 stem:'A machine fills 3 bottles every 2 seconds. At this rate, how many seconds does it take to fill 270 bottles?',
 choices:[],answer:'180',
 expl:'The rate is 1.5 bottles per second, so 270 divided by 1.5 is 180 seconds. Equivalently, 270 bottles is 90 groups of 3, and each group takes 2 seconds.',
 wrong:'Multiplying 270 by 2 and ignoring the 3 gives 540. Set the units up as a proportion and let them cancel rather than guessing which number to multiply by.'},
{id:'SM133',section:'M',type:'MC',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:5,
 stem:'Two data sets each contain 50 values and have the same mean. Set A has a standard deviation of 3.1 and set B has a standard deviation of 9.4. Which statement must be true?',
 choices:['The largest value in set B is greater than the largest value in set A.','Set B contains more distinct values than set A.','The values in set B are more spread out about the mean than those in set A.','The median of set B is greater than the median of set A.'],answer:2,
 expl:'Standard deviation measures spread about the mean, and nothing else. A larger standard deviation means the values sit farther from the mean on average.',
 wrong:'Choice A is very likely but not guaranteed, and the question asks what must be true. Equal means say nothing about the medians either, which rules out choice D.'},
{id:'SM134',section:'M',type:'MC',sub:'Circles',skill:'m_geo',diff:4,
 stem:'A sector of a circle with radius 12 has a central angle of 30 degrees. What is the area of the sector?',
 choices:['6 pi','12 pi','24 pi','144 pi'],answer:1,
 expl:'The sector is 30/360 = 1/12 of the circle. The full area is 144 pi, so the sector is 12 pi.',
 wrong:'Choice A applies the fraction to the circumference rather than the area. Sector area uses pi r squared; arc length uses 2 pi r.'},
{id:'SM135',section:'M',type:'SPR',answerType:'spr',sub:'Lines, angles, and triangles',skill:'m_geo',diff:4,
 stem:'In a triangle, the second angle measures twice the first and the third measures 20 degrees more than the first. What is the measure, in degrees, of the smallest angle?',
 choices:[],answer:'40',
 expl:'With the first angle x, the angles are x, 2x, and x + 20, summing to 4x + 20 = 180. So x = 40, and the three angles are 40, 80, and 60.',
 wrong:'Answering 60 or 80 reports one of the other angles. Once x is found, compute all three and pick the one the question names.'},
{id:'SM136',section:'M',type:'MC',sub:'Right triangles and trigonometry',skill:'m_geo',diff:5,
 stem:'A ladder leans against a wall, reaching 15 feet up the wall, with its base 8 feet from the wall. What is the length of the ladder, in feet?',
 choices:['17','19','21','23'],answer:0,
 expl:'The wall and the ground meet at a right angle, so the ladder is the hypotenuse: 64 + 225 = 289, whose square root is 17. This is the 8-15-17 triple.',
 wrong:'Choice D adds the two legs. The hypotenuse is always longer than either leg and shorter than their sum, which rules out three of these choices at a glance.'}
];
