// Quant bank 2 (original items). Fields: id, section, type, domain, context, skill, diff, stem, choices, answer (index), expl, wrong (optional)
const BANK_QUANT2 = [
// ---------- q_rrp (12) ----------
{id:'Q101',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:2,
 stem:'Working alone, Priya can mow a certain lawn in 45 minutes, and working alone her brother Dev can mow the same lawn in 90 minutes. If they work together at their constant rates, how many minutes will it take them to mow the lawn?',
 choices:['22.5','27','30','45','67.5'],answer:2,
 expl:'Rates add: 1/45 + 1/90 = 2/90 + 1/90 = 3/90 = 1/30 lawn per minute. Time = 30 minutes.',
 wrong:'E (67.5) is the average of the two times. Together must be faster than the faster worker alone (45), which kills D and E immediately.'},
{id:'Q102',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
 stem:'The price of a share of Corvane Ltd rose 25% in January, fell 20% in February, and then rose 10% in March. The price at the end of March was what percent greater than the price at the start of January?',
 choices:['5%','8%','10%','12%','15%'],answer:2,
 expl:'Multiply the factors: 1.25 x 0.80 x 1.10 = 1.00 x 1.10 = 1.10, a 10% overall increase. Start at 100: 125, then 100, then 110.',
 wrong:'E (15%) adds the percents (25 - 20 + 10). Successive percent changes multiply.'},
{id:'Q103',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
 stem:'A cyclist rides 24 kilometers up a hill at a constant speed of 12 kilometers per hour and then rides back down the same 24 kilometers at a constant speed of 24 kilometers per hour. What is the cyclist\'s average speed, in kilometers per hour, for the round trip?',
 choices:['16','17','18','20','21'],answer:0,
 expl:'Uphill time = 24/12 = 2 h; downhill time = 24/24 = 1 h. Total distance 48 km in 3 h, so average speed = 48/3 = 16 km/h.',
 wrong:'C (18) is the simple average of the two speeds. More time is spent at the slower speed, so the average is pulled below 18.'},
{id:'Q104',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_rrp',diff:3,
 stem:'A grocer has 30 kilograms of a trail mix that is 20% cashews by weight. How many kilograms of a second trail mix that is 50% cashews by weight must be added so that the combined mix is 30% cashews?',
 choices:['6','9','12','15','18'],answer:3,
 expl:'Cashews now: 0.20 x 30 = 6 kg. Add x kg of 50% mix: (6 + 0.5x)/(30 + x) = 0.30, so 6 + 0.5x = 9 + 0.3x, so 0.2x = 3, x = 15.',
 wrong:'Alligation check: distances from 30% are 10 (to 20%) and 20 (to 50%), so the ratio of 20% mix to 50% mix is 2:1, i.e., 30:15.'},
{id:'Q105',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
 stem:'At an investment firm, the ratio of analysts to associates is 5 to 2, and the ratio of associates to vice presidents is 3 to 1. If the firm has 12 vice presidents, how many analysts, associates, and vice presidents does it have in total?',
 choices:['138','161','184','207','230'],answer:0,
 expl:'Combine ratios through associates: analysts:associates = 15:6 and associates:VPs = 6:2, so analysts:associates:VPs = 15:6:2. VPs = 12 means the multiplier is 6, so total = (15 + 6 + 2) x 6 = 23 x 6 = 138.',
 wrong:'Scale the two ratios so the shared term (associates) matches before combining.'},
{id:'Q106',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
 stem:'Renata deposits $5,000 in an account that pays 8% annual interest compounded semiannually. How much more interest will she earn in the first year than she would have earned if the account paid 8% simple annual interest?',
 choices:['$4','$8','$16','$40','$80'],answer:1,
 expl:'Semiannual: 4% per half-year, so 5000 x 1.04^2 = 5000 x 1.0816 = 5408, interest $408. Simple: 5000 x 0.08 = $400. Difference = $8.',
 wrong:'The extra interest is just interest on the first half-year\'s interest: 4% of $200 = $8.'},
{id:'Q107',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:4,
 stem:'Pipe A alone can fill an empty tank in 4 hours and pipe B alone can fill it in 6 hours. Drain C alone can empty the full tank in 3 hours. The tank starts empty; pipes A and B are opened at the same time, and drain C is opened exactly 1 hour later. How many hours after A and B are opened will the tank be full?',
 choices:['8','9','10','12','20'],answer:0,
 expl:'A + B fill 1/4 + 1/6 = 5/12 per hour, so after 1 hour the tank is 5/12 full. With C open the net rate is 5/12 - 1/3 = 5/12 - 4/12 = 1/12 per hour. Remaining 7/12 takes 7 hours. Total = 1 + 7 = 8 hours.',
 wrong:'Forgetting the first hour without the drain (using net rate 1/12 for the whole tank) gives 12 hours, choice D.'},
{id:'Q108',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:4,
 stem:'A retailer bought a shipment of identical lamps for a total of $2,400. She sold three-fourths of the lamps at a price 30% above her cost per lamp and sold the remaining lamps at a price 20% below her cost per lamp. Her total profit was what percent of her total cost?',
 choices:['10%','12.5%','15%','17.5%','20%'],answer:3,
 expl:'Cost of first group: 3/4 x 2400 = 1800, sold for 1800 x 1.3 = 2340. Cost of the rest: 600, sold for 600 x 0.8 = 480. Revenue 2820, profit 420, and 420/2400 = 17.5%.',
 wrong:'Weighted average of the percent changes: 0.75 x 30 + 0.25 x (-20) = 22.5 - 5 = 17.5. Do not simply average 30 and -20 to get 5%.'},
{id:'Q109',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:4,
 stem:'On a road trip, a driver covered the first one-third of the total distance at an average speed of 40 miles per hour and the remaining distance at an average speed of 60 miles per hour. What was the driver\'s average speed, in miles per hour, for the entire trip?',
 choices:['50','51 3/7','52','53 1/3','55'],answer:1,
 expl:'Pick total distance 120 miles. First 40 miles at 40 mph = 1 h; remaining 80 miles at 60 mph = 4/3 h. Total 7/3 h. Average = 120/(7/3) = 360/7 = 51 3/7 mph.',
 wrong:'D (53 1/3) is the distance-weighted average of speeds. Average speed is total distance over total time; A (50) is the plain average of the speeds.'},
{id:'Q110',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_rrp',diff:4,
 stem:'A company\'s revenue increased by p percent from 2022 to 2023 and then decreased by p percent from 2023 to 2024. If the company\'s revenue in 2024 was 9% less than its revenue in 2022, what is the value of p?',
 choices:['3','9','10','30','45'],answer:3,
 expl:'(1 + p/100)(1 - p/100) = 1 - (p/100)^2 = 0.91, so (p/100)^2 = 0.09, p/100 = 0.3, p = 30. Check: 100 -> 130 -> 91.',
 wrong:'B (9) treats the loss as if it were p itself; the net loss from an up-then-down move is the square of the fractional change.'},
{id:'Q111',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_rrp',diff:4,
 stem:'Two inlet pipes fill a swimming pool. Alone, the larger pipe fills the empty pool in x hours, and alone the smaller pipe fills it in x + 5 hours. Together the two pipes fill the empty pool in 6 hours. What is the value of x?',
 choices:['6','8','10','12','15'],answer:2,
 expl:'1/x + 1/(x+5) = 1/6. Multiply by 6x(x+5): 6(x+5) + 6x = x^2 + 5x, so x^2 - 7x - 30 = 0, (x - 10)(x + 3) = 0, x = 10. Check: 1/10 + 1/15 = 5/30 = 1/6.',
 wrong:'Back-solve: x must exceed 6 (the combined time), eliminating A. Try C: 1/10 + 1/15 = 1/6. Done.'},
{id:'Q112',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_rrp',diff:5,
 stem:'Working together at their constant rates, Ana and Ben can paint a fence in 2 hours. Working alone, Ana would need 3 hours less than Ben would need alone. If Ana had painted alone for 1 hour and then stopped, and Ben had then finished the fence by himself, how many hours in total would the job have taken?',
 choices:['4','4.5','5','6','7'],answer:2,
 expl:'Let Ana take a hours alone, Ben a + 3. 1/a + 1/(a+3) = 1/2 gives 2(2a + 3) = a^2 + 3a, so a^2 - a - 6 = 0, (a - 3)(a + 2) = 0, a = 3, Ben = 6. Ana does 1/3 in her hour; Ben finishes 2/3 at 1/6 per hour, taking 4 hours. Total 1 + 4 = 5 hours.',
 wrong:'D (6) is Ben\'s solo time; the question asks for the total elapsed time of the two-stage plan.'},
// ---------- q_alg (12) ----------
{id:'Q113',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:2,
 stem:'Maya is currently 4 times as old as her son. In 12 years, Maya will be exactly twice as old as her son. How old is her son now?',
 choices:['4','6','8','10','12'],answer:1,
 expl:'Let son = s, Maya = 4s. 4s + 12 = 2(s + 12), so 4s + 12 = 2s + 24, 2s = 12, s = 6.',
 wrong:'Remember to add 12 to both ages, not just to Maya\'s.'},
{id:'Q114',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:2,
 stem:'If 3^(2x - 1) = 81, what is the value of x?',
 choices:['0.5','1.5','2','2.5','3'],answer:3,
 expl:'81 = 3^4, so 2x - 1 = 4, 2x = 5, x = 2.5.',
 wrong:'C (2) comes from setting 2x = 4 and ignoring the -1 in the exponent.'},
{id:'Q115',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:3,
 stem:'A community theater sold 150 tickets to a play for a total of $1,400. Adult tickets cost $12 each and child tickets cost $7 each. How many adult tickets were sold?',
 choices:['40','50','60','65','70'],answer:4,
 expl:'Let a = adult tickets, 150 - a = child tickets. 12a + 7(150 - a) = 1400, so 5a + 1050 = 1400, 5a = 350, a = 70. Check: 70 x 12 + 80 x 7 = 840 + 560 = 1400.',
 wrong:'If all 150 were child tickets the total would be $1,050; each swap to an adult ticket adds $5, and 350/5 = 70.'},
{id:'Q116',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
 stem:'How many integers x satisfy the inequality |2x - 5| < 7?',
 choices:['5','6','7','8','12'],answer:1,
 expl:'-7 < 2x - 5 < 7, so -2 < 2x < 12, so -1 < x < 6. Integers 0, 1, 2, 3, 4, 5: six of them.',
 wrong:'The endpoints -1 and 6 are excluded because the inequality is strict; including them gives 8 (D).'},
{id:'Q117',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:3,
 stem:'A small bakery\'s weekly cost, in dollars, to produce n specialty cakes is given by C(n) = 250 + 12n, and it sells every cake it produces for $20. What is the least number of cakes the bakery must produce and sell in a week in order to earn a profit?',
 choices:['26','28','30','31','32'],answer:4,
 expl:'Profit = 20n - (250 + 12n) = 8n - 250 > 0, so n > 31.25. The least integer is 32. Check: n = 31 gives 8 x 31 - 250 = -2 (loss); n = 32 gives +6.',
 wrong:'D (31) rounds 31.25 down; at 31 cakes the bakery still loses $2.'},
{id:'Q118',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
 stem:'If f(x) = 2x + 3 and g(x) = x^2 - 1, what is the value of f(g(2)) - g(f(2))?',
 choices:['-39','-15','0','15','39'],answer:0,
 expl:'g(2) = 3, so f(g(2)) = 2 x 3 + 3 = 9. f(2) = 7, so g(f(2)) = 49 - 1 = 48. Difference: 9 - 48 = -39.',
 wrong:'E (39) reverses the order of subtraction; composition order matters, so f(g(2)) and g(f(2)) are different numbers.'},
{id:'Q119',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:4,
 stem:'The length of a rectangular garden is 3 meters more than twice its width. If the area of the garden is 65 square meters, what is its perimeter, in meters?',
 choices:['18','26','32','36','65'],answer:3,
 expl:'w(2w + 3) = 65, so 2w^2 + 3w - 65 = 0, (2w + 13)(w - 5) = 0, w = 5, length = 13. Perimeter = 2(5 + 13) = 36.',
 wrong:'A (18) is length plus width, only half the perimeter. Factor pairs of 65 (5 x 13) make guessing fast.'},
{id:'Q120',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:4,
 stem:'If x + 1/x = 5, what is the value of x^3 + 1/x^3?',
 choices:['100','110','115','120','125'],answer:1,
 expl:'(x + 1/x)^3 = x^3 + 1/x^3 + 3(x + 1/x). So 125 = x^3 + 1/x^3 + 15, giving x^3 + 1/x^3 = 110.',
 wrong:'E (125) forgets the cross terms 3x + 3/x when cubing the sum.'},
{id:'Q121',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:4,
 stem:'A parking meter contains only quarters and dimes. It holds 140 coins with a total value of $23.75. How many quarters does it contain?',
 choices:['45','55','60','65','75'],answer:3,
 expl:'Let q = quarters, 140 - q = dimes. 25q + 10(140 - q) = 2375, so 15q + 1400 = 2375, 15q = 975, q = 65. Check: 65 x 25 + 75 x 10 = 1625 + 750 = 2375.',
 wrong:'E (75) is the number of dimes, not quarters.'},
{id:'Q122',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:4,
 stem:'How many integers x satisfy both x^2 - 9x + 14 < 0 and |x - 6| >= 2?',
 choices:['0','1','2','3','4'],answer:2,
 expl:'x^2 - 9x + 14 = (x - 2)(x - 7) < 0 means 2 < x < 7, so x is in {3, 4, 5, 6}. |x - 6| >= 2 means x <= 4 or x >= 8. Both: x = 3 or 4. Two integers.',
 wrong:'E (4) counts only the quadratic condition and ignores the absolute value restriction.'},
{id:'Q123',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:5,
 stem:'For how many integer values of x is |x - 3| + |x + 2| = 5?',
 choices:['0','1','2','5','6'],answer:4,
 expl:'|x - 3| + |x + 2| is the total distance from x to 3 and to -2. That total equals 5 (the distance between -2 and 3) exactly when x lies between them: -2 <= x <= 3. Integers -2, -1, 0, 1, 2, 3: six values.',
 wrong:'C (2) comes from assuming only the endpoints -2 and 3 work; every point between the two anchors also gives a sum of 5.'},
{id:'Q124',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:5,
 stem:'A vendor sells a certain gadget for p dollars per unit and takes in $2,400 in revenue. If she had lowered the price by $4 per unit, she would have sold 50 more units and taken in the same $2,400. What is the value of p?',
 choices:['12','16','20','24','30'],answer:1,
 expl:'Let n = units at price p, so pn = 2400 and (p - 4)(n + 50) = 2400. Expand: pn + 50p - 4n - 200 = 2400, so 50p - 4n = 200. Substitute n = 2400/p: 50p - 9600/p = 200, so p^2 - 4p - 192 = 0, (p - 16)(p + 12) = 0, p = 16. Check: 16 x 150 = 2400 and 12 x 200 = 2400.',
 wrong:'Back-solve with the choices: p = 16 gives 150 units, p - 4 = 12 gives 200 units, exactly 50 more.'},
// ---------- q_vof (8) ----------
{id:'Q125',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:2,
 stem:'What is the least common multiple of 84 and 126?',
 choices:['42','126','252','504','10,584'],answer:2,
 expl:'84 = 2^2 x 3 x 7 and 126 = 2 x 3^2 x 7. LCM takes the highest power of each prime: 2^2 x 3^2 x 7 = 252.',
 wrong:'A (42) is the GCF, and E (10,584) is the product of the two numbers.'},
{id:'Q126',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_vof',diff:3,
 stem:'Three shuttle buses leave a hotel at the same time at 9:00 a.m. and then depart again every 12 minutes, every 18 minutes, and every 30 minutes, respectively. At what time will all three buses next depart together?',
 choices:['10:30 a.m.','11:00 a.m.','11:30 a.m.','12:00 noon','1:00 p.m.'],answer:3,
 expl:'LCM(12, 18, 30): 12 = 2^2 x 3, 18 = 2 x 3^2, 30 = 2 x 3 x 5, so LCM = 2^2 x 3^2 x 5 = 180 minutes = 3 hours. 9:00 + 3:00 = 12:00 noon.',
 wrong:'B (11:00) uses 120 minutes, the LCM of only 12 and 30 combined with 18 incorrectly.'},
{id:'Q127',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:3,
 stem:'What is the remainder when 7^26 is divided by 5?',
 choices:['0','1','2','3','4'],answer:4,
 expl:'Units digits of powers of 7 cycle 7, 9, 3, 1 (period 4). 26 = 4 x 6 + 2, so 7^26 ends in 9. A number ending in 9 leaves remainder 4 when divided by 5.',
 wrong:'Equivalent: 7 = 2 (mod 5), and 2^26 = (2^4)^6 x 2^2 = 1 x 4 = 4 (mod 5).'},
{id:'Q128',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_vof',diff:4,
 stem:'When a certain number of marbles is divided equally among 8 children, 5 marbles are left over. When the same marbles are divided equally among 6 children, 3 marbles are left over. How many possible values are there for the number of marbles if it is between 100 and 200?',
 choices:['3','4','5','6','8'],answer:1,
 expl:'n = 5 (mod 8) and n = 3 (mod 6). List 5, 13, 21, ...: 21 = 3 (mod 6), so n = 21 (mod 24) since LCM(8, 6) = 24. Between 100 and 200: 117, 141, 165, 189. Four values.',
 wrong:'Note the pattern repeats every LCM(8, 6) = 24, not every 48.'},
{id:'Q129',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:4,
 stem:'How many positive divisors of 360 are even?',
 choices:['6','12','15','18','24'],answer:3,
 expl:'360 = 2^3 x 3^2 x 5. Total divisors = 4 x 3 x 2 = 24. Odd divisors use no factor of 2: 3 x 2 = 6. Even divisors = 24 - 6 = 18.',
 wrong:'E (24) is the total number of divisors; A (6) is the number of odd divisors.'},
{id:'Q130',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:4,
 stem:'If a = 2^30, b = 3^20, and c = 5^12, which of the following correctly orders a, b, and c from least to greatest?',
 choices:['a < b < c','a < c < b','b < a < c','c < b < a','c < a < b'],answer:4,
 expl:'Rewrite with a common exponent. Using exponent 10: a = (2^3)^10 = 8^10 and b = (3^2)^10 = 9^10, so a < b. Compare c with a using exponent 6: a = (2^5)^6 = 32^6 and c = (5^2)^6 = 25^6, so c < a. Order: c < a < b.',
 wrong:'Bigger base does not mean bigger value when exponents differ; rewrite with a common exponent (here 10) before comparing.'},
{id:'Q131',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:4,
 stem:'What is the greatest integer k such that 12^k is a divisor of 30! (30 factorial)?',
 choices:['7','10','13','14','26'],answer:2,
 expl:'12^k = 2^(2k) x 3^k. Powers of 2 in 30!: 15 + 7 + 3 + 1 = 26. Powers of 3: 10 + 3 + 1 = 14. Need 2k <= 26 (k <= 13) and k <= 14, so k = 13.',
 wrong:'D (14) counts only the 3s. Each 12 needs two 2s, and the 2s run out first.'},
{id:'Q132',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_vof',diff:5,
 stem:'A bakery has fewer than 250 cookies. If it packs them in boxes of 12, 7 cookies are left over; if it packs them in boxes of 9, 4 are left over; and if it packs them in boxes of 5, none are left over. How many cookies does the bakery have?',
 choices:['31','55','103','139','175'],answer:4,
 expl:'n = 7 (mod 12): 7, 19, 31, 43, ... Of these, n = 4 (mod 9) first at 31 (31 = 27 + 4), and the pattern repeats every LCM(12, 9) = 36: 31, 67, 103, 139, 175, 211, 247. The first that is a multiple of 5 is 175. Check: 175 = 14 x 12 + 7, 175 = 19 x 9 + 4, 175 = 35 x 5.',
 wrong:'C (103) and D (139) satisfy the first two conditions but are not multiples of 5.'},
// ---------- q_csp (8) ----------
{id:'Q133',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:2,
 stem:'Of the 60 students in a class, 35 are studying French, 28 are studying Spanish, and 8 are studying neither language. How many students are studying both French and Spanish?',
 choices:['11','15','19','23','27'],answer:0,
 expl:'Students studying at least one language: 60 - 8 = 52. French + Spanish - Both = 52, so 35 + 28 - Both = 52, Both = 11.',
 wrong:'Forgetting the "neither" group and setting 35 + 28 - Both = 60 gives 3, which is not offered.'},
{id:'Q134',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_csp',diff:2,
 stem:'The average (arithmetic mean) of five numbers is 20. If four of the numbers are 12, 18, 25, and 30, what is the fifth number?',
 choices:['15','17','20','21','25'],answer:0,
 expl:'Sum of five numbers = 5 x 20 = 100. Sum of the four given = 85. Fifth number = 15.',
 wrong:'Do not average the four given numbers (about 21); the missing value must bring the total to 100.'},
{id:'Q135',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:3,
 stem:'On a certain exam, the 20 students in Section A had an average (arithmetic mean) score of 80, and the 30 students in Section B had an average score of 70. What was the average score of all 50 students?',
 choices:['72','74','75','76','78'],answer:1,
 expl:'Total points = 20 x 80 + 30 x 70 = 1600 + 2100 = 3700. Average = 3700/50 = 74.',
 wrong:'C (75) is the unweighted midpoint; the larger section pulls the average toward 70.'},
{id:'Q136',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:3,
 stem:'A committee of 3 people is to be selected from a group of 7 people. Two of the seven, Lena and Marcus, refuse to serve on the committee together. How many different committees are possible?',
 choices:['10','20','25','30','35'],answer:3,
 expl:'Total committees: C(7,3) = 35. Committees containing both Lena and Marcus: choose the third member from the other 5, so 5. Allowed: 35 - 5 = 30.',
 wrong:'B (20) is C(6,3), which wrongly removes one of the two people entirely.'},
{id:'Q137',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:3,
 stem:'A bag contains 4 red marbles and 6 blue marbles. If two marbles are drawn at random without replacement, what is the probability that at least one of them is red?',
 choices:['1/3','2/5','2/3','11/15','4/5'],answer:2,
 expl:'P(no red) = (6/10)(5/9) = 30/90 = 1/3. P(at least one red) = 1 - 1/3 = 2/3.',
 wrong:'B (2/5) is just P(first is red); "at least one" is easiest via the complement.'},
{id:'Q138',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_csp',diff:4,
 stem:'In a sequence, a_1 = 1 and a_n = a_(n-1) + 2n for every integer n > 1. What is the value of a_10?',
 choices:['55','90','100','101','109'],answer:4,
 expl:'a_n = 1 + (4 + 6 + ... + 2n) = 1 + 2(2 + 3 + ... + n) = 1 + 2(n(n+1)/2 - 1) = n^2 + n - 1. So a_10 = 100 + 10 - 1 = 109. Check small terms: a_2 = 5, a_3 = 11.',
 wrong:'C (100) is n^2, which would be the answer if a_1 were 1 and the step were 2n - 1.'},
{id:'Q139',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_csp',diff:5,
 stem:'A fair coin is tossed 5 times. What is the probability that exactly 3 of the tosses are heads and no two heads occur on consecutive tosses?',
 choices:['1/32','3/32','5/32','5/16','1/2'],answer:0,
 expl:'There are 2^5 = 32 equally likely sequences. Three heads among 5 tosses with no two adjacent forces the pattern H T H T H, the only such sequence. Probability = 1/32.',
 wrong:'D (5/16 = 10/32) is the probability of exactly 3 heads with no adjacency restriction.'},
{id:'Q140',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:5,
 stem:'In a survey of 100 people, 50 said they like brand A, 45 like brand B, and 40 like brand C. Exactly 20 people like exactly two of the three brands, and 10 people like all three brands. How many of the people surveyed like none of the three brands?',
 choices:['5','10','15','20','25'],answer:0,
 expl:'Adding the three counts double-counts the "exactly two" group and triple-counts the "all three" group: 50 + 45 + 40 = 135 = (exactly one) + 2(20) + 3(10), so exactly one = 65. At least one = 65 + 20 + 10 = 95. None = 100 - 95 = 5.',
 wrong:'Using |A u B u C| = 135 - 20 - 2(10) = 95 gives the same result; the trap is subtracting the "exactly two" total as if it were the sum of pairwise overlaps.'}
];
