// bank_sat_math3.js - Original SAT Math items SM067-SM100. Second increment, weighted toward
// student-produced responses: grid-ins are roughly a quarter of the real Math section and were
// under-represented in the first pass.
const BANK_SAT_MATH3 = [
// ---------- Algebra ----------
{id:'SM067',section:'M',type:'SPR',answerType:'spr',sub:'Linear equations in one variable',skill:'m_alg',diff:2,
 stem:'If 4(x - 3) = 20, what is the value of x?',
 choices:[],answer:'8',
 expl:'Divide both sides by 4 to get x - 3 = 5, so x = 8. Distributing first gives 4x - 12 = 20 and the same answer.',
 wrong:'Dividing only the left side by 4 gives x - 3 = 20 and the wrong answer 23. Whatever you do to one side you do to the whole other side.'},
{id:'SM068',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:3,
 stem:'A line passes through the point (-2, 7) and has a slope of -4. What is the value of y when x = 1?',
 choices:['-5','-1','3','19'],answer:0,
 expl:'From x = -2 to x = 1 is a run of 3, and each unit of run drops y by 4, so y falls 12 from 7 to -5.',
 wrong:'Choice D adds 12 instead of subtracting it. A negative slope means y falls as x rises; sketching two points settles the direction faster than the formula.'},
{id:'SM069',section:'M',type:'MC',sub:'Linear equations in two variables',skill:'m_alg',diff:3,
 stem:'What is the x-intercept of the graph of 3x - 7y = 21 in the xy-plane?',
 choices:['-3','3','7','21'],answer:2,
 expl:'The x-intercept is where y = 0, so 3x = 21 and x = 7.',
 wrong:'Choice A is the y-intercept, found by setting x = 0. The x-intercept zeroes out y, which is the opposite substitution from the one most students reach for first.'},
{id:'SM070',section:'M',type:'MC',sub:'Systems of two linear equations',skill:'m_alg',diff:4,
 stem:'If 7x + 3y = 27 and 2x - 3y = 0, what is the value of y?',
 choices:['1','2','3','9'],answer:1,
 expl:'Adding the equations eliminates y: 9x = 27, so x = 3. Then 2(3) - 3y = 0 gives y = 2.',
 wrong:'Choice C is x, not y. When elimination gives you the other variable first, the last step is the one that answers the question.'},
{id:'SM071',section:'M',type:'SPR',answerType:'spr',sub:'Linear functions',skill:'m_alg',diff:4,
 stem:'A phone plan charges 18 dollars per month plus 4 cents per minute of calls. One month the bill was 30 dollars and 60 cents. How many minutes of calls were made that month?',
 choices:[],answer:'315',
 expl:'The call charges came to 30.60 minus 18.00, or 12.60 dollars. At 0.04 dollars per minute, that is 12.60 divided by 0.04, which is 315 minutes.',
 wrong:'Dividing the whole 30.60 by 0.04 gives 765 and ignores the fixed monthly charge. Subtract the fixed part before dividing by the rate.'},
{id:'SM072',section:'M',type:'MC',sub:'Linear inequalities',skill:'m_alg',diff:4,
 stem:'A student has scored 88, 92, and 86 on the first three of four tests. What is the lowest score on the fourth test that gives an average of at least 90 for all four?',
 choices:['90','92','94','96'],answer:2,
 expl:'An average of 90 across four tests needs a total of 360. The first three sum to 266, so the fourth must be at least 94.',
 wrong:'Choice A assumes a 90 on the last test produces a 90 average, but the first three are below 90 on balance and have to be made up.'},
{id:'SM073',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:4,
 stem:'The line y = mx + 6 passes through the point (4, -2). What is the value of m?',
 choices:['-2','-1','1','2'],answer:0,
 expl:'Substitute the point: -2 = 4m + 6, so 4m = -8 and m = -2.',
 wrong:'Choice D drops the sign. Since the line starts at 6 when x is 0 and has fallen to -2 by x = 4, the slope has to be negative.'},
{id:'SM074',section:'M',type:'SPR',answerType:'spr',sub:'Linear equations in one variable',skill:'m_alg',diff:5,
 stem:'If 2(3x - 4) = 5x + 1, what is the value of x?',
 choices:[],answer:'9',
 expl:'Distribute: 6x - 8 = 5x + 1. Subtract 5x to get x - 8 = 1, so x = 9.',
 wrong:'Subtracting 6x instead of 5x leaves -8 = -x + 1 and invites a sign error. Move the smaller variable term so the coefficient you keep stays positive.'},
// ---------- Advanced Math ----------
{id:'SM075',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:2,
 stem:'Which expression is equivalent to (2x - 3)^2?',
 choices:['4x^2 - 9','4x^2 + 9','4x^2 - 6x + 9','4x^2 - 12x + 9'],answer:3,
 expl:'Square the binomial: (2x)^2 - 2(2x)(3) + 3^2 = 4x^2 - 12x + 9.',
 wrong:'Choice A squares each term and drops the middle one, the single most common algebra error on this exam. (a - b)^2 is never a^2 - b^2.'},
{id:'SM076',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:3,
 stem:'What is the greater solution to the equation x^2 + 5x - 24 = 0?',
 choices:[],answer:'3',
 expl:'Find two numbers multiplying to -24 and adding to 5: 8 and -3. So (x + 8)(x - 3) = 0 and the solutions are -8 and 3.',
 wrong:'Reading the factors as the roots gives 8 and -3 with the signs reversed. Each factor is set equal to zero, so x + 8 = 0 means x = -8.'},
{id:'SM077',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:3,
 stem:'The function f is defined by f(x) = 2x^2 + 3. What is the positive value of x for which f(x) = 21?',
 choices:['2','3','6','9'],answer:1,
 expl:'Set 2x^2 + 3 = 21, so 2x^2 = 18 and x^2 = 9. The positive solution is x = 3.',
 wrong:'Choice D stops at x^2 = 9 and reports 9. Choice C divides 18 by 3 rather than taking a square root.'},
{id:'SM078',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:4,
 stem:'For positive x and y, which expression is equivalent to (x^3 y^2)^2 divided by (x^2 y)?',
 choices:['x^4 y^3','x^3 y^3','x^4 y^2','x^8 y^3'],answer:0,
 expl:'The numerator is x^6 y^4. Dividing subtracts exponents: x^(6-2) y^(4-1) = x^4 y^3.',
 wrong:'Choice D multiplies the outer exponent into only one factor or forgets the division. Raise the whole product to the power first, then divide.'},
{id:'SM079',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:4,
 stem:'If 3 raised to the power 2x equals 81, what is the value of x?',
 choices:[],answer:'2',
 expl:'Write 81 as 3^4. With matching bases, 2x = 4 and x = 2.',
 wrong:'Reporting 4 answers for 2x rather than x. Matching bases gives an equation in the exponent that still has to be solved.'},
{id:'SM080',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:4,
 stem:'The function g is defined by g(x) = -2(x + 1)^2 + 7. What is the maximum value of g?',
 choices:['-7','-1','1','7'],answer:3,
 expl:'The squared term is never negative, and the coefficient -2 makes that piece at most zero. The maximum occurs where x = -1, leaving g = 7.',
 wrong:'Choice B is the x-coordinate where the maximum occurs, not the maximum value. The question asks for the output, not the input.'},
{id:'SM081',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:5,
 stem:'If x is a positive number and x + 1/x = 5, what is the value of x^2 + 1/x^2?',
 choices:['21','23','25','27'],answer:1,
 expl:'Square both sides: x^2 + 2 + 1/x^2 = 25, because x times 1/x is 1 and the middle term is 2. Subtracting 2 gives 23.',
 wrong:'Choice C squares the right side and forgets that squaring the left produces a middle term. The cross term is exactly what makes this question work.'},
{id:'SM082',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear functions',skill:'m_adv',diff:4,
 stem:'The function f is defined by f(x) = x^2 - 6x + 5. What is the greater value of x for which f(x) = 0?',
 choices:[],answer:'5',
 expl:'Factor: (x - 1)(x - 5) = 0, so the zeros are 1 and 5.',
 wrong:'Using -b/(2a) gives 3, which is the vertex, not a zero. The vertex sits halfway between the two zeros, which is a useful check but not the answer.'},
{id:'SM083',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:4,
 stem:'For x greater than 0, which expression is equivalent to 1/x + 1/(x + 2)?',
 choices:['2/(2x + 2)','(x + 2)/x','(2x + 2)/(x(x + 2))','1/(2x + 2)'],answer:2,
 expl:'The common denominator is x(x + 2). The numerators become (x + 2) and x, which sum to 2x + 2.',
 wrong:'Choice D adds the denominators, which is never how fractions add. Choice A does the same with the numerators tacked on.'},
{id:'SM084',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:5,
 stem:'A quadratic equation has solutions x = 3 and x = -7. Which of the following could be that equation?',
 choices:['x^2 - 4x - 21 = 0','x^2 + 4x + 21 = 0','x^2 - 10x - 21 = 0','x^2 + 4x - 21 = 0'],answer:3,
 expl:'The factors are (x - 3) and (x + 7), whose product is x^2 + 4x - 21. Checking with the shortcut: the roots sum to -4, so b is +4, and they multiply to -21, so c is -21.',
 wrong:'Choice A reverses the sign of the sum. For x^2 + bx + c the sum of the roots is -b, not b, which is where the sign flip hides.'},
// ---------- Problem-Solving and Data Analysis ----------
{id:'SM085',section:'M',type:'SPR',answerType:'spr',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:2,
 stem:'What is 3/8 of 400?',
 choices:[],answer:'150',
 expl:'One eighth of 400 is 50, so three eighths is 150.',
 wrong:'Dividing 400 by 3/8 gives about 1067. A fraction of a quantity is a multiplication, not a division.'},
{id:'SM086',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:3,
 stem:'On a map, 1 inch represents 24 miles. How many miles does 3.5 inches represent?',
 choices:['68','76','84','96'],answer:2,
 expl:'Multiply by the scale: 3.5 times 24 is 84 miles.',
 wrong:'Choice D comes from 4 times 24, rounding the distance before applying the scale. Round at the end, not at the start.'},
{id:'SM087',section:'M',type:'SPR',answerType:'spr',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:4,
 stem:'The mean score on a test taken by 25 students was 80. After one student who scored 56 was excluded, what was the mean of the remaining 24 scores?',
 choices:[],answer:'81',
 expl:'The 25 scores total 25 times 80, or 2000. Removing 56 leaves 1944 across 24 students, and 1944 divided by 24 is 81.',
 wrong:'Subtracting 56 from the mean itself, or averaging 80 with 56, both ignore that a mean is a total spread over a count. Convert to the total first.'},
{id:'SM088',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:3,
 stem:'A store sells 3 pens for 4 dollars and 50 cents. At that rate, what is the cost of 11 pens?',
 choices:['$14.50','$15.00','$16.50','$18.00'],answer:2,
 expl:'Each pen costs 4.50 divided by 3, or 1.50 dollars, so 11 pens cost 16.50 dollars.',
 wrong:'Choice D prices 12 pens, the next multiple of 3. Find the unit rate rather than scaling the group up to a convenient size.'},
{id:'SM089',section:'M',type:'SPR',answerType:'spr',sub:'Percentages',skill:'m_psda',diff:4,
 stem:'After increasing by 30 percent, a quantity equals 260. What was the quantity before the increase?',
 choices:[],answer:'200',
 expl:'A 30 percent increase multiplies by 1.3, so the original is 260 divided by 1.3, which is 200.',
 wrong:'Taking 30 percent off 260 gives 182, which is not the original. A percent increase is undone by dividing by 1.3, not by subtracting 30 percent of the new value.'},
{id:'SM090',section:'M',type:'MC',sub:'Inference from sample statistics and margin of error',skill:'m_psda',diff:4,
 stem:'In a random sample of 800 registered voters in a county, 336 said they support a ballot measure. Based on this sample, about how many of the county 25,000 registered voters would be expected to support the measure?',
 choices:['8,400','9,600','10,500','12,000'],answer:2,
 expl:'The sample proportion is 336 of 800, which is 0.42. Applying it to 25,000 gives 10,500.',
 wrong:'Choice D applies a rounded-up 48 percent. Compute the proportion exactly before scaling; small rounding at that step moves the answer by thousands.'},
{id:'SM091',section:'M',type:'MC',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:5,
 stem:'Every value in a data set with mean 50 is increased by 8. Which of the following describes the new data set?',
 choices:['The mean is 58 and the standard deviation increases by 8.','The mean is 58 and the standard deviation is unchanged.','The mean is unchanged and the standard deviation is 58.','Both the mean and the standard deviation increase by 8.'],answer:1,
 expl:'Adding the same amount to every value shifts the whole distribution without changing how spread out it is, so the mean moves to 58 and the standard deviation stays put.',
 wrong:'Choices A and D assume spread travels with center. Standard deviation measures distances between values, and shifting everything equally leaves every distance the same.'},
{id:'SM092',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:3,
 stem:'A runner covers 400 meters in 50 seconds. What is that speed in meters per minute?',
 choices:['320','400','480','500'],answer:2,
 expl:'The rate is 400 divided by 50, or 8 meters per second. Sixty seconds at 8 meters per second is 480 meters per minute.',
 wrong:'Choice B reports the distance rather than converting the rate. Track the units through the calculation and stop only when they match what was asked for.'},
// ---------- Geometry and Trigonometry ----------
{id:'SM093',section:'M',type:'SPR',answerType:'spr',sub:'Area and volume',skill:'m_geo',diff:2,
 stem:'A rectangle has an area of 84 and a width of 7. What is its length?',
 choices:[],answer:'12',
 expl:'Area is length times width, so the length is 84 divided by 7, which is 12.',
 wrong:'Using the perimeter formula here gives 35, a number that does not belong to this question at all. Check which measure the question names before choosing a formula.'},
{id:'SM094',section:'M',type:'MC',sub:'Circles',skill:'m_geo',diff:3,
 stem:'A circle has a circumference of 18 pi. What is its radius?',
 choices:['4.5','9','18','81'],answer:1,
 expl:'Circumference is 2 pi r, so 2r = 18 and r = 9.',
 wrong:'Choice C treats the circumference coefficient as the diameter doubled again. Choice D squares the radius, which belongs to area rather than circumference.'},
{id:'SM095',section:'M',type:'MC',sub:'Lines, angles, and triangles',skill:'m_geo',diff:3,
 stem:'The measures of the three angles of a triangle are in the ratio 2 to 3 to 4. What is the measure of the largest angle?',
 choices:['40 degrees','60 degrees','80 degrees','90 degrees'],answer:2,
 expl:'Write the angles as 2k, 3k, and 4k. They sum to 9k = 180, so k = 20 and the largest is 4(20) = 80 degrees.',
 wrong:'Choice D assumes the largest angle in any such triangle is a right angle. A 2 to 3 to 4 ratio produces 40, 60, and 80, so the triangle is acute.'},
{id:'SM096',section:'M',type:'SPR',answerType:'spr',sub:'Right triangles and trigonometry',skill:'m_geo',diff:4,
 stem:'A right triangle has legs of length 5 and 12. What is the perimeter of the triangle?',
 choices:[],answer:'30',
 expl:'The hypotenuse is the square root of 25 + 144, which is 13, one of the common triples. The perimeter is 5 + 12 + 13 = 30.',
 wrong:'Answering 17 gives the two legs only. The perimeter needs the third side, which is exactly the step the Pythagorean theorem is there for.'},
{id:'SM097',section:'M',type:'MC',sub:'Area and volume',skill:'m_geo',diff:4,
 stem:'A right circular cone has a radius of 6 and a height of 10. What is its volume?',
 choices:['60 pi','120 pi','180 pi','360 pi'],answer:1,
 expl:'Cone volume is one third pi r squared h: one third times pi times 36 times 10, which is 120 pi.',
 wrong:'Choice D is the cylinder with the same base and height. A cone holds exactly one third of that cylinder, and forgetting the one third is the standard slip.'},
{id:'SM098',section:'M',type:'MC',sub:'Right triangles and trigonometry',skill:'m_geo',diff:4,
 stem:'In right triangle ABC, the right angle is at B, the tangent of angle A is 3/4, and side AB has length 8. What is the length of side BC?',
 choices:['4','6','10','12'],answer:1,
 expl:'Tangent is the side opposite over the side adjacent. From angle A, BC is opposite and AB is adjacent, so BC/8 = 3/4 and BC = 6.',
 wrong:'Choice D inverts the ratio, using 4/3 instead of 3/4. Name which side is opposite the angle before writing the fraction.'},
{id:'SM099',section:'M',type:'MC',sub:'Circles',skill:'m_geo',diff:5,
 stem:'In the xy-plane, a circle has its center at (2, -5) and passes through the point (2, 1). Which equation represents the circle?',
 choices:['(x + 2)^2 + (y - 5)^2 = 36','(x - 2)^2 + (y + 5)^2 = 36','(x - 2)^2 + (y + 5)^2 = 6','(x - 2)^2 + (y - 5)^2 = 36'],answer:1,
 expl:'The two points share an x-value, so the radius is the vertical distance from -5 to 1, which is 6. The equation takes the center with opposite signs and the radius squared: (x - 2)^2 + (y + 5)^2 = 36.',
 wrong:'Choice C leaves the radius unsquared and choice D mishandles the sign on a negative y-coordinate. A center of (2, -5) appears in the equation as y + 5.'},
{id:'SM100',section:'M',type:'SPR',answerType:'spr',sub:'Lines, angles, and triangles',skill:'m_geo',diff:5,
 stem:'The measures of the four angles of a quadrilateral, in degrees, are x, 2x, 3x, and 4x. What is the measure, in degrees, of the largest angle?',
 choices:[],answer:'144',
 expl:'The angles of a quadrilateral sum to 360 degrees, so 10x = 360 and x = 36. The largest is 4(36) = 144 degrees.',
 wrong:'Using 180 for the sum, as in a triangle, gives x = 18 and a largest angle of 72. A quadrilateral splits into two triangles, so its angles sum to 360.'}
];
