// bank_sat_rw5.js - Original SAT Reading and Writing items SR127-SR162. Fourth increment,
// taking Reading and Writing past three non-repeating sections.
const BANK_SAT_RW5 = [
// ---------- Craft and Structure ----------
{id:'SR127',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:2,
 passage:'The axolotl, a salamander native to a handful of canals near Mexico City, never completes the transformation most amphibians undergo. It keeps its feathery external gills and stays in the water for life. To a nineteenth-century naturalist expecting a land-dwelling adult, the animal looked ______ : permanently, deliberately unfinished.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['arrested','endangered','aggressive','ordinary'],answer:0,
 expl:'The colon defines the blank: permanently, deliberately unfinished. An animal stopped partway through a transformation is arrested in development.',
 wrong:'Endangered is true of the axolotl today but has nothing to do with the incomplete transformation the sentence describes. A blank takes its meaning from the text beside it, not from what you know about the subject.'},
{id:'SR128',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'Reviewers of the first edition complained that the dictionary included slang, regional coinages, and words its editor had found in newspapers. He answered that a dictionary recording only what educated writers approved would be a monument rather than a record, and that his aim had always been ______ rather than prescriptive.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['ornamental','descriptive','provisional','commercial'],answer:1,
 expl:'The word rather than sets the blank against prescriptive, and the editor describes his aim as recording what exists rather than approving it. Descriptive is the standing opposite of prescriptive.',
 wrong:'Provisional means temporary, which does not oppose prescriptive. The blank is set against a specific word, so the answer has to be that word\'s counterpart.'},
{id:'SR129',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:4,
 passage:'The economist argument rests on a single, unstated premise: that the workers displaced by a new technology will find comparable employment within a few years. History offers cases in both directions, and the essay cites only the ones that ______ the premise, which leaves its conclusion resting on a selection the author never defends.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['complicate','anticipate','vindicate','postpone'],answer:2,
 expl:'The criticism is that the essay cites only cases favorable to its premise, leaving an undefended selection. The cited cases must be the ones that support it.',
 wrong:'Complicate names the cases the essay left out, not the ones it cited. Track which group the sentence is describing before choosing.'},
{id:'SR130',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'Early accounts of the Antikythera mechanism treated its gearing as an isolated marvel, a device with no predecessors and no descendants. Fragments of comparable instruments described in later Greek and Arabic texts have made that isolation look ______ : less a fact about ancient engineering than a fact about what happens to survive.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['apparent','deliberate','permanent','inevitable'],answer:0,
 expl:'The colon explains that the isolation reflects survival rather than engineering. Something that seems true but reflects the evidence rather than the world is apparent.',
 wrong:'Inevitable would say the isolation had to happen, which is the opposite of the passage claim that it is an artifact of the record.'},
{id:'SR131',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:4,
 passage:'Guidance on hydration in endurance sport once advised athletes to drink as much as they could tolerate. The advice was not arbitrary; dehydration measurably degrades performance and, in heat, becomes dangerous. But drinking past thirst carries its own risk. Overhydration dilutes blood sodium, and the resulting condition has killed marathon runners whose only error was following the guidance too well.',
 stem:'Which choice best states the function of the second sentence in the text as a whole?',
 choices:['It provides evidence that the advice described in the first sentence was mistaken.','It introduces the condition the text describes in the final sentence.','It explains why endurance athletes ignored the guidance.','It grants a sound basis for the advice the text goes on to qualify.'],answer:3,
 expl:'The second sentence says the advice was not arbitrary and gives the real danger behind it. The third sentence turns with But, so the second exists to concede the case before the qualification.',
 wrong:'Choice A has it backwards. Saying the advice was not arbitrary supports it, and the objection does not arrive until the word But.'},
{id:'SR132',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:5,
 passage:'Museums acquired thousands of natural history specimens in the nineteenth century, and the labels record who collected them, where, and when. Historians of science have begun reading these labels as documents in their own right. A label that names a European collector at a site he reached by a route he could not have found alone, in a season when he was demonstrably elsewhere, is evidence about credit rather than about beetles.',
 stem:'Which choice best describes the overall structure of the text?',
 choices:['It criticizes the accuracy of nineteenth-century specimen labels held in European collections and recommends correcting them.','It compares the collecting practices of European and local naturalists.','It notes an archival feature, describes a new use for it, and illustrates what that use reveals.','It argues that natural history collections should be returned to their countries of origin.'],answer:2,
 expl:'The text moves from what labels record, to historians reading them as documents, to an example showing that a label can testify about attribution rather than about the specimen.',
 wrong:'Choice A treats the example as a call for correction, but the passage is interested in what the labels reveal as evidence, not in fixing them.'},
{id:'SR133',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:3,
 passage:'Writers are often told to cut every adverb. The advice has an obvious appeal: an adverb propping up a weak verb is a sign that the verb should be replaced. It is also, applied as a rule, unusable. Consider how much of a sentence such as "she almost never answered" would survive it.',
 stem:'Which choice best states the function of the last sentence in the text as a whole?',
 choices:['It concedes that the rule holds in most ordinary sentences.','It offers a case in which following the rule would destroy the meaning.','It restates the reason the advice appeals to writers.','It identifies the kind of verb the advice was designed to improve in ordinary prose.'],answer:1,
 expl:'The third sentence calls the rule unusable as a rule, and the last supplies a sentence whose meaning depends entirely on two adverbs. It is the demonstration.',
 wrong:'Choice A reads Consider as a concession. The example is offered against the rule, not in its favor.'},
{id:'SR134',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:4,
 passage:'Text 1\nWild animals should not be fed by the public. Feeding habituates animals to people, concentrates them in unnatural densities where disease spreads, and shifts their diets toward food they did not evolve to process.\n\nText 2\nEach of those harms is real, and each is a harm of unmanaged feeding. Supplementary feeding programs run by wildlife agencies disperse feed deliberately, use formulations matched to the species, and have pulled several populations through winters that would otherwise have halved them. The practice is not the problem; the absence of design is.',
 stem:'Based on the texts, how would the author of Text 2 most likely respond to the argument in Text 1?',
 choices:['By accepting its list of harms while attributing them to a lack of management rather than to feeding itself','By denying that feeding concentrates animals in unnatural densities','By arguing that wildlife agencies should stop running supplementary feeding programs altogether in every season of the year','By claiming that habituation to people benefits most wild populations'],answer:0,
 expl:'Text 2 opens by granting that each harm is real, then assigns them to unmanaged feeding and closes by naming the absence of design as the problem.',
 wrong:'Choice B contradicts the concession Text 2 makes in its first sentence. On a text that concedes before it objects, the opening clause is usually the key.'},
{id:'SR135',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:5,
 passage:'Text 1\nA biography should confine itself to what the record can support. Where a letter is missing or a witness is silent, the honest biographer marks the gap and moves on rather than furnishing a plausible scene.\n\nText 2\nNo narrative is assembled without judgment. Deciding which of a thousand documented facts to place in sequence, and which to leave in the notes, is already an act of construction, and a book built from that judgment is not made more honest by declining to acknowledge it. The distinction is not between constructed and unconstructed lives but between constructions their authors own and constructions they do not.',
 stem:'Based on the texts, the author of Text 2 would most likely argue that the standard in Text 1',
 choices:['would make biography impossible to write at any length about most historical subjects','has been abandoned by most working biographers','applies only to subjects whose papers survive in quantity in a single archive','treats as a bright line a difference that is one of degree'],answer:3,
 expl:'Text 2 argues that selection and sequence are already construction, so the choice is not between constructed and unconstructed but between owned and unowned construction. That collapses the sharp line Text 1 draws.',
 wrong:'Choice A pushes further than Text 2 goes: it does not say biography becomes impossible, only that the proposed line does not mark what Text 1 thinks it marks.'},
// ---------- Information and Ideas ----------
{id:'SR136',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:3,
 passage:'The Voynich manuscript has resisted every attempt at decipherment for more than a century. Statistical work has established that its text behaves like language in several respects: word lengths follow a natural distribution, and certain sequences recur where a language would put common words. Those same properties, critics point out, could be produced by a sufficiently disciplined hoaxer with a table of syllables and a method for combining them.',
 stem:'Which choice best states the main idea of the text?',
 choices:['The Voynich manuscript is written in a language that has since been lost and recorded nowhere else in Europe or anywhere else.','Statistical methods are unsuitable for the study of undeciphered texts.','Statistical evidence that the manuscript resembles language does not by itself rule out an elaborate fabrication.','Hoaxers in the medieval period commonly used tables of syllables.'],answer:2,
 expl:'The passage presents language-like statistics and then the critics point that a disciplined hoax could produce them, which leaves the evidence short of settling the question.',
 wrong:'Choice B overgeneralizes from one limitation into a verdict on the method. The passage uses the statistics, it just declines to treat them as conclusive.'},
{id:'SR137',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:4,
 passage:'The Bauhaus is remembered for the objects it produced, but its most consequential product may have been a curriculum. Every student, regardless of intended specialism, spent the first year in a preliminary course working in unfamiliar materials with no assigned outcome. Graduates carried the structure into schools in Chicago, Ulm, and elsewhere, and the foundation year it established is now standard in design education worldwide.',
 stem:'Which choice best states the main idea of the text?',
 choices:['Bauhaus graduates were more successful as teachers than as designers.','The Bauhaus most lasting influence may lie in a teaching structure rather than in its designed objects.','The preliminary course was the most difficult year of the Bauhaus program for its students and for its teachers.','Design education outside Germany developed independently of the Bauhaus.'],answer:1,
 expl:'The first sentence sets objects against curriculum, and the rest traces the preliminary course to design schools worldwide, which supports the curriculum as the more consequential product.',
 wrong:'Choice A converts a claim about influence into a claim about individual success, which the passage never makes.'},
{id:'SR138',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'A student is writing about the mathematician Emmy Noether and has drafted the following claim: Noether influence ran well beyond her published papers, through a circle of students and colleagues who developed her methods under their own names. The student has gathered four facts.',
 stem:'Which fact, if true, would most directly support the student claim?',
 choices:['Several foundational results in modern algebra were published by her students, who credited the approach and the problems to her lectures and conversation.','Noether was denied a salaried professorship for years and lectured under a colleague name, which kept her off the title page of work she had shaped for most of her years at Gottingen.','Noether theorem connects the symmetries of a physical system to its conservation laws, and it is the result most often cited outside mathematics by physicists working on conservation.','Noether left Germany in 1933 and taught at Bryn Mawr College until her death in 1935, continuing to lecture on the methods she had developed in Gottingen until the last weeks of her life.'],answer:0,
 expl:'The claim is about influence traveling through other people work. Choice A names results published by others who credited her lectures and conversation, which is precisely that route.',
 wrong:'Choice B speaks to the obstacles she faced and choice C to the content of a published result, neither of which shows influence running through her circle.'},
{id:'SR139',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:5,
 passage:'A team hypothesized that city trees reduce summer street temperatures mainly by shading surfaces rather than by transpiring water. They compared paired street segments across one city, matched for width, orientation, and paving material, differing only in canopy cover.',
 stem:'Which finding, if true, would most strongly support the hypothesis?',
 choices:['Segments with high canopy cover were cooler than segments with low canopy cover at every hour of the day that was measured.','Trees on the cooler segments had larger leaf areas than trees on the warmer segments.','Air humidity was slightly higher on segments with high canopy cover.','Segments with artificial shade structures and no trees were nearly as cool as segments with equivalent canopy cover.'],answer:3,
 expl:'The hypothesis singles out shade over transpiration. Artificial shade cools without transpiring at all, so matching its effect to that of a canopy isolates shade as the mechanism.',
 wrong:'Choice A shows trees cool streets but says nothing about which mechanism does the work, which is the only question at issue. Choice C points toward transpiration instead.'},
{id:'SR140',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:4,
 passage:'Species that colonize islands frequently lose the ability to fly. The usual explanation is economy: flight muscle is expensive to build and maintain, and on an island with no ground predators the expense buys little. This account predicts that flightlessness should be rare on islands where mammalian predators are native, and the fossil record of such islands ______',
 stem:'Which choice most logically completes the text?',
 choices:['shows that flightless birds were unusually large there.','contains no evidence of birds of any kind.','suggests that flight muscle is inexpensive to maintain.','bears the prediction out.'],answer:3,
 expl:'The passage sets up a prediction and then turns to the record of exactly the islands the prediction covers. The completion that follows is whether the record matches, and the account is presented as the usual one rather than a refuted one.',
 wrong:'Choice C contradicts the premise the explanation rests on. A blank that follows a prediction and the relevant evidence is asking whether they agree.'},
{id:'SR141',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:5,
 passage:'A publisher compared two cover designs for the same novel by randomly assigning which cover each online visitor saw. Cover A produced more clicks through to the book page; cover B produced fewer clicks but a higher share of purchases among those who clicked. Total sales were nearly identical. A colleague concluded that the covers were equally effective, which overlooks that ______',
 stem:'Which choice most logically completes the text?',
 choices:['the two covers may be attracting different readers rather than the same readers at different rates.','one of the two covers was shown to more visitors than the other.','the number of clicks is a more reliable measure than the number of purchases recorded during the same period.','the publisher should have tested a third cover alongside the first two.'],answer:0,
 expl:'Identical totals are consistent with the covers drawing different audiences: one pulls a wider, less committed group, the other a narrower, more committed one. Equal sales does not mean equal effect.',
 wrong:'Choice B contradicts the random assignment described in the first sentence. Choice D proposes a further study rather than naming what the conclusion overlooks.'},
{id:'SR142',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:3,
 passage:'In 1854 a London physician mapped cholera deaths street by street and found them clustered around a single water pump. The map is now a founding image of epidemiology, and it is often described as having convinced the authorities. It did not. The pump handle was removed after the outbreak had already begun to subside, and the prevailing theory that cholera spread through foul air held for years afterward.',
 stem:'According to the text, what is inaccurate in the usual account of the 1854 map?',
 choices:['The claim that deaths clustered around one water pump in the affected district','The claim that it persuaded the authorities of its conclusion','The claim that the map was drawn street by street','The claim that the pump handle was eventually removed by the parish authorities'],answer:1,
 expl:'The text accepts the clustering, the method, and the removal, and disputes only the idea that the map convinced the authorities, noting that the older theory held for years.',
 wrong:'Choice D is stated as fact in the passage; what the text corrects is the timing and the effect, not whether the handle came off.'},
{id:'SR143',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'Text from a school board meeting: "The argument for moving our start time later is that teenagers cannot fall asleep as early as adults. That is a claim about biology, and if it is right, an earlier bedtime cannot substitute for a later start."',
 stem:'Which finding from sleep research would most effectively support the speaker position?',
 choices:['Teenagers who use screens in the evening report falling asleep later than those who do not use screens in the hours before bed.','Students at schools with later start times report higher satisfaction with their schedules than students at schools that begin earlier in the morning.','Melatonin release shifts about two hours later during adolescence, so most teenagers cannot fall asleep at an adult bedtime even when they try.','Adults who work night shifts accumulate sleep debt over the course of a week that they do not fully repay at the weekend.'],answer:2,
 expl:'The speaker rests on a biological claim and on its consequence, that earlier bedtimes cannot substitute. Choice C supplies the physiological shift and states directly that trying does not overcome it.',
 wrong:'Choice A points to a behavioral cause, which is exactly the alternative the speaker is ruling out. Supporting evidence has to land on the disputed mechanism.'},
{id:'SR144',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:4,
 passage:'Conservators cleaning a seventeenth-century painting found that the varnish had yellowed unevenly, darkening the sky more than the foreground. Visitors and even specialists had long read the composition as a storm scene lit from below. After cleaning, the sky proved pale and the light plainly overhead, which suggests that the storm reading was ______',
 stem:'Which choice most logically completes the text?',
 choices:['shared by the artist contemporaries as well.','based on a misreading of the foreground figures in the lower half of the panel.','confirmed by the results of the cleaning.','an artifact of the varnish rather than a feature of the painting.'],answer:3,
 expl:'The varnish darkened the sky unevenly and the reading depended on a dark sky. Removing the varnish removed the darkness and the reading with it, so the storm was in the coating.',
 wrong:'Choice C reverses the outcome. The cleaning overturned the reading rather than confirming it.'},
// ---------- Standard English Conventions ----------
{id:'SR145',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'The survey covered every household on the island ______ the census that followed two years later reached only about two thirds of them.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:[', whereas',', whereas,','; whereas,','whereas'],answer:0,
 expl:'Whereas is a subordinating conjunction introducing a contrasting clause, and a comma before it is standard. No comma follows it.',
 wrong:'Choice D leaves the two clauses fused with no punctuation at the join. Choices B and C add a comma after whereas, which separates the conjunction from its own clause.'},
{id:'SR146',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'Only one of the three proposed routes avoids the wetland ______ and it is also the most expensive to build.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['',',','; ',': '],answer:1,
 expl:'Two independent clauses joined by and take a comma before the conjunction.',
 wrong:'Choice C puts a semicolon before a coordinating conjunction, which doubles the join. Use one or the other, never both.'},
{id:'SR147',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'The apprenticeship ran for seven years, during which a student ground pigment, prepared panels, and copied the master ______ only in the final year was original work permitted.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['drawings,','drawings','drawings;','drawings and,'],answer:2,
 expl:'Both halves are complete sentences and the second continues the thought closely, so a semicolon joins them. A period would also be correct but is not offered.',
 wrong:'Choice A is a comma splice. The inverted opening of the second clause, only in the final year, disguises that it is a full sentence.'},
{id:'SR148',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'The rover carried instruments from four countries ______ a spectrometer from France, a drill from Spain, a weather station from Finland, and a camera mast assembled in the United States.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:[',','','; namely',':'],answer:3,
 expl:'A complete sentence precedes the blank and a list specifying the instruments follows, which is exactly what a colon introduces.',
 wrong:'Choice C would need a comma after namely and is redundant with the colon it replaces. Choice A leaves a long list dangling off the sentence without a mark that introduces it.'},
{id:'SR149',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:3,
 passage:'Each of the museum four branches ______ its own conservation studio.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['maintains','maintain','are maintaining','have maintained'],answer:0,
 expl:'Each is the subject and is singular, so the verb is singular regardless of the plural branches that follows of.',
 wrong:'Choice B agrees with branches, the nearest noun. Cross out the prepositional phrase and the sentence reads each maintains.'},
{id:'SR150',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'By the time the archive was catalogued, three of the letters ______ already been published elsewhere.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['has','have','had','will have'],answer:2,
 expl:'The publication came before the cataloguing and both are in the past, so the earlier event takes the past perfect. The subject three is plural, which had serves.',
 wrong:'Choice B puts an event that precedes a past moment into the present perfect, which anchors to now rather than to the cataloguing.'},
{id:'SR151',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'The new bridge is longer than the one it replaced, but ______ deck sits lower above the water at high tide.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['it is','its','their','its own'],answer:1,
 expl:'The possessive its modifies deck and refers to the bridge, which is singular.',
 wrong:'Choice A is the contraction it is, which cannot own a noun. Read the sentence with it is substituted in and the error is audible.'},
{id:'SR152',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:5,
 passage:'Recorded on a single afternoon with one microphone, ______',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['the album has a room sound no later session reproduced.','the engineer captured a room sound no later session reproduced.','there is a room sound on the album that no later session reproduced.','it was the room sound, which no later session reproduced.'],answer:0,
 expl:'The opening modifier describes what was recorded, which is the album, so the album must be the subject of the main clause.',
 wrong:'Choice B makes the engineer the thing recorded that afternoon. Ask what the opening phrase describes, then put it directly after the comma.'},
{id:'SR153',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'The grant will fund three activities: surveying the remaining stands of old-growth forest, training local volunteers in identification, and ______ a public database of the results.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['to publish','publication of','it will publish','publishing'],answer:3,
 expl:'The first two items are -ing forms, so the third must match: surveying, training, and publishing.',
 wrong:'Choice A switches to an infinitive and breaks the series. Read the list aloud with the shared opening to hear the mismatch.'},
// ---------- Expression of Ideas ----------
{id:'SR154',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Aluminium was once more valuable than gold. It is among the most abundant metals in the crust, but it never occurs in native form and the processes available before the 1880s could free it from its ore only in small quantities at enormous cost. ______ the discovery of an electrolytic method dropped the price by a factor of more than two hundred within a decade.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Likewise','Regardless','Then','In particular'],answer:2,
 expl:'The passage describes the situation before the 1880s and the last sentence reports what changed afterward, so the relationship is sequence.',
 wrong:'Choice B dismisses the earlier difficulty rather than marking the moment it ended.'},
{id:'SR155',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'Reviewers assumed the newly attributed portrait was a copy, because its pigment layers were thinner than the artist documented practice. Analysis of the panel then dated the wood to within a few years of his workshop. ______ thin paint alone is weak evidence of a copy, since an artist working quickly or cheaply produces the same signature.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['As a result,','In any case,','Similarly,','Until then,'],answer:1,
 expl:'The last sentence undercuts the reviewers original reasoning independently of the dating evidence just reported. A transition that sets the previous point aside and adds a separate objection fits.',
 wrong:'Choice A claims the objection follows from the panel dating, but the point about thin paint stands on its own reasoning about how artists work.'},
{id:'SR156',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Kelp grows faster than almost any land plant, up to half a metre a day in good conditions. It also requires no fresh water, no fertiliser, and no arable land. ______ proposals to farm it at scale have attracted attention from people who would not otherwise be interested in seaweed.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Unsurprisingly,','Even so,','By contrast,','Previously,'],answer:0,
 expl:'The first two sentences list advantages, and the third reports the interest those advantages have drawn. The interest is what the advantages lead you to expect.',
 wrong:'Choice B would require the interest to be surprising in light of the advantages, which reverses the passage logic.'},
{id:'SR157',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'The census counts people where they sleep on a single night. For most residents this is a reasonable simplification. ______ for students, seasonal workers, and people in transitional housing it can assign a person to a place they will not be in a month later, and the funding that follows the count goes with them.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Consequently,','In the same way,','To that end,','For others, however,'],answer:3,
 expl:'The second sentence covers most residents and the third turns to the groups for whom the simplification fails, so the transition must mark both the contrast and the change of group.',
 wrong:'Choice B presents the third sentence as parallel to the second, but the two describe opposite outcomes.'},
{id:'SR158',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'A common recommendation for reducing household energy use is to replace an old appliance with an efficient model. The calculation usually compares the running costs of the two machines. ______ it rarely includes the energy already spent manufacturing the old appliance, which is lost the moment it is discarded.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Therefore,','For instance,','Notably,','Likewise,'],answer:2,
 expl:'The third sentence points out something the calculation leaves out, which is a noteworthy qualification of the method just described.',
 wrong:'Choice A claims the omission follows from the comparison, but the omission is a criticism of it rather than a consequence.'},
{id:'SR159',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The Pantheon in Rome was completed around 126 CE.\n- Its dome remains the largest unreinforced concrete dome in the world.\n- The concrete mix grows lighter toward the top, using pumice in the upper courses.\n- The dome is thinner at the crown than at its base.\n- A circular opening at the crown, the oculus, is nearly nine metres across.',
 stem:'The student wants to explain how the dome supports its own weight. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['The Pantheon, completed around 126 CE, still has the largest unreinforced concrete dome standing anywhere in the world.','The dome carries its own weight by growing lighter and thinner toward the crown, where pumice replaces heavier aggregate and an open oculus removes material altogether.','A circular opening nearly nine metres across, the oculus, sits at the crown of the dome and is open to the sky.','The concrete mix used in the Pantheon dome grows lighter toward the top, with pumice replacing heavier aggregate in the upper courses of the structure.'],answer:1,
 expl:'The goal asks how the structure works. Choice B assembles the three structural notes, lighter mix, thinner shell, and an opening that removes material, into the mechanism.',
 wrong:'Choice D gives one of the three and stops. A how question wants the working explanation, not a single contributing fact.'},
{id:'SR160',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Sequoia trees can live more than three thousand years.\n- Their bark is thick, fibrous, and low in resin.\n- Low-intensity fires clear competing undergrowth without harming mature trees.\n- Sequoia cones require the heat of fire to open and release seed.\n- A century of fire suppression left dense undergrowth in many groves.',
 stem:'The student wants to explain why fire suppression harmed sequoia groves. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Sequoia bark is thick, fibrous, and low in resin, which protects mature trees from low-intensity fire and from the heat of a passing ground fire.','Sequoias depend on fire to clear competing undergrowth and to open their cones, so a century of suppression left groves crowded and seed unreleased.','Sequoia trees can live more than three thousand years, longer than almost any other species.','A century of fire suppression left dense undergrowth in many sequoia groves.'],answer:1,
 expl:'Why requires a cause and its effect. Choice B names the two things fire does for sequoias and states what removing it produced.',
 wrong:'Choice D gives the effect with no explanation of why it is harmful. Without the dependence on fire, dense undergrowth is just a description.'},
{id:'SR161',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:5,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The Library of Ashurbanipal at Nineveh held tens of thousands of clay tablets.\n- The city was sacked and burned in 612 BCE.\n- Clay tablets are fired by intense heat, which hardens rather than destroys them.\n- Most of what survives of Mesopotamian literature comes from this library.\n- Papyrus and parchment libraries of the same era have left almost nothing.',
 stem:'The student wants to explain the irony in how the library survived, without overstating what the notes show. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['The Library of Ashurbanipal at Nineveh held tens of thousands of clay tablets, and most of what survives of Mesopotamian literature comes from that one collection.','Clay tablets are fired by intense heat, which hardens them rather than destroying them, unlike the papyrus and parchment that libraries elsewhere relied on.','The fire that destroyed Nineveh in 612 BCE hardened the library clay tablets, which is why most surviving Mesopotamian literature comes from a collection that was burned.','Papyrus and parchment libraries of the same era have left almost nothing behind, even where their buildings were never burned at all.'],answer:2,
 expl:'The irony is that the destruction preserved the collection. Choice C joins the sack, the hardening, and the survival of most Mesopotamian literature, and claims nothing the notes do not support.',
 wrong:'Choice A adds a comparison the notes never make, that it held more tablets than any other library. Overstating is what the goal explicitly warns against.'},
{id:'SR162',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:3,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Ada Lovelace worked with Charles Babbage on the Analytical Engine in the 1840s.\n- She translated an Italian paper describing the machine.\n- Her appended notes ran roughly three times the length of the paper.\n- The notes include a method for computing Bernoulli numbers on the machine.\n- She also argued the machine could act on symbols other than numbers, such as musical notes.',
 stem:'The student wants to introduce Lovelace notes to an audience unfamiliar with them. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Lovelace argued that the Analytical Engine could act on symbols other than numbers, such as musical notes of any kind.','Lovelace notes include a method for computing Bernoulli numbers on the Analytical Engine.','Ada Lovelace worked with Charles Babbage on the Analytical Engine during the 1840s.','Translating an Italian paper on Babbage Analytical Engine in the 1840s, Lovelace appended notes that ran roughly three times the length of the original.'],answer:3,
 expl:'An introduction has to say what the notes were and how they came about. Choice D gives the occasion, the date, the machine, and the striking fact of their length.',
 wrong:'Choices A and B describe contents for a reader who does not yet know what the notes are. Match the sentence to the audience the goal names.'}
];
