// bank_gre_verbal2.js - Original GRE Verbal items GV021-GV044.
// Second Verbal increment: more Reading Comprehension passages so mock sections can run
// twice without repeating, plus harder Text Completion and Sentence Equivalence.
const BANK_GRE_VERBAL2 = [
// ---------- Reading Comprehension: passage on scientific replication ----------
{id:'GV021',section:'V',type:'RC',sub:'Main idea',skill:'gre_rc',diff:3,
 passage:'When a large replication project failed to reproduce a majority of published psychology findings, commentators drew opposite conclusions. Some treated the result as evidence that the field was fundamentally unsound. Others noted that a failure to replicate is not a demonstration that the original result was false: a replication can fail because the effect is small, because the sample is different, or because a procedure that was never fully described was not reproduced. The more careful reading is that the project measured not the truth of individual findings but the field\'s tolerance for underpowered studies and incomplete reporting.',
 stem:'The primary purpose of the passage is to',
 choices:['reconcile two interpretations by reframing what the project measured','demonstrate that most published psychology findings are false','defend the original studies against the replication project','describe the statistical methods used in replication research','recommend that psychology abandon small-sample research'],answer:0,
 expl:'The passage presents two opposite readings, explains why neither is quite right, and offers a third framing: the project measured the field\'s tolerance for underpowered studies rather than the truth of individual results.',
 wrong:'It explicitly says a failed replication does not show the original was false, so it neither demonstrates falsity nor simply defends the originals.'},
{id:'GV022',section:'V',type:'RC',sub:'Inference',skill:'gre_rc',diff:4,
 passage:'When a large replication project failed to reproduce a majority of published psychology findings, commentators drew opposite conclusions. Some treated the result as evidence that the field was fundamentally unsound. Others noted that a failure to replicate is not a demonstration that the original result was false: a replication can fail because the effect is small, because the sample is different, or because a procedure that was never fully described was not reproduced. The more careful reading is that the project measured not the truth of individual findings but the field\'s tolerance for underpowered studies and incomplete reporting.',
 stem:'The passage implies that a study whose procedure was incompletely described',
 choices:['is more likely to be fraudulent than one fully described','cannot be meaningfully tested by a replication attempt','would produce a larger effect if repeated exactly','should be excluded from any replication project','is necessarily based on too small a sample'],answer:1,
 expl:'The passage lists an undescribed procedure as a reason a replication can fail without the original being false, which means the attempt cannot cleanly test the original claim.',
 wrong:'Fraud is never raised, and the passage names small effects and different samples as separate causes rather than consequences of poor description.'},
{id:'GV023',section:'V',type:'RC',sub:'Function of a sentence',skill:'gre_rc',diff:3,
 passage:'When a large replication project failed to reproduce a majority of published psychology findings, commentators drew opposite conclusions. Some treated the result as evidence that the field was fundamentally unsound. Others noted that a failure to replicate is not a demonstration that the original result was false: a replication can fail because the effect is small, because the sample is different, or because a procedure that was never fully described was not reproduced. The more careful reading is that the project measured not the truth of individual findings but the field\'s tolerance for underpowered studies and incomplete reporting.',
 stem:'The list of three reasons a replication can fail functions primarily to',
 choices:['identify the most common error in published psychology','establish that replication projects are poorly designed','support the claim that failure does not establish falsity','explain why the majority of findings failed to replicate','argue that samples should be standardised across studies'],answer:2,
 expl:'The list follows a colon after the claim that failure is not a demonstration of falsity, and each item is a way failure can occur without the original being wrong. It supports that claim.',
 wrong:'The passage does not rank the three or call replication projects poorly designed; it treats the project as informative when read correctly.'},
// ---------- Reading Comprehension: passage on urban trees ----------
{id:'GV024',section:'V',type:'RC',sub:'Main idea',skill:'gre_rc',diff:2,
 passage:'Cities planting trees to reduce summer heat have tended to count success in numbers planted. Recent measurements complicate that metric. Cooling depends less on the number of trees than on whether their canopies connect: a continuous canopy shades pavement through the hottest hours, while scattered trees of the same total number leave the pavement exposed and absorb heat that radiates back at night. A street with forty connected trees can be several degrees cooler than one with sixty isolated ones.',
 stem:'The passage is primarily concerned with',
 choices:['comparing summer temperatures across different cities','recommending a specific species for urban planting','arguing that cities should plant fewer but larger trees','showing why a common measure of success is misleading','describing how pavement absorbs and releases heat'],answer:3,
 expl:'The passage names the usual metric, says measurements complicate it, explains why connection matters more than count, and gives a case where fewer trees cool more. That is showing the metric misleads.',
 wrong:'It never recommends a species or fewer trees as such; the point is arrangement, and forty connected trees is an illustration rather than a proposal.'},
{id:'GV025',section:'V',type:'RC',sub:'Inference',skill:'gre_rc',diff:3,
 passage:'Cities planting trees to reduce summer heat have tended to count success in numbers planted. Recent measurements complicate that metric. Cooling depends less on the number of trees than on whether their canopies connect: a continuous canopy shades pavement through the hottest hours, while scattered trees of the same total number leave the pavement exposed and absorb heat that radiates back at night. A street with forty connected trees can be several degrees cooler than one with sixty isolated ones.',
 stem:'The passage suggests that a planting program judged solely by trees planted might',
 choices:['be more expensive than one judged by canopy coverage','lead cities to plant trees only on the hottest streets','underestimate the amount of heat stored in pavement','overstate the cost of urban cooling projects','produce less cooling than a smaller, better arranged program'],answer:4,
 expl:'The final sentence gives exactly this case: forty connected trees cooling more than sixty isolated ones. A count-based program could hit a higher number and cool less.',
 wrong:'Cost is never discussed, and the passage gives no view on which streets get planted.'},
// ---------- Text Completion ----------
{id:'GV026',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:2,
 stem:'The report is valuable less for its conclusions, which are conventional, than for the ______ of the data it assembles, much of which had never been published.',
 choices:['novelty','ambiguity','simplicity','familiarity','brevity'],answer:0,
 expl:'The data had never been published, which makes it new. Novelty contrasts with the conventional conclusions.',
 wrong:'Familiarity reverses the meaning. Brevity and simplicity say nothing about whether the data is new.'},
{id:'GV027',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:3,
 stem:'He wore his learning ______, dropping references so quietly that listeners often realised only afterward how much he had known.',
 choices:['ostentatiously','lightly','defensively','grudgingly','systematically'],answer:1,
 expl:'References dropped quietly, noticed only afterward, describes carrying knowledge without display. Lightly captures that.',
 wrong:'Ostentatiously is the opposite of quietly. Defensively and grudgingly describe attitude toward others rather than manner of display.'},
{id:'GV028',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:4,
 stem:'The commission\'s findings were ______ by the very thoroughness that was meant to establish them: by addressing every objection at length, the report gave the impression of a case that needed defending.',
 choices:['duplicated','vindicated','undermined','clarified','accelerated'],answer:2,
 expl:'The colon explains that thoroughness backfired, making the case look weak. Undermined names that self-defeating effect.',
 wrong:'Vindicated and clarified would mean thoroughness helped, which contradicts the explanation after the colon.'},
{id:'GV029',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:5,
 stem:'Once a discipline treats its founding texts as ______, commentary replaces inquiry: scholars explain what the texts meant rather than asking whether they were right.',
 choices:['contested','obsolete','provisional','canonical','obscure'],answer:3,
 expl:'Treating texts as settled authorities produces commentary instead of inquiry. Canonical names texts accorded that status.',
 wrong:'Provisional and contested would invite the questioning the sentence says stops. Obsolete would end commentary too.'},
// ---------- Sentence Equivalence ----------
{id:'GV030',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:3,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nThe account is ______ enough to be useful but too compressed to settle the question it raises.',
 choices:['cursory','thorough','detailed','specific','rambling','partial'],answer:[2,3],
 expl:'It is useful, so it has enough particulars, yet too compressed to settle anything. Detailed and specific both mean carrying particulars.',
 wrong:'Cursory and partial would not be useful enough. Thorough contradicts "too compressed" and has no partner among the choices.'},
{id:'GV031',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:4,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nWhat began as a ______ objection hardened, over three decades, into the organising principle of an entire school of criticism.',
 choices:['trenchant','offhand','casual','systematic','celebrated','hostile'],answer:[1,2],
 expl:'The contrast with what it hardened into, an organising principle over thirty years, means it started unsystematic and unconsidered. Offhand and casual are that pair.',
 wrong:'Systematic and trenchant describe the end state rather than the beginning, and the sentence needs the contrast.'},
{id:'GV032',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:4,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nThe editor\'s corrections were so ______ that the author scarcely recognised her own chapter.',
 choices:['perfunctory','extensive','sweeping','tactful','belated','arbitrary'],answer:[1,2],
 expl:'Corrections that leave a chapter unrecognisable were far-reaching. Extensive and sweeping both carry that scale.',
 wrong:'Perfunctory is the opposite. Tactful, belated and arbitrary describe manner, timing and reason rather than extent.'},
];
