// bank_sat_math2.js - Original SAT Math items SM039-SM066: Problem-Solving and Data Analysis,
// Geometry and Trigonometry. Four choices per multiple-choice item; answerType 'spr' is a grid-in.
const SAT_TWOWAY1 = '<table class="dtable"><thead><tr><th>Grade</th><th>Chose art</th><th>Chose music</th><th>Total</th></tr></thead><tbody>'+
 '<tr><td>Grade 9</td><td>24</td><td>36</td><td>60</td></tr>'+
 '<tr><td>Grade 10</td><td>30</td><td>10</td><td>40</td></tr>'+
 '<tr><td>Total</td><td>54</td><td>46</td><td>100</td></tr></tbody></table>'+
 '<p class="dnote">Elective chosen by the 100 students in a school survey.</p>';
const SAT_DIST1 = '<table class="dtable"><thead><tr><th>Number of pets</th><th>Number of households</th></tr></thead><tbody>'+
 '<tr><td>0</td><td>7</td></tr><tr><td>1</td><td>10</td></tr><tr><td>2</td><td>6</td></tr>'+
 '<tr><td>3</td><td>2</td></tr><tr><td>8</td><td>1</td></tr></tbody></table>'+
 '<p class="dnote">Pets per household for the 26 households in a neighborhood survey.</p>';
const BANK_SAT_MATH2 = [
// ---------- Problem-Solving and Data Analysis ----------
{id:'SM039',section:'M',type:'MC',sub:'Percentages',skill:'m_psda',diff:1,
 stem:'What is 15 percent of 240?',
 choices:['16','24','36','40'],answer:2,
 expl:'Ten percent of 240 is 24 and five percent is half of that, 12. Adding gives 36.',
 wrong:'Choice B is ten percent only. Splitting a percent into 10 percent and 5 percent pieces is faster than the calculator and keeps the parts visible.'},
{id:'SM040',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:2,
 stem:'Two quantities are in the ratio 3 to 5, and their sum is 64. What is the greater quantity?',
 choices:['24','32','40','48'],answer:2,
 expl:'Write the parts as 3k and 5k. Their sum 8k equals 64, so k = 8 and the greater quantity is 5(8) = 40.',
 wrong:'Choice A is the smaller quantity. Ratio problems are safest with a multiplier k, because the parts add to the total only after k is found.'},
{id:'SM041',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:2,
 stem:'A car travels 150 miles in 2.5 hours at a constant speed. At this speed, how far will it travel in 4 hours?',
 choices:['180 miles','200 miles','240 miles','375 miles'],answer:2,
 expl:'The speed is 150/2.5 = 60 miles per hour, so 4 hours covers 240 miles.',
 wrong:'Choice D multiplies 150 by 2.5 instead of dividing. Find the unit rate first; distance per hour is what carries over to a new number of hours.'},
{id:'SM042',section:'M',type:'MC',sub:'Percentages',skill:'m_psda',diff:3,
 stem:'The price of a monthly transit pass rose from 80 dollars to 92 dollars. What was the percent increase?',
 choices:['12 percent','13 percent','15 percent','18 percent'],answer:2,
 expl:'The increase is 12 dollars on an original price of 80, and 12/80 = 0.15, which is 15 percent.',
 wrong:'Choice B divides by the new price instead of the original. Percent change always uses the starting value as the denominator.'},
{id:'SM043',section:'M',type:'MC',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:3,
 stem:'The mean of five numbers is 18. When one of the numbers, 30, is removed, what is the mean of the remaining four numbers?',
 choices:['12','15','16','18'],answer:1,
 expl:'The five numbers total 5 times 18 = 90. Removing 30 leaves 60 across four numbers, so the new mean is 15.',
 wrong:'Choice D assumes removing a value leaves the mean alone. Convert a mean to a sum before adding or removing anything; sums are what actually change.'},
{id:'SM044',section:'M',type:'MC',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:2,
 stem:'What is the median of the data set 4, 9, 11, 15, 22, 30?',
 choices:['11','13','15','15.2'],answer:1,
 expl:'With an even number of values the median is the mean of the two middle ones: (11 + 15)/2 = 13.',
 wrong:'Choice D is the mean of all six values, which sits above the median here. Choices A and C each take one middle value rather than averaging the pair.'},
{id:'SM045',section:'M',type:'MC',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:4,
 passageHtml:SAT_DIST1,
 stem:'For the households summarized in the table, which statement correctly compares the mean and the median number of pets?',
 choices:['The mean is greater than the median.','The median is greater than the mean.','The mean and the median are equal.','The mean is greater than every value in the data set.'],answer:0,
 expl:'The median is the 13th and 14th values in order, both 1 pet. The total is 0(7) + 1(10) + 2(6) + 3(2) + 8(1) = 36 pets across 26 households, a mean of about 1.4. The single household with 8 pets pulls the mean above the median.',
 wrong:'Choice D overreaches: a mean of 1.4 is well below the value 8. One high outlier drags the mean toward the tail but never past the largest value.'},
{id:'SM046',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:3,
 stem:'A recipe uses 2/3 cup of broth per serving. How many cups of broth are needed for 12 servings?',
 choices:['4','8','18','24'],answer:1,
 expl:'Multiply the per-serving amount by the number of servings: (2/3)(12) = 8 cups.',
 wrong:'Choice C divides 12 by 2/3 instead of multiplying. Ask which quantity is per unit: broth per serving times servings leaves cups.'},
{id:'SM047',section:'M',type:'MC',sub:'Probability and conditional probability',skill:'m_psda',diff:4,
 passageHtml:SAT_TWOWAY1,
 stem:'One student is selected at random from those who chose art. What is the probability that the selected student is in grade 10?',
 choices:['5/9','3/10','24/54','2/5'],answer:0,
 expl:'The selection is restricted to the 54 students who chose art, of whom 30 are in grade 10, so the probability is 30/54 = 5/9.',
 wrong:'Choice B divides by all 100 students. When a question says "from those who," the condition replaces the total; the denominator is the group named, not the whole table.'},
{id:'SM048',section:'M',type:'MC',sub:'Two-variable data: models and scatterplots',skill:'m_psda',diff:4,
 stem:'For a set of used cars of the same model, the line of best fit relating a car age x, in years, to its price y, in dollars, is y = 24000 - 1800x. Which is the best interpretation of 1800 in this model?',
 choices:['The predicted price, in dollars, of a car that is one year old','The predicted decrease in price, in dollars, for each additional year of age','The predicted price, in dollars, of a new car','The number of cars in the data set'],answer:1,
 expl:'In a line of best fit the slope is the predicted change in y per one-unit change in x. The negative sign makes it a decrease of 1800 dollars per year of age.',
 wrong:'Choice C describes 24000, the y-intercept. Slope is always a rate of change; the intercept is the predicted value when x is zero.'},
{id:'SM049',section:'M',type:'MC',sub:'Percentages',skill:'m_psda',diff:5,
 stem:'A jacket price is increased by 20 percent and the new price is later decreased by 20 percent. Compared with the original price, the final price is',
 choices:['the same','4 percent lower','4 percent higher','40 percent lower'],answer:1,
 expl:'Successive percent changes multiply: 1.20 times 0.80 = 0.96, which is 4 percent below the original price.',
 wrong:'Choice A is the trap almost everyone reaches for. The second percent is taken on the raised price, so the decrease is larger in dollars than the increase was.'},
{id:'SM050',section:'M',type:'SPR',answerType:'spr',sub:'Percentages',skill:'m_psda',diff:4,
 stem:'After a 25 percent discount, a shirt costs 45 dollars. What was the price, in dollars, before the discount?',
 choices:[],answer:'60',
 expl:'A 25 percent discount leaves 75 percent of the original price, so 0.75p = 45 and p = 60.',
 wrong:'Adding 25 percent to 45 gives 56.25, which is not the original price. A percent off is taken from the original, so divide by what remains rather than marking the sale price back up.'},
{id:'SM051',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:3,
 stem:'Three identical printers working together print 90 pages in 5 minutes. At this rate, how many pages does one printer print in one minute?',
 choices:['6','18','30','450'],answer:0,
 expl:'The three printers together print 90/5 = 18 pages per minute, so one printer prints 18/3 = 6 pages per minute.',
 wrong:'Choice B is the combined rate, not the rate for one machine. Divide by time and by the number of workers; both are in the denominator.'},
{id:'SM052',section:'M',type:'MC',sub:'Inference from sample statistics and margin of error',skill:'m_psda',diff:5,
 stem:'A random sample of 400 adults in a city was surveyed, and 52 percent said they had visited the public library in the past year, with an associated margin of error of 4 percentage points. Which conclusion is best supported?',
 choices:['Exactly 52 percent of all adults in the city visited the library in the past year.','It is plausible that between 48 percent and 56 percent of all adults in the city visited the library in the past year.','Every adult in the city has a 52 percent chance of visiting the library next year.','More than half of all adults in every city visited a library in the past year.'],answer:1,
 expl:'A sample proportion plus and minus the margin of error gives a plausible interval for the population value, here 48 percent to 56 percent for adults in that city.',
 wrong:'Choice A treats the sample figure as exact, which is what the margin of error exists to deny. Choice D generalizes past the population that was actually sampled.'},
// ---------- Geometry and Trigonometry ----------
{id:'SM053',section:'M',type:'MC',sub:'Lines, angles, and triangles',skill:'m_geo',diff:1,
 stem:'Two angles of a triangle measure 45 degrees and 65 degrees. What is the measure of the third angle?',
 choices:['60 degrees','70 degrees','80 degrees','110 degrees'],answer:1,
 expl:'The angles of a triangle sum to 180 degrees, so the third is 180 - 45 - 65 = 70 degrees.',
 wrong:'Choice D is the sum of the two given angles rather than what remains from 180.'},
{id:'SM054',section:'M',type:'MC',sub:'Circles',skill:'m_geo',diff:2,
 stem:'A circle has a radius of 6. What is its area?',
 choices:['12 pi','24 pi','36 pi','72 pi'],answer:2,
 expl:'Area is pi times the radius squared: pi times 36, or 36 pi.',
 wrong:'Choice A is the circumference, 2 pi r. Area squares the radius; circumference doubles it.'},
{id:'SM055',section:'M',type:'MC',sub:'Right triangles and trigonometry',skill:'m_geo',diff:2,
 stem:'A right triangle has legs of length 9 and 12. What is the length of the hypotenuse?',
 choices:['13','15','18','21'],answer:1,
 expl:'By the Pythagorean theorem, 81 + 144 = 225, and the square root of 225 is 15. This is the 3-4-5 triangle scaled by 3.',
 wrong:'Choice D adds the legs. The hypotenuse is always longer than either leg but shorter than their sum.'},
{id:'SM056',section:'M',type:'MC',sub:'Circles',skill:'m_geo',diff:3,
 stem:'In the xy-plane, a circle is given by (x - 3)^2 + (y + 2)^2 = 25. What are the center and radius of the circle?',
 choices:['Center (3, -2), radius 5','Center (-3, 2), radius 5','Center (3, -2), radius 25','Center (-3, 2), radius 25'],answer:0,
 expl:'In the form (x - h)^2 + (y - k)^2 = r^2 the center is (h, k) and the radius is the square root of the constant. Here y + 2 is y - (-2), so k = -2, and r is the square root of 25, which is 5.',
 wrong:'Choice C reports 25 as the radius. The right side of the equation is the radius squared, never the radius.'},
{id:'SM057',section:'M',type:'MC',sub:'Right triangles and trigonometry',skill:'m_geo',diff:3,
 stem:'In a right triangle, the side opposite angle A has length 7 and the hypotenuse has length 25. What is the value of sin A?',
 choices:['7/24','7/25','24/25','25/7'],answer:1,
 expl:'Sine is the opposite side over the hypotenuse, which is 7/25.',
 wrong:'Choice C is cos A, using the third side 24. Naming which side is opposite the angle before writing the ratio prevents the swap.'},
{id:'SM058',section:'M',type:'MC',sub:'Area and volume',skill:'m_geo',diff:4,
 stem:'Two triangles are similar, and the sides of the larger triangle are 3 times the corresponding sides of the smaller. The area of the smaller triangle is 14. What is the area of the larger triangle?',
 choices:['42','84','126','196'],answer:2,
 expl:'Areas of similar figures scale by the square of the linear scale factor, so the area is 14 times 9 = 126.',
 wrong:'Choice A multiplies the area by 3. A scale factor applies once to lengths, twice to areas, and three times to volumes.'},
{id:'SM059',section:'M',type:'MC',sub:'Area and volume',skill:'m_geo',diff:3,
 stem:'A right circular cylinder has a radius of 3 and a height of 10. What is its volume?',
 choices:['30 pi','60 pi','90 pi','300 pi'],answer:2,
 expl:'Volume is pi times the radius squared times the height: pi times 9 times 10 = 90 pi.',
 wrong:'Choice A multiplies the radius by the height without squaring the radius. Every cylinder and cone volume starts from the area of the circular base.'},
{id:'SM060',section:'M',type:'MC',sub:'Circles',skill:'m_geo',diff:4,
 stem:'A circle has a radius of 10. What is the length of an arc cut off by a central angle of 72 degrees?',
 choices:['2 pi','4 pi','5 pi','20 pi'],answer:1,
 expl:'The arc is 72/360 = 1/5 of the circumference. The circumference is 20 pi, so the arc is 4 pi.',
 wrong:'Choice D is the whole circumference. An arc question always ends in a fraction of the circle, set by the central angle over 360 degrees.'},
{id:'SM061',section:'M',type:'MC',sub:'Right triangles and trigonometry',skill:'m_geo',diff:4,
 stem:'In a 30-60-90 triangle, the hypotenuse has length 12. What is the length of the side opposite the 60 degree angle?',
 choices:['6','6 times the square root of 2','6 times the square root of 3','12 times the square root of 3'],answer:2,
 expl:'The sides are in the ratio 1 to the square root of 3 to 2. With a hypotenuse of 12 the short leg is 6, and the side opposite 60 degrees is 6 times the square root of 3.',
 wrong:'Choice A is the short leg, opposite the 30 degree angle. In every triangle the longer side sits opposite the larger angle, which is a fast way to check.'},
{id:'SM062',section:'M',type:'MC',sub:'Right triangles and trigonometry',skill:'m_geo',diff:5,
 stem:'If sin a = 0.6, where a is an acute angle measured in degrees, what is the value of cos(90 - a)?',
 choices:['0.4','0.6','0.8','1.6'],answer:1,
 expl:'Sine and cosine are cofunctions: cos(90 - a) equals sin a for any acute angle a, so the value is 0.6.',
 wrong:'Choice C is cos a, found from the Pythagorean identity. The question asks about the complement of the angle, where the cofunction relationship applies directly.'},
{id:'SM063',section:'M',type:'MC',sub:'Lines, angles, and triangles',skill:'m_geo',diff:3,
 stem:'Two parallel lines are cut by a transversal. One of the eight angles formed measures 118 degrees. Which of the following must also be the measure of one of the other angles?',
 choices:['32 degrees','62 degrees','78 degrees','118 degrees is the only possible measure'],answer:1,
 expl:'Parallel lines cut by a transversal create only two angle measures, and they are supplementary. The other measure is 180 - 118 = 62 degrees.',
 wrong:'Choice A treats the angles as complementary. Angles on a straight line sum to 180 degrees, not 90.'},
{id:'SM064',section:'M',type:'SPR',answerType:'spr',sub:'Area and volume',skill:'m_geo',diff:4,
 stem:'The length of a rectangle is 5 greater than its width, and the perimeter is 46. What is the width of the rectangle?',
 choices:[],answer:'9',
 expl:'With width w the length is w + 5, so the perimeter is 2(w + w + 5) = 46. Then 2w + 5 = 23, 2w = 18, and w = 9. The length is 14, and 2(9 + 14) = 46.',
 wrong:'Dividing 46 by 4 and adjusting from there ignores that the two dimensions differ. Write the perimeter formula once and let the algebra handle the offset.'},
{id:'SM065',section:'M',type:'MC',sub:'Area and volume',skill:'m_geo',diff:5,
 stem:'Each edge of a cube is tripled. The volume of the new cube is how many times the volume of the original cube?',
 choices:['3','9','18','27'],answer:3,
 expl:'Volume depends on the cube of the edge length, so tripling every edge multiplies the volume by 3^3 = 27.',
 wrong:'Choice B is the area factor, which applies to each face rather than to the solid. Lengths scale by k, areas by k squared, volumes by k cubed.'},
{id:'SM066',section:'M',type:'MC',sub:'Lines, angles, and triangles',skill:'m_geo',diff:4,
 stem:'An isosceles triangle has two sides of length 10 and a perimeter of 26. What is the length of the third side?',
 choices:['3','6','8','16'],answer:1,
 expl:'The two equal sides account for 20, so the third side is 26 - 20 = 6. A triangle with sides 10, 10 and 6 satisfies the triangle inequality.',
 wrong:'Choice D subtracts only one of the equal sides. Read how many sides the given length describes before subtracting from the perimeter.'}
];
