// bank_sat_rw4.js - Original SAT Reading and Writing items SR093-SR126. Third increment, sized
// to carry repeat mock sections without recycling. Subject areas follow the official spec:
// literature, history and social studies, the humanities, and science.
const BANK_SAT_RW4 = [
// ---------- Craft and Structure ----------
{id:'SR093',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:2,
 passage:'Coral reefs occupy less than one percent of the ocean floor yet shelter roughly a quarter of all marine species. The structures that make this possible are built slowly: a colony may add only a centimeter of skeleton in a year. A reef that a storm breaks apart in an afternoon can therefore take decades to ______ .',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['rebuild','relocate','reproduce','recede'],answer:0,
 expl:'The sentence contrasts an afternoon of destruction with a long recovery, and the preceding sentence establishes how slowly skeleton accumulates. What takes decades is putting the structure back.',
 wrong:'Reproduce describes what the animals do, not what happens to the broken structure. The blank has to name the process the slow growth rate governs.'},
{id:'SR094',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'The sculptor worked almost exclusively in cast iron, a material most of her contemporaries considered industrial rather than artistic. She did not argue the point. She simply produced work whose surfaces, pitted and streaked by the casting process itself, made the distinction seem ______ .',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['deliberately provocative','beside the point','historically accurate','technically demanding'],answer:1,
 expl:'She did not argue the point tells you she answered the objection by ignoring it. Work that makes the industrial and artistic distinction seem beside the point dissolves the objection rather than rebutting it.',
 wrong:'Choice A suggests she set out to provoke, but the passage stresses that she declined to engage. The blank must match a response that works by indifference.'},
{id:'SR095',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:4,
 passage:'Accounts of the Haitian Revolution written in nineteenth-century Europe tended to treat it as an eruption without antecedents. Recent scholarship has made that reading difficult to sustain: decades of maroon communities, of legal petitions, and of smaller revolts appear in the colonial archive itself, which suggests the uprising was less a rupture than a ______ .',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['coincidence','miscalculation','culmination','concession'],answer:2,
 expl:'The evidence listed is decades of prior resistance, so the revolution ends a long sequence rather than beginning one. A culmination is exactly that, and it is the natural opposite of a rupture.',
 wrong:'Coincidence denies any connection between the earlier resistance and the uprising, which is the opposite of what the archive evidence is offered to show.'},
{id:'SR096',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'Linguists studying sign languages once faced a persistent assumption that these were ______ systems, gestural approximations of the spoken languages around them. Work beginning in the 1960s established that they possess their own grammar, their own regional variation, and syntactic structures with no counterpart in the surrounding spoken language.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['universal','ancient','regional','derivative'],answer:3,
 expl:'The assumption being corrected is that sign languages merely copy spoken ones, which is what derivative names. The evidence that follows shows independent grammar and structure.',
 wrong:'Choice C names something the passage attributes to sign languages as a fact, not as a mistaken assumption. The blank belongs to the view being overturned.'},
{id:'SR097',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:4,
 passage:'The standard history of the shipping container credits Malcom McLean with inventing it in 1956. Containers of roughly that shape had in fact been in use for decades. What McLean supplied was not the box but the system around it: ships redesigned to hold the boxes in cells, cranes built to the same dimensions, trucks and rail cars that accepted the identical unit, and a tariff structure that made the whole chain cheaper than loose cargo.',
 stem:'Which choice best states the function of the last sentence in the text as a whole?',
 choices:['It specifies the contribution the text argues was actually original.','It provides examples of containers that predated 1956.','It questions whether the shipping container reduced costs.','It explains why historians credit McLean with the invention.'],answer:0,
 expl:'The second sentence removes the box itself from McLean credit, and the last sentence supplies what remains: the system of ships, cranes, vehicles, and tariffs built around it.',
 wrong:'Choice B attaches the list to the wrong claim. The items listed are parts of McLean system, not earlier containers.'},
{id:'SR098',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:4,
 passage:'Every few years a study reports that a common houseplant removes formaldehyde or benzene from indoor air, and the finding travels widely. The original experiments were conducted in sealed chambers of a few hundred liters. A room is thousands of times that volume and exchanges air with the outside continuously. Scaled to a real house, the measured removal rates imply that a living room would need something on the order of a thousand plants to match the effect of opening a window.',
 stem:'Which choice best describes the overall structure of the text?',
 choices:['It contrasts two experiments that reached opposite conclusions about air quality.','It reports a popular claim and then identifies the conditions that make it misleading at ordinary scale.','It recommends a specific number of plants for improving indoor air.','It traces how a scientific finding was deliberately misrepresented.'],answer:1,
 expl:'The text gives the claim, names the chamber conditions behind it, notes how a room differs, and works out what that means at real scale. Claim, then the conditions that undercut it.',
 wrong:'Choice D imputes deliberate misrepresentation the text never alleges. A finding that travels past the conditions it was measured under is not the same as a lie.'},
{id:'SR099',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:3,
 passage:'Mary Shelley began the novel that became Frankenstein at eighteen, during a cold summer on Lake Geneva when volcanic ash from an eruption half a world away had darkened European skies. The weather kept her party indoors and produced the ghost-story contest that prompted the book. It is a tidy origin story, and it explains almost nothing about the novel itself.',
 stem:'Which choice best states the function of the final sentence in the text as a whole?',
 choices:['It disputes the historical accuracy of the events described earlier in the text.','It introduces a different account of how the novel came to be written.','It concedes the appeal of the account just given while denying its explanatory value.','It identifies the aspect of the novel that the origin story best explains.'],answer:2,
 expl:'Calling the story tidy grants its appeal; saying it explains almost nothing about the novel withholds any explanatory weight. The sentence does both at once.',
 wrong:'Choice A is the common misread. The text never doubts that the summer happened as described; it doubts what the summer accounts for.'},
{id:'SR100',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:4,
 passage:'Text 1\nRequiring students to take a course outside their major broadens them. A physics student who studies poetry acquires a way of reading that the physics curriculum cannot supply, and the acquisition is worth a semester.\n\nText 2\nThe argument assumes that a single required course produces the acquisition it describes. Survey data on distribution requirements suggest that students select the courses within them that demand least, complete the work at the minimum, and retain little. The broadening effect appears where students choose the outside field themselves, not where a requirement assigns it.',
 stem:'Based on the texts, the author of Text 2 would most likely argue that the case in Text 1 fails to account for',
 choices:['the cost in tuition of an additional semester of study','the difficulty of teaching poetry to students trained in the sciences','whether physics students have any interest in poetry at all','how students actually behave when a course is required rather than chosen'],answer:3,
 expl:'Text 2 objection is empirical and specific: required courses get minimum effort, and the benefit shows up when the choice is the student own. That is a claim about behavior under a requirement.',
 wrong:'Choice C is close but narrower than Text 2 argument, which is about what requirement does to effort generally, not about interest in one subject.'},
{id:'SR101',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:5,
 passage:'Text 1\nA restored building should read as restored. Filling a gap in a facade with stone cut to match the original deceives the eye and, over time, the record: later observers cannot tell what survived from what was supplied.\n\nText 2\nThe scruple is real but the remedy is often worse. A visibly modern infill draws the eye to itself and away from the composition the building was designed around. Where documentation of the missing element is complete, matching material restores the intended reading, and the record can be kept in the archive rather than written across the wall.',
 stem:'Based on the texts, the author of Text 2 would most likely agree with the author of Text 1 that',
 choices:['distinguishing original from supplied material matters','a visibly modern infill is the best available solution','buildings should be restored only when documentation is complete','the composition of a facade is less important than its material history'],answer:0,
 expl:'Text 2 calls the scruple real and proposes keeping the record in the archive, which accepts that the distinction matters while disputing where it should be recorded.',
 wrong:'Choice B is the position Text 2 argues against. Agreement questions are won by finding the premise both authors share, not the conclusion they split on.'},
// ---------- Information and Ideas ----------
{id:'SR102',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:3,
 passage:'Octavia Butler kept a commonplace book in which she wrote, repeatedly and in the present tense, the terms of a career she did not yet have: the books sold, the audiences reached, the money earned. Biographers have sometimes read these pages as affirmations in the self-help sense. Her drafts suggest something more workmanlike. The same notebooks track word counts, rejection dates, and the specific revisions each rejection prompted.',
 stem:'Which choice best states the main idea of the text?',
 choices:['Butler career progressed more slowly than her early notebooks anticipated.','Butler notebooks record a working method rather than only the aspirations biographers have emphasized.','Commonplace books were a common practice among twentieth-century novelists.','Rejection letters were the primary influence on Butler revisions.'],answer:1,
 expl:'The passage sets the affirmation reading against what the same notebooks also contain, word counts and revisions traced to rejections, and calls that more workmanlike.',
 wrong:'Choice D seizes on one item in the list and promotes it to the main point. A detail offered as evidence for a broader claim is not itself the claim.'},
{id:'SR103',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:4,
 passage:'Economists studying the effect of a new rail line on nearby property values face a problem of direction. Values may rise because the line arrived, or the line may have been routed through areas whose values were already rising fastest. Studies that compare properties near a station with properties far from one cannot separate the two. The more informative comparisons use lines whose routes were fixed by engineering constraints, such as a river crossing, rather than by projected demand.',
 stem:'According to the text, why are lines routed by engineering constraints more informative for this research?',
 choices:['They tend to be built in areas where property values are lower to begin with.','They are more likely to be completed on schedule than other lines.','Their routes were not chosen on the basis of expected growth in property values.','They serve a larger number of properties than demand-routed lines do.'],answer:2,
 expl:'The problem named is that routes may follow areas already rising. A route fixed by a river crossing was not selected for projected demand, which breaks that link.',
 wrong:'Choice A invents a claim about the level of values. The passage cares about why a route was chosen, not about where values started.'},
{id:'SR104',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'A student is writing about the composer Florence Price and has drafted the following claim: Price late works show her drawing on the idioms of Black spirituals within the forms of the European symphonic tradition rather than setting the two apart. The student has collected four observations.',
 stem:'Which observation, if true, would most directly support the student claim?',
 choices:['Price was the first Black woman to have a symphony performed by a major American orchestra, when the Chicago Symphony played her First Symphony in 1933.','Price composed more than three hundred works across every major form, many of which went unpublished during her lifetime and were rediscovered only decades later.','Price studied at the New England Conservatory, where the curriculum emphasized European models and students were drilled in the symphonic forms of the nineteenth century.','In the third movement of her Symphony in E minor, Price replaces the conventional scherzo with a juba dance, keeping the movement structural role while changing its idiom.'],answer:3,
 expl:'The claim is about the two traditions operating together inside one form. Choice D shows a European structural slot filled with a Black vernacular idiom, which is exactly that combination.',
 wrong:'Choice C establishes that she knew the European tradition but says nothing about how she used it alongside another. Half the claim supported is not support.'},
{id:'SR105',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:5,
 passage:'A laboratory reported that mice raised in enriched cages, with tunnels, running wheels, and companions, performed better on a spatial memory task than mice raised in standard cages. The researchers concluded that environmental enrichment improves spatial memory.',
 stem:'Which finding, if true, would most seriously weaken the researchers conclusion?',
 choices:['Enriched-cage mice were substantially more active and completed the task faster without making fewer wrong turns.','Enriched-cage mice weighed slightly more at the end of the study than standard-cage mice.','The spatial memory task had been used in several previous studies of rodent learning.','Standard-cage mice were housed in the same room and on the same light cycle as enriched-cage mice.'],answer:0,
 expl:'If the enriched mice were only faster and not more accurate, the measured advantage reflects activity rather than memory, and the conclusion about memory does not follow.',
 wrong:'Choice D describes good experimental control, which strengthens rather than weakens. The strongest objection reinterprets the result the study already has.'},
{id:'SR106',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:4,
 passage:'Glass is not a true solid in the ordinary sense; its molecules are frozen in a disordered arrangement rather than a lattice. A persistent story holds that medieval window panes are thicker at the bottom because the glass has flowed downward over centuries. Measurements of Roman glass, considerably older, show no such thickening, and the medieval panes were made by a spinning process that produced uneven thickness from the start. The uneven panes therefore ______',
 stem:'Which choice most logically completes the text?',
 choices:['demonstrate that glass flows more slowly than was once believed.','reflect how they were manufactured rather than how they have aged.','were installed with the thicker edge at the bottom for structural reasons.','are thinner overall than panes produced by modern methods.'],answer:1,
 expl:'The passage removes flow as the cause, by way of the older Roman glass, and supplies manufacture as the alternative. The conclusion is that the unevenness is original.',
 wrong:'Choice A keeps the flow explanation alive at a slower rate, but the Roman glass evidence is offered to rule it out, not to slow it down.'},
{id:'SR107',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:5,
 passage:'A city requires restaurants to post a letter grade from its health inspections in the window. Inspectors are assigned to establishments at random, and an appeal of a grade triggers a second inspection by a different inspector. Analysts reviewing five years of data found that appealed grades were revised upward far more often than they were confirmed, and that the size of the revision did not depend on which inspector had issued the original grade. The pattern suggests that the appeal process ______',
 stem:'Which choice most logically completes the text?',
 choices:['identifies the small number of inspectors who grade more harshly than their colleagues.','is used most often by restaurants that received the lowest initial grades.','operates less as a check on individual inspectors than as a general path to a higher grade.','produces grades that are more accurate than those issued in first inspections.'],answer:2,
 expl:'If revisions did not track which inspector graded first, appeals are not correcting particular inspectors. Combined with upgrades far outnumbering confirmations, the process functions as a route to a better grade generally.',
 wrong:'Choice A is what a working check would look like, and the finding that revisions are independent of the original inspector is precisely what rules it out.'},
{id:'SR108',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:3,
 passage:'The Antonine Wall, built across central Scotland around 142 CE, was abandoned within a generation, and Roman forces fell back to Hadrian Wall to the south. Excavation has turned up no evidence of a defeat at the wall itself. What the record does show is a supply line that ran farther than any other on the northern frontier and a garrison drawn from units needed elsewhere as pressures rose along the Danube.',
 stem:'According to the text, what does the archaeological record indicate about the abandonment of the Antonine Wall?',
 choices:['It followed a series of engagements that the Roman garrison lost.','It occurred because Hadrian Wall was a more defensible structure.','It was planned from the time the wall was first constructed.','It is better explained by the costs of supply and competing demands for troops than by a military defeat.'],answer:3,
 expl:'The text reports no evidence of a defeat and then names two things the record does show: an unusually long supply line and troops needed on the Danube.',
 wrong:'Choice B offers a comparison the passage never makes. The fallback position is mentioned only as where the forces went.'},
{id:'SR109',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'Text from a public meeting: "I keep hearing that our library branch closures were driven by falling use. Circulation of physical books did fall. But circulation is one service among many, and the branches we closed were the ones where the other services were busiest."',
 stem:'Which quotation from a library system report would most effectively support the speaker position?',
 choices:['"At the four closed branches, public computer sessions and program attendance were each above the system median in every year from 2021 to 2025."','"Systemwide circulation of physical books declined by 19 percent between 2019 and 2025, continuing a trend visible at every branch in the county."','"The library system operates 22 branches across the county, four of which were closed during the most recent budget cycle."','"Three of the four closed branches were built before 1970 and required significant deferred maintenance, with roof and boiler work deferred repeatedly since 2015."'],answer:0,
 expl:'The speaker concedes falling book circulation and claims the closed branches were busiest in other services. Choice A measures exactly those other services at exactly those branches.',
 wrong:'Choice B restates the half of the argument the speaker already concedes, and choice D supplies a different reason for closure rather than supporting the claim about use.'},
{id:'SR110',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:4,
 passage:'Tree rings record not only a year of growth but the conditions of that year, and a drought leaves a narrow ring in every tree exposed to it. Because the resulting pattern of wide and narrow rings is shared across a region, a beam from a building can be matched to a master sequence built from living trees and older timbers, dating the beam to a single year. The method fails, however, in the wet tropics, where growth is not interrupted by a dry season, which means tropical timbers often ______',
 stem:'Which choice most logically completes the text?',
 choices:['grow more slowly than timbers in temperate regions.','produce rings that are wider than those of temperate trees.','lack the annual boundaries the method depends on.','have been used in construction for a shorter period of time.'],answer:2,
 expl:'The method rests on rings that mark off years, and the passage attributes those to an interrupted growing season. Without the interruption there are no reliable annual boundaries to count or match.',
 wrong:'Choice A mistakes uninterrupted growth for slow growth, which is closer to the opposite. The passage identifies a missing boundary, not a missing quantity.'},
// ---------- Standard English Conventions ----------
{id:'SR111',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'The cartographer worked from three incompatible surveys, each drawn to a different standard and none of them ______ the coastline she produced was accurate to within a few hundred meters.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['complete, even so,','complete. Even so,','complete even so,','complete; even so'],answer:1,
 expl:'Even so is a transitional phrase, not a conjunction, so the two independent clauses need a full stop between them with the transition opening the second.',
 wrong:'Choice A leaves a comma splice with a transitional phrase sitting inside it. Choice D punctuates correctly before but drops the comma the transition needs after.'},
{id:'SR112',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'Three instruments recorded the eruption from different distances: a seismometer twelve kilometers ______ a pressure sensor on the far side of the island, and a satellite passing overhead at the moment of the blast.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['away,','away','away;','away:'],answer:0,
 expl:'The colon has introduced a list of three items, and the items are separated by commas because none of them contains internal commas.',
 wrong:'Choice C mixes separators inside one list. Semicolons belong in a list only when the items themselves contain commas.'},
{id:'SR113',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'Marie Tharp, who plotted thousands of depth soundings by ______ produced the first map to show a continuous rift running the length of the mid-ocean ridge.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['hand','hand;','hand:','hand,'],answer:3,
 expl:'The clause beginning who is nonrestrictive and already opened with a comma after Tharp, so it must close with one before the main verb.',
 wrong:'Choice A opens the interrupting element without closing it. Paired commas come in pairs, and the opening one is already on the page.'},
{id:'SR114',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'The conservators disagreed about almost every step of the treatment plan ______ they agreed about the varnish, which all of them wanted removed.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['; but','but',', but',','],answer:2,
 expl:'Two independent clauses joined by the coordinating conjunction but take a comma before the conjunction.',
 wrong:'Choice A puts a semicolon before a coordinating conjunction, which doubles up the join. Choice D leaves a comma splice with no conjunction at all.'},
{id:'SR115',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:3,
 passage:'The committee reviewing the three proposals ______ its recommendation to the board next month.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['will have submitted','will submit','submitted','have submitted'],answer:1,
 expl:'Next month places the action in the future, and committee is singular, so the simple future will submit is correct.',
 wrong:'Choice A is the future perfect, which describes an action completed before some later future point the sentence never names.'},
{id:'SR116',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'The archive holds letters from seven correspondents, only one of ______ ever met the poet in person.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['whom','who','which','them'],answer:0,
 expl:'The pronoun is the object of the preposition of, which calls for the objective form whom.',
 wrong:'Choice D would leave two independent clauses joined by a comma. The relative pronoun is what makes the second half a clause rather than a sentence.'},
{id:'SR117',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'The two translations differ in how they handle the poem refrain: the earlier one preserves the original meter, while the later one ______ the imagery more closely.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['follow','following','to follow','follows'],answer:3,
 expl:'The subject of the second clause is the later one, which is singular, and it needs a finite verb to parallel preserves in the first clause.',
 wrong:'Choice B leaves the clause without a finite verb, turning the second half into a fragment attached by while.'},
{id:'SR118',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:5,
 passage:'Having been buried under volcanic ash within hours of the eruption, ______',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['archaeologists found the loaves of bread in the bakery nearly intact.','the bakery is where archaeologists found nearly intact loaves of bread.','the loaves of bread in the bakery survived nearly intact.','it was the loaves of bread that archaeologists found nearly intact.'],answer:2,
 expl:'The opening modifier describes whatever was buried within hours of the eruption, which is the loaves, so they must be the subject of the main clause.',
 wrong:'Choice A buries the archaeologists in the eruption. Choice D pushes the loaves into a complement, leaving the expletive it as the grammatical subject the modifier attaches to.'},
// ---------- Expression of Ideas ----------
{id:'SR119',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Emperor penguins breed on sea ice that forms and melts on a predictable annual cycle, and their chicks need that ice to remain stable until their waterproof feathers grow in. In several recent years the ice broke up weeks early at multiple colonies. ______ entire breeding seasons at those colonies produced no surviving chicks.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['In contrast,','As a result,','Admittedly,','Beforehand,'],answer:1,
 expl:'Early ice breakup is the cause and the failure of the breeding season is its consequence, which the chicks dependence on stable ice explains.',
 wrong:'Choice C signals a concession, but the last sentence completes the chain rather than qualifying it.'},
{id:'SR120',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'A widely cited estimate holds that a third of food produced worldwide is lost or wasted. The figure comes from a study that combined national statistics of varying quality, some measured at the farm and some inferred from consumption. ______ it remains the best available number, and the studies published since have not moved it much.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Consequently,','For all that,','Similarly,','In other words,'],answer:1,
 expl:'The middle sentence raises doubts about how the figure was built, and the last defends it anyway. That reversal calls for a concessive transition.',
 wrong:'Choice A makes the defense follow from the doubts, which inverts the logic the passage is running.'},
{id:'SR121',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Restoring a wetland is rarely a matter of simply adding water. The soil chemistry of a drained marsh changes within a few seasons, and the seed bank that would repopulate it may be gone within a decade. ______ a project that reflooded a drained field in the Netherlands spent four years importing seed and adjusting sulfate levels before the first target species established.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Nevertheless,','By comparison,','For example,','Therefore,'],answer:2,
 expl:'The last sentence gives one project as an instance of the difficulty the second sentence describes.',
 wrong:'Choice D would present the Dutch project as a logical consequence of the general claim rather than an illustration of it.'},
{id:'SR122',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'Anonymous peer review is meant to let a reviewer judge a manuscript without regard to who wrote it. In practice, specialists in a small field can often identify an author from the citations and the method alone. ______ removing the name from the title page may do less to remove bias than the practice assumes.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Even then,','On the contrary,','Until recently,','If that is so,'],answer:3,
 expl:'The third sentence draws out what follows conditionally from the second, treating identification by specialists as the premise.',
 wrong:'Choice B signals contradiction, but the last sentence agrees with the second and extends it.'},
{id:'SR123',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The Grand Canal in China runs more than 1,700 kilometers from Beijing to Hangzhou.\n- Sections of it were dug as early as the fifth century BCE.\n- It was linked into a single system under the Sui dynasty around 609 CE.\n- The canal moved grain from the agricultural south to the political north.\n- Parts of it remain in commercial use today.',
 stem:'The student wants to explain the canal purpose in the period after it was unified. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Once the Sui dynasty linked its sections into a single system around 609 CE, the canal carried grain from the agricultural south to the political north.','The Grand Canal runs more than 1,700 kilometers from Beijing to Hangzhou, and parts of it remain in commercial use today.','Sections of the Grand Canal were dug as early as the fifth century BCE, long before the Sui dynasty.','The Grand Canal was linked into a single system under the Sui dynasty around 609 CE.'],answer:0,
 expl:'The goal names both a period and a purpose. Choice A dates the unification and states what the canal then carried and why that mattered.',
 wrong:'Choice D gives the period without the purpose. Goals that pair a time with a function need both halves in the sentence.'},
{id:'SR124',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Wangari Maathai founded the Green Belt Movement in Kenya in 1977.\n- The movement paid rural women a small sum for each seedling that survived.\n- More than 30 million trees were planted through the movement.\n- Maathai received the Nobel Peace Prize in 2004.\n- The Nobel committee cited her contribution to sustainable development, democracy, and peace.',
 stem:'The student wants to explain the design feature that made the movement effective. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Wangari Maathai founded the Green Belt Movement in Kenya in 1977 and received the Nobel Peace Prize in 2004.','The Green Belt Movement paid rural women for each seedling that survived, tying the payment to the outcome rather than to the planting.','More than 30 million trees were planted through the Green Belt Movement.','The Nobel committee cited Maathai contribution to sustainable development, democracy, and peace.'],answer:1,
 expl:'A design feature is a choice about how the program worked. Paying for survival rather than for planting is that choice, and choice B names it and says what it aligned.',
 wrong:'Choice C reports the result the design produced rather than the design. The goal asks what made it effective, not how effective it was.'},
{id:'SR125',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:5,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Vantablack is a coating made of vertically aligned carbon nanotubes.\n- It absorbs more than 99.9 percent of visible light that strikes it.\n- Light entering the forest of nanotubes bounces among them and is absorbed rather than reflected.\n- The coating was developed for calibrating optical instruments and reducing stray light in telescopes.\n- It is fragile and cannot be touched without damage.',
 stem:'The student wants to explain why the coating appears so dark, for an audience unfamiliar with it. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Vantablack absorbs more than 99.9 percent of the visible light that strikes it, a figure almost no other coating approaches.','Vantablack was developed for calibrating optical instruments and for reducing stray light inside telescopes, where a stray reflection degrades the image.','Vantablack is a forest of vertically aligned carbon nanotubes, and light that enters it bounces among the tubes until it is absorbed rather than reflected back to the eye.','Vantablack is fragile and cannot be touched without being damaged, which limits where the coating can be applied.'],answer:2,
 expl:'Explaining why requires the mechanism. Choice C gives the structure and traces what happens to light inside it, which is the reason the surface reads as black.',
 wrong:'Choice A states how dark it is without saying why, which is the distinction the goal turns on.'},
{id:'SR126',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:3,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The passenger pigeon was once among the most numerous birds in North America.\n- Flocks were described as darkening the sky for hours.\n- Commercial hunting expanded rapidly once railroads reached nesting grounds.\n- The last known individual died in a zoo in 1914.\n- The species nested in enormous colonies and bred poorly in small groups.',
 stem:'The student wants to explain why the population collapsed as quickly as it did. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['The passenger pigeon was once among the most numerous birds in North America, and flocks were described as darkening the sky for hours at a time.','The last known passenger pigeon died in a zoo in 1914, only a few decades after observers were still describing flocks that darkened the sky.','Commercial hunting of passenger pigeons expanded rapidly once railroads reached the nesting grounds, putting hunters and shipping within reach of colonies that had been remote.','Because the species nested in enormous colonies and bred poorly in small groups, the commercial hunting that railroads made possible cut the population below the size at which it could recover.'],answer:3,
 expl:'Speed is explained by combining the pressure with the biology. Choice D pairs the railroad-driven hunting with a breeding system that failed once colonies shrank.',
 wrong:'Choice C gives the pressure alone, which explains decline but not why it ran so fast. The note about breeding poorly in small groups is in the list for a reason.'}
];
