// bank_gre_rc2.js - Original GRE Reading Comprehension items GR001-GR026.
//
// Generated by src/mk_bank_gre_rc2.py. Edit that file, not this one.
//
// The last flagged reading gap. GRE Reading Comprehension held 14 items spread across
// three files, the one GRE skill the review bot reported under twenty five. These 26
// take it to 40.
//
// Eight passages in the shape the GRE uses: six short passages of one dense paragraph
// carrying three questions each, and two longer ones carrying four. Subtypes are the
// ones the existing GRE banks use: main idea, inference, function of a sentence, and
// strengthen and weaken.
//
// The existing GRE banks inline the passage text on every item that shares it. These use
// a named constant, which is how the LSAT and ACT banks do it and which stops the same
// paragraph being stored three times in one file.
//
// The corrections every hand written bank needs are in src/bank_emit.py (INC-0001,
// INC-0003, INC-0039, INC-0059, INC-0062).

const GR_PA = "The conventional account of the printing press credits it with the spread of literacy. The causation may run the other way. Presses were capital investments that required a market, and the towns where they were established first were those that already supported scribal workshops, notarial schools and a class of merchants who kept their own accounts. What the press changed was not whether people read but what reading cost, and a fall in cost matters most to those who are already readers.";
const GR_PB = "Reviewers of the manuscript objected that its central claim rested on a single excavated site. The objection is fair as far as it goes, but it mistakes what the claim is. The author does not argue that the practice was widespread; she argues that it existed, which one site can establish, and that its existence is incompatible with the chronology the field has assumed. A counterexample does not need to be typical to do its work.";
const GR_PC = "For decades the sterile male technique was the standard method of suppressing screwworm populations: irradiated males were released in numbers large enough to swamp the wild population, and the females that mated with them produced no offspring. The method worked because female screwworms mate once. Applied to species whose females mate repeatedly, it has largely failed, and the failures were for years attributed to insufficient release numbers rather than to the biology that made the original success possible.";
const GR_PD = "It is often said that the novel form arrived with the eighteenth century. The claim survives because of how the term is defined. Prose narratives of substantial length with invented characters existed in Japan by the eleventh century and in the Hellenistic world well before that. What the eighteenth century produced in England was a market, a critical vocabulary and an audience that read alone and silently, and it is the institution rather than the form that is being dated.";
const GR_PE = "The standard objection to a wealth tax is that it is difficult to administer, since illiquid assets must be valued annually and valuation invites dispute. The objection is sound and it is also not decisive, because every tax base requires valuation of something and the question is comparative. Income is no easier to define at its edges than wealth is, and the fact that a familiar difficulty has been absorbed into routine does not make it a smaller difficulty than an unfamiliar one.";
const GR_PF = "Birds that cache food in autumn and recover it months later show seasonal growth in the hippocampus, and the growth is largest in the species that cache most. The correlation was taken as evidence that caching drives the growth. A complication has since emerged: in several species the enlargement precedes the caching season rather than following it, and in one it occurs in individuals prevented from caching at all. Whatever the hippocampus is responding to, it is not the act of storing food.";
const GR_PG = "The argument that a language shapes the thought of its speakers has had two lives. In its strong form, which held that speakers of a language lacking a distinction cannot make that distinction, it was tested repeatedly through the middle of the twentieth century and abandoned. In its weak form, which holds only that habitual distinctions are made faster and more reliably than unfamiliar ones, it has been confirmed many times and is unsurprising.\n\nThe difficulty is that the weak form is often defended with rhetoric belonging to the strong one. A finding that speakers of a language with obligatory evidential marking attend more closely to sources is reported as showing that they inhabit a different world. They do not; they answer a particular class of question faster, which is what was measured and is worth knowing. The inflation is not harmless, because it invites a refutation of the strong claim to be read as a refutation of the weak one, and the weak one is true.";
const GR_PH = "Peer review is defended on two grounds that are usually run together. The first is that it filters: unsound work is stopped before publication. The second is that it improves: reviewers find errors the author missed and the published version is better than the submitted one. The evidence for the second is reasonably good. The evidence for the first is poor, and the studies that exist suggest reviewers agree with one another barely more than chance would predict on whether a given paper should be accepted.\n\nThis matters for what reform should aim at. If review is mainly a filter, the reasonable response to its unreliability is to strengthen it, with more reviewers and stricter criteria. If it is mainly an improver, the unreliability of the accept and reject decision is close to irrelevant, and the reasonable response is to decouple the two functions: publish more and review after, which is what several fields have begun to do.";

const BANK_GRE_RC2 = [
// ---------- GRPA ----------
{id:'GR001',section:'V',type:'RC',sub:"Main idea",passageId:'GRPA',passage:GR_PA,skill:'gre_rc',diff:3,
 stem:"The primary purpose of the passage is to",
 choices:["argue that the printing press had little effect on the cost of books once it was widely adopted","question the direction of a causal claim about a technology and its social effect","describe the economic conditions under which early presses were financed and established","establish that literacy rates were higher before printing than is usually supposed","compare scribal workshops with the presses that replaced them"],answer:1,
 expl:"It names the conventional account, says the causation may run the other way, and gives the reason: presses went where readers already were.",
 wrong:"No rate is claimed, the financing is a premise rather than the subject, the cost fell on the passage's own account, and the workshops appear only as evidence."},
{id:'GR002',section:'V',type:'RC',sub:"Inference",passageId:'GRPA',passage:GR_PA,skill:'gre_rc',diff:4,
 stem:"The passage suggests that a fall in the cost of reading matter would be of least benefit to",
 choices:["towns that supported notarial schools","merchants who kept their own accounts","a population in which few people could already read","scribes whose livelihoods depended on copying","readers who had previously borrowed rather than bought books from others"],answer:2,
 expl:"The last sentence says a fall in cost matters most to those already reading. Its least effect is therefore where readers are few.",
 wrong:"Merchants, notarial towns and previous borrowers are all readers. Scribes are harmed rather than unbenefited, which is a different thing."},
{id:'GR003',section:'V',type:'RC',sub:"Function of a sentence",passageId:'GRPA',passage:GR_PA,skill:'gre_rc',diff:3,
 stem:"The reference to capital investments serves primarily to",
 choices:["explain why presses appeared first where a reading public already existed","suggest that early printers were motivated chiefly by profit","contrast the expense of printing with the expense of scribal copying at the same volume","indicate that presses were beyond the means of most towns","introduce the objection that the rest of the passage answers"],answer:0,
 expl:"It is the reason presses needed a market, which is the mechanism for the reversed causation.",
 wrong:"No cost comparison is drawn, motive is not the point, affordability is not claimed, and no objection follows."},
// ---------- GRPB ----------
{id:'GR004',section:'V',type:'RC',sub:"Main idea",passageId:'GRPB',passage:GR_PB,skill:'gre_rc',diff:3,
 stem:"The passage is primarily concerned with",
 choices:["defending the practice of drawing conclusions from single archaeological sites in general","explaining why an objection, though accurate, does not tell against the claim it targets","proposing a revised chronology for the period in question","criticising reviewers for failing to read the manuscript carefully enough","establishing that the practice described was more widespread than the reviewers were willing to allow"],answer:1,
 expl:"The objection is called fair as far as it goes and then shown to mistake what the claim is: existence, not prevalence.",
 wrong:"No general defence of single sites is offered, prevalence is expressly not claimed, the reviewers are not accused of carelessness, and no chronology is proposed."},
{id:'GR005',section:'V',type:'RC',sub:"Inference",passageId:'GRPB',passage:GR_PB,skill:'gre_rc',diff:4,
 stem:"The passage implies that the reviewers' objection would have been telling if the author had argued that",
 choices:["the excavation was more carefully conducted than earlier ones","the site had been dated by more than one method before publication","the existing chronology was correct in outline","a counterexample must be typical to be informative about the period","the practice was common across the region and period"],answer:4,
 expl:"The objection is that one site is too little. That bites against a claim of prevalence, which is precisely the claim the author did not make.",
 wrong:"Dating method, the chronology and excavation quality are not what the objection concerns, and the fourth is the principle the passage denies."},
{id:'GR006',section:'V',type:'RC',sub:"Function of a sentence",passageId:'GRPB',passage:GR_PB,skill:'gre_rc',diff:4,
 stem:"The final sentence functions to",
 choices:["concede a limitation that the author will need to address in later work","introduce a second objection that the reviewers had overlooked","state the general principle on which the passage's defence of the author rests","summarise the reviewers' position in its strongest form before answering it","qualify the claim that the practice existed"],answer:2,
 expl:"A counterexample does not need to be typical to do its work is the principle that makes one site sufficient for an existence claim.",
 wrong:"Nothing is conceded or qualified, no second objection appears, and it states the author's defence rather than the reviewers' case."},
// ---------- GRPC ----------
{id:'GR007',section:'V',type:'RC',sub:"Main idea",passageId:'GRPC',passage:GR_PC,skill:'gre_rc',diff:3,
 stem:"The primary purpose of the passage is to",
 choices:["describe the biological mechanism by which irradiation prevents reproduction in released males","identify the condition that made a technique work and explain why its failures were misread","compare the cost of the sterile male technique with that of chemical control over time","argue that the sterile male technique should be abandoned for all species","establish that screwworm populations have been permanently suppressed"],answer:1,
 expl:"The passage names the single mating of female screwworms as the condition, notes the failures elsewhere, and says they were attributed to release numbers rather than to that biology.",
 wrong:"No general abandonment is urged, irradiation is not explained, cost is absent, and permanence is not claimed."},
{id:'GR008',section:'V',type:'RC',sub:"Inference",passageId:'GRPC',passage:GR_PC,skill:'gre_rc',diff:4,
 stem:"It can be inferred from the passage that increasing the number of sterile males released would be least effective in a species whose females",
 choices:["mate several times over their reproductive lives","survive for a shorter period than males do","produce unusually large numbers of offspring in a single generation","disperse widely from their site of emergence","are difficult to distinguish from males in the field"],answer:0,
 expl:"The technique depends on a female's single mating being wasted. Repeated mating gives her other chances, so more releases do not rescue it.",
 wrong:"Fecundity, dispersal, identification and survival are all relevant to control in general but none is the condition the passage isolates."},
{id:'GR009',section:'V',type:'RC',sub:"Strengthen and weaken",passageId:'GRPC',passage:GR_PC,skill:'gre_rc',diff:4,
 stem:"Which of the following, if true, most strengthens the passage's account of why the technique failed in other species?",
 choices:["In a species whose females mate twice, doubling the release rate produced no greater suppression than the original rate.","The irradiation dose used in later programmes was lower than that used against screwworms.","Wild males in later programmes were more numerous than had been estimated.","Sterile males released in later programmes survived for fewer days after release.","Later programmes were conducted over smaller geographic areas than the screwworm campaign."],answer:0,
 expl:"The account says the limit is biological rather than numerical. A doubled release rate achieving nothing is exactly that prediction confirmed.",
 wrong:"Dose, area, wild numbers and survival are all versions of the numerical explanation the passage is arguing against."},
// ---------- GRPD ----------
{id:'GR010',section:'V',type:'RC',sub:"Main idea",passageId:'GRPD',passage:GR_PD,skill:'gre_rc',diff:3,
 stem:"The passage is chiefly concerned with",
 choices:["comparing Hellenistic prose narratives with later European ones","showing that a familiar claim about origins depends on how a term is defined","arguing that critical vocabulary is a prerequisite for any literary form to emerge","establishing that the novel originated in Japan rather than in England in the eleventh century","describing the reading practices of eighteenth century English audiences in some detail"],answer:1,
 expl:"The claim survives because of how the term is defined, and the passage then separates the form from the institution being dated.",
 wrong:"No rival origin is asserted, the reading practices are evidence, no prerequisite claim is made, and no comparison is drawn."},
{id:'GR011',section:'V',type:'RC',sub:"Inference",passageId:'GRPD',passage:GR_PD,skill:'gre_rc',diff:4,
 stem:"The passage implies that a historian who dated the novel to the eighteenth century would be understood by the author to be dating",
 choices:["the earliest surviving prose narrative of substantial length in any language","a claim that the author regards as simply mistaken","the conditions surrounding the form rather than the form itself","the point at which invented characters first appeared in prose narrative","the emergence of silent reading as a private activity among English audiences"],answer:2,
 expl:"The last sentence says it is the institution rather than the form that is being dated, and names the market, the vocabulary and the audience.",
 wrong:"The earlier narratives are granted. Silent reading is one of three conditions rather than the whole. The author calls the claim dependent on definition rather than mistaken."},
{id:'GR012',section:'V',type:'RC',sub:"Function of a sentence",passageId:'GRPD',passage:GR_PD,skill:'gre_rc',diff:3,
 stem:"The reference to Japan and the Hellenistic world serves to",
 choices:["illustrate the difficulty of dating undated manuscripts","show that the defining features of the form predate the period usually given","establish that prose narrative developed independently in several places","question whether length is a useful criterion for identifying a novel","suggest that the English novel was influenced by earlier traditions from outside Europe"],answer:1,
 expl:"They are instances of prose narratives of substantial length with invented characters, which is the definition the sentence before supplies.",
 wrong:"No influence is claimed, independence is not the point being made, length is used rather than questioned, and dating difficulty is absent."},
// ---------- GRPE ----------
{id:'GR013',section:'V',type:'RC',sub:"Main idea",passageId:'GRPE',passage:GR_PE,skill:'gre_rc',diff:3,
 stem:"The primary purpose of the passage is to",
 choices:["argue that valuation disputes are rare in practice","establish that income is impossible to define at its edges in any tax code","recommend that wealth be taxed at the same rate as income","grant an objection while denying that it settles the question","demonstrate that a wealth tax would be simpler to administer than an income tax"],answer:3,
 expl:"The objection is called sound and also not decisive, and the reason given is that the question is comparative.",
 wrong:"Simpler is stronger than the passage claims. Disputes are granted, no rate is recommended, and income is called no easier rather than impossible."},
{id:'GR014',section:'V',type:'RC',sub:"Inference",passageId:'GRPE',passage:GR_PE,skill:'gre_rc',diff:4,
 stem:"The passage suggests that the familiarity of a difficulty can",
 choices:["reduce the number of disputes that the difficulty generates","indicate that the difficulty has in fact been solved by administrators","justify treating the tax base that carries it as preferable","make it harder to measure the cost of administering a tax of either kind","make it seem smaller than a comparable unfamiliar one"],answer:4,
 expl:"The last clause says absorbing a familiar difficulty into routine does not make it a smaller difficulty than an unfamiliar one, which implies it looks smaller.",
 wrong:"Fewer disputes, solution and justification are all things the passage denies follow, and measurement cost is not discussed."},
{id:'GR015',section:'V',type:'RC',sub:"Strengthen and weaken",passageId:'GRPE',passage:GR_PE,skill:'gre_rc',diff:5,
 stem:"Which of the following, if true, would most weaken the passage's argument?",
 choices:["Income tax codes have grown substantially longer over the past century.","Wealth is distributed more unequally than income in most countries.","Most household wealth in developed economies is held in liquid form.","Valuation disputes over illiquid assets consume several times the administrative resources that income definition disputes do.","Several countries that adopted a wealth tax later repealed it within a decade."],answer:3,
 expl:"The argument is that the comparison is what matters and that familiarity disguises the income side. A large measured gap in the comparison is what would defeat it.",
 wrong:"Repeal has many causes, liquid holdings would help the argument, code length is ambiguous, and distribution is a different question."},
// ---------- GRPF ----------
{id:'GR016',section:'V',type:'RC',sub:"Main idea",passageId:'GRPF',passage:GR_PF,skill:'gre_rc',diff:3,
 stem:"The primary purpose of the passage is to",
 choices:["report evidence that unsettles an accepted explanation of a correlation","propose an alternative cause for the enlargement observed in the caching species","establish that hippocampal growth is unrelated to food caching in any species","describe the seasonal behaviour of birds that store food","argue that correlational evidence is unreliable in behavioural ecology generally"],answer:0,
 expl:"The correlation and its accepted reading are stated, then the timing and the prevented individuals complicate it, and the passage stops short of an alternative.",
 wrong:"Unrelated is stronger than the evidence given. The behaviour is background, no general claim about correlation is made, and no alternative is proposed."},
{id:'GR017',section:'V',type:'RC',sub:"Inference",passageId:'GRPF',passage:GR_PF,skill:'gre_rc',diff:4,
 stem:"The finding about individuals prevented from caching is significant because it",
 choices:["establishes that caching is unnecessary for winter survival","separates the enlargement from the behaviour it was thought to result from","suggests that the birds were prevented from caching too late in the season","shows that the enlargement is larger in species that cache more","confirms that the enlargement is seasonal rather than permanent in those species"],answer:1,
 expl:"If the enlargement occurs without caching, caching cannot be what produces it, which is the passage's conclusion.",
 wrong:"The species comparison is the original correlation. Seasonality is assumed throughout. Survival is not discussed, and the timing objection would undercut rather than explain the finding."},
{id:'GR018',section:'V',type:'RC',sub:"Function of a sentence",passageId:'GRPF',passage:GR_PF,skill:'gre_rc',diff:4,
 stem:"The last sentence of the passage functions to",
 choices:["state what the evidence rules out without asserting what is responsible","identify the environmental cue that triggers the enlargement","recommend a particular design for future experiments on the question","summarise the correlation described at the start of the passage","concede that the complication may prove to be an artefact"],answer:0,
 expl:"Whatever the hippocampus is responding to, it is not the act of storing food, which excludes a cause without naming one.",
 wrong:"No cue is identified, the correlation is not restated, nothing is conceded as artefact, and no design is recommended."},
// ---------- GRPG ----------
{id:'GR019',section:'V',type:'RC',sub:"Main idea",passageId:'GRPG',passage:GR_PG,skill:'gre_rc',diff:4,
 stem:"The primary purpose of the passage is to",
 choices:["establish that habitual distinctions are made faster than unfamiliar ones by speakers","distinguish two versions of a claim and object to how the weaker one is presented","report experimental findings about speakers of languages with evidential marking in particular","argue that linguistic relativity has been refuted in all its forms","trace the history of a hypothesis from its formulation to its abandonment in the strong form"],answer:1,
 expl:"The two forms are separated, the weak one is called true, and the objection is that it is defended with rhetoric belonging to the strong one.",
 wrong:"The weak form is affirmed rather than refuted. The evidential finding is an example, the speed result is granted rather than established here, and the history is compressed background."},
{id:'GR020',section:'V',type:'RC',sub:"Inference",passageId:'GRPG',passage:GR_PG,skill:'gre_rc',diff:5,
 stem:"The passage suggests that the inflation it describes is harmful chiefly because it",
 choices:["exaggerates the speed advantage that the experiments actually measured","implies that speakers of some languages are incapable of certain thoughts","discourages researchers from testing the strong form of the claim experimentally","allows a refutation of the strong claim to be taken as a refutation of the weak one","makes the weak form difficult to distinguish from an untestable assertion about experience"],answer:3,
 expl:"The last sentence says exactly this and adds that the weak one is true.",
 wrong:"The speed result is reported accurately; the inflation is in the interpretation. Testing, incapacity and testability are not the stated harm."},
{id:'GR021',section:'V',type:'RC',sub:"Function of a sentence",passageId:'GRPG',passage:GR_PG,skill:'gre_rc',diff:4,
 stem:"The statement that they answer a particular class of question faster serves to",
 choices:["introduce a distinction between speed and accuracy of response","concede that the evidential marking result has not been replicated","restate a reported finding in terms of what was actually measured","establish that evidential marking is unusual among languages of the world","suggest that the finding is too small to be of interest"],answer:2,
 expl:"It follows they do not, and replaces inhabiting a different world with the measurement, then says it is worth knowing.",
 wrong:"No replication issue is raised, speed and accuracy are not separated, the finding is called worth knowing, and frequency across languages is not the point."},
{id:'GR022',section:'V',type:'RC',sub:"Strengthen and weaken",passageId:'GRPG',passage:GR_PG,skill:'gre_rc',diff:5,
 stem:"Which of the following, if true, would most undermine the passage's characterisation of the weak form?",
 choices:["The strong form of the claim was defended by researchers who also endorsed the weak form.","Evidential marking is obligatory in a smaller number of languages than was once believed.","Speakers showed no advantage on distinctions their language marks obligatorily once education was controlled for.","Speakers of languages without evidential marking can be trained to attend to sources.","Some experiments on habitual distinctions have used very small samples of speakers."],answer:2,
 expl:"The passage calls the weak form confirmed many times. Removing the advantage once education is controlled would remove the confirmation itself.",
 wrong:"Who defended what, how many languages mark evidentiality, individual sample sizes and trainability all leave the confirmed effect standing."},
// ---------- GRPH ----------
{id:'GR023',section:'V',type:'RC',sub:"Main idea",passageId:'GRPH',passage:GR_PH,skill:'gre_rc',diff:4,
 stem:"The primary purpose of the passage is to",
 choices:["describe the reforms that several fields have recently adopted in place of review before publication","demonstrate that peer review improves the papers it is applied to before publication","establish that reviewers disagree with one another more often than they agree","separate two functions of a practice and draw out what follows for how it should be changed","argue that peer review should be abolished in favour of publishing everything"],answer:3,
 expl:"The filter and the improver are separated, the evidence for each is weighed, and the final paragraph says what each account implies for reform.",
 wrong:"Abolition is not urged. The agreement statistic is evidence rather than the point. The reforms are an illustration, and the improvement claim is one half of the distinction."},
{id:'GR024',section:'V',type:'RC',sub:"Inference",passageId:'GRPH',passage:GR_PH,skill:'gre_rc',diff:5,
 stem:"According to the passage, someone who believed peer review functions mainly as a filter would most likely favour",
 choices:["abandoning the requirement that reviewers agree with one another before a decision","separating the decision to publish from the effort to improve a paper before it appears","publishing submissions promptly and collecting reviews afterwards","measuring the improvement between submitted and published versions of the same paper","increasing the number of reviewers and tightening the criteria for acceptance"],answer:4,
 expl:"The final paragraph states that response directly for the filter account.",
 wrong:"The other four belong to the improver account or to measurement rather than to strengthening the filter."},
{id:'GR025',section:'V',type:'RC',sub:"Function of a sentence",passageId:'GRPH',passage:GR_PH,skill:'gre_rc',diff:4,
 stem:"The observation that reviewers agree barely more than chance would predict is offered as",
 choices:["a concession that weakens the passage's own position on reform","evidence bearing on one of the two defences the passage distinguishes","a reason to doubt that peer review improves the papers it is applied to","the main conclusion for which the rest of the passage argues","an explanation of why several fields have begun publishing before review"],answer:1,
 expl:"It sits in the paragraph weighing the evidence, and it bears on the filter defence specifically.",
 wrong:"The conclusion is about reform. It bears on filtering rather than improving, it is evidence rather than an explanation of the reforms, and the passage has no position it weakens."},
{id:'GR026',section:'V',type:'RC',sub:"Strengthen and weaken",passageId:'GRPH',passage:GR_PH,skill:'gre_rc',diff:5,
 stem:"Which of the following, if true, would most strengthen the case for the decoupling the passage describes?",
 choices:["Papers rejected by one journal and published unchanged by another are cited at the same rate as papers accepted first time.","The number of papers submitted for review has risen faster than the number of reviewers.","Journals that publish more papers receive more submissions the following year.","Most authors report that reviewer comments improved their manuscripts.","Reviewers spend more time on papers they expect to recommend for acceptance."],answer:0,
 expl:"Decoupling assumes the accept and reject decision carries little information. Equal citation rates for papers that failed it are that assumption confirmed.",
 wrong:"Reviewer effort, author satisfaction, submission volume and reviewer supply bear on the practice without testing whether the decision is informative."},
];
