// bank_sat_rw3.js - Original SAT Reading and Writing items SR063-SR092. Second increment,
// weighted toward Expression of Ideas (the thinnest domain) and adding the quantitative
// Command of Evidence format, where the evidence is a table rather than a sentence.
const RW_TABLE1 = '<div class="passage">Researchers tracking four urban beehives recorded the share of foraging trips that ended at each of four plant types over one season. The team expected hives closer to the restored meadow to rely more heavily on native wildflowers than hives sited on rooftops downtown. The data bear this out: at the meadow-adjacent hive, ______</div>'+
 '<table class="dtable"><thead><tr><th>Hive</th><th>Native wildflowers</th><th>Ornamental garden plants</th><th>Street trees</th><th>Other</th></tr></thead><tbody>'+
 '<tr><td>Meadow edge</td><td>61%</td><td>14%</td><td>19%</td><td>6%</td></tr>'+
 '<tr><td>Riverside</td><td>43%</td><td>22%</td><td>28%</td><td>7%</td></tr>'+
 '<tr><td>Downtown roof A</td><td>18%</td><td>37%</td><td>39%</td><td>6%</td></tr>'+
 '<tr><td>Downtown roof B</td><td>15%</td><td>41%</td><td>36%</td><td>8%</td></tr></tbody></table>'+
 '<p class="dnote">Share of recorded foraging trips by plant type, one season.</p>';
const RW_TABLE2 = '<div class="passage">A museum tested whether adding a short interpretive label beside a work changed how long visitors stayed with it. Staff timed visitors at four works, first with the standard title card alone and then with an added label of about sixty words. The effect was not uniform: the increase was largest for the work that had held visitors for the shortest time to begin with, which suggests that ______</div>'+
 '<table class="dtable"><thead><tr><th>Work</th><th>Median dwell time, title card only</th><th>Median dwell time, with added label</th></tr></thead><tbody>'+
 '<tr><td>Portrait of a Surveyor</td><td>11 seconds</td><td>34 seconds</td></tr>'+
 '<tr><td>Harbor at Dusk</td><td>26 seconds</td><td>41 seconds</td></tr>'+
 '<tr><td>Study in Grey</td><td>38 seconds</td><td>47 seconds</td></tr>'+
 '<tr><td>The Glassblowers</td><td>52 seconds</td><td>55 seconds</td></tr></tbody></table>'+
 '<p class="dnote">Median time visitors spent at each work, before and after the added label.</p>';
const RW_TABLE3 = '<div class="passage">A transit agency replaced printed timetables at four stops with screens showing live arrival predictions. Riders surveyed afterward reported less uncertainty about wait times, and the agency wanted to know whether reported uncertainty tracked the accuracy of the predictions rather than their mere presence. The stop with the least accurate predictions is instructive: ______</div>'+
 '<table class="dtable"><thead><tr><th>Stop</th><th>Median prediction error</th><th>Riders reporting low uncertainty</th></tr></thead><tbody>'+
 '<tr><td>Ash Street</td><td>0.6 minutes</td><td>84%</td></tr>'+
 '<tr><td>Beech Lane</td><td>1.1 minutes</td><td>79%</td></tr>'+
 '<tr><td>Cypress Park</td><td>2.4 minutes</td><td>66%</td></tr>'+
 '<tr><td>Delta Yard</td><td>4.8 minutes</td><td>41%</td></tr></tbody></table>'+
 '<p class="dnote">Prediction accuracy and survey response by stop, after the screens were installed.</p>';
const BANK_SAT_RW3 = [
// ---------- Information and Ideas: quantitative Command of Evidence ----------
{id:'SR063',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passageHtml:RW_TABLE1,
 stem:'Which choice most effectively uses data from the table to complete the text?',
 choices:['61 percent of foraging trips ended at native wildflowers, compared with 18 percent and 15 percent at the two downtown rooftop hives.','native wildflowers accounted for a smaller share of trips than street trees did.','ornamental garden plants accounted for 14 percent of trips, the lowest such share of any hive.','trips to street trees made up 19 percent of the total, more than at either downtown hive.'],answer:0,
 expl:'The claim is that the meadow-adjacent hive relies more on native wildflowers than the downtown hives do. Choice A reports that hive wildflower share and sets it against both downtown figures, which is exactly the comparison the claim makes.',
 wrong:'Choice C reads the table correctly but reports the wrong column: the claim is about wildflowers, not ornamentals. Choice D reverses a comparison the table does not support, since both downtown hives show higher street tree shares.'},
{id:'SR064',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:5,
 passageHtml:RW_TABLE2,
 stem:'Which choice most effectively uses data from the table to complete the text?',
 choices:['the labels do the most for works that visitors would otherwise pass quickly, since dwell time at Portrait of a Surveyor rose from 11 to 34 seconds while The Glassblowers rose only from 52 to 55.','the labels raised dwell time at every work, with Study in Grey rising from 38 to 47 seconds.','visitors spend longer with works whose titles are more descriptive, as Harbor at Dusk shows.','the added labels had no measurable effect on works that already held visitors for more than 30 seconds.'],answer:0,
 expl:'The sentence commits to the work with the shortest starting dwell time gaining most. Choice A names that work, gives both of its figures, and contrasts them with the work that started highest and gained least.',
 wrong:'Choice B is true but supports a different claim, that the labels helped everywhere. Choice D overstates: Study in Grey started above 30 seconds and still gained 9.'},
{id:'SR065',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passageHtml:RW_TABLE3,
 stem:'Which choice most effectively uses data from the table to complete the text?',
 choices:['at Delta Yard, where the median prediction error was 4.8 minutes, only 41 percent of riders reported low uncertainty.','at Delta Yard, the median prediction error was 4.8 minutes, the highest of the four stops.','Ash Street had both the smallest prediction error and the highest share of riders reporting low uncertainty.','riders at Cypress Park reported low uncertainty at a rate of 66 percent.'],answer:0,
 expl:'The agency question is whether reported uncertainty tracks accuracy rather than the presence of the screens. Choice A pairs the worst accuracy with the lowest share reporting low uncertainty, which is the pairing the sentence sets up.',
 wrong:'Choice B gives only the error and choice D only the survey figure, so neither shows the two moving together. Choice C is the right kind of pairing at the wrong stop: the sentence promised the least accurate one.'},
{id:'SR066',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:3,
 passage:'When the sociologist Elijah Anderson studied a public market in a segregated city, he was struck less by what happened there than by what did not. People who elsewhere kept to their own neighborhoods shared benches, asked each other for directions, and queued together without incident. Anderson called such places cosmopolitan canopies and argued that their value lies in rehearsal: brief, low-stakes contact that makes later contact easier.',
 stem:'Which choice best states the main idea of the text?',
 choices:['Ordinary shared spaces can provide practice at everyday contact across social divides.','Public markets attract more visitors than other civic spaces in segregated cities.','Segregation in American cities has declined faster than sociologists predicted.','People behave more politely in crowded settings than in uncrowded ones.'],answer:0,
 expl:'The passage defines the canopy by what it makes possible: brief, low-stakes contact that Anderson describes as rehearsal for later contact.',
 wrong:'Choice C makes a claim about a trend the passage never measures. A main idea has to be the point the text argues, not a topic it sits near.'},
{id:'SR067',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:4,
 passage:'Conventional wisdom held that the woolly mammoth vanished at the close of the last ice age, roughly ten thousand years ago. Sediment cores and radiocarbon dates from Wrangel Island, off the Siberian coast, tell a different story: a population survived there until about four thousand years ago, when the pyramids at Giza already stood. The island was cut off by rising seas early in that interval, which means the mammoths that lived on it were ______',
 stem:'Which choice most logically completes the text?',
 choices:['isolated from the mainland population for thousands of years.','larger than their mainland relatives had been.','hunted more intensively than mainland mammoths.','the first mammoths to reach the Siberian coast.'],answer:0,
 expl:'The text states that rising seas cut the island off early in an interval lasting thousands of years, so a population living there after that point had no mainland contact.',
 wrong:'Choices B and C are claims the passage gives no basis for. An inference must follow from the sentences on the page, not from what is generally known about island populations.'},
{id:'SR068',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'A student is writing about the Dutch engineer Cornelis Lely and has drafted the following claim: Lely design for enclosing the Zuiderzee was adopted only after a disaster made the case he had been making for decades. The student has gathered four facts.',
 stem:'Which fact, if true, would most directly support the claim?',
 choices:['Lely published his enclosure plan in 1891, and the Dutch parliament authorized construction in 1918, months after a flood killed dozens and inundated villages around the bay.','Lely served as minister of transport and public works on three separate occasions.','The enclosing dam was completed in 1932 and is more than thirty kilometers long.','Several engineers had proposed enclosing the Zuiderzee before Lely published his plan.'],answer:0,
 expl:'The claim links a long delay to a specific triggering disaster. Choice A supplies the interval, the authorization, and the flood that preceded it by months.',
 wrong:'Choice C describes the finished structure and choice B his career, neither of which speaks to why the plan was adopted when it was.'},
{id:'SR069',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:4,
 passage:'Instrument makers in seventeenth-century Delft ground their own lenses, and the quality of a microscope depended less on its design than on the hand that shaped its glass. Antonie van Leeuwenhoek kept his grinding method secret, and no contemporary reproduced the magnifications he reported. For more than a century his observations of what he called animalcules were accepted largely on the testimony of witnesses he invited to look, rather than on any independent confirmation.',
 stem:'According to the text, van Leeuwenhoek observations were accepted mainly because',
 choices:['witnesses he invited confirmed what they had seen through his lenses','other instrument makers replicated his grinding method','his microscope design was widely copied across Europe','his reported magnifications matched theoretical predictions'],answer:0,
 expl:'The last sentence says the observations rested on the testimony of witnesses he invited to look, rather than on independent confirmation.',
 wrong:'Choice B contradicts the passage, which says no contemporary reproduced his magnifications. Detail questions often offer the exact thing the text denies.'},
{id:'SR070',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:5,
 passage:'A pharmacologist testing a compound in cell culture reported a striking effect at a concentration of 40 micromolar. A colleague noted that the drug binds tightly to serum albumin, a protein abundant in blood but absent from the culture medium used, and that plasma concentrations in treated patients rarely exceed 5 micromolar of unbound drug. The colleague concern is that results obtained in that medium may ______',
 stem:'Which choice most logically completes the text?',
 choices:['overstate the effect the compound would produce in the body.','apply only to compounds that do not bind serum proteins.','be impossible to reproduce in any other laboratory.','understate how much of the compound reaches its target.'],answer:0,
 expl:'Without albumin to bind it, far more of the compound stays free in the culture than would in blood, and the tested concentration is eight times the unbound level patients reach. The culture result therefore flatters the drug.',
 wrong:'Choice D reverses the direction. The absence of the binding protein means more free drug in the dish, not less, which is the whole basis of the colleague objection.'},
// ---------- Craft and Structure ----------
{id:'SR071',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'The first histories of the Silk Road described a single highway carrying goods from China to the Mediterranean. Archaeology has made that picture look ______: what existed was a shifting web of shorter routes, most traders covering only a segment of it, with goods changing hands many times before arriving anywhere.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['too tidy','entirely false','newly urgent','deliberately vague'],answer:0,
 expl:'The correction is not that the old picture was invented but that it was simpler than the evidence supports. A shifting web replacing a single highway makes the old account too tidy.',
 wrong:'Choice B overshoots: the passage keeps the trade and the destinations, and revises only the shape of the network. Precision items punish the strongest available word.'},
{id:'SR072',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:4,
 passage:'Reviewers of the choreographer first evening-length work often reached for the word austere, and the label stuck. It fit the bare stage and the absence of score for long stretches. It fit less well the dancing itself, which was ______ in its detail: a shift of weight in one dancer hip would be answered, four counts later, across the stage.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['lavish','sparse','erratic','conventional'],answer:0,
 expl:'The colon supplies the evidence: an elaborate call and response of small gestures. The sentence sets the dancing against the austere label, so the blank must be its opposite.',
 wrong:'Choice B agrees with the label the sentence is pushing back on. The phrase fit less well marks the turn, and the blank sits after the turn.'},
{id:'SR073',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:4,
 passage:'Every account of the discovery of penicillin begins with a contaminated culture plate, and most stop there. The mold that drifted into Alexander Fleming laboratory in 1928 was indeed a matter of chance. Turning the observation into a usable drug was not: it took a decade, a separate team at Oxford, a method for producing the compound in quantity, and a war that made the effort urgent enough to fund.',
 stem:'Which choice best describes the overall structure of the text?',
 choices:['It acknowledges a familiar element of a story and then argues that the element accounts for only part of it.','It disputes the accuracy of a widely repeated anecdote about a scientific discovery.','It compares the contributions of two research teams working on the same problem.','It traces the development of a drug from laboratory to mass production in chronological order.'],answer:0,
 expl:'The passage grants that the contamination was chance, then lists everything else that was required. It concedes and then enlarges.',
 wrong:'Choice B is the confident misread: the text never says the plate story is false, only that it is incomplete. Conceding a point is not disputing it.'},
{id:'SR074',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:3,
 passage:'Botanists had long assumed that a plant response to touch was a curiosity of a few species such as the Venus flytrap. Then experiments showed that brushing the leaves of ordinary thale cress triggers a wave of calcium signaling within seconds and alters the plant growth for days. Whatever else touch sensitivity is, it is not rare.',
 stem:'Which choice best states the function of the final sentence in the text as a whole?',
 choices:['It draws the conclusion that the experimental result forces on the prior assumption.','It proposes an explanation for the calcium signaling described in the second sentence.','It qualifies the experimental result by noting a limit on its scope.','It restates the assumption described in the first sentence.'],answer:0,
 expl:'The first sentence states the assumption that touch sensitivity is confined to a few species; the second gives the finding; the third states what the finding does to the assumption.',
 wrong:'Choice C reads the concessive opening of the sentence as a limit, but whatever else touch sensitivity is grants everything else in order to insist on one point.'},
{id:'SR075',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:5,
 passage:'Text 1\nOpen-plan offices were designed to increase collaboration. Removing walls, the reasoning went, removes the friction of walking down a corridor and knocking on a door, and colleagues who can see each other will talk more.\n\nText 2\nWhen one firm converted to an open plan, sensors recorded a sharp fall in face-to-face interaction and a rise in electronic messaging. Employees appear to have responded to the loss of privacy by withdrawing, using headphones and screens to rebuild the boundary the walls had provided.',
 stem:'Based on the texts, the author of Text 2 would most likely characterize the reasoning in Text 1 as',
 choices:['plausible but contradicted by what employees actually did','correct about collaboration but wrong about the cost of the renovation','applicable only to firms whose employees already knew each other well','a fair description of how walls affect the movement of employees'],answer:0,
 expl:'Text 2 does not argue the reasoning is incoherent; it reports measurements showing the opposite of what the reasoning predicted, and offers a mechanism for the reversal.',
 wrong:'Choice D endorses the premise about walls, but Text 2 shows employees rebuilding the boundary by other means, which cuts against the premise rather than granting it.'},
{id:'SR076',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:4,
 passage:'Text 1\nA museum that holds an object taken during a colonial occupation should return it. The claim of the community it came from is older and stronger than any claim a purchaser can acquire, and no amount of careful stewardship converts a wrong into a title.\n\nText 2\nThe principle is easier to state than to apply. Many objects passed through a dozen hands, some of them legitimate; some source communities no longer exist as political entities, while several successor bodies may claim the same object. A rule that says return it settles who should not hold an object without settling who should.',
 stem:'Based on the texts, the author of Text 2 would most likely respond to the claim in Text 1 by',
 choices:['accepting its moral force while noting that it does not identify a recipient','arguing that careful stewardship can in fact establish a valid title','denying that any object in a museum was taken under colonial occupation','contending that the age of a claim has no bearing on its strength'],answer:0,
 expl:'Text 2 calls the principle easier to state than to apply and ends by saying it settles who should not hold an object without settling who should, which grants the principle and challenges its implementation.',
 wrong:'Choice B contradicts a point Text 2 never disputes. The objection is about identifying the rightful recipient, not about whether the current holder has title.'},
// ---------- Standard English Conventions ----------
{id:'SR077',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'The harvest depends on a single week in ______ the flowers open, the bees work, and the crop is set for the year.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['spring:','spring,','spring','spring; when'],answer:0,
 expl:'A complete sentence precedes the blank, and the list that follows spells out what happens in that week. A colon after an independent clause introduces it.',
 wrong:'Choice B leaves three independent clauses joined by commas. The colon is available because the second half explains the first.'},
{id:'SR078',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'Lin-Manuel Miranda first performed an early version of the opening number at a White House poetry ______ six years before the show reached Broadway.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['evening,','evening;','evening','evening:'],answer:2,
 expl:'The closing phrase is a simple modifier of the verb performed, not an independent clause, so no punctuation separates it from what it modifies.',
 wrong:'Choice B joins a sentence to a fragment with a semicolon, which requires complete sentences on both sides. Six years before the show reached Broadway cannot stand alone.'},
{id:'SR079',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'The expedition brought back three things no previous survey had ______ a complete tidal record, photographs of the inner glacier, and an accurate chart of the approach.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['produced:','produced,','produced;','produced'],answer:0,
 expl:'The words before the blank form a complete sentence, and what follows is the list it promises. That is the colon.',
 wrong:'Choice C would need an independent clause after it. A list of noun phrases is not a sentence, so a semicolon cannot introduce it.'},
{id:'SR080',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:3,
 passage:'Neither the conductor nor the soloists ______ seen the revised score before the morning of the performance.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['had','has','was','is'],answer:0,
 expl:'With neither and nor, the verb agrees with the nearer subject, which is the plural soloists. Had works for either number here, while has does not.',
 wrong:'Choice B agrees with conductor, the farther subject. In a neither-nor pair the verb looks to whichever subject sits closest to it.'},
{id:'SR081',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'The survey team recorded more nesting sites in the northern valley than ______ in the southern valley the previous season.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['it had recorded','they had recorded','it had record','recording'],answer:0,
 expl:'The subject is team, a singular noun in American usage, and the earlier season calls for the past perfect had recorded.',
 wrong:'Choice B treats team as plural. Collective nouns such as team, committee and jury take singular verbs and singular pronouns on this exam.'},
{id:'SR082',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'Sealed in a dry cave for two thousand years, ______',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['the scrolls survived in a condition no one had expected.','researchers found the scrolls in a condition no one had expected.','the condition of the scrolls was better than anyone had expected.','it was a surprise to researchers how well the scrolls had survived.'],answer:0,
 expl:'The opening modifier describes what was sealed in the cave, and that is the scrolls, so the scrolls must be the subject of the main clause.',
 wrong:'Choice B puts researchers in the cave for two thousand years, and choice C puts the condition there. Ask what the opening phrase describes, then make it the subject.'},
// ---------- Expression of Ideas: Transitions ----------
{id:'SR083',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Sea otters eat enormous quantities of sea urchins, and urchins graze on kelp. Where otter populations collapsed along the North Pacific coast, urchin numbers exploded and kelp forests were stripped to bare rock. ______ protecting a single predator can determine whether an entire forest stands.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['In short,','By contrast,','Even so,','Previously,'],answer:0,
 expl:'The final sentence compresses the chain just described into its lesson, so a summarizing transition fits.',
 wrong:'Choice C signals a concession, but the last sentence agrees with the evidence rather than resisting it.'},
{id:'SR084',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'Early radiocarbon dates for the settlement clustered around 1200 CE, which fit the accepted chronology well. ______ the samples had come from structural timbers of a slow-growing species, and later work on short-lived seeds from the same layers returned dates nearly a century younger.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['However,','Therefore,','Similarly,','For instance,'],answer:0,
 expl:'The first sentence reports a comfortable result and the second undercuts it by naming a flaw in the samples. The relationship is contrast.',
 wrong:'Choice B claims the flaw follows from the good fit, which reverses the logic. The second sentence explains why the first result should not be trusted.'},
{id:'SR085',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Most commercial vanilla comes from a single orchid species whose flowers open for less than a day and, outside Mexico, have no natural pollinator. Every pod therefore begins with a worker who opens each flower by hand and transfers pollen with a sliver of bamboo. ______ the price of vanilla tracks the cost of labor more closely than the cost of land.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Unsurprisingly,','Nevertheless,','In contrast,','Earlier,'],answer:0,
 expl:'Hand pollination of every flower makes labor the dominant input, so a price that tracks labor is exactly what the description leads you to expect.',
 wrong:'Choice B would require the price behavior to be surprising given the hand work, which is the opposite of what the passage sets up.'},
{id:'SR086',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'The library digitized its entire run of a nineteenth-century newspaper and made the scans searchable. Historians who had worked with the paper for decades began finding articles they had never seen. ______ several of them reported that the search tool pushed them toward keywords they already expected to find, and away from the browsing that had produced their best discoveries.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['At the same time,','As a result,','For example,','In conclusion,'],answer:0,
 expl:'The third sentence reports a drawback running alongside the benefit in the second. A transition that holds both at once is what the passage needs.',
 wrong:'Choice B makes the drawback a consequence of finding new articles, which the passage does not claim. The two effects are concurrent, not causal.'},
{id:'SR087',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'A city can measure the success of a bike lane in several ways. Counting riders captures use but says nothing about who is riding. ______ a lane used heavily by experienced commuters and one used by children and older riders may post similar counts while serving very different purposes.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['For instance,','Consequently,','On the other hand,','Afterward,'],answer:0,
 expl:'The third sentence gives a concrete case of the limitation named in the second, so it is illustration.',
 wrong:'Choice C sets up a contrast, but the example agrees with the point before it rather than opposing it.'},
// ---------- Expression of Ideas: Rhetorical Synthesis ----------
{id:'SR088',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The Tuvan practice of khoomei is a form of throat singing.\n- A single singer produces a low fundamental note and one or more higher whistling tones at the same time.\n- The higher tones are overtones of the fundamental, amplified by changing the shape of the mouth and throat.\n- Khoomei was inscribed on the UNESCO list of intangible cultural heritage in 2009.\n- Conservatories in Tuva now teach the technique formally alongside oral transmission within families.',
 stem:'The student wants to explain how khoomei produces more than one pitch at once. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['A khoomei singer sustains a low fundamental while reshaping the mouth and throat to amplify particular overtones of it, producing higher whistling tones simultaneously.','Khoomei, a Tuvan form of throat singing, was inscribed on the UNESCO list of intangible cultural heritage in 2009.','Conservatories in Tuva teach khoomei formally, alongside the oral transmission that has long occurred within families.','In khoomei, a single singer produces a low fundamental note and one or more higher whistling tones at the same time.'],answer:0,
 expl:'The goal asks for the mechanism. Choice A names the fundamental, the reshaping of the vocal tract, and the amplified overtones, which is how the second pitch is produced.',
 wrong:'Choice D states that it happens without explaining how, which is the distinction the goal turns on. A synthesis question rewards the sentence that does the named job, not the one closest to the topic.'},
{id:'SR089',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Bessie Coleman was born in Texas in 1892.\n- No US flight school would admit her because she was Black and a woman.\n- She learned French, moved to France, and earned an international pilot license in 1921.\n- She was the first Black woman and the first Native American woman to hold such a license.\n- She refused to perform at segregated events after returning to the United States.',
 stem:'The student wants to emphasize the lengths to which Coleman went in order to train. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Barred from every US flight school on account of her race and sex, Coleman learned French and moved to France, earning her pilot license there in 1921.','Bessie Coleman, born in Texas in 1892, earned an international pilot license in 1921.','Coleman was the first Black woman and the first Native American woman to hold an international pilot license.','After returning to the United States, Coleman refused to perform at events that were segregated.'],answer:0,
 expl:'The goal is about what training cost her. Choice A names the barrier and the two steps she took to get around it, learning a language and emigrating.',
 wrong:'Choice C reports the achievement rather than the effort. The notes that matter are the ones the goal points at, not the most impressive ones.'},
{id:'SR090',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:5,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The Aral Sea was once the fourth largest lake in the world.\n- Beginning in the 1960s, the rivers feeding it were diverted to irrigate cotton fields.\n- By 2007 the lake had shrunk to about a tenth of its original volume.\n- A dam completed in 2005 raised the water level in the northern portion, and fishing has partly recovered there.\n- The southern portion has continued to shrink and is now largely desert.',
 stem:'The student wants to present the outcome of the 2005 dam accurately, without overstating it. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['The 2005 dam raised water levels in the northern Aral and allowed fishing to partly recover there, while the southern portion has continued to shrink.','The 2005 dam reversed the shrinking of the Aral Sea and restored the lake fishing industry.','By 2007 the Aral Sea had shrunk to roughly a tenth of the volume it once held.','The rivers that fed the Aral Sea were diverted beginning in the 1960s to irrigate cotton.'],answer:0,
 expl:'The goal asks for accuracy without overstatement. Choice A reports the northern recovery and pairs it with the southern decline, which is what the notes support.',
 wrong:'Choice B is the overstatement the goal warns against: the notes credit the dam with the northern portion only, and describe the southern portion as still shrinking.'},
{id:'SR091',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:3,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Mangroves are trees that grow in salt water along tropical coastlines.\n- Their tangled prop roots slow incoming water.\n- A belt of mangroves can reduce the height of an incoming storm wave.\n- Mangrove forests store carbon in their waterlogged soils at rates well above those of most land forests.\n- Roughly a third of the world mangrove area was lost during the second half of the twentieth century.',
 stem:'The student wants to explain why mangroves are valuable to coastal communities. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Mangroves protect coastlines directly, because their tangled prop roots slow incoming water and a belt of them can reduce the height of a storm wave.','Mangroves are trees that grow in salt water along tropical coastlines.','Roughly a third of the world mangrove area was lost during the second half of the twentieth century.','Mangrove soils are waterlogged, which is unusual among forest soils.'],answer:0,
 expl:'Value to a coastal community is protection, and choice A gives both the mechanism, the prop roots, and the effect, a reduced wave height.',
 wrong:'Choice C establishes that the loss matters but never says what is being lost. Explaining value means naming the benefit, not the scale of the decline.'},
{id:'SR092',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Jane Jacobs published The Death and Life of Great American Cities in 1961.\n- Planners of the period favored clearing dense neighborhoods and rebuilding at lower density.\n- Jacobs argued that the density and mixed uses planners treated as blight were what made streets safe and lively.\n- She had no formal training in planning or architecture.\n- Her arguments about street life are now standard in planning curricula.',
 stem:'The student wants to contrast Jacobs position with the prevailing view of her time. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Where planners of the early 1960s saw density and mixed uses as blight to be cleared, Jacobs argued that these were exactly what made a street safe and lively.','Jane Jacobs published The Death and Life of Great American Cities in 1961, though she had no formal training in planning or architecture.','Jacobs arguments about street life have become standard in planning curricula.','Planners of the early 1960s favored clearing dense neighborhoods and rebuilding them at lower density.'],answer:0,
 expl:'A contrast needs both positions on the same question. Choice A sets the planners reading of density against Jacobs reading of the same feature.',
 wrong:'Choice D gives only the prevailing view, so nothing is contrasted with it. One half of a contrast is never the answer to a contrast goal.'}
];
