// Quant seed bank. Fields: id, section, type, domain, context, skill, diff, stem, choices, answer (index), expl, wrong (optional notes on traps)
const BANK_QUANT = [
{id:'Q001',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:2,
 stem:'A store marks up the cost of a jacket by 40% to set its list price, then sells the jacket at a 15% discount off the list price. The store\'s profit is what percent of the cost of the jacket?',
 choices:['15%','19%','21%','25%','40%'],answer:1,
 expl:'Pick cost = 100. List price = 140. Selling price = 140 x 0.85 = 119. Profit = 19, which is 19% of cost.',
 wrong:'A (15%) and D (25%) come from adding or subtracting the percentages directly. Successive percent changes multiply; they never simply add.'},
{id:'Q002',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
 stem:'Machine A can complete a job in 6 hours and Machine B can complete the same job in 9 hours. Working together at their constant rates, how long will the two machines take to complete the job?',
 choices:['3 hours 12 minutes','3 hours 36 minutes','4 hours','4 hours 30 minutes','7 hours 30 minutes'],answer:1,
 expl:'Rates add: 1/6 + 1/9 = 3/18 + 2/18 = 5/18 job per hour. Time = 18/5 = 3.6 hours = 3 hours 36 minutes.',
 wrong:'E (7.5) is the average of the two times, a classic trap. Combined time must be less than the faster machine alone (6 hours), which eliminates C, D, E instantly.'},
{id:'Q003',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_rrp',diff:3,
 stem:'A train travels 180 miles at a constant speed of v miles per hour. If the train had traveled 15 miles per hour faster, the trip would have taken 1 hour less. What is v?',
 choices:['30','36','45','60','75'],answer:2,
 expl:'180/v - 180/(v+15) = 1. Multiply out: 180(v+15) - 180v = v(v+15), so 2700 = v^2 + 15v, so v^2 + 15v - 2700 = 0, (v-45)(v+60)=0, v = 45. Faster: back-solve. Try C: 180/45 = 4 h; 180/60 = 3 h. Difference 1 h. Done.',
 wrong:'Back-solving from the answer choices is faster than the quadratic here. Start with the middle choice.'},
{id:'Q004',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_rrp',diff:2,
 stem:'If 30 percent of x equals 45 percent of y, and x and y are positive, what is the ratio of x to y?',
 choices:['2:3','3:2','3:5','5:3','9:4'],answer:1,
 expl:'0.30x = 0.45y, so x/y = 0.45/0.30 = 3/2. Ratio 3:2.',
 wrong:'A (2:3) is the reversed ratio. Since x needs a smaller percent to match y, x must be the larger number.'},
{id:'Q005',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_rrp',diff:4,
 stem:'A 40-liter solution is 25% acid. How many liters of pure acid must be added so that the resulting solution is 40% acid?',
 choices:['6','8','10','12','15'],answer:2,
 expl:'Acid now = 10 L. Add x liters of pure acid: (10 + x)/(40 + x) = 0.4, so 10 + x = 16 + 0.4x, so 0.6x = 6, x = 10.',
 wrong:'A (6) comes from 15% of 40, forgetting the added acid also increases total volume.'},
{id:'Q006',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
 stem:'A town\'s population increased by 20% during one year and then decreased by 20% during the following year. Compared with its size at the start of the two-year period, the population at the end was',
 choices:['unchanged','2% smaller','4% smaller','4% larger','8% smaller'],answer:2,
 expl:'1.20 x 0.80 = 0.96, a 4% decrease. Up-then-down by the same percent always ends below the start.',
 wrong:'A (unchanged) is the intuitive trap; percent changes are taken from different bases.'},
{id:'Q007',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:2,
 stem:'How many positive divisors does 72 have?',
 choices:['8','10','12','16','18'],answer:2,
 expl:'72 = 2^3 x 3^2. Number of divisors = (3+1)(2+1) = 12.',
 wrong:'Listing divisors by hand risks missing one; use the exponent-plus-one formula.'},
{id:'Q008',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:3,
 stem:'What is the remainder when 7^25 is divided by 5?',
 choices:['0','1','2','3','4'],answer:2,
 expl:'7 leaves remainder 2 when divided by 5, so look at powers of 2 mod 5: 2, 4, 3, 1, then repeats every 4. 25 = 24 + 1, so 7^25 behaves like 2^1: remainder 2.',
 wrong:'Units-digit patterns (7, 9, 3, 1) give the remainder mod 10, not mod 5; here they still work (units digit of 7^25 is 7, and 7 mod 5 = 2) but the cycle method is the general tool.'},
{id:'Q009',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:3,
 stem:'If n is a positive integer and n^2 is divisible by 72, what is the largest positive integer that must divide n?',
 choices:['6','12','24','36','48'],answer:1,
 expl:'72 = 2^3 x 3^2. For n^2 to contain 2^3, n must contain 2^2 (since exponents in n^2 are even and at least 3). For 3^2, n needs 3^1. So n must be divisible by 4 x 3 = 12.',
 wrong:'D (36) treats n as if it must be divisible by 72 itself; only n^2 must be.'},
{id:'Q010',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_vof',diff:2,
 stem:'The sum of five consecutive integers is 85. What is the largest of the five integers?',
 choices:['17','18','19','20','21'],answer:2,
 expl:'The average of consecutive integers is the middle term: 85/5 = 17. The set is 15, 16, 17, 18, 19. Largest = 19.',
 wrong:'A (17) is the middle term, not the largest.'},
{id:'Q011',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:4,
 stem:'What is the least common multiple of 84 and 126?',
 choices:['168','252','336','504','10,584'],answer:1,
 expl:'84 = 2^2 x 3 x 7; 126 = 2 x 3^2 x 7. LCM takes the highest power of each prime: 2^2 x 3^2 x 7 = 252.',
 wrong:'E (10,584) is the product 84 x 126, which is the LCM only when the numbers share no factors.'},
{id:'Q012',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:2,
 stem:'Which of the following has the greatest value?',
 choices:['2/3','0.66','5/8','0.67','13/20'],answer:3,
 expl:'Convert to decimals: 2/3 = 0.6667, 5/8 = 0.625, 13/20 = 0.65. The largest is 0.67.',
 wrong:'A (2/3 = 0.6667) is very close but 0.67 is slightly larger.'},
{id:'Q013',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:1,
 stem:'If 3x - 7 = 2x + 5, what is the value of x?',
 choices:['2','5','7','12','14'],answer:3,
 expl:'Subtract 2x from both sides: x - 7 = 5, so x = 12.'},
{id:'Q014',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
 stem:'If x^2 - 5x + 6 = 0 and x^2 - 4 = 0, what is the value of x?',
 choices:['-2','2','3','2 or 3','-2 or 2'],answer:1,
 expl:'First equation: (x-2)(x-3)=0, so x = 2 or 3. Second: x = 2 or -2. Both must hold, so x = 2.',
 wrong:'D and E each satisfy only one equation.'},
{id:'Q015',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
 stem:'If |2x - 3| < 7, which of the following describes all possible values of x?',
 choices:['-5 < x < 2','-2 < x < 5','x < -2 or x > 5','-7 < x < 7','2 < x < 5'],answer:1,
 expl:'-7 < 2x - 3 < 7, add 3: -4 < 2x < 10, divide by 2: -2 < x < 5.',
 wrong:'C is the solution to |2x-3| > 7 (the outside region).'},
{id:'Q016',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:4,
 stem:'If x > 0 and x^2 + 1/x^2 = 7, what is the value of x + 1/x?',
 choices:['sqrt(5)','3','sqrt(7)','5','9'],answer:1,
 expl:'(x + 1/x)^2 = x^2 + 2 + 1/x^2 = 7 + 2 = 9, so x + 1/x = 3 (positive since x > 0).',
 wrong:'C (sqrt 7) forgets the cross term 2 when squaring.'},
{id:'Q017',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:3,
 stem:'A theater sold 50 tickets for a total of $520. Adult tickets cost $12 and child tickets cost $8. How many adult tickets were sold?',
 choices:['20','25','30','35','40'],answer:2,
 expl:'Let a = adults. 12a + 8(50 - a) = 520, so 4a + 400 = 520, a = 30. Check: 30 x 12 + 20 x 8 = 360 + 160 = 520.',
 wrong:'Back-solving works: try C first, it checks.'},
{id:'Q018',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:3,
 stem:'The length of a rectangle is 3 more than twice its width. If the perimeter is 36, what is the area of the rectangle?',
 choices:['40','55','65','78','91'],answer:2,
 expl:'Let width = w, length = 2w + 3. Perimeter: 2(w + 2w + 3) = 36, so 3w + 3 = 18, w = 5, length = 13. Area = 65.',
 wrong:'Translate each phrase in order: "3 more than twice the width" is 2w + 3, not 2(w + 3).'},
{id:'Q019',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
 stem:'If a/b = 3/4 and a + b = 28, what is the value of b - a?',
 choices:['2','4','6','8','12'],answer:1,
 expl:'a = 3k, b = 4k, so 7k = 28, k = 4. a = 12, b = 16, b - a = 4.',
 wrong:'Ratio multiplier method: write both quantities in terms of one variable k.'},
{id:'Q020',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:4,
 stem:'For which values of k does the equation x^2 + kx + 9 = 0 have exactly one real solution?',
 choices:['3 only','6 only','-6 or 6','-3 or 3','9 only'],answer:2,
 expl:'One real solution means the discriminant is zero: k^2 - 4(1)(9) = 0, so k^2 = 36, k = 6 or -6. (Perfect squares (x+3)^2 and (x-3)^2.)',
 wrong:'B forgets the negative root; k = -6 gives (x - 3)^2.'},
{id:'Q021',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:4,
 stem:'Ana is now 25 years old. In 5 years, Ana will be twice as old as Ben was 3 years ago. How old is Ben now?',
 choices:['12','15','18','21','24'],answer:2,
 expl:'Ana in 5 years = 30. Ben 3 years ago = B - 3. 30 = 2(B - 3), so B - 3 = 15, B = 18.',
 wrong:'Anchor each phrase to "now" before writing the equation; age problems fail on time-frame slips, not arithmetic.'},
{id:'Q022',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
 stem:'If 2^(x+2) = 64, what is the value of x?',
 choices:['3','4','5','6','8'],answer:1,
 expl:'64 = 2^6, so x + 2 = 6, x = 4.',
 wrong:'D (6) forgets the +2 in the exponent.'},
{id:'Q023',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_csp',diff:3,
 stem:'How many different committees of 3 people can be chosen from a group of 7 people?',
 choices:['21','35','42','210','343'],answer:1,
 expl:'Order does not matter: C(7,3) = 7!/(3!4!) = 35.',
 wrong:'D (210) is the permutation count 7 x 6 x 5; committees are unordered so divide by 3! = 6.'},
{id:'Q024',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:4,
 stem:'Five people are to be seated in a row of five chairs. If two particular people insist on sitting next to each other, in how many different orders can the five people be seated?',
 choices:['24','48','72','96','120'],answer:1,
 expl:'Glue the pair into one unit: 4 units can be arranged 4! = 24 ways, and the pair can be ordered within its unit 2 ways. 24 x 2 = 48.',
 wrong:'A (24) forgets to multiply by 2 for the internal order of the pair; E (120) is the unrestricted count.'},
{id:'Q025',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:3,
 stem:'A bag contains 4 red marbles and 6 blue marbles. If two marbles are drawn at random without replacement, what is the probability that both are red?',
 choices:['2/15','4/25','1/5','2/9','4/15'],answer:0,
 expl:'P = 4/10 x 3/9 = 12/90 = 2/15.',
 wrong:'B (4/25) is the with-replacement answer 4/10 x 4/10.'},
{id:'Q026',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:4,
 stem:'In a class of 30 students, 18 study French, 15 study Spanish, and 5 study neither language. How many students study both French and Spanish?',
 choices:['3','5','8','10','13'],answer:2,
 expl:'Students studying at least one language = 30 - 5 = 25. Then 18 + 15 - both = 25, so both = 8.',
 wrong:'A (3) forgets to subtract the "neither" group first: 18 + 15 - 30 = 3 is wrong because 30 includes the 5 who study neither.'},
{id:'Q027',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_csp',diff:3,
 stem:'For the set {3, 7, 8, 12, 15}, what is the mean minus the median?',
 choices:['0','1','2','3','4'],answer:1,
 expl:'Mean = 45/5 = 9. Median (middle value) = 8. Difference = 1.'},
{id:'Q028',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:3,
 stem:'The average (arithmetic mean) of 5 numbers is 20. When one of the numbers is removed, the average of the remaining 4 numbers is 18. What number was removed?',
 choices:['20','24','26','28','32'],answer:3,
 expl:'Total of 5 = 100. Total of remaining 4 = 72. Removed = 100 - 72 = 28.',
 wrong:'Always convert averages to sums first; averages themselves cannot be subtracted.'},
{id:'Q029',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_csp',diff:4,
 stem:'In an arithmetic sequence, the first term is 5 and the tenth term is 41. What is the sum of the first 10 terms?',
 choices:['205','230','250','410','460'],answer:1,
 expl:'Sum = (number of terms) x (first + last)/2 = 10 x (5 + 41)/2 = 10 x 23 = 230. (Common difference 4 is not even needed.)',
 wrong:'E (460) forgets to divide by 2 (it uses first + last instead of their average).'},
{id:'Q030',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_csp',diff:5,
 stem:'A fair coin is tossed 4 times. What is the probability of getting at least 3 heads?',
 choices:['1/16','1/4','5/16','3/8','1/2'],answer:2,
 expl:'Exactly 3 heads: C(4,3) = 4 outcomes. Exactly 4 heads: 1 outcome. Total favorable = 5 out of 16. P = 5/16.',
 wrong:'B (1/4) counts only exactly 3 heads; "at least" includes 4.'},
{id:'Q031',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:4,
 stem:'A car gets 30 miles per gallon on the highway and 20 miles per gallon in the city. On a 300-mile trip, 180 miles were on the highway and 120 miles were in the city. What was the car\'s average fuel efficiency for the whole trip, in miles per gallon?',
 choices:['24','25','26','27','28'],answer:1,
 expl:'Gas used = 180/30 + 120/20 = 6 + 6 = 12 gallons. Average = 300/12 = 25 mpg.',
 wrong:'C (26) is the mileage-weighted average of the rates, which is wrong: average rate = total distance / total gas, always.'},
{id:'Q032',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:2,
 stem:'A recipe calls for flour and sugar in the ratio 5:2. If a baker uses 21 cups of flour and sugar combined, how many cups of sugar are used?',
 choices:['4','5','6','7','15'],answer:2,
 expl:'Total parts = 7, each part = 3 cups. Sugar = 2 x 3 = 6 cups.',
 wrong:'E (15) is the flour amount.'}
];
