// bank_sat_math4.js - Original SAT Math items SM101-SM122. Third increment, continuing to raise
// the grid-in share and to give repeat mock sections enough fresh items.
const BANK_SAT_MATH4 = [
// ---------- Algebra ----------
{id:'SM101',section:'M',type:'MC',sub:'Linear equations in two variables',skill:'m_alg',diff:3,
 stem:'If 6x - 2y = 18, what is the value of 3x - y?',
 choices:['3','6','9','12'],answer:2,
 expl:'The expression 3x - y is exactly half of 6x - 2y, so it equals half of 18, which is 9. There is no need to find x or y separately.',
 wrong:'Choice D comes from trying to solve for individual variables, which is impossible from one equation. When a question asks for a combination, check whether it is a multiple of what you were given.'},
{id:'SM102',section:'M',type:'SPR',answerType:'spr',sub:'Linear equations in one variable',skill:'m_alg',diff:2,
 stem:'If x/4 + 3 = 10, what is the value of x?',
 choices:[],answer:'28',
 expl:'Subtract 3 to get x/4 = 7, then multiply both sides by 4 to get x = 28.',
 wrong:'Multiplying by 4 before subtracting the 3 gives x + 3 = 40 only if the 3 is also multiplied. Undo the addition first, then the division.'},
{id:'SM103',section:'M',type:'MC',sub:'Linear inequalities',skill:'m_alg',diff:4,
 stem:'Renting a floor sander costs a flat 35 dollars plus 9 dollars for each hour of use. Which inequality gives all numbers of hours h that can be rented for no more than 125 dollars?',
 choices:['9 + 35h is less than or equal to 125','35 + 9h is less than or equal to 125','35 + 9h is greater than or equal to 125','35h + 9 is greater than or equal to 125'],answer:1,
 expl:'The flat fee is a one-time 35 and the 9 dollars repeats per hour, so the total is 35 + 9h. No more than 125 means at most 125.',
 wrong:'Choice A swaps the flat fee and the hourly rate. Ask which number repeats: the one attached to the variable is always the per-unit rate.'},
{id:'SM104',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:4,
 stem:'A line passes through the point (1, 4) and is parallel to the line y = 2x - 5. What is the y-intercept of this line?',
 choices:['-2','2','4','6'],answer:1,
 expl:'Parallel lines share a slope, so this line is y = 2x + b. Substituting (1, 4) gives 4 = 2 + b, so b = 2.',
 wrong:'Choice A uses the perpendicular slope or carries the -5 through. Parallel means copy the slope exactly; only the intercept changes.'},
{id:'SM105',section:'M',type:'SPR',answerType:'spr',sub:'Systems of two linear equations',skill:'m_alg',diff:5,
 stem:'If 4x + 3y = 25 and x - y = 1, what is the value of x?',
 choices:[],answer:'4',
 expl:'From the second equation x = y + 1. Substituting gives 4(y + 1) + 3y = 25, so 7y = 21 and y = 3, which makes x = 4.',
 wrong:'Reporting 3 answers for y. The second equation is the easy one to rearrange, which makes it easy to solve for the wrong variable and stop.'},
{id:'SM106',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:3,
 stem:'The function f is defined by f(x) = 5 - 3x. For what value of x does f(x) = -4?',
 choices:['-3','1','3','9'],answer:2,
 expl:'Set 5 - 3x = -4. Subtracting 5 gives -3x = -9, so x = 3.',
 wrong:'Choice A drops a sign when dividing two negatives. A negative divided by a negative is positive, which a quick check in the original equation confirms.'},
// ---------- Advanced Math ----------
{id:'SM107',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:3,
 stem:'Which expression is equivalent to (x - 6)(x + 6)?',
 choices:['x^2 + 36','x^2 - 36','x^2 - 12x - 36','x^2 - 12x + 36'],answer:1,
 expl:'This is a difference of squares: the middle terms -6x and +6x cancel, leaving x^2 - 36.',
 wrong:'Choice D is the expansion of (x - 6)^2, a different expression entirely. Matching signs in the two factors means squaring; opposite signs mean the middle term vanishes.'},
{id:'SM108',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:4,
 stem:'What is the sum of the solutions to the equation x^2 - 10x + 21 = 0?',
 choices:[],answer:'10',
 expl:'Factoring gives (x - 3)(x - 7) = 0, so the solutions are 3 and 7 and their sum is 10. The shortcut is faster: for x^2 + bx + c the roots sum to -b, here 10.',
 wrong:'Answering 21 gives the product of the roots rather than the sum. Both appear in the equation, which is exactly why the question is worth asking.'},
{id:'SM109',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:4,
 stem:'If 9 raised to the power x equals 3 raised to the power (x + 4), what is the value of x?',
 choices:['2','3','4','8'],answer:2,
 expl:'Write 9 as 3^2, so the left side is 3^(2x). With matching bases, 2x = x + 4 and x = 4.',
 wrong:'Choice A comes from setting x = 4 divided by 2 without first rewriting the base. Convert both sides to the same base before comparing exponents.'},
{id:'SM110',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:5,
 stem:'The function f is defined by f(x) = (x - 2)(x + 5). For which values of x is f(x) less than 0?',
 choices:['x is less than -5 or x is greater than 2','-5 is less than x, which is less than 2','-2 is less than x, which is less than 5','x is less than -2 or x is greater than 5'],answer:1,
 expl:'The parabola opens upward and crosses zero at x = -5 and x = 2, so it sits below the axis strictly between those roots. Testing x = 0 gives (-2)(5) = -10, which is negative.',
 wrong:'Choice C flips the signs of the roots. Setting each factor to zero gives x = 2 from (x - 2) and x = -5 from (x + 5), not the reverse.'},
{id:'SM111',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear functions',skill:'m_adv',diff:4,
 stem:'The height of a ball, in feet, t seconds after it is thrown is given by h(t) = -16t^2 + 64t. For what positive value of t does the ball return to a height of 0 feet?',
 choices:[],answer:'4',
 expl:'Set -16t^2 + 64t = 0 and factor: -16t(t - 4) = 0. The solutions are t = 0, the throw, and t = 4, the landing.',
 wrong:'Answering 2 gives the time at the peak, which is the vertex rather than a zero. The peak sits halfway between the two zeros, so it is worth computing as a check but is not the answer.'},
{id:'SM112',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:5,
 stem:'For x not equal to 2, which expression is equivalent to (x^2 - 5x + 6)/(x - 2)?',
 choices:['x + 3','x - 6','x^2 - 3','x - 3'],answer:3,
 expl:'The numerator factors as (x - 2)(x - 3). Cancelling the common factor x - 2 leaves x - 3.',
 wrong:'Choice B subtracts the constants instead of cancelling a factor. Only whole factors cancel, never individual terms.'},
// ---------- Problem-Solving and Data Analysis ----------
{id:'SM113',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:3,
 stem:'A recipe that serves 6 uses 450 grams of flour. At the same rate, how many grams of flour are needed to serve 10?',
 choices:['540','675','750','810'],answer:2,
 expl:'Each serving uses 450 divided by 6, or 75 grams, so 10 servings need 750 grams.',
 wrong:'Choice D adds 450 and 360 by scaling in the wrong direction. Find the per-serving amount first; it makes any number of servings a single multiplication.'},
{id:'SM114',section:'M',type:'SPR',answerType:'spr',sub:'Percentages',skill:'m_psda',diff:3,
 stem:'In a survey of 250 students, 40 percent chose option A. How many students chose option A?',
 choices:[],answer:'100',
 expl:'Forty percent of 250 is 0.40 times 250, which is 100.',
 wrong:'Answering 40 reports the percent rather than the count. A percent is a rate; it becomes a number only after it is applied to the total.'},
{id:'SM115',section:'M',type:'MC',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:4,
 stem:'A data set consists of the values 7, 9, 12, 12, 15, 20, and 31. What is the median of the data set?',
 choices:['9','12','15','16'],answer:1,
 expl:'With seven values in order, the median is the fourth, which is 12.',
 wrong:'Choice D is close to the mean of about 15.1, which the single large value 31 pulls above the median. Questions like this exist to separate the two measures.'},
{id:'SM116',section:'M',type:'SPR',answerType:'spr',sub:'Percentages',skill:'m_psda',diff:5,
 stem:'After decreasing by 15 percent, a quantity equals 187. What was the quantity before the decrease?',
 choices:[],answer:'220',
 expl:'A 15 percent decrease leaves 85 percent of the original, so the original is 187 divided by 0.85, which is 220.',
 wrong:'Adding 15 percent to 187 gives about 215, which is not the original. Undo a percent decrease by dividing by what remains, not by marking the new value back up.'},
{id:'SM117',section:'M',type:'MC',sub:'Two-variable data: models and scatterplots',skill:'m_psda',diff:4,
 stem:'For a set of paired measurements, the line of best fit is y = 0.8x + 12. What value of y does the model predict when x = 35?',
 choices:['28','40','47','54'],answer:1,
 expl:'Substitute: 0.8 times 35 is 28, and adding 12 gives 40.',
 wrong:'Choice A stops after multiplying by the slope and forgets the intercept. A line of best fit is not proportional unless its intercept is zero.'},
// ---------- Geometry and Trigonometry ----------
{id:'SM118',section:'M',type:'MC',sub:'Area and volume',skill:'m_geo',diff:3,
 stem:'The perimeter of a square is 36. What is the area of the square?',
 choices:['36','72','81','144'],answer:2,
 expl:'Each side is 36 divided by 4, or 9, so the area is 9 squared, which is 81.',
 wrong:'Choice D squares the perimeter divided by 3, and choice A repeats the perimeter as the area. Find the side length first; every other measure follows from it.'},
{id:'SM119',section:'M',type:'SPR',answerType:'spr',sub:'Area and volume',skill:'m_geo',diff:3,
 stem:'A triangle has a base of length 14 and a height of 9. What is the area of the triangle?',
 choices:[],answer:'63',
 expl:'Area is one half base times height: one half of 14 times 9, which is 63.',
 wrong:'Answering 126 skips the one half. The triangle is exactly half the rectangle built on the same base and height.'},
{id:'SM120',section:'M',type:'MC',sub:'Lines, angles, and triangles',skill:'m_geo',diff:4,
 stem:'Two angles are supplementary, and one is 4 times the measure of the other. What is the measure of the smaller angle?',
 choices:['30 degrees','36 degrees','45 degrees','144 degrees'],answer:1,
 expl:'Let the smaller be x. Then x + 4x = 180, so 5x = 180 and x = 36 degrees. The larger is 144.',
 wrong:'Choice D is the larger angle. Choice C solves x + 4x = 225 or treats the angles as complementary, which would sum to 90.'},
{id:'SM121',section:'M',type:'SPR',answerType:'spr',sub:'Area and volume',skill:'m_geo',diff:5,
 stem:'A right circular cylinder has a volume of 200 pi and a radius of 5. What is its height?',
 choices:[],answer:'8',
 expl:'Volume is pi r squared h, so 200 pi = pi times 25 times h. Dividing by 25 pi gives h = 8.',
 wrong:'Answering 40 divides 200 by 5 without squaring the radius. The base area uses the radius squared, which is 25, not 5.'},
{id:'SM122',section:'M',type:'MC',sub:'Right triangles and trigonometry',skill:'m_geo',diff:5,
 stem:'In a right triangle, the cosine of angle A is 5/13 and the hypotenuse has length 26. What is the length of the side adjacent to angle A?',
 choices:['5','10','12','24'],answer:1,
 expl:'Cosine is the adjacent side over the hypotenuse, so the adjacent side is 26 times 5/13, which is 10.',
 wrong:'Choice A reads the numerator of the ratio as the length. A trigonometric ratio gives a proportion, which has to be scaled by the actual hypotenuse.'}
];
