// bank_sat_rw2.js - Original SAT Reading and Writing items SR033-SR062:
// Standard English Conventions, Expression of Ideas. Four choices per item, own passage per item.
const BANK_SAT_RW2 = [
// ---------- Standard English Conventions: Boundaries ----------
{id:'SR033',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:2,
 passage:'The Mariana Trench reaches nearly eleven kilometers below the surface of the western ______ at that depth exceeds one thousand times the pressure at sea level.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['Pacific, pressure','Pacific pressure','Pacific. Pressure','Pacific; and pressure'],answer:2,
 expl:'Both halves are complete sentences, so they need a period, a semicolon, or a comma with a coordinating conjunction. Only the period is offered.',
 wrong:'Choice A is a comma splice, the most common punctuation error on this exam. Test each side of the boundary on its own: if both stand alone, a comma by itself is never enough.'},
{id:'SR034',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'Solar panels lose efficiency as their temperature ______ however, arrays in cool and sunny climates often outproduce identical arrays installed in hotter places.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['rises,','rises','rises and','rises;'],answer:3,
 expl:'However is a conjunctive adverb, not a conjunction. Joining two independent clauses across it requires a semicolon before it and a comma after.',
 wrong:'Choice A produces a comma splice despite the presence of however. Words like however, therefore, and moreover cannot hold two sentences together on their own.'},
{id:'SR035',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'The restoration team faced a problem it could not solve with chemistry ______ the pigment the artist had used was no longer manufactured anywhere in the world.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:[':',',','','and,'],answer:0,
 expl:'A complete sentence precedes the blank, and what follows explains the problem just named. A colon after an independent clause is the correct way to introduce that explanation.',
 wrong:'Choice B joins two independent clauses with a comma. A colon is available precisely because the second half defines the first.'},
{id:'SR036',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:3,
 passage:'The physicist Chien-Shiung ______ measurements overturned the assumption that nature makes no distinction between left and right, was not named on the Nobel Prize awarded for the discovery.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['Wu whose','Wu, whose','Wu; whose','Wu. Whose'],answer:1,
 expl:'The clause beginning whose is nonrestrictive and already closes with a comma before was. A nonrestrictive element needs a comma on both sides.',
 wrong:'Choice A opens the element without closing punctuation to match the comma that follows it. Paired punctuation has to come in pairs.'},
{id:'SR037',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'The decision to route the new rail line along the river rather than through the ______ the city council after eleven months of public hearings.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['ridge, divided','ridge; divided','ridge divided','ridge: divided'],answer:2,
 expl:'The subject is the decision and the verb is divided. No punctuation belongs between a subject and its verb, however long the subject runs.',
 wrong:'Choice A is the trap a long subject invites: the sentence feels ready for a pause. Strip the modifiers and the sentence reads the decision divided the council, with nothing between them.'},
{id:'SR038',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:2,
 passage:'After spending two winters recording wolf howls in the Superior National ______ biologist was able to distinguish individual animals by voice alone.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['Forest the','Forest; the','Forest. The','Forest, the'],answer:3,
 expl:'The opening element beginning with After is an introductory phrase, not a complete sentence, so it is set off from the main clause with a comma.',
 wrong:'Choice C treats the introductory phrase as a sentence, leaving a fragment. A phrase with no subject and no finite verb cannot stand alone.'},
{id:'SR039',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'The touring exhibition will open in three cities next ______ Ohio; Tacoma, Washington; and Athens, Georgia.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['year: Toledo,','year, Toledo','year: Toledo;','year Toledo,'],answer:0,
 expl:'A colon after the complete clause introduces the list, and because the items contain internal commas they are separated by semicolons. Inside each item, the city and state take a comma.',
 wrong:'Choice C puts a semicolon where the city and state boundary belongs, breaking the pattern the rest of the list follows.'},
{id:'SR040',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:4,
 passage:'Of the several hundred languages spoken in Nigeria, the ______ have official status at the national level are English and, in practice, three widely used regional languages.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['ones that','ones, that','ones; that','ones. That'],answer:0,
 expl:'The clause beginning that identifies which ones are meant, so it is restrictive and takes no comma before it.',
 wrong:'Choice B sets off information the sentence cannot spare. Removing that have official status would leave the sentence saying nothing specific, which is the test for a restrictive clause.'},
// ---------- Standard English Conventions: Form, Structure, and Sense ----------
{id:'SR041',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:2,
 passage:'The collection of letters written by the four Grimke sisters and their correspondents ______ held at a university library in South Carolina.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['are','have been being','were','is'],answer:3,
 expl:'The subject is collection, a singular noun. The words between the subject and the verb describe the collection but do not change its number.',
 wrong:'Choice A agrees with correspondents, the nearest noun rather than the subject. Cross out the prepositional phrases and the sentence reads the collection is held.'},
{id:'SR042',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:3,
 passage:'Each of the twelve prototypes tested by the engineering team ______ a different arrangement of cooling fins.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['use','are using','uses','have used'],answer:2,
 expl:'Each is singular and remains the subject regardless of the plural noun that follows of.',
 wrong:'Choice A is pulled in by prototypes. Each, every, either, and neither are singular subjects even when a plural noun sits right beside them.'},
{id:'SR043',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'By the time the surveying party reached the pass in September, the first snow ______ for more than a week, and the route they had planned in June was no longer usable.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['falls','had been falling','will have fallen','is falling'],answer:1,
 expl:'The snow began before the party arrived, and both events are in the past, so the earlier one takes the past perfect.',
 wrong:'Choice C puts an event that precedes a past arrival into the future. Fix the timeline before picking a tense: earlier past event, past perfect.'},
{id:'SR044',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:3,
 passage:'Although a honeybee colony contains tens of thousands of workers, ______ survival depends on a single queen whose egg laying no other member of the hive can replace.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['its','their','it is','they are'],answer:0,
 expl:'The possessive refers to the colony, which is singular, and the sentence needs a possessive rather than a contraction.',
 wrong:'Choice C is the contraction it is, which cannot own the noun survival. Read the sentence with it is substituted in and the error becomes audible.'},
{id:'SR045',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'The museum has recently acquired several works by early twentieth-century ______ studio was destroyed in a fire before any of the pieces were exhibited.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['printmakers, who is','printmakers who is','printmakers whose shared,','printmakers whose shared'],answer:3,
 expl:'The relative pronoun must be possessive to introduce studio, and the clause identifies which printmakers, so it takes no comma.',
 wrong:'Choices A and B use who is, which is both singular and non-possessive, leaving studio with nothing to attach to.'},
{id:'SR046',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'Trained as a civil engineer before turning to photography, ______',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['Berenice Abbott images of New York City show a structural eye.','the images of New York City that Berenice Abbott made show a structural eye.','Berenice Abbott brought a structural eye to her images of New York City.','it was a structural eye that Berenice Abbott brought to her images of New York City.'],answer:2,
 expl:'An opening modifier attaches to the subject that follows it. The person trained as an engineer is Berenice Abbott, so her name has to be the subject.',
 wrong:'Choice B makes the images the thing trained as a civil engineer. Ask who or what performed the action in the modifier, then make that the subject.'},
{id:'SR047',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:3,
 passage:'The field season required the crew to map the outcrop, collect samples from every exposed ______ the site before the road was closed for winter.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['layer, and photographing','layer, and photograph','layer, photographing','layer and to photographing'],answer:1,
 expl:'The three tasks share the word to from required the crew to, so each must be a bare infinitive: map, collect, and photograph.',
 wrong:'Choice A switches the third item to an -ing form and breaks the series. Read the shared word into each item in turn to hear the mismatch.'},
{id:'SR048',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:4,
 passage:'Among the documents recovered from the wreck ______ a ledger that records the cargo, the crew, and the ports of call for the final voyage.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['is','are','have been','were being'],answer:0,
 expl:'The sentence is inverted: the subject is a ledger, which is singular, and it follows the verb.',
 wrong:'Choice B agrees with documents, which sits inside the opening prepositional phrase. In an inverted sentence, find the subject after the verb before choosing.'},
// ---------- Expression of Ideas: Transitions ----------
{id:'SR049',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:2,
 passage:'Most commercially grown bananas belong to a single cultivar, the Cavendish, and are propagated from cuttings rather than seeds. Every plant in a plantation is therefore a genetic copy of every other. ______ a fungal strain able to kill one plant is able to kill them all.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Nevertheless,','For instance,','In contrast,','As a result,'],answer:3,
 expl:'Genetic uniformity is the cause and shared vulnerability to one fungus is its consequence, so the transition must signal result.',
 wrong:'Choice B would require the last sentence to be an example of the previous claim rather than what follows from it.'},
{id:'SR050',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Analyses of the ice core suggested that volcanic sulfate arrived in Greenland during a single winter. The tree ring record from northern Europe pointed to a cold summer two years later. ______ the two archives were eventually reconciled when researchers corrected a counting error in the ice core chronology.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Consequently,','Despite this apparent conflict,','Likewise,','For example,'],answer:1,
 expl:'The first two sentences disagree about timing and the third reports a reconciliation, so the transition must acknowledge the conflict before it is resolved.',
 wrong:'Choice C claims the two records agree, which is precisely what the reconciliation was needed to achieve.'},
{id:'SR051',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'A composer writing for a string quartet controls four independent lines and can rely on the players to balance themselves in the room. ______ a composer writing for orchestra must anticipate how eighty players will balance in a hall none of them has heard.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Accordingly,','In addition,','By contrast,','For this reason,'],answer:2,
 expl:'The two sentences set a small ensemble against a large one and self-balancing against anticipated balance, which is a contrast.',
 wrong:'Choice B adds the second case to the first as if they were similar. The second sentence differs from the first in every detail it repeats.'},
{id:'SR052',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'Field guides once described the cuckoo strategy of laying eggs in other birds nests as a straightforward theft of parental care. Later work found that some host species that tolerate cuckoo eggs suffer fewer nest raids by predators than neighbors that reject them. ______ the relationship may be less one-sided than the older account allowed.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Nonetheless,','Previously,','In particular,','In other words,'],answer:3,
 expl:'The final sentence restates what the new finding implies about the older description, so the transition must signal a restatement.',
 wrong:'Choice A signals a concession, but the last sentence agrees with the evidence just presented rather than pushing back against it.'},
{id:'SR053',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Roman concrete harbor structures have survived two thousand years of seawater that destroys modern concrete in decades. Researchers analyzing cores from those structures found crystals of a rare mineral growing inside the cement. ______ seawater percolating through the material was reacting with volcanic ash to make the concrete stronger over time.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['Apparently,','However,','Similarly,','Instead of this,'],answer:0,
 expl:'The last sentence draws the inference the crystals point to, so a transition marking an apparent conclusion fits.',
 wrong:'Choice B sets up a contrast, but the explanation follows directly from the crystals rather than opposing them.'},
{id:'SR054',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:4,
 passage:'Economists studying minimum wage increases once relied largely on national time series, comparing employment before and after a change. That approach cannot separate the effect of the wage from everything else moving in the economy at the same time. ______ researchers began comparing neighboring counties on either side of a state line, where conditions are similar and only the wage law differs.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['In the same way,','To address this problem,','Regardless,','Admittedly,'],answer:1,
 expl:'The second sentence names a flaw and the third describes the design adopted to get around it, which is a purpose relationship.',
 wrong:'Choice C dismisses the problem instead of solving it, which misreads why the county comparison exists.'},
{id:'SR055',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:3,
 passage:'Digitizing a herbarium collection is slow work: each pressed specimen must be photographed, and the handwritten label transcribed. Several herbaria have opened their images to volunteers who transcribe labels online. ______ one institution cleared a backlog of ninety thousand specimens in under two years.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['On the other hand,','Therefore,','For example,','Earlier,'],answer:2,
 expl:'The final sentence supplies one institution as an instance of the volunteer transcription just described.',
 wrong:'Choice B claims the result follows logically from the practice in general, but a single named institution is an illustration rather than a deduction.'},
// ---------- Expression of Ideas: Rhetorical Synthesis ----------
{id:'SR056',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:3,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The Great Green Wall is a project to restore degraded land across the African Sahel.\n- It was launched by the African Union in 2007.\n- Early plans described a continuous belt of planted trees.\n- Survival rates for planted seedlings in the driest zones were low.\n- Later work shifted toward assisted natural regeneration, protecting seedlings that sprout on their own.',
 stem:'The student wants to explain why the project approach changed. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['The Great Green Wall, launched by the African Union in 2007, is a project to restore degraded land across the African Sahel.','Early plans for the Great Green Wall described a continuous belt of planted trees across the Sahel.','Assisted natural regeneration protects seedlings that sprout on their own rather than relying on planting.','Because planted seedlings survived poorly in the driest zones, the project moved away from a continuous planted belt toward assisted natural regeneration.'],answer:3,
 expl:'The goal asks for a cause and a change. Only choice D pairs the low survival rates with the shift from planting to assisted natural regeneration.',
 wrong:'Choices B and C are each accurate but give only one end of the change. A synthesis question is scored on the goal, not on whether the sentence is true.'},
{id:'SR057',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Hedy Lamarr was a film actor who worked in Hollywood in the 1930s and 1940s.\n- With composer George Antheil she co-invented a frequency-hopping system in 1941.\n- The system was intended to keep radio-guided torpedoes from being jammed.\n- The US Navy did not adopt the design during the war.\n- Frequency hopping later became a building block of wireless communication technologies.',
 stem:'The student wants to emphasize the long-term significance of the 1941 invention. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Although the Navy declined the frequency-hopping system Lamarr and Antheil patented in 1941, the technique later became a building block of wireless communication.','Hedy Lamarr, a film actor who worked in Hollywood in the 1930s and 1940s, co-invented a frequency-hopping system with the composer George Antheil.','Lamarr and Antheil designed their system to keep radio-guided torpedoes from being jammed during the war.','The US Navy did not adopt the frequency-hopping design that Lamarr and Antheil developed in 1941.'],answer:0,
 expl:'Long-term significance requires the later use, and only choice A reaches it, setting the wartime rejection against what the technique became.',
 wrong:'Choice D stops at the rejection. Notes that mention a later outcome are usually there because the goal depends on it.'},
{id:'SR058',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:3,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Cahokia was a city near present-day St. Louis.\n- At its height around 1100 CE it may have held more than ten thousand people.\n- Monks Mound, its largest earthwork, covers about six hectares at the base.\n- The site was largely depopulated by about 1350 CE.\n- Researchers continue to debate the causes of that decline.',
 stem:'The student wants to introduce Cahokia to an audience unfamiliar with it. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Researchers continue to debate why Cahokia was largely depopulated by about 1350 CE.','Cahokia, a city near present-day St. Louis, may have held more than ten thousand people around 1100 CE.','Monks Mound, the largest earthwork at Cahokia, covers about six hectares at its base.','Cahokia was largely depopulated by about 1350 CE, roughly two centuries after its height.'],answer:1,
 expl:'An introduction has to say what Cahokia was and place it. Choice B gives the identification, the location, and the scale.',
 wrong:'Choices A and D open on the decline, which assumes the reader already knows the city. Match the sentence to the audience the goal names.'},
{id:'SR059',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Two bridges of similar span were built over the same river, one in 1962 and one in 2014.\n- The 1962 bridge used a steel truss design.\n- The 2014 bridge used a cable-stayed design.\n- The 1962 bridge required lane closures for painting roughly every seven years.\n- The 2014 bridge uses weathering steel that forms a protective surface layer and is not painted.',
 stem:'The student wants to compare the maintenance demands of the two bridges. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['The two bridges span a similar distance across the same river but were built fifty-two years apart.','The 1962 bridge used a steel truss design, whereas the 2014 bridge used a cable-stayed design.','The 1962 bridge needed repainting with lane closures about every seven years, while the 2014 bridge uses weathering steel and is not painted at all.','Weathering steel forms a protective surface layer, which is why the 2014 bridge is not painted.'],answer:2,
 expl:'The goal names maintenance, and only choice C puts the two maintenance facts side by side.',
 wrong:'Choice B compares the two bridges on structural design instead. A comparison question still has to compare the specific property the goal names.'},
{id:'SR060',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:4,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Sourdough starters host communities of yeasts and lactic acid bacteria.\n- A 2021 study sampled starters maintained by bakers in several countries.\n- Starters kept in the same household for years still differed from one another in species composition.\n- Flour type and hydration predicted composition better than geography did.\n- Bakers often assume their local air determines the character of a starter.',
 stem:'The student wants to present the finding that challenges a common assumption. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['A 2021 study sampled sourdough starters maintained by bakers in several countries and analyzed their species composition.','Sourdough starters host communities of yeasts and lactic acid bacteria that vary from starter to starter.','Although bakers often credit local air for the character of a starter, the 2021 study found flour type and hydration to be better predictors of species composition than geography.','Starters kept in the same household for years still differed from one another in species composition.'],answer:2,
 expl:'The goal needs both the assumption and the finding that unsettles it. Choice C names the local air belief and sets the predictors against it.',
 wrong:'Choice D reports a real finding but leaves the assumption unstated, so nothing is challenged. Goals that mention an assumption require the assumption in the sentence.'},
{id:'SR061',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:3,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Katherine Dunham was a dancer and choreographer.\n- She trained in anthropology at the University of Chicago.\n- In the 1930s she conducted fieldwork on dance in the Caribbean.\n- She built a technique that drew on movement she had documented there.\n- The Dunham technique is still taught in dance conservatories.',
 stem:'The student wants to explain the origin of the Dunham technique. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Katherine Dunham was a dancer and choreographer who trained in anthropology at the University of Chicago.','Dunham built her technique from movement she documented during 1930s fieldwork on dance in the Caribbean.','The Dunham technique continues to be taught in dance conservatories today.','Katherine Dunham conducted fieldwork in the Caribbean during the 1930s.'],answer:1,
 expl:'Origin means where the technique came from, and choice B connects the fieldwork directly to the building of the technique.',
 wrong:'Choice D reports the fieldwork without linking it to the technique, which leaves the origin unexplained.'},
{id:'SR062',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:5,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Lidar surveys map ground surfaces by timing laser pulses from an aircraft.\n- Dense forest canopy had long limited archaeological survey in the Maya lowlands.\n- A 2018 lidar survey covered more than two thousand square kilometers of Guatemala.\n- The survey identified causeways, terraces, and defensive works beneath the canopy.\n- Ground crews had mapped a small fraction of that area over several decades.',
 stem:'The student wants to emphasize how the lidar survey changed the pace of archaeological work in the region. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['A single 2018 lidar survey covered more than two thousand square kilometers, far more than ground crews had mapped in the Maya lowlands over several decades.','Lidar maps ground surfaces by timing laser pulses sent from an aircraft toward the ground below.','The 2018 survey identified causeways, terraces, and defensive works hidden beneath the forest canopy.','Dense forest canopy had long limited archaeological survey in the Maya lowlands of Guatemala.'],answer:0,
 expl:'Pace requires a comparison of coverage against time, and only choice A sets one survey against decades of ground work.',
 wrong:'Choice C reports what was found rather than how quickly. The goal decides which of several true sentences is the right one.'}
];
