// bank_sat_easy.js - Original SAT items SR163-SR192 and SM137-SM148, all at difficulty 1 and 2.
// The digital SAT routes a struggling student into an easier second module, and the bank could
// not fill one: Reading and Writing had 9 items at difficulty 1 to 2 against the 27 a module
// needs. These exist so that routing down actually delivers an easier module.
const BANK_SAT_EASY = [
// ---------- Reading and Writing: Craft and Structure ----------
{id:'SR163',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:1,
 passage:'Honeybees communicate the location of food by dancing. A returning forager moves in a figure-eight pattern whose angle points toward the flowers and whose duration signals how far away they are. Other bees watch and then fly out, using the information to ______ the same patch.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['locate','avoid','plant','describe'],answer:0,
 expl:'The dance communicates where food is and the other bees fly out using that information, so what they do with it is find the patch.',
 wrong:'Avoid reverses the purpose of the dance. The sentence says the bees use the information, and the information is about where the flowers are.'},
{id:'SR164',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:1,
 passage:'When the printing press reached a new city, the first books produced there were usually copies of texts already circulating in manuscript. Printers had to be sure a book would sell before committing paper and labor to it, so they chose titles whose demand was already ______ .',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['proven','uncertain','declining','hidden'],answer:0,
 expl:'Printers wanted to be sure a book would sell, so they picked titles already circulating, whose demand had been demonstrated.',
 wrong:'Uncertain describes exactly the risk printers were trying to avoid. The blank must match the reason given in the sentence before it.'},
{id:'SR165',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:2,
 passage:'The violinist practiced the same four bars for an hour, slowing them until each note could be played cleanly and only then raising the speed. Watching her, a student expecting fireworks found the session almost ______ .',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['tedious','frightening','chaotic','effortless'],answer:0,
 expl:'An hour on four bars, slowed down and repeated, is the opposite of the fireworks the student expected. Tedious names that contrast.',
 wrong:'Effortless describes how the playing might sound, not how the session looked to someone who expected excitement.'},
{id:'SR166',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:2,
 passage:'Many people believe that goldfish have a memory of only a few seconds. Researchers have trained goldfish to push a lever for food at a particular time of day, and the fish return to the lever at that hour weeks later. The few-second claim has no experimental basis at all.',
 stem:'Which choice best states the function of the second sentence in the text as a whole?',
 choices:['It presents evidence against the belief described in the first sentence.','It explains why the belief described in the first sentence became popular.','It introduces a second common belief about goldfish.','It describes an experiment that failed to produce a clear result.'],answer:0,
 expl:'The first sentence gives the belief and the second reports fish remembering for weeks, which contradicts it. The third states the verdict.',
 wrong:'Choice D misreads the result: the fish returned to the lever weeks later, which is a clear outcome, not a failure.'},
{id:'SR167',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:2,
 passage:'The tallest tree ever measured was a Douglas fir in British Columbia, recorded at over 120 metres before it was felled in the nineteenth century. No living tree comes close. The tallest standing today is a coast redwood in California, at about 116 metres, and its exact location is kept secret to protect it from visitors.',
 stem:'Which choice best states the function of the last sentence in the text as a whole?',
 choices:['It identifies the current record holder and notes a measure taken to preserve it.','It questions whether the nineteenth-century measurement was accurate.','It explains why Douglas firs no longer reach their former heights.','It compares the growth rates of two species of tree.'],answer:0,
 expl:'After the historical record and the claim that nothing living matches it, the last sentence names the tallest living tree and explains why its location is withheld.',
 wrong:'Choice B doubts the old measurement, but the passage reports it without challenge and moves on to living trees.'},
{id:'SR168',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:2,
 passage:'Text 1\nSchool uniforms reduce distraction. When students are not comparing clothes, attention shifts toward the lesson, and mornings get simpler for families.\n\nText 2\nStudies comparing schools before and after uniform policies find small effects on attention, and those effects fade within a year. What does change is spending: families report paying more once a specific uniform is required.',
 stem:'Based on the texts, the author of Text 2 would most likely say that the benefit described in Text 1 is',
 choices:['smaller and shorter-lived than it is usually presented','the main reason uniforms should be adopted','impossible to measure in any school setting','larger in older students than in younger ones'],answer:0,
 expl:'Text 2 reports small effects on attention that fade within a year, which is a claim that the benefit is minor and temporary.',
 wrong:'Choice C says the effect cannot be measured, but Text 2 is describing studies that did measure it.'},
// ---------- Reading and Writing: Information and Ideas ----------
{id:'SR169',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:1,
 passage:'Sea otters eat sea urchins, and sea urchins eat kelp. When otters were hunted almost to extinction along parts of the Pacific coast, urchin populations grew without check and grazed the kelp forests down to bare rock. Where otters have returned, the kelp has grown back.',
 stem:'Which choice best states the main idea of the text?',
 choices:['The presence of sea otters affects whether kelp forests survive.','Sea urchins are the most numerous animals on the Pacific coast.','Kelp forests grow more slowly than they once did.','Hunting sea otters was banned in order to protect kelp.'],answer:0,
 expl:'The passage traces otters to urchins to kelp in both directions: remove the otters and the kelp goes, return them and it comes back.',
 wrong:'Choice D gives a reason for a ban that the passage never mentions. Stick to what the text states.'},
{id:'SR170',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:2,
 passage:'Before refrigeration, ice was harvested from frozen lakes in winter, cut into blocks, and packed in sawdust in insulated houses. A well-built ice house could keep its contents frozen through an entire summer. The trade was large enough that ships carried New England lake ice as far as India.',
 stem:'According to the text, what made it possible to keep harvested ice through the summer?',
 choices:['Packing the blocks in sawdust inside insulated ice houses','Cutting the blocks into uniform sizes before storage','Shipping the blocks to colder regions during warm months','Harvesting the ice later in the winter season'],answer:0,
 expl:'The passage says the blocks were packed in sawdust in insulated houses and that a well-built ice house held its contents through a summer.',
 wrong:'Choice C reverses the trade described: ships carried the ice to warmer places such as India, not to colder ones.'},
{id:'SR171',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:2,
 passage:'Katherine Johnson calculated flight trajectories for NASA at a time when electronic computers were new and not fully trusted. Before his 1962 orbital flight, John Glenn asked that the machine-generated numbers be checked by hand, and specifically that Johnson do the checking. She spent days on the calculation, and the flight proceeded.',
 stem:'According to the text, why did John Glenn request a hand calculation?',
 choices:['Electronic computers were new and not yet fully trusted.','Johnson had worked on every previous orbital flight.','The machine-generated numbers had already been shown to be wrong.','Hand calculation was faster than the available computers.'],answer:0,
 expl:'The first sentence gives the reason directly: computers were new and not fully trusted, which is why Glenn wanted the numbers checked by hand.',
 wrong:'Choice C says the numbers were known to be wrong, but the passage describes a precaution, not a correction.'},
{id:'SR172',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:2,
 passage:'Penguins have solid, dense bones, while most birds have hollow bones that reduce weight for flight. Dense bones make a body less buoyant and easier to hold underwater. Because penguins hunt by diving rather than by flying, their heavy skeletons ______',
 stem:'Which choice most logically completes the text?',
 choices:['suit the way they actually feed.','prevent them from swimming efficiently.','are lighter than those of other birds.','developed only in the largest species.'],answer:0,
 expl:'Dense bones help a body stay under water, and penguins hunt by diving, so the heavy skeleton matches how they feed.',
 wrong:'Choice C contradicts the first sentence, which states plainly that penguin bones are solid and dense rather than hollow.'},
{id:'SR173',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:2,
 passage:'A bakery tracked which loaves sold out first over six months. Sourdough sold out before noon on almost every day it was offered, while the seeded rye was still on the shelf at closing more often than not. If the bakery wants to reduce waste at the end of the day, the record suggests it should ______',
 stem:'Which choice most logically completes the text?',
 choices:['bake fewer loaves of the seeded rye.','stop offering sourdough altogether.','raise the price of both breads.','bake the two breads in equal numbers.'],answer:0,
 expl:'Waste at closing comes from the bread still on the shelf, which the record identifies as the seeded rye. Baking fewer of those reduces it.',
 wrong:'Choice B removes the bread that always sells, which would cut sales rather than waste.'},
{id:'SR174',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:2,
 passage:'A student is writing about the painter Hilma af Klint and has drafted the following claim: af Klint produced large abstract paintings years before the artists usually credited with inventing abstraction. The student has gathered four facts.',
 stem:'Which fact, if true, would most directly support the student claim?',
 choices:['She completed a series of large non-representational canvases in 1906, several years before the first abstract works of the painters usually credited with the form.','She studied at the Royal Academy of Fine Arts in Stockholm.','She asked that her abstract work not be exhibited until twenty years after her death.','She produced botanical illustrations and portraits throughout her career.'],answer:0,
 expl:'The claim is about dates: abstract work earlier than the usual credited artists. Choice A gives the year and the comparison.',
 wrong:'Choice C explains why the work went unseen, which is interesting but says nothing about when it was made.'},
// ---------- Reading and Writing: Standard English Conventions ----------
{id:'SR175',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:1,
 passage:'The museum opens at ten on weekdays ______ it opens an hour earlier on weekends.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:[', but',' but,','but',';but'],answer:0,
 expl:'Two complete sentences joined by but take a comma before the conjunction.',
 wrong:'Choice C leaves the two sentences with nothing between them. Cover the join and read each side: both stand alone, so they need punctuation.'},
{id:'SR176',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:1,
 passage:'After the storm passed ______ crews spent three days clearing branches from the road.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:[',','','; ',': '],answer:0,
 expl:'After the storm passed is an introductory clause, so a comma separates it from the main clause that follows.',
 wrong:'Choice C requires a complete sentence on both sides, and the opening clause cannot stand alone.'},
{id:'SR177',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:2,
 passage:'The recipe calls for three spices ______ cinnamon, cardamom, and cloves.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:[':',',','','; '],answer:0,
 expl:'A complete sentence comes first and a list naming the spices follows, which is what a colon introduces.',
 wrong:'Choice D would need a complete sentence after it. A list of three nouns is not a sentence.'},
{id:'SR178',section:'RW',type:'RW',sub:'Boundaries',skill:'rw_sec',diff:2,
 passage:'The violinist ______ who grew up in Caracas, joined the orchestra last spring.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:[',','','; ',': '],answer:0,
 expl:'The clause beginning who is set off by a comma at its end, so it needs a matching comma at its start.',
 wrong:'Choice B opens the interrupting clause with no punctuation while closing it with a comma. Paired punctuation has to come in pairs.'},
{id:'SR179',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:1,
 passage:'The box of tools ______ on the workbench by the door.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['sits','sit','are sitting','have sat'],answer:0,
 expl:'The subject is box, which is singular. Of tools is a prepositional phrase and does not change the number of the subject.',
 wrong:'Choice B agrees with tools, the nearest noun rather than the subject. Cross out the phrase and the sentence reads the box sits.'},
{id:'SR180',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:2,
 passage:'The orchestra will perform three pieces this evening, and ______ conductor has chosen to open with the shortest.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['its','it is','their','its own'],answer:0,
 expl:'The possessive its refers to the orchestra, a singular collective noun.',
 wrong:'Choice B is the contraction it is, which cannot own the noun conductor. Substituting it is into the sentence makes the error audible.'},
{id:'SR181',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:2,
 passage:'Last winter the research team ______ more snowfall at the summit station than in any season since records began.',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['recorded','records','will record','has recorded'],answer:0,
 expl:'Last winter places the action firmly in the past and it is finished, so the simple past is correct.',
 wrong:'Choice D is the present perfect, which connects a past action to now and clashes with the fixed past time last winter.'},
{id:'SR182',section:'RW',type:'RW',sub:'Form, Structure, and Sense',skill:'rw_sec',diff:2,
 passage:'Built in 1931 and restored twice since, ______',
 stem:'Which choice completes the text so that it conforms to the conventions of Standard English?',
 choices:['the theater still uses its original seats.','audiences still sit in the theater original seats.','the original seats are what audiences still use.','it is the theater that still has original seats.'],answer:0,
 expl:'The opening modifier describes what was built in 1931 and restored, which is the theater, so the theater must be the subject.',
 wrong:'Choice B puts the audiences in 1931. Ask what the opening phrase describes, then place it right after the comma.'},
// ---------- Reading and Writing: Expression of Ideas ----------
{id:'SR183',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:1,
 passage:'Bamboo is a grass, not a tree, and some species grow nearly a metre a day. ______ a bamboo stand can be harvested every few years, while a timber forest needs decades.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['As a result,','However,','By contrast,','Earlier,'],answer:0,
 expl:'The rapid growth is the cause and the short harvest cycle is its consequence.',
 wrong:'Choice B signals a contrast, but the second sentence follows naturally from the first rather than opposing it.'},
{id:'SR184',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:2,
 passage:'Most of the salt used on winter roads comes from underground mines rather than from the sea. ______ the largest such mine in North America runs for kilometres beneath a lake.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['In fact,','Nevertheless,','In contrast,','Afterward,'],answer:0,
 expl:'The second sentence extends the first with a striking instance of underground mining, which in fact introduces.',
 wrong:'Choice C sets the two sentences against each other, but the mine beneath a lake is an example of the claim, not an exception to it.'},
{id:'SR185',section:'RW',type:'RW',sub:'Transitions',skill:'rw_eoi',diff:2,
 passage:'Paper maps do not run out of battery and do not lose signal in a canyon. ______ they cannot tell you where you are standing, which is what most hikers who get lost actually need to know.',
 stem:'Which choice completes the text with the most logical transition?',
 choices:['On the other hand,','Therefore,','Similarly,','For example,'],answer:0,
 expl:'The first sentence gives advantages of paper maps and the second gives a disadvantage, which is a contrast.',
 wrong:'Choice B makes the limitation follow from the advantages, which does not hold.'},
{id:'SR186',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:2,
 passage:'While researching a topic, a student has taken the following notes:\n\n- The Eiffel Tower was completed in 1889 for a world fair.\n- It was intended to stand for twenty years and then be dismantled.\n- Gustave Eiffel installed antennas and offered the tower for radio experiments.\n- Its usefulness for radio transmission saved it from demolition.\n- It is now the most visited paid monument in the world.',
 stem:'The student wants to explain why the tower was not dismantled. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['The tower was meant to stand only twenty years, but its usefulness for radio transmission saved it from demolition.','The Eiffel Tower was completed in 1889 for a world fair held in Paris.','The Eiffel Tower is now the most visited paid monument in the world.','Gustave Eiffel installed antennas at the top of the tower.'],answer:0,
 expl:'The goal asks why it survived. Choice A gives the original plan and the reason it was not carried out.',
 wrong:'Choice D names the step Eiffel took without saying what it prevented. The goal asks for the outcome, not just the action.'},
{id:'SR187',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:2,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Mangrove forests grow along tropical coastlines in salt water.\n- Their roots trap sediment carried by rivers and tides.\n- Trapped sediment builds up the land behind the forest over time.\n- Mangroves also shelter young fish among their roots.\n- Many coastal communities fish those waters.',
 stem:'The student wants to describe how mangroves change the shoreline itself. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Mangrove roots trap sediment carried by rivers and tides, which builds up the land behind the forest over time.','Mangrove forests grow along tropical coastlines in salt water.','Mangroves shelter young fish among their roots, and many coastal communities fish those waters.','Mangroves are found in tropical regions rather than temperate ones.'],answer:0,
 expl:'Changing the shoreline is about sediment and land, and choice A gives the mechanism and the result.',
 wrong:'Choice C describes a benefit to fisheries rather than a change to the shoreline. Match the sentence to what the goal names.'},
{id:'SR188',section:'RW',type:'RW',sub:'Rhetorical Synthesis',skill:'rw_eoi',diff:1,
 passage:'While researching a topic, a student has taken the following notes:\n\n- Braille is a writing system of raised dots read by touch.\n- Louis Braille developed it in the 1820s while a student in Paris.\n- He based it on a military code for reading messages at night.\n- Each character fits under a fingertip.\n- The system is now adapted for dozens of languages.',
 stem:'The student wants to introduce Braille to an audience unfamiliar with it. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
 choices:['Braille is a writing system of raised dots, read by touch, in which each character fits under a fingertip.','Louis Braille based his system on a military code for reading messages at night.','The Braille system has now been adapted for dozens of languages.','Louis Braille was a student in Paris during the 1820s.'],answer:0,
 expl:'An introduction says what the thing is. Choice A defines the system and adds the detail that makes it work.',
 wrong:'Choice B gives an origin detail that assumes the reader already knows what Braille is.'},
// ---------- Math ----------
{id:'SM137',section:'M',type:'MC',sub:'Linear equations in one variable',skill:'m_alg',diff:1,
 stem:'If x + 9 = 23, what is the value of x?',
 choices:['14','16','32','207'],answer:0,
 expl:'Subtract 9 from both sides: x = 14.',
 wrong:'Choice C adds 9 instead of subtracting it. Undo the operation shown, and check by putting your answer back in.'},
{id:'SM138',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:1,
 stem:'The function f is defined by f(x) = 4x - 5. What is the value of f(3)?',
 choices:['7','12','17','-2'],answer:0,
 expl:'Substitute 3 for x: 4(3) - 5 = 12 - 5 = 7.',
 wrong:'Choice B stops after multiplying and forgets to subtract 5.'},
{id:'SM139',section:'M',type:'SPR',answerType:'spr',sub:'Linear equations in one variable',skill:'m_alg',diff:2,
 stem:'If 7x = 56, what is the value of x?',
 choices:[],answer:'8',
 expl:'Divide both sides by 7: x = 8.',
 wrong:'Multiplying instead of dividing gives 392. When a number sits beside the variable, divide by it.'},
{id:'SM140',section:'M',type:'MC',sub:'Linear equations in two variables',skill:'m_alg',diff:2,
 stem:'What is the slope of the line y = -5x + 2?',
 choices:['-5','2','5','-2'],answer:0,
 expl:'In slope-intercept form y = mx + b, the slope is the coefficient of x, here -5.',
 wrong:'Choice B is the y-intercept. The number multiplied by x is always the slope; the lone constant is the intercept.'},
{id:'SM141',section:'M',type:'MC',sub:'Percentages',skill:'m_psda',diff:1,
 stem:'What is 20 percent of 150?',
 choices:['30','20','35','75'],answer:0,
 expl:'Ten percent of 150 is 15, so 20 percent is 30.',
 wrong:'Choice B repeats the percent rather than applying it. A percent becomes a number only after it is taken of something.'},
{id:'SM142',section:'M',type:'MC',sub:'Ratios, rates, proportional relationships, and units',skill:'m_psda',diff:2,
 stem:'A printer produces 24 pages in 3 minutes. At this rate, how many pages does it produce in 7 minutes?',
 choices:['56','48','63','72'],answer:0,
 expl:'The rate is 24 divided by 3, or 8 pages per minute, so 7 minutes gives 56 pages.',
 wrong:'Choice D multiplies 24 by 3. Find the per-minute rate first, then scale it to the time asked for.'},
{id:'SM143',section:'M',type:'SPR',answerType:'spr',sub:'One-variable data: distributions and measures of center and spread',skill:'m_psda',diff:2,
 stem:'What is the mean of the values 4, 8, 9, and 11?',
 choices:[],answer:'8',
 expl:'The values sum to 32, and 32 divided by 4 is 8.',
 wrong:'Answering 8.5 reports the median, the average of the two middle values. The mean divides the total by the count.'},
{id:'SM144',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:2,
 stem:'Which expression is equivalent to 3(x + 5)?',
 choices:['3x + 15','3x + 5','x + 15','3x + 8'],answer:0,
 expl:'Distribute the 3 to both terms inside the parentheses: 3x + 15.',
 wrong:'Choice B multiplies only the first term. Distribution reaches every term inside the parentheses.'},
{id:'SM145',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:2,
 stem:'If x^2 = 36 and x is positive, what is the value of x?',
 choices:['6','18','72','1296'],answer:0,
 expl:'The positive square root of 36 is 6.',
 wrong:'Choice B halves 36 rather than taking a root, and choice D squares it again.'},
{id:'SM146',section:'M',type:'MC',sub:'Area and volume',skill:'m_geo',diff:1,
 stem:'A rectangle has a length of 9 and a width of 4. What is its area?',
 choices:['36','13','26','18'],answer:0,
 expl:'Area is length times width: 9 times 4 is 36.',
 wrong:'Choice C is the perimeter, 2(9 + 4). Area multiplies the two dimensions; perimeter adds around the outside.'},
{id:'SM147',section:'M',type:'MC',sub:'Lines, angles, and triangles',skill:'m_geo',diff:2,
 stem:'Two angles of a triangle measure 30 degrees and 90 degrees. What is the measure of the third angle?',
 choices:['60 degrees','30 degrees','90 degrees','120 degrees'],answer:0,
 expl:'The angles of a triangle sum to 180 degrees, so the third is 180 - 30 - 90 = 60.',
 wrong:'Choice D adds the two given angles instead of subtracting them from 180.'},
{id:'SM148',section:'M',type:'SPR',answerType:'spr',sub:'Circles',skill:'m_geo',diff:2,
 stem:'A circle has a diameter of 14. What is its radius?',
 choices:[],answer:'7',
 expl:'The radius is half the diameter: 14 divided by 2 is 7.',
 wrong:'Answering 28 doubles the diameter. The radius reaches from the center to the edge, which is half the way across.'}
];
