// bank_sat_rw.js - Original SAT Reading and Writing items SR001-SR032:
// Craft and Structure, Information and Ideas. On the digital SAT each question carries its own
// short passage (25 to 150 words) and four answer choices, so every item here holds its own text.
const BANK_SAT_RW = [
// ---------- Craft and Structure: Words in Context ----------
{id:'SR001',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:2,
 passage:'Marine biologists who study the ocean twilight zone face a practical problem: many of the animals living there are gelatinous and nearly transparent, and a traditional sampling net tears them apart on contact. Researchers have responded by building camera systems that photograph the creatures where they drift, leaving the animals ______ and the records intact.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['unnoticed','unproven','unrelated','undisturbed'],answer:3,
 expl:'The sentence contrasts nets that tear the animals apart with cameras that photograph them in place. The blank needs a word meaning the animals are left unharmed, which is undisturbed.',
 wrong:'Unnoticed reverses the point: the cameras exist precisely so the animals are observed. A contrast blank takes the opposite of the problem named just before it.'},
{id:'SR002',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'Rather than working up a portrait from preliminary sketches, the painter John Singer Sargent often began directly on the canvas, revising the pose and the background as he went. Critics who prize deliberate planning have judged the approach ______, yet the finished portraits carry a spontaneity that more cautious studio methods rarely produce.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['methodical','derivative','reckless','celebrated'],answer:2,
 expl:'The word yet signals that the critics judgment is negative while the result is admirable. Critics who prize planning would call an unplanned method reckless.',
 wrong:'Methodical describes the critics own preference, not what they think of Sargent. When a sentence turns on yet or but, the two halves must disagree.'},
{id:'SR003',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'In her address at the 1848 convention in Seneca Falls, Elizabeth Cady Stanton did not ask her audience to accept an unfamiliar principle. She argued instead that the rights already named in the Declaration of Independence should be applied ______: if the claim that all are created equal meant anything, its reach could not stop at men.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['selectively','consistently','reluctantly','privately'],answer:1,
 expl:'The colon introduces the explanation: a principle that means anything cannot stop partway. Applying it without exception is applying it consistently.',
 wrong:'Selectively names exactly what Stanton objected to. Text after a colon defines the blank before it, so read the explanation before choosing.'},
{id:'SR004',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:4,
 passage:'Ecologists long described a mature forest as an arena of competition, with old trees crowding seedlings out of the light. Studies of the fungal networks threading through forest soil have ______ that account: mature trees appear to pass carbon through those networks to shaded young trees, including trees not of their own species.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['complicated','confirmed','restated','abandoned'],answer:0,
 expl:'The new finding does not overturn competition outright; it adds a cooperative mechanism the older account did not include. Complicated captures a view made less simple rather than proved or discarded.',
 wrong:'Abandoned is too strong: the text says the new evidence sits alongside the old picture, not that ecologists dropped it. Precision questions punish the most dramatic word.'},
{id:'SR005',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:5,
 passage:'The butler who narrates the novel recounts thirty years of service without once naming what he feels. He notes the polish on the silver, the timing of the bells, the exact wording of an employer instruction. His account is so ______ that the reader must assemble his grief out of the subjects he declines to raise.',
 stem:'Which choice completes the text with the most logical and precise word or phrase?',
 choices:['ornate','erratic','indignant','restrained'],answer:3,
 expl:'The narrator reports surfaces and withholds feeling, which the last clause confirms by saying the reader must infer grief from omissions. Restrained names that withholding.',
 wrong:'Indignant supplies an emotion the text says the narrator never expresses. The blank has to match the behavior described, not the feeling hidden underneath it.'},
{id:'SR006',section:'RW',type:'RW',sub:'Words in Context',skill:'rw_cs',diff:3,
 passage:'Working without the computers that later mapmakers would rely on, the geologist Marie Tharp plotted thousands of individual depth soundings by hand to chart the floor of the Atlantic. Her drawings revealed a continuous rift valley running the length of the mid-ocean ridge, a feature a colleague at first dismissed out of hand. Within a decade that rift had become central evidence for seafloor spreading, and Tharp painstaking method was taken up across the field.',
 stem:'As used in the text, what does the word "painstaking" most nearly mean?',
 choices:['Physically uncomfortable','Widely publicized','Careful and thorough','Recently invented'],answer:2,
 expl:'The text describes thousands of soundings plotted one at a time by hand, which is a description of care and thoroughness.',
 wrong:'Choice A reads the parts of the word rather than its use. Vocabulary questions are settled by the sentences around the word, not by its spelling.'},
// ---------- Craft and Structure: Text Structure and Purpose ----------
{id:'SR007',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:3,
 passage:'For most of the twentieth century, textbooks treated the octopus as a solitary animal of modest intelligence. Aquarium keepers told a different story, trading accounts of octopuses that opened latched jars, squirted water at particular staff members, and escaped through drain pipes overnight. Laboratory work has since caught up with the keepers: octopuses solve novel mechanical puzzles, and individuals differ reliably in how boldly they approach them.',
 stem:'Which choice best states the function of the last sentence in the text as a whole?',
 choices:['It introduces an objection to the claims made by aquarium keepers.','It presents research findings that support observations the text had described as informal.','It explains why textbooks were slow to revise their account of the octopus.','It proposes a new experiment that researchers have yet to carry out.'],answer:1,
 expl:'The keepers accounts were anecdotal; the final sentence reports laboratory results that match them, so it lends formal support to informal observation.',
 wrong:'Choice A has the relationship backward. The phrase caught up with tells you the research agrees with the keepers rather than disputing them.'},
{id:'SR008',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:4,
 passage:'Composers writing for silent film theaters in the 1920s faced a constraint their concert-hall colleagues did not: the music had to be assembled in a week, played by whatever players a house could afford, and cut to fit reels that might arrive shorter than advertised. The solution was the cue sheet, a catalog of short interchangeable passages indexed by mood. A conductor could build an evening score in an afternoon. The practice produced little music that survives on its own, but it trained a generation of arrangers in the pacing that later defined film scoring in Hollywood.',
 stem:'Which choice best describes the overall structure of the text?',
 choices:['It describes a practical problem, explains the method developed to solve it, and identifies a lasting consequence of that method.','It compares two schools of composition and argues that one produced better music than the other.','It traces the career of a single composer from early constraints to later success.','It lists objections to a common practice and then rejects each of them in turn.'],answer:0,
 expl:'The text moves from the constraint film composers faced, to the cue sheet that answered it, to the effect on later Hollywood scoring. That is problem, solution, consequence.',
 wrong:'Choice B seizes on the single clause about music that does not survive. One evaluative aside does not make the whole text a comparison.'},
{id:'SR009',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:3,
 passage:'Every year, migrating songbirds collide with lighted office towers in large numbers. The usual remedy proposed is bird-safe glass, which is expensive and slow to install across a skyline. A study in Chicago points to something cheaper: on nights when building managers switched off roughly half the lights in one exhibition hall, collisions at that building fell sharply. Light, not glass alone, appears to be what draws the birds off course.',
 stem:'Which choice best states the function of the second sentence in the text as a whole?',
 choices:['It offers evidence that supports the claim made in the first sentence.','It identifies the cause of the problem introduced in the first sentence.','It concedes a weakness in the study the text later reports.','It names a solution whose drawbacks set up the alternative the text goes on to describe.'],answer:3,
 expl:'The second sentence presents bird-safe glass as expensive and slow, and the word cheaper in the next sentence marks the study as the alternative. Its job is to set up that contrast.',
 wrong:'Choice B names the cause, but the cause arrives in the last sentence, which identifies light. A sentence function question asks what that sentence does, not what the text concludes.'},
{id:'SR010',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:5,
 passage:'Historians of the Dust Bowl once explained the disaster largely through drought, treating the plowed grassland as an unlucky stage for a natural event. More recent work reverses the emphasis. Rainfall records show dry spells of comparable severity in the same region in earlier decades without comparable dust storms; what had changed by the 1930s was the removal of deep-rooted native grasses across millions of acres. The drought was the trigger. The soil had already been made ready to move.',
 stem:'Which choice best describes the main rhetorical purpose of the text?',
 choices:['To establish that drought played no role in the Dust Bowl','To argue that a familiar explanation mistakes a trigger for an underlying cause','To compare the severity of several droughts in the same region','To recommend a specific method for preventing future dust storms'],answer:1,
 expl:'The text grants that drought triggered the storms but argues the deeper cause was the loss of native grass cover, which is a correction about what counts as the cause.',
 wrong:'Choice A overstates. The text explicitly calls the drought the trigger; it reassigns the weight rather than denying the role.'},
{id:'SR011',section:'RW',type:'RW',sub:'Text Structure and Purpose',skill:'rw_cs',diff:4,
 passage:'Zora Neale Hurston trained as an anthropologist before she published the novel for which she is now best known. That training shows in her ear: the speech in her fiction is transcribed rather than smoothed, with the rhythms and idioms of the Florida communities she had documented left intact. Contemporaries who preferred a more literary diction read this as a failure of craft. Later readers have read it as the point.',
 stem:'Which choice best states the function of the final sentence in the text as a whole?',
 choices:['It explains how Hurston anthropological training was received by her colleagues.','It concedes that the criticism described earlier in the text was justified.','It contrasts a later assessment of a feature of Hurston writing with an earlier one.','It introduces a new feature of Hurston fiction not previously mentioned.'],answer:2,
 expl:'The last sentence sets later readers against the contemporaries of the sentence before, reversing the judgment on the same feature of her prose.',
 wrong:'Choice B inverts the meaning. Read this as the point says the earlier critics missed what Hurston was doing, not that they were right.'},
// ---------- Craft and Structure: Cross-Text Connections ----------
{id:'SR012',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:4,
 passage:'Text 1\nUrban planners have argued for decades that adding lanes to a congested highway relieves congestion. The reasoning is straightforward: a road carrying more vehicles per hour should move a given number of drivers in less time.\n\nText 2\nTravel data from widened corridors complicates that reasoning. Within a few years of an expansion, traffic volume typically rises to fill the new capacity, and average travel times return to roughly what they were. Drivers who had shifted their trips to off-peak hours or to other routes shift back once the road looks faster.',
 stem:'Based on the texts, how would the author of Text 2 most likely respond to the reasoning presented in Text 1?',
 choices:['By agreeing that widening a highway reduces travel times for most drivers','By arguing that planners have rarely widened highways in practice','By pointing out that off-peak travel is more dangerous than peak travel','By noting that the reasoning holds capacity fixed while treating demand as if it were fixed too'],answer:3,
 expl:'Text 2 says volume rises to fill new capacity because drivers change their behavior. That is an objection to treating the number of drivers as a fixed quantity.',
 wrong:'Choice A agrees with Text 1, which is the opposite of what Text 2 shows. A cross-text question turns on the disagreement, so name it before reading the choices.'},
{id:'SR013',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:5,
 passage:'Text 1\nThe standard account of the printing press credits it with spreading new scientific ideas quickly through Europe. By making identical copies cheap, the press is said to have let a claim made in one city be tested in another.\n\nText 2\nThe press printed whatever sold, and what sold in the first century of printing was mostly devotional work, almanacs, and reprints of classical authorities. Editions of ancient texts circulated far more widely than any new observation. What the press changed first was not the supply of new ideas but the durability of old ones.',
 stem:'Based on the texts, the author of Text 2 would most likely characterize the account in Text 1 as',
 choices:['accurate about the eventual effect of printing but misleading about its early effect','correct in every respect but insufficiently detailed','mistaken in assuming that printed copies were identical','persuasive because it rests on the commercial record of early printers'],answer:0,
 expl:'Text 2 does not deny that printing spread new claims; it says that in the first century the press mostly multiplied old texts. The objection is about timing and emphasis.',
 wrong:'Choice C attacks a point Text 2 never disputes. Identical copies is Text 1 mechanism, and Text 2 quarrels with what was copied, not with whether copies matched.'},
{id:'SR014',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:4,
 passage:'Text 1\nA long-running claim in cognitive science holds that people learn better when material is presented in the format they prefer, whether visual, auditory, or hands-on. Surveys find that most teachers accept this idea.\n\nText 2\nTesting the claim requires a specific design: match some learners to their stated preference, mismatch others, and compare results on the same assessment. Studies that use this design generally find no advantage for the matched group. What does predict performance is whether the format suits the material, a picture for spatial relationships, for instance, regardless of preference.',
 stem:'Based on the texts, how would the author of Text 2 most likely respond to the surveys mentioned in Text 1?',
 choices:['By arguing that teachers surveyed were not familiar with the relevant material','By observing that widespread belief in the claim is not evidence that the claim is true','By suggesting that the surveys should have included more visual learners','By concluding that learner preferences have no effect on any outcome'],answer:1,
 expl:'Text 2 answers the claim with experimental design and results, treating the question as empirical. The popularity reported in Text 1 is simply beside that point.',
 wrong:'Choice D goes further than Text 2 does: it reports no advantage in matched formats, not that preferences never matter for anything.'},
{id:'SR015',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:4,
 passage:'Text 1\nConservation programs have often measured success by counting individuals. A population that grows from two hundred animals to six hundred is treated as a recovery, and protection is relaxed accordingly.\n\nText 2\nCounts can rise while a population becomes more fragile. If the growth traces back to a handful of breeding individuals, genetic variation stays low, and low variation leaves a population poorly equipped for a new disease or a shifted climate. Census size and effective population size are not the same quantity.',
 stem:'Based on the texts, the author of Text 2 would most likely argue that the practice described in Text 1',
 choices:['sets its numerical threshold for recovery too low','should be applied to plant populations as well as animal populations','relies on a measure that can miss an important kind of vulnerability','has been abandoned by most conservation programs'],answer:2,
 expl:'Text 2 distinguishes census size from effective population size and shows a count can rise while genetic vulnerability persists. That is an objection to the measure itself.',
 wrong:'Choice A accepts counting and only quarrels with the number. Text 2 objection is that the quantity being counted is the wrong one.'},
{id:'SR016',section:'RW',type:'RW',sub:'Cross-Text Connections',skill:'rw_cs',diff:5,
 passage:'Text 1\nThe poet insisted that a poem should carry no message that could be stated in prose. A poem that can be summarized, she wrote, has been replaced by its summary.\n\nText 2\nEvery poem that has mattered politically has been paraphrasable, and its paraphrase is often what carried it. Readers repeat a line because of what it says. To require that a poem resist summary is to confuse a quality some poems have with a standard all poems must meet.',
 stem:'Based on the texts, the author of Text 2 would most likely describe the standard proposed in Text 1 as',
 choices:['an accurate rule that most contemporary poets fail to meet','a position that no reader has ever seriously defended','a useful test for distinguishing political poetry from other kinds','a description of one kind of poem mistaken for a rule about all poems'],answer:3,
 expl:'The final sentence of Text 2 states the objection directly: a quality some poems have has been turned into a standard all poems must meet.',
 wrong:'Choice A agrees with Text 1 standard and only doubts compliance. Text 2 rejects the standard itself.'},
// ---------- Information and Ideas: Central Ideas and Details ----------
{id:'SR017',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:2,
 passage:'The Antikythera mechanism, recovered from a Roman-era shipwreck in 1901, spent decades in storage as a corroded lump of bronze. Imaging with X-ray tomography eventually revealed more than thirty interlocking gears inside. The device modeled the motions of the sun and moon and predicted eclipses. Nothing of comparable mechanical complexity is known from the next thousand years of surviving evidence.',
 stem:'Which choice best states the main idea of the text?',
 choices:['An ancient device turned out to be far more mechanically sophisticated than its condition suggested.','Underwater archaeology has produced more discoveries than land-based excavation.','X-ray tomography was invented in order to study ancient artifacts.','Roman shipwrecks usually contain scientific instruments.'],answer:0,
 expl:'The text moves from a corroded lump to thirty interlocking gears to a thousand years without an equal, all supporting the sophistication of the object.',
 wrong:'Choice C reverses cause and use: tomography was applied to the artifact, which is not a claim about why the technique exists.'},
{id:'SR018',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:3,
 passage:'In the 1930s the folklorist John Lomax traveled the American South with a recording machine weighing more than three hundred pounds, cutting songs directly onto aluminum and lacquer discs. The weight dictated the collection: he recorded where a truck could go and where a power source could be found. The archive that resulted is indispensable and, in a way easy to overlook, shaped by the road network of the decade in which it was made.',
 stem:'Which choice best states the main idea of the text?',
 choices:['Early recording equipment produced sound quality inferior to that of modern devices.','A valuable recorded archive was shaped in part by the practical limits of the equipment used to make it.','Folk songs from the American South were in danger of disappearing in the 1930s.','Lomax preferred to record musicians who lived near major highways.'],answer:1,
 expl:'The last sentence states the idea directly: the archive is indispensable and shaped by where a heavy machine could be taken.',
 wrong:'Choice D turns a constraint into a preference. The text says the weight dictated where he could record, not that he chose those musicians for their own sake.'},
{id:'SR019',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:2,
 passage:'Emperor penguins huddle through the Antarctic winter in groups that can exceed a thousand birds. The huddle is not static. Birds at the windward edge gradually shuffle toward the interior as the group moves, and the traveling wave that results circulates individuals through the warm center and the cold perimeter over the course of hours.',
 stem:'According to the text, what is true of the position of an individual penguin within a huddle?',
 choices:['It is fixed once the huddle forms for the season.','It is determined by the size of the bird relative to its neighbors.','It changes over time as the huddle circulates birds between the edge and the center.','It shifts only when the wind direction reverses.'],answer:2,
 expl:'The text says birds at the windward edge shuffle inward and that the resulting wave circulates individuals through center and perimeter over hours.',
 wrong:'Choice D attaches the movement to a change in wind. The text describes continuous circulation, not a response to a reversal.'},
{id:'SR020',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:4,
 passage:'Architects have long assumed that occupants of naturally ventilated buildings accept a wider range of indoor temperatures than occupants of air-conditioned ones. Field surveys across several climates support the assumption and suggest a mechanism: when people can open a window, adjust a blind, or move a fan, the same temperature is reported as more comfortable than it is when the setting is fixed. Comfort tracks control as much as it tracks degrees.',
 stem:'Which choice best states the main idea of the text?',
 choices:['Naturally ventilated buildings maintain more stable temperatures than air-conditioned buildings.','Field surveys are a more reliable research method than laboratory experiments.','Perceived thermal comfort depends on an occupant ability to adjust conditions, not on temperature alone.','Occupants of air-conditioned buildings report discomfort at every temperature.'],answer:2,
 expl:'The closing sentence states it: comfort tracks control as much as it tracks degrees, with the survey mechanism explaining how.',
 wrong:'Choice A reverses the physics. Naturally ventilated buildings vary more in temperature; what is wider is the range occupants accept.'},
{id:'SR021',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:3,
 passage:'When the sculptor Ruth Asawa began making her looped-wire hanging forms in the 1950s, galleries had trouble placing them. The pieces were made with a crochet technique Asawa had learned in Mexico, using industrial wire, and they hung in the air rather than standing on a base. Reviewers reached for the vocabulary of craft and domestic handwork, and the sculptures were widely described as decorative for the better part of three decades.',
 stem:'According to the text, why did reviewers of Asawa early work describe it as decorative?',
 choices:['Her sculptures were smaller than most gallery pieces of the period.','The technique and materials she used were associated with craft rather than with sculpture.','She exhibited primarily outside of major cities.','The work was designed to be displayed in private homes.'],answer:1,
 expl:'The text links the description to the crochet technique and the way the pieces hung, which sent reviewers to the vocabulary of craft and domestic handwork.',
 wrong:'Choice D supplies a reason the text never gives. Detail questions are answered inside the passage, never from plausible background knowledge.'},
{id:'SR022',section:'RW',type:'RW',sub:'Central Ideas and Details',skill:'rw_ii',diff:4,
 passage:'A common account of language loss describes it as a gradual thinning, with each generation speaking a slightly reduced version of what came before. Linguists working with communities in the Pacific Northwest describe something different and faster. A language can pass from full daily use to ceremonial use within one generation when schooling, employment, and media all shift to another language at once. The change is not a slope but a step.',
 stem:'Which choice best states the main idea of the text?',
 choices:['Language loss can occur abruptly rather than through the gradual decline often assumed.','Languages of the Pacific Northwest are more resilient than languages elsewhere.','Ceremonial use of a language is more durable than daily use.','Schooling is the single cause of language loss in most communities.'],answer:0,
 expl:'The text sets a gradual thinning against a one-generation shift and closes with not a slope but a step, which is the contrast it exists to draw.',
 wrong:'Choice D isolates one of three pressures the text names together. The passage attributes the speed to schooling, employment, and media shifting at once.'},
// ---------- Information and Ideas: Command of Evidence ----------
{id:'SR023',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'A student is researching the poet Gwendolyn Brooks and has written the following claim: Brooks used tightly controlled traditional forms to hold material that those forms had rarely been asked to carry. The student has gathered four observations about the 1945 collection A Street in Bronzeville.',
 stem:'Which observation, if true, would most directly support the student claim?',
 choices:['The collection was published when Brooks was twenty-eight years old.','Brooks revised a number of the poems substantially between their first publication in magazines and their appearance in the book.','Critics at the time praised the collection for its technical accomplishment.','Several poems in the collection are strict sonnets whose subjects are wartime segregation and daily life in a Chicago kitchenette building.'],answer:3,
 expl:'The claim has two halves: strict traditional form, and unexpected subject matter. Only choice D supplies both, naming sonnets and the subjects they carry.',
 wrong:'Choice C praises technique but says nothing about subject matter, so it supports only half the claim. Evidence questions are won by matching every part of the claim, not by finding the most flattering fact.'},
{id:'SR024',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'Researchers hypothesized that urban coyotes avoid people not by leaving developed areas but by shifting when they use them. To test the hypothesis, the team fitted coyotes in a metropolitan area with GPS collars and compared their locations and activity with those of coyotes in nearby rural areas.',
 stem:'Which finding from the study, if true, would most strongly support the hypothesis?',
 choices:['Urban coyotes occupied smaller territories overall than rural coyotes did.','Urban coyotes and rural coyotes consumed a similar number of small mammals.','Urban coyotes used the same range of habitats as rural coyotes but were active mainly between midnight and dawn.','Urban coyotes were observed more often near parks than near residential streets.'],answer:2,
 expl:'The hypothesis is that avoidance happens in time rather than in space. Same habitats plus a shift to the hours when people are absent is exactly that pattern.',
 wrong:'Choice A is about space alone and, if anything, cuts against the claim that the animals are not leaving developed areas. Match the finding to the variable the hypothesis names, which here is timing.'},
{id:'SR025',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:5,
 passage:'In a study of how people judge the reliability of news, participants rated headlines they had seen once before as more likely to be true than headlines they were seeing for the first time, even when the repeated headlines carried a warning label. The researchers concluded that familiarity influences judgments of truth independently of what a reader is told about accuracy.',
 stem:'Which finding, if true, would most directly undermine the researchers conclusion?',
 choices:['Participants rated headlines about politics as less reliable than headlines about science.','Participants who reported paying close attention to the warning labels rated repeated and new headlines as equally likely to be true.','Most participants could not recall which specific headlines they had seen before.','The study was conducted with participants recruited from a single university.'],answer:1,
 expl:'The conclusion is that familiarity works independently of the warning. If attending to the warning erases the repetition advantage, the effect is not independent of what readers are told.',
 wrong:'Choice C is consistent with the conclusion rather than against it: an effect that works without conscious recall is still an effect. Choice D limits how far the result generalizes but leaves the mechanism intact.'},
{id:'SR026',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:4,
 passage:'A researcher studying a nineteenth-century mill town claims that the town payroll records are a poor guide to who actually worked in the mills. She has assembled several kinds of documentary evidence from the same decade.',
 stem:'Which piece of evidence, if true, would most directly support the researcher claim?',
 choices:['Census returns list hundreds of women and children as mill operatives whose names appear nowhere in the payroll ledgers, which recorded payments to household heads.','The payroll ledgers were kept in a consistent format throughout the decade.','Mill output rose steadily during the decade covered by the records.','Several other mill towns in the region kept payroll records of a similar kind.'],answer:0,
 expl:'The claim is that the payroll misses workers. Choice A names a specific group who worked but were not recorded, and explains the mechanism: payment went to household heads.',
 wrong:'Choice B supports the records consistency, which is closer to the opposite of the claim. Consistent and complete are different properties.'},
{id:'SR027',section:'RW',type:'RW',sub:'Command of Evidence',skill:'rw_ii',diff:5,
 passage:'Text from a lecture: "The objection I keep hearing is that community solar programs serve only households wealthy enough to subscribe. That was true of the first generation of programs, which required an upfront payment. It is not true of the programs built since, and the enrollment data show it."',
 stem:'Which quotation from a program report would most effectively support the lecturer position?',
 choices:['"Community solar capacity in the state has tripled over the past four years."','"Subscribers report high satisfaction with the program regardless of household income."','"The first community solar programs in the state launched in 2012 and required a payment of at least 500 dollars."','"Since the subscription fee was replaced by an on-bill credit, 61 percent of new subscribers have come from households below the area median income."'],answer:3,
 expl:'The lecturer claims newer program designs changed who enrolls. Choice D ties a specific design change to a majority of new subscribers below median income.',
 wrong:'Choice C restates the part of the objection the lecturer already concedes. Supporting evidence has to speak to the disputed half of a claim, not the conceded half.'},
// ---------- Information and Ideas: Inferences ----------
{id:'SR028',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:3,
 passage:'Honeybee colonies choosing a new nest site send scouts to inspect candidate cavities. A scout that finds a promising site returns and dances, and the length of her dance scales with the quality of what she found. Other scouts visit the advertised site and dance in turn if they agree. Because a weak site attracts short dances and therefore few recruits, ______',
 stem:'Which choice most logically completes the text?',
 choices:['individual scouts usually inspect every available cavity before dancing.','the colony chooses a site before any scout has inspected it.','the colony tends to converge on the best of the sites its scouts have found.','dance length is unrelated to the number of scouts recruited.'],answer:2,
 expl:'Better sites produce longer dances, longer dances recruit more scouts, and more scouts produce more dances. The described feedback loop concentrates support on the best site found.',
 wrong:'Choice D contradicts the sentence it is meant to complete, which says a weak site attracts short dances and therefore few recruits.'},
{id:'SR029',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:4,
 passage:'Archaeologists dating a site often rely on radiocarbon measurements of charcoal from hearths. Charcoal, however, records the year the tree grew the wood, not the year someone burned it. In regions where builders favored long-lived species and salvaged old timber, a hearth sample can be centuries older than the fire it came from. For sites in such regions, therefore, ______',
 stem:'Which choice most logically completes the text?',
 choices:['radiocarbon dating cannot be applied to charcoal of any kind.','radiocarbon dates from charcoal may indicate an occupation earlier than the actual one.','the occupation is likely to be more recent than any other method would suggest.','charcoal samples are more reliable than samples of short-lived material.'],answer:1,
 expl:'If the wood predates the fire, the measured date predates the occupation, so the site would appear older than it is.',
 wrong:'Choice D reverses the implication. The passage identifies exactly the weakness that makes short-lived material, such as seeds, the safer sample.'},
{id:'SR030',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:4,
 passage:'A city measured traffic speed on a commercial street before and after narrowing the driving lanes and widening the sidewalks. Average vehicle speed fell by about six miles per hour, and the number of vehicles passing per hour was essentially unchanged. Because the same number of drivers continued to use the street, the change in speed cannot be explained by ______',
 stem:'Which choice most logically completes the text?',
 choices:['the width of the sidewalks after the redesign.','the behavior of drivers responding to a narrower lane.','measurements taken at different times of day.','a reduction in the number of vehicles using the street.'],answer:3,
 expl:'The passage explicitly reports that vehicle volume was essentially unchanged, which rules out fewer vehicles as the explanation for the slowdown.',
 wrong:'Choice B names the explanation the data actually leave standing. The blank follows cannot be explained by, so it takes the eliminated cause, not the surviving one.'},
{id:'SR031',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:5,
 passage:'Two islands in the same chain were colonized by the same finch species. On the larger island, where several seed types are abundant year round, beak depth in the population varies widely. On the smaller island, where a single hard-shelled seed is the only reliable food during the dry season, beak depth clusters tightly around a deep profile. This pattern suggests that ______',
 stem:'Which choice most logically completes the text?',
 choices:['a narrow range of available food can reduce variation in a trait tied to feeding.','islands of larger area always support greater genetic diversity in every trait.','beak depth is unrelated to the types of seeds a finch can open.','the finches on the smaller island arrived more recently than those on the larger island.'],answer:0,
 expl:'The contrast is between varied food with varied beaks and one hard seed with uniformly deep beaks, which points to the food supply narrowing the trait.',
 wrong:'Choice B generalizes to every trait and to all islands from a single pair. An inference must stay inside what the evidence covers.'},
{id:'SR032',section:'RW',type:'RW',sub:'Inferences',skill:'rw_ii',diff:3,
 passage:'Museums that have begun publishing high-resolution images of their collections without use restrictions report an outcome that surprised some curators. Rather than reducing visits, the open images have coincided with steady or rising attendance, and staff note that visitors increasingly arrive already familiar with specific works. This suggests that for these museums, free access to images functions less like a substitute for a visit than like ______',
 stem:'Which choice most logically completes the text?',
 choices:['a replacement for the collection catalog.','an invitation to one.','a source of licensing revenue.','a restriction on scholarly use.'],answer:1,
 expl:'The sentence sets up a contrast with substitute, and the evidence is steady or rising attendance by visitors who already know the works. An invitation completes that contrast.',
 wrong:'Choice C introduces revenue, which the passage never raises and which the phrase without use restrictions argues against.'}
];
