// bank_act_reading.js - Original ACT Reading items AR001-AR040.
// Four answer choices. Skills are ACT's three published reporting categories for Reading:
// Key Ideas and Details, Craft and Structure, and Integration of Knowledge and Ideas.
// ACT describes the section as made of multiple parts, some a single long prose passage and
// some shorter prose passages, with paired shorter passages in at least one part, so this bank
// mixes lengths and includes one paired set. Every part covers all three categories.
const AR_P1 = 'LITERARY NARRATIVE: The Inventory\n\nMy grandmother kept a ledger of everything in her house. Not a list of valuables for insurance, which is what I assumed when I first found it, but an inventory of objects, each with a line of provenance: where it came from, who had owned it before, and, in a column she had ruled herself, what she called its use.\n\nThe use column was the strange one. A copper pot was entered as "soup, and holding the door in August." A chipped enamel basin: "washing greens; catching the drip under the sink, 1971 to 1974." Some entries had been amended twice. The ledger was not a record of what she owned. It was a record of what she had asked her possessions to do.\n\nI was twenty-two when she died and the house had to be emptied in four days. My aunt wanted the furniture gone; my mother wanted the photographs; nobody wanted the ledger, which was water-stained along the bottom edge and written in a hand that had grown difficult in the last decade. I took it because no one stopped me.\n\nFor years I treated it as a curiosity. Then I moved into a flat with almost nothing in it and found myself, one evening, looking at a secondhand chair and thinking about what I would write in the use column. The question turned out to be harder than owning the chair. It required me to admit that I had bought it because it resembled a chair in a photograph, and that I had not yet asked it to do anything at all.\n\nI have kept my own ledger since, though I am not as honest in it as she was. She recorded failures. Against a set of good knives, given at a wedding, she had written "not used; too good," and then, in different ink, years later, "still not used." She left the line standing. She did not go back and invent a purpose to fill it.';
const AR_P2 = 'SOCIAL SCIENCE: Counting the Commons\n\nFor three decades after 1968, most economics textbooks presented common ownership of a resource as a recipe for its destruction. The argument was elegant: if a pasture is open to all, each herder gains the full benefit of an additional animal while bearing only a fraction of the cost of overgrazing, so every herder adds animals until the pasture fails. The logic is sound, and the conclusion drawn from it, that commons must be privatised or placed under state control, followed so naturally that few economists examined whether real commons behaved that way.\n\nElinor Ostrom did examine them. Beginning in the 1970s she and her collaborators assembled case studies of irrigation systems, inshore fisheries, forests and alpine pastures, some of which had been managed collectively for centuries without collapsing. The Swiss village commons she studied had written rules dating to the thirteenth century. Spanish irrigation communities had operated water courts continuously since the medieval period. These were not curiosities; they were working systems, and the theory said they should not exist.\n\nWhat Ostrom found was that the successful cases shared features the model had abstracted away. Users could communicate with one another and had done so for generations. Boundaries were clear, so it was known who had a right to the resource. Rules were made by the users themselves rather than imposed, and could be changed as conditions changed. Monitoring was carried out by the users or by people accountable to them, and sanctions for breaking rules escalated gradually rather than jumping to expulsion.\n\nNone of this showed the original argument to be wrong. It showed that it described a particular situation, one in which users cannot communicate, cannot exclude outsiders, and cannot make or enforce rules, and that this situation is not the only form common ownership takes. The policy conclusion had been drawn from the model rather than from the world.\n\nOstrom was careful about the limits of her own finding. Collective management fails often, and she catalogued failures alongside successes. Her claim was not that commons work but that whether they work is an empirical question, which is a less satisfying thing to put in a textbook and a more useful thing to know.';
const AR_P3 = 'HUMANITIES: The Copyist\n\nBefore photography, the only way to study a painting you could not travel to was to look at a copy. A copyist sat in front of the original for weeks, and what arrived in another city was that person\'s reading of it: the passages they had understood, the ones they had simplified, and the corrections they had quietly made.\n\nArt historians once treated these copies as failures, useful only for recording works since lost. That view has shifted. A copy made in 1790 records not only the painting but the attention of a trained viewer of 1790, and where a copyist has strengthened an outline or brightened a shadow, the change marks something that the period found unclear or unsatisfying.\n\nThe most revealing copies are the ones with mistakes. A copyist working from a dark varnished surface sometimes rendered as a single object two things that were in fact separate, and the error tells us how the painting looked before cleaning. In a few cases a copy has been the only evidence that a restoration went too far.';
const AR_P4A = 'PAIRED PASSAGES: Two views of the field notebook\n\nPassage A\n\nThe field notebook is often described as a neutral record, but its format shapes what gets recorded. A notebook ruled into columns invites counts, and a notebook of blank pages invites description. Ornithologists working with printed forms in the 1950s recorded abundance carefully and behaviour hardly at all, not because behaviour did not interest them but because there was no column for it.\n\nThis matters for anyone using old notebooks as data. An absence in a record can mean the observer saw nothing, or that the observer saw something the page had no room for. Distinguishing the two usually requires knowing what form the observer was using, which is information that is rarely archived alongside the notes.';
const AR_P4B = 'Passage B\n\nI have kept field notes for thirty-one years and have changed format three times. The first change was forced on me by a supervisor who wanted comparable counts across sites. The second I made myself, after realising that my comparable counts had cost me everything I used to notice about weather. The third was a compromise: a ruled column on the left, a blank half-page on the right.\n\nWhat I did not expect was how much the blank half changed the counts. Writing a sentence about what the birds were doing made me look longer, and looking longer, I found more birds. The two halves of the page were not independent records. The one I thought of as soft was improving the one I thought of as hard.';
const AR_P5 = 'NATURAL SCIENCE: The Problem of the Missing Sink\n\nWhen researchers first added up where human carbon emissions were going, the books did not balance. A portion could be measured in the atmosphere, and a further portion was taken up by the oceans, whose chemistry is well enough understood to estimate. A substantial remainder was unaccounted for, and it acquired a name: the missing sink.\n\nThe obvious candidate was land vegetation, but the obvious candidate raised a difficulty. Forests were being cleared on a large scale, which should have made land a net source of carbon rather than a sink. For land to absorb the remainder, the world\'s remaining vegetation would have to be taking up more carbon than it had before, and at a rate large enough to offset both the clearing and the shortfall.\n\nTwo mechanisms were proposed. Higher atmospheric carbon dioxide can increase the rate of photosynthesis in many plants, an effect demonstrated repeatedly in enclosures. Nitrogen deposited from industrial and agricultural sources can relieve a nutrient limitation in forests that are short of it. Both effects are real. Whether either operates at the scale required, across whole continents and for decades rather than seasons, has been much harder to establish, and enclosure experiments are a poor guide because a plot open on all sides behaves differently from a sealed chamber.\n\nThe accounting has since improved. Inventories of forest biomass, measurements of the small difference in carbon dioxide concentration between the northern and southern hemispheres, and the ratio of carbon isotopes in the atmosphere all give partly independent estimates, and they agree that a large land sink exists in the northern mid-latitudes. What they do not settle is how long it will last. A sink driven by the recovery of forests cleared a century ago will saturate as those forests mature. A sink driven by fertilisation may weaken as some other nutrient becomes limiting.\n\nThe practical consequence is uncomfortable. Roughly a quarter of what is emitted each year is currently removed by land, and the size of that service is known far better than its durability.';
const BANK_ACT_READING = [
// ---------- Part 1: literary narrative ----------
{id:'AR001',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Central idea',skill:'act_r_kid',diff:3,
 stem:'The main purpose of the passage is to:',
 choices:['explain how the narrator came to understand a grandmother\'s ledger and adopt the practice.','argue that household objects should be valued for their usefulness rather than their cost.','recount the difficulty of emptying a house in a short period of time after a funeral.','describe a family dispute over which possessions to keep after a death in the household and which to give away.'],answer:0,
 expl:'The passage moves from finding the ledger, to misreading it, to grasping what the use column recorded, to keeping one. The narrator\'s changing understanding is the through line.',
 wrong:'The dispute and the four-day clearance are single details along the way. The passage never argues for a general rule about how objects should be valued.'},
{id:'AR002',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Detail',skill:'act_r_kid',diff:2,
 stem:'According to the passage, the narrator initially assumed the ledger was:',
 choices:['a record of items lent to other family members over many years.','a list of valuables kept for insurance purposes.','a diary of daily household events kept for decades in the same hand.','an inventory prepared for the settling of an estate.'],answer:1,
 expl:'The second sentence says so directly: not a list of valuables for insurance, which is what the narrator assumed on first finding it.',
 wrong:'A diary, an estate inventory, and a lending record are never suggested as the narrator\'s first assumption.'},
{id:'AR003',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Inference',skill:'act_r_kid',diff:3,
 stem:'It can reasonably be inferred that the narrator took the ledger primarily because:',
 choices:['it was the most valuable object left in the house.','the grandmother had asked that it be given to the narrator.','no one else claimed it and there was no resistance.','it contained photographs the mother had overlooked.'],answer:2,
 expl:'The passage lists what everyone else wanted, notes that nobody wanted the ledger, and ends the sentence with the narrator taking it because no one stopped them. Absence of competition is the stated reason.',
 wrong:'Its value is never asserted, no request from the grandmother is mentioned, and the photographs were a separate item the mother wanted.'},
{id:'AR004',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Sequence',skill:'act_r_kid',diff:2,
 stem:'Which of the following events in the passage happened last chronologically?',
 choices:['The house was emptied over four days.','The grandmother wrote "still not used" beside the knives.','The narrator found the ledger and misread its purpose.','The narrator moved into a nearly empty flat.'],answer:3,
 expl:'The move comes years after the grandmother\'s death, which followed the ledger entries and the discovery. The passage marks it with "for years I treated it as a curiosity. Then I moved."',
 wrong:'The knives entry and the discovery precede the death; the clearance happens at the death itself.'},
{id:'AR005',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Word meaning',skill:'act_r_cs',diff:3,
 stem:'As it is used in the passage, the phrase "asked her possessions to do" most nearly means:',
 choices:['recorded what work each object actually performed.','required that every object serve more than one purpose.','demanded that her family justify each purchase she had made.','expected her belongings to increase in value after her death.'],answer:0,
 expl:'The use column lists what each object did: soup and holding a door, washing greens and catching a drip. The phrase names that record of actual work.',
 wrong:'No demand on family or expectation of value appears. Multiple purposes occur in some entries but are not required, as the unused knives show.'},
{id:'AR006',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Tone and perspective',skill:'act_r_cs',diff:4,
 stem:'The narrator\'s statement that "I am not as honest in it as she was" primarily serves to:',
 choices:['admit that the narrator finds the ledger too difficult to maintain regularly.','indicate that the narrator sometimes invents a use rather than leaving a line empty.','imply that the grandmother concealed the true origin of certain possessions.','suggest that the narrator falsifies the provenance of inherited objects.'],answer:1,
 expl:'The admission is followed immediately by the grandmother\'s example: she recorded a failure, left it standing, and did not invent a purpose to fill it. The contrast defines what the narrator\'s dishonesty consists of.',
 wrong:'Provenance and concealment are not at issue, and difficulty of upkeep is not what the sentence concedes.'},
{id:'AR007',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Integration of ideas',skill:'act_r_iki',diff:4,
 stem:'The detail about the secondhand chair functions in the passage mainly to:',
 choices:['explain why the narrator had to move into a flat with almost nothing in it.','contrast the narrator\'s taste in furnishings with the grandmother\'s.','show the moment the narrator understood what the use column demanded.','establish that the narrator had inherited none of the grandmother\'s furniture.'],answer:2,
 expl:'Facing the chair, the narrator finds the question harder than ownership and has to admit the chair had been asked to do nothing. That is the passage\'s turning point.',
 wrong:'The empty flat is the setting rather than a consequence, and nothing compares the two characters\' taste or tracks the inherited furniture.'},
{id:'AR008',section:'R',type:'R',passageId:'ARP1',passage:AR_P1,sub:'Integration of ideas',skill:'act_r_iki',diff:4,
 stem:'Which conclusion about the grandmother is best supported by the entry concerning the good knives?',
 choices:['She revised her inventory only when an object changed hands.','She regretted having received a gift she considered impractical.','She valued objects chiefly according to what they had cost.','She was willing to let her record show that something went unused.'],answer:3,
 expl:'She wrote "not used; too good," returned years later to write "still not used," and left the line standing. The record was allowed to show a failure.',
 wrong:'No regret is expressed, cost is never her measure, and this revision involved no change of ownership at all.'},
// ---------- Part 2: social science ----------
{id:'AR009',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Central idea',skill:'act_r_kid',diff:3,
 stem:'The main idea of the passage is that:',
 choices:['an elegant model was mistaken for a general finding until case evidence showed its conditions were special.','textbooks written after 1968 misrepresented the arguments economists had actually made about common resources.','common ownership of resources reliably leads to their destruction over time wherever it is found.','Ostrom proved that collective management of resources succeeds more often than privatisation or control by a central state authority does.'],answer:0,
 expl:'The passage sets out the model, notes that its conclusion followed so naturally that few checked it, presents Ostrom\'s cases, and concludes that the policy conclusion came from the model rather than the world.',
 wrong:'The first option states the view the passage complicates. Ostrom catalogued failures and made no claim about relative frequency, and textbooks are criticised for over-reach rather than misquotation.'},
{id:'AR010',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Detail',skill:'act_r_kid',diff:2,
 stem:'According to the passage, the Spanish irrigation communities Ostrom studied:',
 choices:['depended on rules imposed by a national authority.','had operated water courts continuously since the medieval period.','were established after 1968 as an experiment in collective management.','had been privatised and then returned to collective control by their users.'],answer:1,
 expl:'The second paragraph states it directly, alongside the Swiss commons with rules dating to the thirteenth century.',
 wrong:'The point of these cases is their age, not recent creation. Neither privatisation nor imposed national rules is mentioned.'},
{id:'AR011',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Detail',skill:'act_r_kid',diff:3,
 stem:'The passage lists all of the following as features of successful commons EXCEPT:',
 choices:['sanctions that escalate gradually rather than beginning with expulsion.','monitoring by users or by people accountable to them.','a legal guarantee that no user may be excluded for any reason.','clearly defined boundaries around who may use the resource and on what terms.'],answer:2,
 expl:'The third paragraph lists communication, clear boundaries, user-made rules, user monitoring, and graduated sanctions. A guarantee against exclusion contradicts both clear boundaries and the sanctions described.',
 wrong:'Boundaries, graduated sanctions, and accountable monitoring are all named in that paragraph.'},
{id:'AR012',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Inference',skill:'act_r_kid',diff:4,
 stem:'It can be inferred from the passage that the original pasture argument would best describe a situation in which:',
 choices:['a state agency sets grazing limits and inspects the pasture regularly each season of the grazing year.','the pasture is owned outright by a single herder who grazes it alone.','herders have grazed the same pasture for many generations under written rules that they drew up themselves.','users are strangers to one another and cannot exclude newcomers or enforce agreements.'],answer:3,
 expl:'The fourth paragraph says the argument describes a situation in which users cannot communicate, cannot exclude outsiders, and cannot make or enforce rules. Strangers without exclusion or enforcement is that case.',
 wrong:'Generational rules, state inspection, and sole ownership each supply something the model assumes absent.'},
{id:'AR013',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Text structure',skill:'act_r_cs',diff:3,
 stem:'The passage is organised mainly by:',
 choices:['presenting a widely accepted argument, then the evidence that narrowed its scope.','tracing the history of one economist\'s career in chronological order from her first paper to her last.','comparing two competing schools of economic thought point by point.','listing a series of policy recommendations in order of how expensive each one would be to carry out.'],answer:0,
 expl:'The first paragraph gives the accepted argument, the second and third give Ostrom\'s cases and what they shared, and the fourth states what the evidence showed about the argument\'s scope.',
 wrong:'It is not a career history, not a point-by-point comparison of schools, and contains no ranked recommendations.'},
{id:'AR014',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Author perspective',skill:'act_r_cs',diff:4,
 stem:'The author\'s remark that an empirical question is "a less satisfying thing to put in a textbook" suggests that the author believes:',
 choices:['Ostrom\'s work was too technical for an introductory audience.','a clean general rule is more appealing to teach than a conditional finding.','economists deliberately suppressed evidence that contradicted the model.','textbooks should omit any claim that remains subject to dispute.'],answer:1,
 expl:'The contrast is between a tidy rule and a finding that depends on conditions. The remark explains why the elegant version travelled so easily.',
 wrong:'The author wants the conditional finding taught rather than omitted, does not call the work too technical, and alleges inattention rather than suppression.'},
{id:'AR015',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Integration of ideas',skill:'act_r_iki',diff:4,
 stem:'Which of the following, if true, would most strengthen the passage\'s account of why the original conclusion went unexamined?',
 choices:['Privatisation of common land increased sharply in several countries during the 1980s.','Surveys show that most economists publishing after 1968 had read Ostrom\'s early case studies of irrigation systems and alpine pasture.','Long-lived collective arrangements were documented mainly in regional journals that general economists rarely read.','The pasture argument was first stated in a paper that also discussed population growth in the same decade.'],answer:2,
 expl:'The passage says the conclusion followed so naturally that few examined whether real commons behaved that way. Evidence that the counter-cases sat in journals economists did not read explains how the examination was skipped.',
 wrong:'Wide readership of Ostrom would weaken the account. The paper\'s other contents and later privatisation trends do not bear on why nobody checked.'},
{id:'AR016',section:'R',type:'R',passageId:'ARP2',passage:AR_P2,sub:'Integration of ideas',skill:'act_r_iki',diff:3,
 stem:'The author includes the detail that Ostrom catalogued failures alongside successes mainly to:',
 choices:['suggest that the failures she catalogued resembled the original pasture argument very closely indeed.','concede that her conclusions were eventually withdrawn.','establish that collective management works in the large majority of cases that have been studied.','show that her claim was about how to settle the question rather than about the answer.'],answer:3,
 expl:'The final sentence makes the point explicit: her claim was not that commons work but that whether they work is an empirical question. The failures show she was not arguing the opposite general rule.',
 wrong:'Nothing was withdrawn, no majority claim is made, and the failures are not said to match the model.'},
// ---------- Part 3: humanities, shorter passage ----------
{id:'AR017',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Central idea',skill:'act_r_kid',diff:3,
 stem:'The passage is primarily concerned with:',
 choices:['describing a change in how art historians regard painted copies of paintings.','arguing that copyists were more skilled than they have been given credit for.','recounting the training a copyist underwent before beginning work.','explaining why photography replaced copying as a way of studying paintings in the galleries.'],answer:0,
 expl:'The middle paragraph states that historians once treated copies as failures and that the view has shifted, and the rest explains what copies are now taken to record.',
 wrong:'Photography sets the scene in one clause, skill is never the claim, and no training is described.'},
{id:'AR018',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Detail',skill:'act_r_kid',diff:2,
 stem:'According to the passage, what did a copyist produce for viewers in another city?',
 choices:['an exact duplicate verified against the original','that copyist\'s reading of the painting','a written description accompanied by measurements','a preparatory sketch later worked up by an engraver'],answer:1,
 expl:'The first paragraph says what arrived in another city was that person\'s reading of it, including simplifications and quiet corrections.',
 wrong:'Exactness is precisely what the passage denies, and neither written descriptions nor engravers are mentioned.'},
{id:'AR019',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Inference',skill:'act_r_kid',diff:4,
 stem:'It can be inferred that a copy showing two separate objects merged into one is valuable because it:',
 choices:['shows that the copyist was working from another copy rather than the original.','demonstrates that the copyist lacked the training to read the composition.','indicates how the original appeared before its varnish was removed.','proves that the original painting has since been lost or destroyed.'],answer:2,
 expl:'The passage attributes the merging to a dark varnished surface and says the error tells us how the painting looked before cleaning.',
 wrong:'The passage treats such errors as evidence rather than as proof of incompetence, loss, or second-hand copying.'},
{id:'AR020',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Word meaning',skill:'act_r_cs',diff:3,
 stem:'As it is used in the passage, "quietly" most nearly means:',
 choices:['with unusual delicacy of brushwork','in a subdued range of colours','after consulting the painting\'s owner','without announcing or marking the change'],answer:3,
 expl:'The corrections are listed among things the copyist did to the original without signalling them, which is what makes a copy a reading rather than a duplicate.',
 wrong:'The word describes disclosure rather than technique, palette, or permission.'},
{id:'AR021',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Text structure',skill:'act_r_cs',diff:3,
 stem:'The final paragraph relates to the second paragraph by:',
 choices:['carrying the second paragraph\'s claim further, to copies that contain errors.','returning to the situation that had been described before the second paragraph began its argument.','qualifying the second paragraph\'s claim with an exception.','restating the second paragraph\'s claim in more technical language.'],answer:0,
 expl:'The second paragraph says deliberate changes record period judgement. The third goes further: even unintended errors carry evidence, sometimes the only evidence about a lost state.',
 wrong:'Nothing is excepted, restated, or returned to; the movement is an extension.'},
{id:'AR022',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Integration of ideas',skill:'act_r_iki',diff:4,
 stem:'Suppose a copy made in 1790 shows a figure\'s outline more sharply than the original does today. Based on the passage, an art historian would most likely treat this as evidence about:',
 choices:['the size of the room in which the original then hung.','what viewers in 1790 found unclear in the painting.','the price the copy commanded when it was sold.','whether the original was painted by more than one hand.'],answer:1,
 expl:'The second paragraph says that where a copyist strengthened an outline, the change marks something the period found unclear or unsatisfying. A sharpened outline is that case exactly.',
 wrong:'Price, attribution, and the hanging space are questions the passage never connects to copying decisions.'},
{id:'AR023',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Integration of ideas',skill:'act_r_iki',diff:3,
 stem:'The passage suggests that the older view of copies was limited mainly because it:',
 choices:['confused copies made for study with copies made for sale.','assumed copies were made only of paintings likely to be lost.','judged copies solely against the original rather than as records of their own moment.','overlooked the fact that most copyists worked from the original painting in person over a period of weeks.'],answer:2,
 expl:'The older view called them failures, useful only for recording lost works. The shift came from reading a copy as recording the attention of a trained viewer of its own date.',
 wrong:'The passage does not describe assumptions about which works were copied, working practice is stated rather than overlooked, and the study-versus-sale distinction is never raised.'},
{id:'AR024',section:'R',type:'R',passageId:'ARP3',passage:AR_P3,sub:'Author perspective',skill:'act_r_cs',diff:3,
 stem:'The author\'s attitude toward copies containing mistakes is best described as:',
 choices:['sceptical that they can tell us anything reliable about the original.','indifferent, since the original is generally available for study.','regretful that so many have survived in preference to accurate copies.','interested in them as an unusually informative kind of evidence.'],answer:3,
 expl:'The final paragraph opens by calling the most revealing copies the ones with mistakes, then explains what those mistakes preserve.',
 wrong:'No regret, scepticism or indifference appears; the errors are presented as the richest source in the paragraph.'},
// ---------- Part 4: paired passages ----------
{id:'AR025',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Central idea',skill:'act_r_kid',diff:3,
 stem:'The main idea of Passage A is that:',
 choices:['the format of a notebook determines what its keeper records and therefore what later readers can infer.','ornithologists working in the 1950s were not interested in recording the behaviour of the birds they observed.','printed forms should be abandoned in favour of blank notebooks.','field notebooks from the 1950s are too unreliable to use as data.'],answer:0,
 expl:'Passage A argues that ruled columns invite counts and blank pages invite description, then draws the consequence for anyone reading an absence in an old record.',
 wrong:'It urges care rather than dismissal, explicitly denies the lack of interest, and recommends no replacement format.'},
{id:'AR026',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Detail',skill:'act_r_kid',diff:2,
 stem:'According to Passage B, the writer\'s second change of format was made:',
 choices:['at the insistence of a supervisor who wanted comparable counts.','after realising that comparable counts had cost attention to weather.','in order to record more birds at each site visited.','when the first notebook format was no longer available.'],answer:1,
 expl:'The writer says the second change was self-made, after realising the comparable counts had cost everything once noticed about weather.',
 wrong:'The supervisor forced the first change. More birds was an unexpected result of the third format, and availability is never mentioned.'},
{id:'AR027',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Inference',skill:'act_r_kid',diff:4,
 stem:'Passage A suggests that a blank entry in an old notebook is difficult to interpret because it may mean that:',
 choices:['the observer was absent on the day in question.','the notebook was damaged before it reached the archive.','the observer saw nothing, or saw something the page had no room for.','the observer recorded the information in a separate volume that has not survived.'],answer:2,
 expl:'Passage A states the ambiguity in those terms and adds that resolving it requires knowing which form was used, which is rarely archived.',
 wrong:'Absence, damage, and separate volumes are not the alternatives the passage names.'},
{id:'AR028',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Word meaning',skill:'act_r_cs',diff:3,
 stem:'As used at the end of Passage B, "soft" and "hard" most nearly distinguish:',
 choices:['recent observations from older ones.','personal notes from notes intended for publication.','pencil entries from entries made in ink.','descriptive writing from numerical counting.'],answer:3,
 expl:'The two halves of the page are the blank descriptive side and the ruled column of counts. The writer reports that the descriptive half improved the numerical one.',
 wrong:'The contrast is between kinds of record on one page, not between dates, audiences, or writing materials.'},
{id:'AR029',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Tone and perspective',skill:'act_r_cs',diff:3,
 stem:'The tone of Passage B differs from that of Passage A chiefly in that Passage B is:',
 choices:['more personal, drawing its evidence from the writer\'s own practice.','more technical, relying throughout on specialised ornithological terminology.','more sharply critical of colleagues who use printed forms.','more cautious about drawing any general conclusion at all.'],answer:0,
 expl:'Passage B is written in the first person and built from thirty-one years of the writer\'s own notebooks and three changes of format. Passage A argues in the third person about records generally.',
 wrong:'No colleagues are criticised, a clear conclusion is drawn, and the vocabulary is plainer than in Passage A.'},
{id:'AR030',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Comparing passages',skill:'act_r_iki',diff:4,
 stem:'Both passages support the conclusion that a notebook\'s format:',
 choices:['is usually recorded in archives along with the notes themselves.','affects the content of the record rather than merely its arrangement.','should be standardised across all observers at a given site.','becomes less important as an observer gains experience.'],answer:1,
 expl:'Passage A says the format shapes what gets recorded; Passage B reports that adding a blank half changed both the descriptions and the counts. Both treat format as affecting content.',
 wrong:'Passage B resists standardisation, experience did not reduce the effect for that writer, and Passage A says format information is rarely archived.'},
{id:'AR031',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Comparing passages',skill:'act_r_iki',diff:4,
 stem:'Passage B complicates Passage A\'s argument most directly by suggesting that:',
 choices:['an observer\'s memory of a day in the field is a more accurate source than any written record of it.','old notebooks are more reliable as data than Passage A allows.','the two kinds of record on a page can influence each other rather than stand apart.','printed forms produce better counts than blank pages do.'],answer:2,
 expl:'Passage A treats columns and blank pages as inviting different content. Passage B reports that the blank half made the writer look longer and so improved the counts, so the two are not independent.',
 wrong:'Passage B says nothing about the reliability of archived notebooks, does not rank the formats for accuracy, and never appeals to memory.'},
{id:'AR032',section:'R',type:'R',passageId:'ARP4',passage:AR_P4A+'\n\n'+AR_P4B,sub:'Integration of ideas',skill:'act_r_iki',diff:4,
 stem:'A researcher studying 1950s abundance records would, on the basis of both passages, be best advised to:',
 choices:['discard any record that does not include behavioural description.','average the counts across observers to remove the effect of format.','treat every behavioural gap in the record as evidence that the behaviour did not in fact occur.','establish which recording form each observer used before interpreting gaps.'],answer:3,
 expl:'Passage A says distinguishing the two meanings of a gap requires knowing the form used. Passage B shows format also affects the counts, so knowing the form matters for both halves of the record.',
 wrong:'Reading gaps as absence is the error Passage A warns against, discarding records throws away usable counts, and averaging would not reveal what the format suppressed.'},
// ---------- Part 5: natural science ----------
{id:'AR033',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Central idea',skill:'act_r_kid',diff:3,
 stem:'The passage is mainly concerned with:',
 choices:['describing how a gap in carbon accounting was identified, narrowed, and left partly open.','arguing that forest clearing has been underestimated in carbon inventories.','establishing that land vegetation absorbs roughly a quarter of the carbon emitted each year by human activity.','explaining why enclosure experiments give misleading results.'],answer:0,
 expl:'The passage names the missing sink, sets out the difficulty and the two proposed mechanisms, reports the independent lines of evidence that located the sink, and closes on what remains unsettled.',
 wrong:'The quarter figure and the enclosure limitation are supporting details, and clearing is not claimed to be underestimated.'},
{id:'AR034',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Detail',skill:'act_r_kid',diff:2,
 stem:'According to the passage, the oceans\' uptake of carbon could be estimated because:',
 choices:['their uptake was measured directly by ship surveys.','their chemistry is well enough understood.','their surface temperature is measured continuously.','their volume is known with great precision.'],answer:1,
 expl:'The first paragraph gives that reason directly when listing where emissions were going.',
 wrong:'Temperature, volume, and ship surveys are not offered as the basis for the estimate.'},
{id:'AR035',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Detail',skill:'act_r_kid',diff:3,
 stem:'The passage identifies which of the following as making land an unlikely candidate for the missing sink?',
 choices:['Land vegetation had not been measured before the 1990s.','Nitrogen deposition was declining across the same period.','Large-scale forest clearing should have made land a net source of carbon.','Photosynthesis slows at the carbon dioxide concentrations then observed.'],answer:2,
 expl:'The second paragraph states the difficulty: clearing was extensive, which should have made land a source rather than a sink.',
 wrong:'Nitrogen deposition is offered as a mechanism that helps rather than hinders, higher carbon dioxide is said to increase photosynthesis, and the measurement gap concerns satellites elsewhere.'},
{id:'AR036',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Inference',skill:'act_r_kid',diff:4,
 stem:'It can be inferred from the passage that a sink driven mainly by regrowth of previously cleared forest would:',
 choices:['grow larger as atmospheric carbon dioxide rises.','be undetectable by forest biomass inventories.','continue at its present rate indefinitely.','diminish as those forests reach maturity.'],answer:3,
 expl:'The final paragraph says a sink driven by the recovery of forests cleared a century ago will saturate as those forests mature.',
 wrong:'Indefinite continuation is what the passage questions, growth with carbon dioxide describes the fertilisation mechanism, and biomass inventories are named as one way the sink was detected.'},
{id:'AR037',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Text structure',skill:'act_r_cs',diff:3,
 stem:'The third paragraph serves mainly to:',
 choices:['present two candidate mechanisms and note the difficulty of establishing their scale.','reject both proposed mechanisms on experimental grounds.','describe in detail the instruments that researchers use to measure carbon dioxide in the atmosphere.','trace the history of enclosure experiments in plant physiology.'],answer:0,
 expl:'It introduces carbon dioxide fertilisation and nitrogen deposition, grants both are real, and says the hard part is whether either works at continental scale over decades.',
 wrong:'Neither is rejected, no instruments are described, and the enclosure remark is a single limitation rather than a history.'},
{id:'AR038',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Word meaning',skill:'act_r_cs',diff:3,
 stem:'As it is used in the final paragraph, "service" most nearly refers to:',
 choices:['the provision of data by hemispheric measurements.','the removal of carbon from the atmosphere by land.','the maintenance of forest inventories by researchers.','the delivery of nutrients to nitrogen-limited forests.'],answer:1,
 expl:'The sentence says roughly a quarter of annual emissions is removed by land and that the size of that service is known better than its durability. The service is the removal.',
 wrong:'Inventories, nutrient delivery, and data provision are all mentioned elsewhere but are not what is sized at a quarter of emissions.'},
{id:'AR039',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Integration of ideas',skill:'act_r_iki',diff:4,
 stem:'The passage indicates that the several methods of estimating the land sink are valuable chiefly because they:',
 choices:['measure the durability of the sink as well as its size.','are inexpensive compared with enclosure experiments.','rest on partly independent evidence yet agree with one another.','can each be carried out by a single research group.'],answer:2,
 expl:'The fourth paragraph lists biomass inventories, the hemispheric concentration difference, and isotope ratios as partly independent estimates that agree a large northern sink exists.',
 wrong:'Cost and group size are never discussed, and the paragraph ends by saying these methods do not settle durability.'},
{id:'AR040',section:'R',type:'R',passageId:'ARP5',passage:AR_P5,sub:'Integration of ideas',skill:'act_r_iki',diff:4,
 stem:'The author calls the practical consequence "uncomfortable" most likely because:',
 choices:['the several measurement methods disagree with one another about how much carbon the land actually absorbs.','the land sink has begun to release more carbon than it absorbs.','emissions are rising faster than the land sink can be measured.','a large and currently helpful process may not persist, and its persistence is what is least known.'],answer:3,
 expl:'The closing sentences pair a large present service with the admission that its durability is known far less well than its size. Depending on something whose lifetime is unknown is the discomfort.',
 wrong:'No reversal is reported, the comparison with emissions growth is not made, and the methods are said to agree.'}
];
