// bank_act_english.js - Original ACT English items AE001-AE054.
// Four answer choices, which is what the enhanced ACT uses in every section. Skills are ACT's
// three published reporting categories for English: Production of Writing, Knowledge of
// Language, and Conventions of Standard English.
// Six passages of nine questions each. Every passage exercises all three categories, because
// the engine builds a section out of whole passage groups and a category confined to one
// passage would vanish whenever that passage was not selected.
const AE_P1 = 'The Tuesday Bread Club\n\n[1] Marisol Vega started the Tuesday Bread Club in the back room of a hardware store. [2] She had been baking for two years by then, mostly badly, and she wanted company for the failures. [3] Six people came to the first meeting. [4] Four of them had never worked with yeast, and one had driven ninety minutes from a town with no bakery at all. [5] They made a single loaf together and ate it standing up.\n\n[6] The club now meets in a church basement and draws about forty people. [7] Marisol still runs it, though she insists the word is too strong for what she does. [8] She sets out flour, answers questions, and refuses to grade anyone work. [9] The only rule is that whatever comes out of the oven gets eaten in the room, successes and disasters alike. [10] That rule, she says, is the whole method: a loaf you have to eat in front of witnesses teaches you more than a loaf you can quietly throw away.';
const AE_P2 = 'Repainting the Water Tower\n\n[1] The water tower on the edge of Kelso has been repainted four times since it was built in 1931. [2] Each repainting has been an argument. [3] The first, in 1958, covered a hand-lettered town name that had faded past reading. [4] The second, in 1977, replaced a mural of a leaping trout. [5] The trout had been added without permission by a sign painter who lived nearby, and its removal was still being discussed at town meetings a decade later.\n\n[6] The current design, approved in 2019, is plain silver with the town name in block letters. [7] It was chosen after a public vote in which the trout finished second. [8] Supporters of the plain design argued that a water tower is infrastructure and should look like it. [9] Opponents pointed out that nobody drives forty miles to photograph infrastructure. [10] Both sides agreed on one thing, which was that the tower would be repainted again eventually, and the argument would start over.';
const AE_P3 = 'What the Tide Gauge Knew\n\n[1] For most of the twentieth century, the tide gauge at the end of the pier was read by hand. [2] A keeper walked out twice a day, noted the level against a painted scale, and wrote the number in a ledger. [3] The ledgers were stored in a shed and nobody consulted them. [4] When the shed was cleared in 1994, a graduate student asked whether she could take the boxes instead of letting them go to the landfill.\n\n[5] The records turned out to cover eighty-one years with almost no gaps. [6] That continuity is rare, and it made the series valuable in a way none of the keepers had anticipated. [7] Modern satellite measurements are more precise, but they begin in the 1990s. [8] A local record reaching back to 1913 gives that shorter series something to stand on. [9] The student who rescued the boxes now runs a laboratory. [10] She keeps one ledger on a shelf in her office, open to a page where a keeper had noted, in the margin, that it was raining hard and his pencil kept slipping.';
const AE_P4 = 'The Case for the Slow Bridge\n\n[1] When the footbridge over the ravine was rebuilt, the engineers proposed a straight span. [2] It would have been cheaper and it would have crossed in forty seconds. [3] The design that was actually built curves, and takes about two minutes to walk. [4] The extra time was deliberate.\n\n[5] The ravine is the only place in town where the creek is visible from a public path. [6] A straight span would have carried walkers over it so quickly that most would not have looked down. [7] The curve forces a change of direction halfway across, and at that point the walker is facing directly downstream. [8] Counts taken in the first year found that people stopped on the bridge at roughly three times the rate recorded on the old one. [9] The town has since applied the same thinking to two other paths. [10] Neither is faster than the route it replaced, and that is the point.';
const AE_P5 = 'A Second Life for the Cannery\n\n[1] The cannery closed in 1981 and stood empty for twenty-six years. [2] Proposals to demolish it appeared roughly every three years, and each one failed for a different reason. [3] The building is too large for most uses and too solid to knock down cheaply. [4] Its concrete walls are eighteen inches thick.\n\n[5] The conversion that finally happened in 2007 did not try to make the cannery into something else. [6] The architects kept the floor plan, the freight doors, and the overhead rails that had once carried crates. [7] Tenants were told they could hang things from the rails. [8] What arrived was a mix nobody had planned for, including a boat builder, two ceramicists, and a company that repairs theatre lighting. [9] The rails are now used for all three. [10] The building works, the architects say, because they stopped short of finishing it.';
const AE_P6 = 'Learning the River\n\n[1] Pilots who guide ships up the river spend years learning a channel they can rarely see. [2] The water is opaque with silt for most of the year. [3] What a pilot learns is not the river exactly but a model of it, built from soundings, from the behaviour of the current against the banks, and from how a particular hull answers in a particular stretch.\n\n[4] The model has to be revised constantly. [5] A single flood can move a bar half a mile. [6] Pilots trade this information at the end of each run, in conversations that outsiders find almost unintelligible. [7] A remark such as "the shoal is making below the light" carries, to another pilot, a specific and actionable meaning. [8] Electronic charts have changed the work but not removed the need for it. [9] The charts show where the channel was surveyed, and a survey is a photograph of a moving thing. [10] The pilot supplies what the photograph leaves out.';
const BANK_ACT_ENGLISH = [
// ---------- Passage 1 ----------
{id:'AE001',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Usage',skill:'act_e_cse',diff:2,
 stem:'In sentence 8, which choice corrects the error in the underlined portion "refuses to grade anyone work"?',
 choices:['refuses to grade anyones work','refuses to grade anyone\'s work','refuses grading anyone work','NO CHANGE'],answer:1,
 expl:'The work belongs to the person, so the possessive form is needed: anyone\'s work. Indefinite pronouns take an apostrophe and s exactly as singular nouns do.',
 wrong:'Leaving it as anyone work gives a noun with no possessive marker. Anyones drops the apostrophe. Refuses grading changes the verb pattern without fixing the possessive.'},
{id:'AE002',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Sentence structure',skill:'act_e_cse',diff:3,
 stem:'Which choice best combines sentences 3 and 4 without repeating information?',
 choices:['Six people came to the first meeting; four had never worked with yeast, and one had driven ninety minutes from a town with no bakery.','Six people came to the first meeting and four of the six people who came had never worked with yeast and one had driven ninety minutes.','Six people came to the first meeting, and of these six people, four had never worked with yeast, one having driven ninety minutes.','Six people came to the first meeting, four of them had never worked with yeast, and one had driven ninety minutes from a town with no bakery.'],answer:0,
 expl:'A semicolon joins the two independent statements cleanly, and dropping the repeated "of them" after four avoids restating the group already named.',
 wrong:'Joining the clauses with a comma alone produces a run-on. The version that repeats "the six people who came" restates the subject, and the participial ending leaves the last clause dangling.'},
{id:'AE003',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Word choice',skill:'act_e_kol',diff:2,
 stem:'In sentence 2, which choice most precisely conveys that Marisol wanted other people present while she made mistakes?',
 choices:['she wanted pity for the failures','she wanted company for the failures','she wanted friendship for the failures','she wanted assistance for the failures'],answer:1,
 expl:'Company means the presence of others, which is what the sentence describes and what the club provides. It is the precise word for wanting people there.',
 wrong:'Friendship and pity name feelings rather than presence. Assistance suggests she wanted help baking, but the paragraph says she wanted others around for the failures.'},
{id:'AE004',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Redundancy',skill:'act_e_kol',diff:2,
 stem:'Which choice best replaces the underlined portion of sentence 9, "successes and disasters alike", to avoid redundancy with the rest of the sentence?',
 choices:['NO CHANGE','whether the loaf turned out well or badly','no matter what the result of the baking was','including both the good loaves and the bad loaves'],answer:0,
 expl:'The sentence says whatever comes out of the oven gets eaten; the phrase adds the range compactly. The alternatives restate "whatever comes out of the oven" at greater length without adding meaning.',
 wrong:'Each alternative spells out the same contrast in more words, which is the redundancy the question asks to avoid.'},
{id:'AE005',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Transitions',skill:'act_e_pow',diff:3,
 stem:'Which transition, placed at the beginning of sentence 6, best signals the relationship between the two paragraphs?',
 choices:['For example,','Yet,','Today,','In other words,'],answer:2,
 expl:'The first paragraph describes the club\'s beginning and the second describes what it has become. A time marker is what the shift needs.',
 wrong:'The second paragraph is not an example of the first, does not contradict it, and does not restate it.'},
{id:'AE006',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Topic development',skill:'act_e_pow',diff:3,
 stem:'The writer is considering deleting sentence 5. Should the sentence be kept or deleted?',
 choices:['Deleted, because it repeats information already given about the first meeting.','Deleted, because it introduces a detail about eating that the passage does not develop.','Kept, because it establishes that the club has always been larger than its founder expected.','Kept, because it shows the club\'s founding practice in an image the final sentence returns to.'],answer:3,
 expl:'Sentence 5 shows the first group making one loaf and eating it together, which is exactly the practice the closing sentences identify as the club\'s whole method. It sets up the ending.',
 wrong:'It says nothing about expectations of size, repeats nothing, and the eating detail is developed at length in the second paragraph.'},
{id:'AE007',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Organization',skill:'act_e_pow',diff:4,
 stem:'For the sake of logic and cohesion, sentence 7 should be placed',
 choices:['after sentence 10.','where it is now.','before sentence 6.','after sentence 8.'],answer:1,
 expl:'Sentence 6 says the club now draws forty people; sentence 7 notes Marisol still runs it and qualifies the word; sentence 8 then shows what she actually does. The order moves from scale to role to detail.',
 wrong:'Moving it before sentence 6 introduces "still runs it" before the present-day club is established. Moving it after 8 or 10 separates the qualification from the description it qualifies.'},
{id:'AE008',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Punctuation',skill:'act_e_cse',diff:3,
 stem:'Which choice provides the correct punctuation for the underlined portion of sentence 10: "That rule she says is the whole method"?',
 choices:['That rule; she says; is the whole method','NO CHANGE','That rule, she says, is the whole method','That rule she says, is the whole method'],answer:2,
 expl:'She says is an interrupting element inside the sentence and takes a comma on each side.',
 wrong:'Leaving it unpunctuated runs the interruption into the clause. A single comma punctuates only one side, and semicolons cannot set off a phrase this way.'},
{id:'AE009',section:'E',type:'E',passageId:'AEP1',passage:AE_P1,sub:'Style and tone',skill:'act_e_kol',diff:3,
 stem:'Which choice for the underlined portion of sentence 1 best maintains the essay\'s plain, factual tone?',
 choices:['founded the beloved Tuesday Bread Club','began the Tuesday Bread Club in the rear premises of a retail hardware establishment','started the Tuesday Bread Club in the back room of a hardware store','launched her now legendary Tuesday Bread Club in a humble hardware store back room'],answer:2,
 expl:'The essay reports plainly and lets the details carry the interest. Started, with the location given directly, matches that register.',
 wrong:'Legendary and beloved import praise the essay avoids. Retail hardware establishment is stiff where the rest is direct.'},
// ---------- Passage 2 ----------
{id:'AE010',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Punctuation',skill:'act_e_cse',diff:2,
 stem:'Which choice correctly punctuates the underlined portion of sentence 6: "approved in 2019 is plain silver"?',
 choices:['approved in 2019; is plain silver','approved, in 2019 is plain silver','NO CHANGE','approved in 2019, is plain silver'],answer:3,
 expl:'The current design, approved in 2019, is a nonessential phrase between the subject and verb, so it is closed with a comma on each side. The opening comma is already in the sentence.',
 wrong:'Omitting the second comma leaves the phrase half enclosed. A semicolon cannot separate a subject from its verb, and the last option brackets the wrong words.'},
{id:'AE011',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Verb tense',skill:'act_e_cse',diff:3,
 stem:'Which choice for the underlined portion of sentence 5 keeps the verb tenses consistent with the rest of the paragraph?',
 choices:['was being added without permission','is added without permission','has been added without permission','had been added without permission'],answer:3,
 expl:'The removal happened in 1977, and the trout was painted before that. The past perfect places the painting earlier than the past-tense removal.',
 wrong:'The past progressive suggests an action underway, the present is inconsistent with a 1977 narrative, and the present perfect connects the painting to now rather than to 1977.'},
{id:'AE012',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Conciseness',skill:'act_e_kol',diff:3,
 stem:'Which choice most concisely expresses the underlined portion of sentence 10: "Both sides agreed on one thing, which was that the tower would be repainted again"?',
 choices:['Both sides agreed on one thing, this being that the tower would be repainted again','Both sides agreed that the tower would be repainted again','Both sides were in agreement about the one thing that the tower would be repainted again','NO CHANGE'],answer:1,
 expl:'Agreed that carries the whole idea. Naming "one thing" and then defining it with a relative clause adds words without adding meaning.',
 wrong:'The other options keep the empty placeholder and, in two cases, make the construction heavier still.'},
{id:'AE013',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Topic development',skill:'act_e_pow',diff:3,
 stem:'Which choice, if added after sentence 2, would best support the claim that each repainting has been an argument?',
 choices:['Every repainting is preceded by months of letters to the local paper and at least one crowded meeting.','Repainting a steel water tower costs considerably more than repainting a wooden building.','The 1931 construction of the tower was funded by a bond issue that passed narrowly.','The tower holds two hundred thousand gallons and serves the northern half of town.'],answer:0,
 expl:'Letters and crowded meetings are the evidence that the repaintings provoke public dispute, which is exactly what the claim asserts.',
 wrong:'Capacity, cost, and the original bond issue are facts about the tower rather than evidence that repainting it causes argument.'},
{id:'AE014',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Transitions',skill:'act_e_pow',diff:3,
 stem:'Which transition best introduces sentence 9, given its relationship to sentence 8?',
 choices:['Opponents for instance argued','Opponents pointed out','Opponents therefore concluded','Opponents also noted'],answer:1,
 expl:'Sentence 9 answers sentence 8 with a contrasting consideration. Pointed out introduces that reply without claiming it follows from the previous sentence or merely echoes it.',
 wrong:'Therefore claims a conclusion drawn from sentence 8, also claims agreement, and for instance makes the reply an example of the previous point.'},
{id:'AE015',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Word choice',skill:'act_e_kol',diff:2,
 stem:'In sentence 3, which choice most precisely describes lettering that could no longer be read?',
 choices:['had faded past repair','had faded past memory','had faded past reading','had faded past recognition'],answer:2,
 expl:'The point is that the letters could not be read, and faded past reading says exactly that.',
 wrong:'Recognition shifts to identifying the object rather than reading it, repair addresses the paint rather than legibility, and memory changes the subject to what people recall.'},
{id:'AE016',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Sentence structure',skill:'act_e_cse',diff:4,
 stem:'Which choice best corrects the underlined portion of sentence 7: "It was chosen after a public vote in which the trout finished second"?',
 choices:['NO CHANGE','It was chosen after a public vote, the trout finished second','It was chosen after a public vote, in which the trout finishing second','It was chosen after a public vote and the trout finished second in it'],answer:0,
 expl:'The relative clause in which the trout finished second attaches correctly to vote and needs no comma, since it identifies which vote is meant.',
 wrong:'Replacing the relative pronoun with a comma creates a comma splice. The participial version leaves the clause without a finite verb, and the last option is wordier without being clearer.'},
{id:'AE017',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Organization',skill:'act_e_pow',diff:4,
 stem:'The writer wants to add the following sentence: "The trout has never entirely gone away." The sentence would most logically be placed',
 choices:['after sentence 10.','after sentence 1.','after sentence 5.','after sentence 7.'],answer:3,
 expl:'Sentence 7 reports that the trout finished second in the 2019 vote, which is the most recent evidence that it persists. The new sentence comments directly on that.',
 wrong:'Placed after sentence 1 or 5 it precedes the evidence it depends on, and after sentence 10 it follows the essay\'s closing point and blunts it.'},
{id:'AE018',section:'E',type:'E',passageId:'AEP2',passage:AE_P2,sub:'Punctuation',skill:'act_e_cse',diff:2,
 stem:'Which choice correctly punctuates the underlined portion of sentence 1: "since it was built in 1931"?',
 choices:['NO CHANGE','since it was built, in 1931','since, it was built in 1931','since it was built in 1931,'],answer:0,
 expl:'The clause needs no internal punctuation, and it ends the sentence, so no comma belongs anywhere in it.',
 wrong:'Each alternative inserts a comma that separates elements which belong together.'},
// ---------- Passage 3 ----------
{id:'AE019',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Pronoun agreement',skill:'act_e_cse',diff:3,
 stem:'Which choice for the underlined portion of sentence 3, "The ledgers were stored in a shed and nobody consulted them", is clearest?',
 choices:['The ledgers, stored in a shed, and nobody consulted them','NO CHANGE','The ledgers were stored in a shed, and nobody consulted them','The ledgers were stored in a shed where nobody consulted it'],answer:2,
 expl:'Two independent clauses joined by and take a comma before the conjunction.',
 wrong:'Omitting the comma runs the clauses together. It does not agree with the plural ledgers, and the participial version leaves the sentence without a main clause for its first half.'},
{id:'AE020',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Modifier placement',skill:'act_e_cse',diff:4,
 stem:'Which choice best corrects the modifier problem in sentence 4: "When the shed was cleared in 1994, a graduate student asked whether she could take the boxes"?',
 choices:['NO CHANGE','Clearing the shed in 1994, the boxes were requested by a graduate student','Cleared in 1994, a graduate student asked for the boxes from the shed','Having been cleared in 1994, the graduate student asked for the shed boxes'],answer:0,
 expl:'The sentence as written uses a full subordinate clause with its own subject, so nothing dangles. It is already correct.',
 wrong:'Each rewrite opens with a participial phrase whose implied subject is wrong, attaching the clearing to the boxes or to the student rather than to the shed.'},
{id:'AE021',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Word choice',skill:'act_e_kol',diff:3,
 stem:'In sentence 6, which choice best conveys that no keeper could have foreseen the value the records acquired?',
 choices:['in a way none of the keepers had confirmed','in a way none of the keepers had anticipated','in a way none of the keepers had appreciated','in a way none of the keepers had authorised'],answer:1,
 expl:'Anticipated means foreseen, which is the point: the value emerged from uses that did not exist when the readings were taken.',
 wrong:'Appreciated suggests they failed to value something already there, authorised implies permission, and confirmed implies verification.'},
{id:'AE022',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Conciseness',skill:'act_e_kol',diff:2,
 stem:'Which choice most concisely expresses the underlined portion of sentence 5: "turned out to cover eighty-one years with almost no gaps"?',
 choices:['turned out to be covering eighty-one years and having almost no gaps','NO CHANGE','turned out to cover a period of eighty-one years in which there were almost no gaps','covered eighty-one years with almost no gaps'],answer:3,
 expl:'The simple past states the fact in the fewest words, and nothing in the sentence requires the discovery framing.',
 wrong:'The longer options add a relative clause or a progressive construction without adding meaning.'},
{id:'AE023',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Topic development',skill:'act_e_pow',diff:4,
 stem:'The writer wants to end the essay by suggesting that routine record keeping can matter in ways its authors never see. Which choice best accomplishes this?',
 choices:['the numbers for a single week were recorded twice, apparently by mistake','a keeper had calculated the average level for the month and underlined it twice','a keeper had noted, in the margin, that it was raining hard and his pencil kept slipping','the handwriting changes abruptly, indicating that a new keeper had taken over the duty'],answer:2,
 expl:'The rain and the slipping pencil are the most ordinary details imaginable, written by someone with no idea the page would ever be read. Ending there makes the point about unforeseen value concrete.',
 wrong:'A change of hand, a duplicated week, and a calculated average are all about the record keeping itself rather than about the gap between a routine act and its later significance.'},
{id:'AE024',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Transitions',skill:'act_e_pow',diff:3,
 stem:'Which choice best introduces sentence 7 in relation to sentence 6?',
 choices:['Modern satellite measurements are more precise, so they begin in the 1990s.','Modern satellite measurements are more precise, and they begin in the 1990s.','Modern satellite measurements are more precise because they begin in the 1990s.','Modern satellite measurements are more precise, but they begin in the 1990s.'],answer:3,
 expl:'The sentence concedes an advantage and then names the limitation that makes the old ledgers useful. But carries that contrast.',
 wrong:'So and because assert a causal link between precision and start date that does not exist, and and flattens the contrast the paragraph depends on.'},
{id:'AE025',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Organization',skill:'act_e_pow',diff:3,
 stem:'Which sentence, if removed, would least affect the essay\'s development?',
 choices:['Sentence 9','Sentence 2','Sentence 5','Sentence 8'],answer:0,
 expl:'Sentence 9 reports where the student ended up. The essay\'s argument runs from the routine readings to their unforeseen value, and her later career adds biography rather than support.',
 wrong:'Sentence 2 establishes the routine, sentence 5 supplies the continuity that makes the record valuable, and sentence 8 states why that continuity matters.'},
{id:'AE026',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Punctuation',skill:'act_e_cse',diff:2,
 stem:'Which choice correctly punctuates the underlined portion of sentence 2: "walked out twice a day noted the level against a painted scale and wrote the number in a ledger"?',
 choices:['NO CHANGE','walked out twice a day, noted the level against a painted scale, and wrote the number in a ledger','walked out twice a day; noted the level against a painted scale; and wrote the number in a ledger','walked out twice a day noted the level against a painted scale, and wrote the number in a ledger'],answer:1,
 expl:'Three verbs in a series take commas between the items.',
 wrong:'Leaving the series unpunctuated runs the actions together, semicolons are for items that already contain commas, and the last option punctuates only part of the series.'},
{id:'AE027',section:'E',type:'E',passageId:'AEP3',passage:AE_P3,sub:'Style and tone',skill:'act_e_kol',diff:3,
 stem:'Which choice for the underlined portion of sentence 8 best matches the measured tone of the essay?',
 choices:['hands it the base it desperately needed','gives that shorter series something to stand on','gives that shorter series a truly priceless foundation to stand on','provides that shorter series with an absolutely essential grounding'],answer:1,
 expl:'The essay states things plainly and lets the facts do the work. Something to stand on is understated in the same way.',
 wrong:'Priceless, absolutely essential, and desperately needed all raise the temperature well above the rest of the piece.'},
// ---------- Passage 4 ----------
{id:'AE028',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Topic development',skill:'act_e_pow',diff:3,
 stem:'Which choice, if added after sentence 4, would most effectively preview the rest of the essay?',
 choices:['The engineers who proposed the straight span were not consulted about the final design.','Construction took eleven months and ran slightly over budget.','The curve was not an aesthetic decision but a decision about how long people would spend above the creek.','Curved spans are more expensive to build than straight ones for reasons involving load distribution.'],answer:2,
 expl:'The rest of the essay explains that the curve exists to slow walkers so they look at the creek. Stating that the curve is about time above the creek sets up exactly that argument.',
 wrong:'Budget, load distribution, and the engineers\' involvement are details the essay never develops.'},
{id:'AE029',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Sentence structure',skill:'act_e_cse',diff:3,
 stem:'Which choice best combines sentences 1 and 2?',
 choices:['When the footbridge over the ravine was rebuilt and the engineers proposed a straight span, being cheaper and crossing in forty seconds.','When the footbridge over the ravine was rebuilt the engineers proposed a straight span; cheaper, and crossing in forty seconds.','When the footbridge over the ravine was rebuilt, the engineers proposed a straight span, it would have been cheaper and would have crossed in forty seconds.','When the footbridge over the ravine was rebuilt, the engineers proposed a straight span that would have been cheaper and would have crossed in forty seconds.'],answer:3,
 expl:'A relative clause attaches both facts about the span directly to the span, and the parallel verbs keep the two claims balanced.',
 wrong:'The first option splices two independent clauses with a comma. The third leaves no main clause, and the fourth misuses a semicolon before a fragment.'},
{id:'AE030',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Word choice',skill:'act_e_kol',diff:2,
 stem:'In sentence 7, which choice most precisely describes what the curve does to a walker?',
 choices:['allows a change halfway across','forces a change of direction halfway across','requires a change of direction halfway across','encourages a change of direction halfway across'],answer:1,
 expl:'The geometry leaves the walker no option, so forces is the accurate verb, and it fits the essay\'s claim that the effect is designed rather than hoped for.',
 wrong:'Encourages and allows both suggest the walker could do otherwise. Requires is close but reads as a rule imposed rather than a physical consequence.'},
{id:'AE031',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Punctuation',skill:'act_e_cse',diff:3,
 stem:'Which choice correctly punctuates the underlined portion of sentence 3: "The design that was actually built curves and takes about two minutes to walk"?',
 choices:['NO CHANGE','The design that was actually built, curves and takes about two minutes to walk','The design, that was actually built, curves and takes about two minutes to walk','The design that was actually built curves, and takes about two minutes to walk'],answer:0,
 expl:'The relative clause identifies which design is meant, so it takes no commas, and curves and takes are compound verbs sharing one subject, so no comma divides them.',
 wrong:'Each alternative inserts a comma between a subject and its verb or between two verbs that share a subject.'},
{id:'AE032',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Transitions',skill:'act_e_pow',diff:3,
 stem:'Which choice best opens sentence 9, given its relationship to the preceding sentences?',
 choices:['For example, the town has applied the same thinking to two other paths.','In contrast, the town has applied the same thinking to two other paths.','The town has since applied the same thinking to two other paths.','However, the town applied it elsewhere.'],answer:2,
 expl:'The counts in sentence 8 show the approach worked, and sentence 9 reports the town extending it. Since carries that sequence without implying contrast.',
 wrong:'However and in contrast set up an opposition the sentence does not contain, and the extension is a consequence rather than an example of the counts.'},
{id:'AE033',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Conciseness',skill:'act_e_kol',diff:2,
 stem:'Which choice most concisely expresses the underlined portion of sentence 8: "found that people stopped on the bridge at roughly three times the rate recorded on the old one"?',
 choices:['NO CHANGE','found that people stopped on the bridge at a rate that was roughly three times higher than the rate that had been recorded on the old one','found people stopping at roughly triple the old rate','found that the rate of people stopping was roughly three times the old bridge rate'],answer:2,
 expl:'Triple the old rate carries the comparison in the fewest words while keeping the meaning exact.',
 wrong:'The other options restate rate two or three times in the same sentence.'},
{id:'AE034',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Topic development',skill:'act_e_pow',diff:4,
 stem:'The writer is considering deleting sentence 5. Doing so would primarily cause the essay to lose',
 choices:['an acknowledgement that the straight span had genuine advantages','the statistical support for the claim that walkers now stop more often','a transition to the cost','the reason the view from the bridge is worth slowing down for'],answer:3,
 expl:'Sentence 5 states that the ravine is the only public place the creek can be seen. Without it the curve looks like an arbitrary delay rather than a way of buying time above something worth seeing.',
 wrong:'The advantages appear in sentence 2, the statistics in sentence 8, and cost is not discussed after sentence 2.'},
{id:'AE035',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Verb agreement',skill:'act_e_cse',diff:3,
 stem:'Which choice for the underlined portion of sentence 10, "Neither is faster than the route it replaced", is correct?',
 choices:['NO CHANGE','Neither are faster than the route they replaced','Neither of them are faster than the routes it replaced','Neither were faster than the route it replaced'],answer:0,
 expl:'Neither is singular and takes a singular verb, and the singular pronoun it agrees with the singular route.',
 wrong:'Are and were treat neither as plural, and the third option mismatches the plural routes with the singular it.'},
{id:'AE036',section:'E',type:'E',passageId:'AEP4',passage:AE_P4,sub:'Style and tone',skill:'act_e_kol',diff:3,
 stem:'Which choice for the final clause of sentence 10 best preserves the essay\'s understated conclusion?',
 choices:['and that is the point','and that, remarkably, is the entire point of the exercise','and so it goes','and that is exactly and completely the point'],answer:0,
 expl:'The essay ends by letting a plain statement do the work. The short clause matches the restraint of the rest of the piece.',
 wrong:'Remarkably and exactly and completely both add emphasis the sentence does not need, and so it goes swaps the essay\'s plain ending for a weary cliche.'},
// ---------- Passage 5 ----------
{id:'AE037',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Punctuation',skill:'act_e_cse',diff:3,
 stem:'Which choice correctly punctuates the underlined portion of sentence 8: "a mix nobody had planned for including a boat builder two ceramicists and a company that repairs theatre lighting"?',
 choices:['a mix nobody had planned for including, a boat builder, two ceramicists and a company that repairs theatre lighting','a mix nobody had planned for; including a boat builder, two ceramicists, and a company that repairs theatre lighting','NO CHANGE','a mix nobody had planned for, including a boat builder, two ceramicists, and a company that repairs theatre lighting'],answer:3,
 expl:'A comma sets off the including phrase, and commas separate the three items in the list that follows.',
 wrong:'The unpunctuated version runs the list together, placing the comma after including separates the word from its list, and a semicolon cannot introduce a phrase that is not an independent clause.'},
{id:'AE038',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Topic development',skill:'act_e_pow',diff:4,
 stem:'Which choice, if added after sentence 4, would best support the point sentences 3 and 4 are making?',
 choices:['The building was added to the county register of historic places in 1998.','A demolition contractor estimated that removing the walls would cost more than the empty site would be worth.','The cannery processed salmon for most of its working life and employed up to three hundred people.','Concrete of that thickness was standard for industrial buildings of the period.'],answer:1,
 expl:'Sentences 3 and 4 say the building is too solid to knock down cheaply. A demolition estimate exceeding the value of the cleared site makes that concrete and explains why the proposals failed.',
 wrong:'Employment history, period norms, and the historic register do not bear on the cost of demolition, which is the claim being supported.'},
{id:'AE039',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Word choice',skill:'act_e_kol',diff:3,
 stem:'In sentence 10, which choice best conveys that the architects deliberately left the building incomplete?',
 choices:['because they ran out of time before finishing it','because they had no clear plan for finishing it','because they stopped short of finishing it','because they could not finish'],answer:2,
 expl:'Stopped short states a choice, which is what the essay has argued: the architects kept the rails and doors and let tenants decide the use.',
 wrong:'Could not finish, ran out of time, and no clear plan all attribute the unfinished state to failure rather than to intention.'},
{id:'AE040',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Sentence structure',skill:'act_e_cse',diff:3,
 stem:'Which choice best combines sentences 3 and 4 to show the relationship between them?',
 choices:['The building is too large for most uses and too solid to knock down cheaply, and its concrete walls being eighteen inches thick.','The building is too large for most uses and too solid to knock down cheaply; because its concrete walls are eighteen inches thick.','The building is too large for most uses and too solid to knock down cheaply, its concrete walls are eighteen inches thick.','The building is too large for most uses and too solid to knock down cheaply: its concrete walls are eighteen inches thick.'],answer:3,
 expl:'The second statement explains the first, and a colon is the mark for an explanation that follows an independent clause.',
 wrong:'A comma alone splices the clauses, the participial version has no finite verb, and a semicolon does not precede a subordinating conjunction this way.'},
{id:'AE041',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Transitions',skill:'act_e_pow',diff:2,
 stem:'Which choice best opens sentence 5 in relation to the first paragraph?',
 choices:['The conversion that then happened in 2007','The conversion that finally happened in 2007','The conversion that consequently happened in 2007','The conversion that similarly happened in 2007'],answer:1,
 expl:'The first paragraph lists repeated failed proposals across twenty-six years. Finally marks the end of that sequence.',
 wrong:'Consequently claims the conversion followed from the failures, similarly claims likeness to them, and then marks mere sequence and drops the point about the long series of failures.'},
{id:'AE042',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Conciseness',skill:'act_e_kol',diff:2,
 stem:'Which choice most concisely expresses the underlined portion of sentence 1: "closed in 1981 and stood empty for twenty-six years"?',
 choices:['NO CHANGE','closed in 1981 and then proceeded to stand empty for a period of twenty-six years','closed in 1981, after which it stood empty for the next twenty-six years','closed during 1981 and was standing empty for twenty-six years thereafter'],answer:0,
 expl:'Two past-tense verbs joined by and state both facts in the fewest words.',
 wrong:'Proceeded to, after which, and thereafter all add words without adding information.'},
{id:'AE043',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Organization',skill:'act_e_pow',diff:4,
 stem:'For the sake of logic and cohesion, sentence 9 should be placed',
 choices:['after sentence 5.','after sentence 10.','where it is now.','before sentence 7.'],answer:2,
 expl:'Sentence 7 says tenants could hang things from the rails, sentence 8 names the three unexpected tenants, and sentence 9 reports that all three now use the rails. It has to follow the list it refers to.',
 wrong:'Placing it before sentence 7 or after sentence 5 puts the reference ahead of the rails and the tenants. Placing it last separates it from the list and weakens the closing sentence.'},
{id:'AE044',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Verb tense',skill:'act_e_cse',diff:3,
 stem:'Which choice for the underlined portion of sentence 6 keeps the tense consistent with the paragraph?',
 choices:['the overhead rails that have once carried crates','the overhead rails that once carry crates','the overhead rails that were once carrying crates','the overhead rails that had once carried crates'],answer:3,
 expl:'The carrying happened before the 2007 conversion described in the past tense, so the past perfect is correct.',
 wrong:'The present perfect links the action to now, the present is inconsistent with once, and the past progressive suggests an action in progress at an unspecified time.'},
{id:'AE045',section:'E',type:'E',passageId:'AEP5',passage:AE_P5,sub:'Style and tone',skill:'act_e_kol',diff:3,
 stem:'Which choice for the underlined portion of sentence 5 best fits the essay\'s restrained tone?',
 choices:['did not try to make the cannery into something else','did not attempt the impossible task of transforming the cannery entirely','wisely refrained from the folly of turning the cannery into something else','made no effort to convert it'],answer:0,
 expl:'The essay reports decisions without praising them and lets the outcome make the case. The plain phrasing matches.',
 wrong:'Impossible task and wisely and folly both editorialise where the essay does not, and the blunt denial of any effort misstates what the architects did.'},
// ---------- Passage 6 ----------
{id:'AE046',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Punctuation',skill:'act_e_cse',diff:4,
 stem:'Which choice correctly punctuates the underlined portion of sentence 3: "not the river exactly but a model of it built from soundings from the behaviour of the current against the banks and from how a particular hull answers"?',
 choices:['NO CHANGE','not the river exactly but a model of it, built from soundings, from the behaviour of the current against the banks, and from how a particular hull answers','not the river exactly, but a model of it built from soundings from the behaviour of the current against the banks, and from how a particular hull answers','not the river exactly but a model of it; built from soundings; from the behaviour of the current against the banks; and from how a particular hull answers'],answer:1,
 expl:'A comma sets off the participial phrase, and commas separate the three parallel from phrases in the series.',
 wrong:'The unpunctuated version merges the series, the third option punctuates the contrast but leaves the series unmarked, and semicolons are not needed for items without internal commas.'},
{id:'AE047',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Word choice',skill:'act_e_kol',diff:3,
 stem:'In sentence 2, which choice most precisely describes water that cannot be seen through?',
 choices:['turbulent with silt','opaque with silt','obscure with silt','dense with silt'],answer:1,
 expl:'Opaque means light does not pass through, which is exactly why the pilot cannot see the channel.',
 wrong:'Obscure describes something hard to understand, dense describes concentration rather than transparency, and turbulent describes motion.'},
{id:'AE048',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Topic development',skill:'act_e_pow',diff:4,
 stem:'Which choice, if added after sentence 7, would most effectively support the paragraph\'s point about how pilots exchange information?',
 choices:['Conversations between pilots are not recorded and are rarely written down afterwards.','Most pilots serve an apprenticeship of several years before working a stretch alone.','The phrase names a bar that is building up, its position, and the landmark it is measured from, in seven words.','River pilots are licensed separately for each stretch of water they work.'],answer:2,
 expl:'Sentence 7 says the remark carries a specific and actionable meaning to another pilot. Unpacking exactly how much the seven words encode demonstrates that claim instead of restating it.',
 wrong:'Apprenticeship length and licensing describe how pilots are trained, and the absence of records repeats sentence 6 without showing what the language conveys.'},
{id:'AE049',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Sentence structure',skill:'act_e_cse',diff:3,
 stem:'Which choice best corrects the underlined portion of sentence 9: "and a survey is a photograph of a moving thing"?',
 choices:['NO CHANGE','and a survey being a photograph of a moving thing','and a survey, a photograph of a moving thing','; and a survey is a photograph of a moving thing'],answer:0,
 expl:'The clause is independent and joined to the previous independent clause by and with a comma already in place, which is correct.',
 wrong:'The participial and appositive versions remove the finite verb the clause needs, and adding a semicolon before and over-punctuates the join.'},
{id:'AE050',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Transitions',skill:'act_e_pow',diff:3,
 stem:'Which choice best opens sentence 8, given its relationship to the preceding paragraph?',
 choices:['Electronic charts removed the need.','Electronic charts have changed the work, similarly removing the need for it.','Electronic charts have changed the work because they removed the need for it.','Electronic charts have changed the work but not removed the need for it.'],answer:3,
 expl:'The paragraph closes by saying the pilot supplies what the chart leaves out, so the sentence must concede the change and deny the replacement. But does both.',
 wrong:'Similarly and because both assert that the charts removed the need, and the flat assertion that they removed it contradicts the sentence that follows.'},
{id:'AE051',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Conciseness',skill:'act_e_kol',diff:2,
 stem:'Which choice most concisely expresses the underlined portion of sentence 4: "The model has to be revised constantly"?',
 choices:['NO CHANGE','The model is something that has to undergo constant revision','The model has to be subjected to a constant process of revision','The model is in need of being revised on a constant basis'],answer:0,
 expl:'A simple verb with an adverb says it in five words.',
 wrong:'Each alternative converts the verb into a noun phrase and adds a supporting verb, which lengthens the sentence without changing its meaning.'},
{id:'AE052',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Organization',skill:'act_e_pow',diff:3,
 stem:'The writer wants to add the following sentence: "The channel itself moves." That sentence would most logically be placed',
 choices:['after sentence 2.','after sentence 4.','after sentence 6.','after sentence 9.'],answer:1,
 expl:'Sentence 4 says the model must be revised constantly and sentence 5 gives the flood that moves a bar half a mile. The new sentence states the reason between the claim and its example.',
 wrong:'After sentence 2 it interrupts the account of what a pilot learns, and after sentence 6 or 9 it arrives long after the revision point has been made.'},
{id:'AE053',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Pronoun clarity',skill:'act_e_cse',diff:3,
 stem:'Which choice for the underlined portion of sentence 10 makes the reference clearest?',
 choices:['The pilot supplies what they leave out.','The pilot supplies what the same leaves out.','The pilot supplies what the photograph leaves out.','The pilot supplies what it leaves out.'],answer:2,
 expl:'Repeating the noun photograph keeps the reference unambiguous, since both charts and surveys have been mentioned in the preceding sentence.',
 wrong:'It and they could point to charts, surveys or the photograph, and the same is not idiomatic English here.'},
{id:'AE054',section:'E',type:'E',passageId:'AEP6',passage:AE_P6,sub:'Style and tone',skill:'act_e_kol',diff:3,
 stem:'Which choice for the underlined portion of sentence 6 best matches the essay\'s tone?',
 choices:['in baffling conversations','in conversations that are total gibberish to anyone listening in','in conversations that outsiders could never hope to comprehend','in conversations that outsiders find almost unintelligible'],answer:3,
 expl:'Almost unintelligible is precise and measured, and the qualifier matters because the next sentence goes on to translate one such remark.',
 wrong:'Baffling on its own drops the outsiders the sentence is about, and total gibberish and never hope to comprehend both overstate, contradicting the translation the essay supplies.'}
];
