// bank_quant6.js - Original GMAT Focus Quant items Q261-Q267: Value / Order / Factors reinforcement
const BANK_QUANT6 = [
{id:'Q261',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:2,
 stem:'How many positive divisors does 84 have?',
 choices:['8','10','12','14','16'],answer:2,
 expl:'Factor: 84 = 2^2 x 3 x 7. The divisor count multiplies one more than each exponent: (2+1)(1+1)(1+1) = 12.',
 wrong:'Listing divisors by hand invites missing a pair such as 6 and 14; the exponent rule is faster and safer. Counting only the prime factors gives 3, which is not offered, but half-counting pairs leads to 8.'},
{id:'Q262',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:3,
 stem:'What is the smallest positive integer n for which 540n is a perfect square?',
 choices:['5','9','15','30','60'],answer:2,
 expl:'540 = 2^2 x 3^3 x 5. A perfect square needs even exponents everywhere, so one more 3 and one more 5 are required: n = 3 x 5 = 15. Then 540 x 15 = 8100 = 90^2.',
 wrong:'Choosing 30 or 60 over-corrects exponents that are already even; choosing 5 or 9 fixes only one of the two odd exponents.'},
{id:'Q263',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:3,
 stem:'If x is a positive integer and 3^x is a factor of 9^6 x 27^3, what is the greatest possible value of x?',
 choices:['9','12','18','21','24'],answer:3,
 expl:'Rewrite in base 3: 9^6 = 3^12 and 27^3 = 3^9, so the product is 3^21. The greatest power of 3 dividing it is 3^21, so x = 21.',
 wrong:'Multiplying the exponents (12 x 9) or adding the wrong pair (6 + 3 = 9, then doubling) produces the trap answers; exponents add when the bases multiply.'},
{id:'Q264',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:4,
 stem:'Positive integers a and b have a greatest common divisor of 12 and a least common multiple of 360. If a = 24, what is b?',
 choices:['90','120','150','180','240'],answer:3,
 expl:'For any two positive integers, a x b = gcd x lcm. So b = (12 x 360) / 24 = 180. Check: gcd(24, 180) = 12 and lcm(24, 180) = 360.',
 wrong:'Picking 120 comes from using lcm / gcd x 4; picking 360 / 24 = 15 is not offered, but 90 comes from halving the correct product relationship.'},
{id:'Q265',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:2,
 stem:'Which of the following is greatest?',
 choices:['7/9','11/14','4/5','17/21','0.79'],answer:3,
 expl:'Convert to decimals: 7/9 is about 0.778, 11/14 about 0.786, 4/5 = 0.800, 17/21 about 0.810, and 0.79. The greatest is 17/21.',
 wrong:'4/5 looks biggest because it is the cleanest fraction, but 17/21 sits closer to 1: its gap below 1 is 4/21, smaller than the 1/5 gap of 4/5.'},
{id:'Q266',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:4,
 stem:'What is the units digit of 7^49?',
 choices:['1','3','5','7','9'],answer:3,
 expl:'Units digits of powers of 7 cycle with period 4: 7, 9, 3, 1. Since 49 = 4 x 12 + 1, 7^49 lands on the first member of the cycle, 7.',
 wrong:'Treating the cycle as starting at 7^0 shifts every answer by one place and gives 1; the cycle here is indexed from 7^1.'},
{id:'Q267',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:5,
 stem:'When the positive integer n is divided by 7, the remainder is 4. What is the remainder when n^2 + 3n is divided by 7?',
 choices:['0','1','2','4','6'],answer:0,
 expl:'Work with remainders: n leaves 4, so n^2 leaves the remainder of 16, which is 2, and 3n leaves the remainder of 12, which is 5. Then 2 + 5 = 7 leaves remainder 0. Check with n = 4: 16 + 12 = 28 = 4 x 7.',
 wrong:'Adding the raw remainders 16 + 12 = 28 and stopping at 28, or forgetting to reduce 16 and 12 mod 7 first, leads to 2 or 6.'}
];
