// Start From Nowhere trainer: GMAT Focus Quant bank, batch 4 (Q221-Q240), original items
const BANK_QUANT4 = [
{id:'Q221',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:2,
stem:'A jacket originally priced at $120 is marked down by 25 percent. At the register, an additional 10 percent is taken off the reduced price. What is the final price of the jacket?',
choices:['$78','$81','$84','$90','$108'],answer:1,
expl:'Apply the discounts in sequence: 120 x 0.75 = 90, then 90 x 0.90 = 81. Successive discounts multiply; they never simply add.',
wrong:'Choosing $78 comes from adding the discounts to get 35 percent off the original price; the second discount applies to the already reduced price, not to $120.'},
{id:'Q222',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:2,
stem:'A salesperson earns a base salary of $400 per week plus a commission equal to 5 percent of her weekly sales. Last week her total earnings were $650. What were her sales for the week?',
choices:['$3,000','$4,000','$5,000','$6,500','$13,000'],answer:2,
expl:'Commission earned was 650 - 400 = 250. Since 0.05 x sales = 250, sales = 250/0.05 = 5,000.',
wrong:'$13,000 comes from dividing the full $650 by 0.05 without first subtracting the $400 base salary.'},
{id:'Q223',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:2,
stem:'Which of the following is closest to the value of (0.51 x 79.8)/0.199?',
choices:['20','40','100','200','400'],answer:3,
expl:'Round each number: (0.5 x 80)/0.2 = 40/0.2 = 200. The choices are far apart, so rough rounding is safe.',
wrong:'Picking 20 or 40 comes from mishandling the division by 0.199, which multiplies the product by about 5, not by 0.5.'},
{id:'Q224',section:'Q',type:'PS',domain:'statistics',context:'real',skill:'q_csp',diff:2,
stem:'The average (arithmetic mean) weight of 5 packages in a shipment is 42 pounds. Four of the packages weigh 38, 40, 45, and 47 pounds. What is the weight, in pounds, of the fifth package?',
choices:['38','40','42','44','46'],answer:1,
expl:'The total weight is 5 x 42 = 210 pounds. The four known packages total 38 + 40 + 45 + 47 = 170, so the fifth weighs 210 - 170 = 40 pounds.',
wrong:'Choosing 42 assumes the fifth package must equal the mean; the mean constrains only the total, not any single value.'},
{id:'Q225',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
stem:'Working alone, Maya can paint a fence in 8 hours and Liam can paint the same fence in 12 hours. They work together for 3 hours, and then Liam leaves. How many more hours will Maya need to finish the fence alone?',
choices:['1.5','2','2.5','3','4'],answer:3,
expl:'Together they complete 1/8 + 1/12 = 5/24 of the fence per hour, so in 3 hours they finish 15/24 = 5/8. The remaining 3/8 at Maya\'s rate of 1/8 per hour takes (3/8)/(1/8) = 3 hours.',
wrong:'Answers like 1.5 or 2 typically come from using the combined rate for the remaining work instead of Maya\'s rate alone.'},
{id:'Q226',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:3,
stem:'A cafe sells small coffees for $3 each and large coffees for $5 each. One morning the cafe sold 60 coffees for a total of $236. How many large coffees were sold?',
choices:['24','26','28','32','36'],answer:2,
expl:'If all 60 had been small, revenue would be $180. Each large coffee adds $2, so the number of large coffees is (236 - 180)/2 = 28. Check: 32 x 3 + 28 x 5 = 96 + 140 = 236.',
wrong:'32 is the number of small coffees; the question asks for large. Setting up 3s + 5l = 236 and solving for the wrong variable is the usual slip.'},
{id:'Q227',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:3,
stem:'Which of the following fractions is greatest?',
choices:['5/8','7/11','2/3','13/20','9/14'],answer:2,
expl:'Convert to decimals: 5/8 = 0.625, 7/11 is about 0.636, 2/3 is about 0.667, 13/20 = 0.65, and 9/14 is about 0.643. The greatest is 2/3. A shortcut: compare each fraction to 2/3 by cross multiplication and note every other one falls short.',
wrong:'13/20 = 0.65 looks large because both its numerator and denominator are big, but 2/3 is still greater.'},
{id:'Q228',section:'Q',type:'PS',domain:'counting',context:'real',skill:'q_csp',diff:3,
stem:'A locker code consists of two different letters chosen from A, B, C, D, and E, written in order, followed by one odd digit. How many different codes are possible?',
choices:['50','100','120','125','200'],answer:1,
expl:'There are 5 choices for the first letter, 4 for the second because the letters must differ, and 5 odd digits (1, 3, 5, 7, 9). Total: 5 x 4 x 5 = 100.',
wrong:'125 comes from allowing repeated letters (5 x 5 x 5); 50 comes from treating the two letters as an unordered pair even though the code is written in order.'},
{id:'Q229',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
stem:'A punch is mixed with juice and sparkling water in the ratio 3 to 2. After 4 liters of sparkling water are added, the ratio of juice to sparkling water becomes 3 to 4. How many liters of juice are in the punch?',
choices:['4','5','6','10','14'],answer:2,
expl:'Let the amounts be 3x and 2x. Then 3x/(2x + 4) = 3/4, so 12x = 6x + 12 and x = 2. The juice is 3x = 6 liters.',
wrong:'4 is the original amount of sparkling water (2x), and 10 is the original total volume; both come from solving for x correctly but reporting the wrong quantity.'},
{id:'Q230',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
stem:'If x + 1/x = 5, what is the value of x^2 + 1/x^2?',
choices:['21','23','25','27','29'],answer:1,
expl:'Square both sides: (x + 1/x)^2 = x^2 + 2 + 1/x^2 = 25. So x^2 + 1/x^2 = 25 - 2 = 23. No need to solve for x itself.',
wrong:'25 forgets the middle term 2 that appears when squaring; 27 adds it instead of subtracting.'},
{id:'Q231',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:3,
stem:'What is the value of (3^8 - 3^6)/24?',
choices:['27','81','243','729','2187'],answer:2,
expl:'Factor out 3^6: (3^6)(3^2 - 1)/24 = (3^6 x 8)/24 = 3^6/3 = 3^5 = 243. Factoring first avoids computing 3^8 = 6561.',
wrong:'Subtracting exponents to get 3^2 = 9 or treating 3^8 - 3^6 as 3^2 leads to the small choices; exponents cannot be subtracted across a difference.'},
{id:'Q232',section:'Q',type:'PS',domain:'counting',context:'real',skill:'q_csp',diff:3,
stem:'A bag contains 4 red chips and 6 blue chips. Two chips are drawn at random, one after the other, without replacement. What is the probability that both chips are blue?',
choices:['3/10','1/3','9/25','2/5','3/5'],answer:1,
expl:'The first draw is blue with probability 6/10, and the second with probability 5/9. Multiply: (6/10)(5/9) = 30/90 = 1/3.',
wrong:'9/25 comes from (6/10)^2, treating the draws as if the first chip were replaced; without replacement the second probability is 5/9.'},
{id:'Q233',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:4,
stem:'The monthly price of a wireless data plan rose by 20 percent in January. In June the new price fell by p percent, and the resulting price was 2 percent higher than the price before the January increase. What is the value of p?',
choices:['12','15','18','20','22'],answer:1,
expl:'Take the original price as 100. After January the price is 120, and the final price must be 102. Since 102/120 = 0.85, the June decrease was 15 percent.',
wrong:'18 comes from subtracting percentages directly (20 - 2); percent changes apply to different bases and cannot be netted this way.'},
{id:'Q234',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:4,
stem:'How many integers x satisfy the inequality |2x - 5| < 9?',
choices:['6','7','8','9','10'],answer:2,
expl:'Rewrite as -9 < 2x - 5 < 9, so -4 < 2x < 14 and -2 < x < 7. The integers are -1, 0, 1, 2, 3, 4, 5, 6, which is 8 values.',
wrong:'9 comes from including the endpoints -2 and 7, but the inequality is strict, so neither endpoint counts; 7 comes from starting the count at 0 and missing -1.'},
{id:'Q235',section:'Q',type:'PS',domain:'arithmetic',context:'pure',skill:'q_vof',diff:4,
stem:'What is the value of the sum 1/(1 x 2) + 1/(2 x 3) + 1/(3 x 4) + ... + 1/(9 x 10)?',
choices:['4/5','8/9','9/10','10/11','1'],answer:2,
expl:'Each term splits as 1/(n(n + 1)) = 1/n - 1/(n + 1), so the sum telescopes to 1 - 1/10 = 9/10. Everything between the first and last pieces cancels.',
wrong:'10/11 comes from running the telescoping one term too far, as if the last term were 1/(10 x 11); 1 assumes the whole tail cancels to nothing.'},
{id:'Q236',section:'Q',type:'PS',domain:'counting',context:'real',skill:'q_csp',diff:4,
stem:'A coach must select a 4-player relay team from a squad of 8 players. Player J must be on the team, and player K must not be on the team. How many different teams can the coach select?',
choices:['15','20','30','35','70'],answer:1,
expl:'With J in and K out, the coach fills the 3 remaining spots from the other 6 players: C(6,3) = 20.',
wrong:'35 = C(7,3) applies only the J condition and forgets to remove K from the pool; 70 = C(8,4) ignores both conditions.'},
{id:'Q237',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:4,
stem:'Machine X packs 30 percent more boxes per hour than machine Y. Working simultaneously at their constant rates, the two machines pack 2,760 boxes in 6 hours. How many boxes per hour does machine X pack?',
choices:['200','230','240','260','280'],answer:3,
expl:'The combined rate is 2760/6 = 460 boxes per hour. If Y packs r per hour, then r + 1.3r = 2.3r = 460, so r = 200 and X packs 1.3 x 200 = 260.',
wrong:'200 is machine Y\'s rate, not X\'s; 230 splits the combined rate in half, ignoring that X is 30 percent faster.'},
{id:'Q238',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:5,
stem:'If r and s are the two roots of the equation x^2 - 7x + 9 = 0, what is the value of 1/r + 1/s?',
choices:['1/7','7/9','9/7','7','9'],answer:1,
expl:'Combine the fractions: 1/r + 1/s = (r + s)/(rs). By Vieta\'s relations, r + s = 7 and rs = 9, so the value is 7/9. Solving for the roots themselves is unnecessary since the discriminant is not a perfect square.',
wrong:'9/7 swaps the roles of the sum and the product of the roots in the formula (r + s)/(rs).'},
{id:'Q239',section:'Q',type:'PS',domain:'number properties',context:'pure',skill:'q_vof',diff:4,
stem:'The number (2^20)(5^17) is closest to which of the following powers of 10?',
choices:['10^17','10^18','10^20','10^37','10^40'],answer:1,
expl:'Pair the factors: (2^17)(5^17) = 10^17, leaving 2^3 = 8. So the number is 8 x 10^17, which is closer to 10^18 than to 10^17 because 8 is closer to 10 than to 1 on a ratio basis.',
wrong:'10^37 comes from adding the exponents 20 + 17, which would be valid only if the bases were equal.'},
{id:'Q240',section:'Q',type:'PS',domain:'counting',context:'real',skill:'q_csp',diff:4,
stem:'Each shipment leaving a warehouse passes final inspection with probability 0.8, independently of the others. If 3 shipments leave the warehouse, what is the probability that at least one of them fails final inspection?',
choices:['0.008','0.200','0.488','0.512','0.600'],answer:2,
expl:'Use the complement: P(all three pass) = 0.8^3 = 0.512, so P(at least one fails) = 1 - 0.512 = 0.488.',
wrong:'0.512 answers the complementary question (all pass); 0.600 adds 0.2 three times, which overcounts the outcomes where more than one shipment fails.'}
];
