// bank_sat_math.js - Original SAT Math items SM001-SM038: Algebra and Advanced Math.
// Four answer choices per multiple-choice item, as on the digital SAT; answerType 'spr' marks a
// student-produced response (grid-in), graded by value so 1/2, 0.5 and .5 all count.
const BANK_SAT_MATH = [
// ---------- Algebra: linear equations, linear functions, systems, inequalities ----------
{id:'SM001',section:'M',type:'MC',sub:'Linear equations in one variable',skill:'m_alg',diff:1,
 stem:'If 5x + 3 = 28, what is the value of x?',
 choices:['4','5','6','25'],answer:1,
 expl:'Subtract 3 from both sides to get 5x = 25, then divide by 5 to get x = 5.',
 wrong:'Choosing 25 means stopping after the subtraction and forgetting to divide by the coefficient. Undo addition first, then undo multiplication.'},
{id:'SM002',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:1,
 stem:'A line in the xy-plane has a slope of -3 and passes through the point (0, 4). Which equation represents this line?',
 choices:['y = 4x - 3','y = -3x + 4','y = 3x + 4','y = -3x - 4'],answer:1,
 expl:'Slope-intercept form is y = mx + b. The slope m is -3, and because the point given has x = 0, its y-value 4 is the y-intercept b.',
 wrong:'Choice A swaps the slope and the intercept. The number multiplied by x is always the slope; the lone constant is always the y-intercept.'},
{id:'SM003',section:'M',type:'MC',sub:'Linear equations in one variable',skill:'m_alg',diff:2,
 stem:'If 3(x - 2) = 4x + 5, what is the value of x?',
 choices:['-11','-1','1','11'],answer:0,
 expl:'Distribute on the left: 3x - 6 = 4x + 5. Subtract 3x from both sides to get -6 = x + 5, then subtract 5 to get x = -11.',
 wrong:'Choice D is the same digits with the sign dropped. When the variable ends up on the right side, the constant that moves across changes sign.'},
{id:'SM004',section:'M',type:'MC',sub:'Systems of two linear equations',skill:'m_alg',diff:2,
 stem:'If 2x + 3y = 12 and y = 2x, what is the value of x?',
 choices:['0.75','1.5','2','3'],answer:1,
 expl:'Substitute y = 2x into the first equation: 2x + 3(2x) = 12, so 8x = 12 and x = 1.5.',
 wrong:'Choice D is the value of y, not x. Substitution answers whichever variable the question names, so read the last line again before gridding.'},
{id:'SM005',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:2,
 stem:'The function f is defined by f(x) = 7 - 2x. What is the value of f(-3)?',
 choices:['-13','1','11','13'],answer:3,
 expl:'Substitute -3 for x: f(-3) = 7 - 2(-3) = 7 + 6 = 13.',
 wrong:'Choice B comes from computing 7 - 2(3) and ignoring the negative sign on the input. Subtracting a negative adds.'},
{id:'SM006',section:'M',type:'MC',sub:'Linear equations in two variables',skill:'m_alg',diff:3,
 stem:'A line in the xy-plane passes through the points (2, 5) and (6, 17). What is the y-intercept of this line?',
 choices:['-1','1','3','11'],answer:0,
 expl:'The slope is (17 - 5)/(6 - 2) = 12/4 = 3. Using y = 3x + b with the point (2, 5): 5 = 6 + b, so b = -1.',
 wrong:'Choice C is the slope, not the intercept. Finding the slope is only step one; you still have to substitute a point to solve for b.'},
{id:'SM007',section:'M',type:'MC',sub:'Systems of two linear equations',skill:'m_alg',diff:3,
 stem:'If 3x + 2y = 16 and x - 2y = 0, what is the value of x + y?',
 choices:['2','4','6','8'],answer:2,
 expl:'Add the two equations to eliminate y: 4x = 16, so x = 4. Then 4 - 2y = 0 gives y = 2, and x + y = 6.',
 wrong:'Choice B is x alone. Elimination hands you one variable quickly, which makes it easy to stop before answering the combination the question actually asked for.'},
{id:'SM008',section:'M',type:'MC',sub:'Linear inequalities',skill:'m_alg',diff:3,
 stem:'Which of the following describes all values of x that satisfy -4x + 9 > 21?',
 choices:['x > -3','x < 3','x > 3','x < -3'],answer:3,
 expl:'Subtract 9 from both sides to get -4x > 12. Dividing by -4 reverses the inequality sign, giving x < -3.',
 wrong:'Choice A keeps the original direction. Multiplying or dividing an inequality by a negative number always flips the sign; check by testing x = -4, which does satisfy the inequality.'},
{id:'SM009',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:3,
 stem:'A plumber charges a fixed call-out fee plus an hourly rate. The total charge C, in dollars, for a job lasting h hours is given by C = 45 + 72h. Which of the following is the best interpretation of the number 72 in this context?',
 choices:['The charge, in dollars, for each hour worked','The call-out fee, in dollars','The total charge, in dollars, for a one-hour job','The number of hours in a typical job'],answer:0,
 expl:'In a linear model the coefficient of the variable is the rate of change. Here each additional hour adds 72 dollars to the total, so 72 is the hourly rate.',
 wrong:'Choice C is the trap: a one-hour job costs 45 + 72 = 117 dollars, not 72. The coefficient describes change per unit, never a total.'},
{id:'SM010',section:'M',type:'MC',sub:'Systems of two linear equations',skill:'m_alg',diff:4,
 stem:'The system of equations 2x + ky = 8 and 6x + 12y = 24 has infinitely many solutions. What is the value of k?',
 choices:['2','3','4','6'],answer:2,
 expl:'Infinitely many solutions means the two equations describe the same line. Multiplying the first equation by 3 gives 6x + 3ky = 24, so 3k must equal 12 and k = 4.',
 wrong:'Choice D comes from comparing 12 and 2 directly without scaling the whole equation. Every term has to be multiplied by the same factor, constants included.'},
{id:'SM011',section:'M',type:'MC',sub:'Systems of two linear equations',skill:'m_alg',diff:4,
 stem:'The system of equations ax + 3y = 12 and 4x + 6y = 15 has no solution. What is the value of a?',
 choices:['1','2','3','8'],answer:1,
 expl:'No solution means the lines are parallel: the x and y coefficients are proportional but the constants are not. Setting a/4 = 3/6 gives a = 2, and 12/15 is not 1/2, so the lines really are parallel rather than identical.',
 wrong:'Choice D matches the constants instead of the coefficients. Parallel lines are decided by the coefficients alone; the constants only confirm that the lines are not the same line.'},
{id:'SM012',section:'M',type:'MC',sub:'Linear equations in one variable',skill:'m_alg',diff:2,
 stem:'If (1/2)(6x - 8) = 5, what is the value of x?',
 choices:['1','3','4.5','9'],answer:1,
 expl:'Distribute the one half: 3x - 4 = 5, so 3x = 9 and x = 3.',
 wrong:'Choice D comes from solving 3x = 9 and reporting 9 instead of dividing. Distributing first keeps the numbers small enough to finish cleanly.'},
{id:'SM013',section:'M',type:'SPR',answerType:'spr',sub:'Linear equations in one variable',skill:'m_alg',diff:3,
 stem:'If 3(2x + 1) - 4 = 17, what is the value of x?',
 choices:[],answer:'3',
 expl:'Distribute: 6x + 3 - 4 = 17, so 6x - 1 = 17, 6x = 18, and x = 3.',
 wrong:'Combining 3 - 4 as +1 instead of -1 is the common slip here and produces x = 13/6. Simplify the constants on one side before moving anything across.'},
{id:'SM014',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:3,
 stem:'The linear function f satisfies f(1) = 7 and f(4) = 19. What is the value of f(10)?',
 choices:['31','39','43','47'],answer:2,
 expl:'The rate of change is (19 - 7)/(4 - 1) = 4 per unit. From f(4) = 19, six more units add 24, so f(10) = 43.',
 wrong:'Choice B doubles f(4) plus one, a shortcut that only works for functions through the origin. A linear function with a nonzero intercept is never proportional.'},
{id:'SM015',section:'M',type:'MC',sub:'Systems of two linear equations',skill:'m_alg',diff:4,
 stem:'One gym charges a 60 dollar joining fee plus 25 dollars per month. A second gym charges 40 dollars per month and no joining fee. After how many months will the total amounts paid be equal?',
 choices:['2','3','4','6'],answer:2,
 expl:'Set the totals equal: 60 + 25m = 40m. Subtracting gives 60 = 15m, so m = 4. Both plans have cost 160 dollars at that point.',
 wrong:'Choice D divides 60 by 10 rather than by the difference in monthly rates. What closes the gap is the difference between the rates, which is 40 - 25 = 15.'},
{id:'SM016',section:'M',type:'SPR',answerType:'spr',sub:'Systems of two linear equations',skill:'m_alg',diff:4,
 stem:'If 5x - 2y = 14 and x + 2y = 10, what is the value of x + y?',
 choices:[],answer:'7',
 expl:'Add the equations to eliminate y: 6x = 24, so x = 4. Then 4 + 2y = 10 gives y = 3, and x + y = 7.',
 wrong:'Stopping at x = 4 is the usual error. Adding the equations is the fast move, but the question asks for a combination, not a single variable.'},
{id:'SM017',section:'M',type:'MC',sub:'Linear equations in two variables',skill:'m_alg',diff:3,
 stem:'Which of the following points lies on the line 2x - 5y = 20?',
 choices:['(0, 4)','(5, 2)','(-10, 0)','(10, 0)'],answer:3,
 expl:'Substitute each point. For (10, 0): 2(10) - 5(0) = 20, which matches.',
 wrong:'Choice A satisfies 5y = 20 but ignores the x term and the minus sign; substituting it gives -20, not 20. Testing points is fast, but every term has to be evaluated.'},
{id:'SM018',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:5,
 stem:'Line k is perpendicular to the line y = (2/3)x + 1 and passes through the point (4, -1). What is the y-intercept of line k?',
 choices:['-7','2','5','11'],answer:2,
 expl:'Perpendicular slopes are negative reciprocals, so line k has slope -3/2. Substituting (4, -1) into y = (-3/2)x + b gives -1 = -6 + b, so b = 5.',
 wrong:'Choice A uses the original slope 2/3 instead of flipping and negating it. Negative reciprocal means both invert the fraction and change the sign.'},
{id:'SM019',section:'M',type:'MC',sub:'Linear equations in two variables',skill:'m_alg',diff:3,
 stem:'If 5x - 2y = 8, which of the following expresses y in terms of x?',
 choices:['y = (8 - 5x)/2','y = (5x - 8)/2','y = 5x/2 - 8','y = (5x + 8)/2'],answer:1,
 expl:'Subtract 5x from both sides: -2y = 8 - 5x. Dividing by -2 gives y = (5x - 8)/2.',
 wrong:'Choice A forgets that dividing by -2 also changes the sign of every term in the numerator. Choice C divides only the first term by 2.'},
{id:'SM020',section:'M',type:'MC',sub:'Linear functions',skill:'m_alg',diff:5,
 stem:'A tank drains at a constant rate. Two minutes after draining begins it holds 46 gallons, and seven minutes after draining begins it holds 21 gallons. How many gallons did the tank hold at the moment draining began?',
 choices:['51','56','61','66'],answer:1,
 expl:'The rate is (21 - 46)/(7 - 2) = -5 gallons per minute. Working back two minutes from 46 gallons adds 10 gallons, so the tank started with 56.',
 wrong:'Choice A works back only one minute. Sketch the pairs (2, 46) and (7, 21) and count the steps to t = 0 rather than adding the rate once by reflex.'},
// ---------- Advanced Math: equivalent expressions, nonlinear equations, nonlinear functions ----------
{id:'SM021',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:2,
 stem:'Which expression is equivalent to (x + 3)(x - 5)?',
 choices:['x^2 + 2x - 15','x^2 - 8x - 15','x^2 - 2x - 15','x^2 - 2x + 15'],answer:2,
 expl:'Expand: x^2 - 5x + 3x - 15 = x^2 - 2x - 15.',
 wrong:'Choice D keeps the constant positive. A positive times a negative is negative, so the product of 3 and -5 must be -15.'},
{id:'SM022',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:2,
 stem:'What is the greater solution to the equation x^2 - 9x + 20 = 0?',
 choices:['4','5','9','20'],answer:1,
 expl:'Factor into (x - 4)(x - 5) = 0, so the solutions are 4 and 5, and the greater one is 5.',
 wrong:'Choices C and D are the sum and the product of the roots, which appear in the equation itself. Factoring gives the roots; reading coefficients gives their sum and product.'},
{id:'SM023',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:3,
 stem:'The function f is defined by f(x) = x^2 - 4x + 1. What is the value of f(3)?',
 choices:['-6','-2','2','22'],answer:1,
 expl:'Substitute: f(3) = 9 - 12 + 1 = -2.',
 wrong:'Choice D comes from evaluating (3^2 - 4)(3) + 1, which changes the order of operations. Square first, then multiply, then add.'},
{id:'SM024',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:3,
 stem:'What is the sum of all solutions to the equation |2x - 5| = 9?',
 choices:['-2','5','7','9'],answer:1,
 expl:'Split into 2x - 5 = 9, giving x = 7, and 2x - 5 = -9, giving x = -2. Their sum is 5.',
 wrong:'Choice C is the positive solution only. An absolute value equation has two branches unless the right side is zero, and this question asks for both.'},
{id:'SM025',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:3,
 stem:'If 2^(x + 3) = 32, what is the value of x?',
 choices:['2','3','5','8'],answer:0,
 expl:'Write 32 as 2^5. With the same base, the exponents must match: x + 3 = 5, so x = 2.',
 wrong:'Choice C is the full exponent 5 rather than x. Matching bases gives you an equation about the exponents, which still has to be solved.'},
{id:'SM026',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:4,
 stem:'What are the coordinates of the vertex of the parabola y = x^2 - 6x + 11?',
 choices:['(-3, 2)','(3, -2)','(6, 11)','(3, 2)'],answer:3,
 expl:'The vertex x-value is -b/(2a) = 6/2 = 3. Then y = 9 - 18 + 11 = 2, so the vertex is (3, 2). Completing the square gives the same result: y = (x - 3)^2 + 2.',
 wrong:'Choice A drops the negative in -b/(2a). With b = -6, the formula gives +3, and a quick check shows y is smaller at x = 3 than at x = -3.'},
{id:'SM027',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:4,
 stem:'The equation x^2 + kx + 36 = 0 has exactly one real solution, and k is positive. What is the value of k?',
 choices:['6','9','12','18'],answer:2,
 expl:'Exactly one real solution means the discriminant is zero: k^2 - 4(1)(36) = 0, so k^2 = 144 and k = 12 for the positive value.',
 wrong:'Choice A is the square root of 36, the repeated root itself rather than the coefficient. One solution means the quadratic is (x + 6)^2 = x^2 + 12x + 36.'},
{id:'SM028',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:4,
 stem:'For x not equal to 4, which expression is equivalent to (x^2 - 16)/(x - 4)?',
 choices:['x - 4','x + 4','x^2 - 4','16'],answer:1,
 expl:'The numerator is a difference of squares: (x - 4)(x + 4). Cancelling the common factor x - 4 leaves x + 4.',
 wrong:'Choice A cancels the wrong factor. Factor the numerator completely before cancelling, and remember that only whole factors cancel, never individual terms.'},
{id:'SM029',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:5,
 stem:'If a is a positive number and a^(1/2) = 5, what is the value of a^(3/2)?',
 choices:['15','25','75','125'],answer:3,
 expl:'Since a^(3/2) = (a^(1/2))^3, the value is 5^3 = 125. Checking directly, a = 25 and 25^(3/2) = 125.',
 wrong:'Choice A multiplies the base by 3 instead of cubing it. Multiplying an exponent by 3 raises the whole quantity to the third power.'},
{id:'SM030',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:4,
 stem:'What is the greater solution to the equation x^2 = 7x - 10?',
 choices:[],answer:'5',
 expl:'Move every term to one side: x^2 - 7x + 10 = 0, which factors as (x - 5)(x - 2) = 0. The solutions are 5 and 2.',
 wrong:'Dividing both sides by x to get x = 7 - 10/x goes nowhere and can lose a root. Set a quadratic equal to zero before factoring.'},
{id:'SM031',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:3,
 stem:'Which expression is equivalent to (3x^2)(4x^5)?',
 choices:['7x^7','12x^10','7x^10','12x^7'],answer:3,
 expl:'Multiply the coefficients and add the exponents: 3 times 4 is 12, and x^2 times x^5 is x^7.',
 wrong:'Choice B multiplies the exponents. Exponents add when powers of the same base are multiplied and multiply only when a power is raised to another power.'},
{id:'SM032',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:5,
 stem:'The function g is defined by g(x) = 2(x - 1)^2 - 8. What is the sum of the values of x for which g(x) = 0?',
 choices:['-2','2','4','6'],answer:1,
 expl:'Set 2(x - 1)^2 - 8 = 0, so (x - 1)^2 = 4 and x - 1 = 2 or -2. The solutions are 3 and -1, and their sum is 2.',
 wrong:'Choice C is the larger solution alone. Taking a square root always produces both a positive and a negative branch.'},
{id:'SM033',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:4,
 stem:'A population of 400 bacteria doubles every 6 hours. Which function gives the population P after t hours?',
 choices:['P = 400 + 2t','P = 400(2)^(t/6)','P = 400(2)^(6t)','P = 400(6)^(t/2)'],answer:1,
 expl:'Doubling makes the base 2, and one doubling happens per 6 hours, so the exponent counts doublings as t/6. At t = 6 the model gives 400 times 2, which is 800.',
 wrong:'Choice C multiplies rather than divides by the doubling time, so it predicts 400 times 2^36 after six hours. Test any model at one known time before trusting it.'},
{id:'SM034',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:5,
 stem:'If (x + y)^2 = 49 and xy = 10, what is the value of x^2 + y^2?',
 choices:['19','29','39','49'],answer:1,
 expl:'Expanding gives x^2 + 2xy + y^2 = 49. Substituting xy = 10 gives x^2 + y^2 + 20 = 49, so x^2 + y^2 = 29.',
 wrong:'Choice D treats (x + y)^2 as x^2 + y^2 and ignores the middle term. The cross term 2xy is exactly what the second equation was given for.'},
{id:'SM035',section:'M',type:'MC',sub:'Nonlinear equations in one variable',skill:'m_adv',diff:3,
 stem:'If the square root of (x + 5) equals 4, what is the value of x?',
 choices:['3','9','11','16'],answer:2,
 expl:'Square both sides: x + 5 = 16, so x = 11. Checking, the square root of 16 is 4.',
 wrong:'Choice D is the value of x + 5, not x. Choice A comes from subtracting 5 before squaring; undo the square root first.'},
{id:'SM036',section:'M',type:'SPR',answerType:'spr',sub:'Nonlinear functions',skill:'m_adv',diff:4,
 stem:'The function f is defined by f(x) = 3x^2 - 2x + 4. What is the value of f(-2)?',
 choices:[],answer:'20',
 expl:'Substitute carefully: 3(-2)^2 = 12, -2(-2) = 4, and the constant is 4, so f(-2) = 12 + 4 + 4 = 20.',
 wrong:'Writing 3(-2)^2 as -12 squares only the 2 and not the sign. The square of a negative input is positive; the coefficient is applied after squaring.'},
{id:'SM037',section:'M',type:'MC',sub:'Nonlinear functions',skill:'m_adv',diff:4,
 stem:'The graph of y = x^2 - 5x + 6 crosses the x-axis at two points. What is the product of the x-coordinates of those points?',
 choices:['-6','1','5','6'],answer:3,
 expl:'Setting y = 0 and factoring gives (x - 2)(x - 3) = 0, so the crossings are at x = 2 and x = 3 and the product is 6.',
 wrong:'Choice C is the sum of the roots. For x^2 + bx + c the sum is -b and the product is c, which is a useful check but easy to swap.'},
{id:'SM038',section:'M',type:'MC',sub:'Equivalent expressions',skill:'m_adv',diff:5,
 stem:'For x not equal to 3, which expression is equivalent to (2x + 1)/(x - 3) - 1?',
 choices:['(x + 4)/(x - 3)','(x - 2)/(x - 3)','(3x - 2)/(x - 3)','(x + 4)/(x + 3)'],answer:0,
 expl:'Write 1 as (x - 3)/(x - 3), then subtract numerators: (2x + 1 - x + 3)/(x - 3) = (x + 4)/(x - 3).',
 wrong:'Choice B subtracts x - 3 without distributing the minus sign across both terms, losing the +3. Put the whole numerator in parentheses before subtracting.'}
];
