// bank_quant5.js - Original GMAT Focus Quant items Q241-Q260 for the Start From Nowhere trainer
const BANK_QUANT5 = [
  {
    id: 'Q241',
    section: 'Q',
    type: 'PS',
    domain: 'arithmetic',
    context: 'real',
    skill: 'q_rrp',
    diff: 2,
    stem: 'A traveler exchanged 300 US dollars for euros at a rate of 1 dollar = 0.9 euros. She spent 216 euros, then exchanged all of her remaining euros back into dollars at a rate of 1 euro = 1.1 dollars.\n\nHow many dollars did she receive in the final exchange?',
    choices: ['48.60', '54.00', '59.40', '66.00', '75.60'],
    answer: 2,
    expl: 'She received 300 x 0.9 = 270 euros and had 270 - 216 = 54 euros left after spending. Converting back gives 54 x 1.1 = 59.40 dollars.',
    wrong: '54.00 forgets to convert the leftover euros back into dollars; 48.60 applies the 0.9 rate in the wrong direction on the return exchange.'
  },
  {
    id: 'Q242',
    section: 'Q',
    type: 'PS',
    domain: 'arithmetic',
    context: 'real',
    skill: 'q_rrp',
    diff: 3,
    stem: 'A marathoner ran the first 16 miles of a 26 mile course at an average pace of 10 minutes per mile.\n\nWhat average pace, in minutes per mile, must she maintain over the final 10 miles in order to average 9 minutes per mile for the entire course?',
    choices: ['7.0', '7.4', '7.5', '8.0', '8.5'],
    answer: 1,
    expl: 'The whole course must take 26 x 9 = 234 minutes, and the first 16 miles used 16 x 10 = 160 minutes. That leaves 74 minutes for the last 10 miles, or 74 / 10 = 7.4 minutes per mile.',
    wrong: '8.0 comes from averaging 10 and the unknown pace equally, ignoring that the two segments cover different distances; 7.0 overcorrects in the same spirit.'
  },
  {
    id: 'Q243',
    section: 'Q',
    type: 'PS',
    domain: 'arithmetic',
    context: 'real',
    skill: 'q_rrp',
    diff: 3,
    stem: 'Working alone at its constant rate, robot P can clear a warehouse order backlog in 9 hours, and robot Q can clear the same backlog in 12 hours. The two robots work together for 3 hours, and then robot P is taken offline while robot Q finishes the job alone.\n\nHow many hours in total, from start to finish, does it take to clear the backlog?',
    choices: ['5', '6', '7.5', '8', '9'],
    answer: 3,
    expl: 'The combined rate is 1/9 + 1/12 = 7/36 of the backlog per hour, so 3 hours together complete 21/36 of the job. The remaining 15/36 = 5/12 takes robot Q alone (5/12) / (1/12) = 5 hours, for a total of 3 + 5 = 8 hours.',
    wrong: '5 counts only the hours robot Q works alone at the end, not the total time; 9 is robot P\'s solo time for the whole job, which is irrelevant here.'
  },
  {
    id: 'Q244',
    section: 'Q',
    type: 'PS',
    domain: 'arithmetic',
    context: 'real',
    skill: 'q_rrp',
    diff: 4,
    stem: 'The ratio of fiction titles to nonfiction titles in a publisher\'s catalog was 7 to 4. After the publisher added 5 new fiction titles and 6 new nonfiction titles, the ratio of fiction to nonfiction became 3 to 2.\n\nHow many titles were in the catalog originally?',
    choices: ['28', '33', '44', '55', '66'],
    answer: 2,
    expl: 'Let the original counts be 7k and 4k, so (7k + 5) / (4k + 6) = 3/2. Cross multiplying gives 14k + 10 = 12k + 18, so k = 4, and the original total is 7(4) + 4(4) = 44. As a check, 33 to 22 is indeed 3 to 2.',
    wrong: '28 is only the original number of fiction titles; 55 is the total after the additions rather than before.'
  },
  {
    id: 'Q245',
    section: 'Q',
    type: 'PS',
    domain: 'arithmetic',
    context: 'real',
    skill: 'q_rrp',
    diff: 5,
    stem: 'Operating at 25 percent below its full speed, a printing press needs 2 hours more to complete a certain print run than it needs at full speed. A second press, working alone at its own constant speed, completes the same run in 12 hours.\n\nWorking together, with the first press at full speed, how many hours do the two presses need to complete the run?',
    choices: ['3.6', '4', '4.5', '4.8', '6'],
    answer: 1,
    expl: 'At 75 percent of full speed the time becomes 4/3 of the full speed time T, so (4/3)T = T + 2 gives T = 6 hours. Together the rates are 1/6 + 1/12 = 1/4 of the run per hour, so the job takes 4 hours. The key shortcut is that cutting speed by 1/4 multiplies time by 4/3, not by 5/4.',
    wrong: '4.8 comes from assuming a 25 percent speed cut raises the time by 25 percent, which gives 8 hours instead of 6 for the first press; 6 is the first press working entirely alone.'
  },
  {
    id: 'Q246',
    section: 'Q',
    type: 'PS',
    domain: 'algebra',
    context: 'pure',
    skill: 'q_alg',
    diff: 1,
    stem: 'If 4(w - 5) = 2w + 6, what is the value of w?',
    choices: ['4', '7', '11', '13', '26'],
    answer: 3,
    expl: 'Expanding gives 4w - 20 = 2w + 6. Subtracting 2w and adding 20 to both sides gives 2w = 26, so w = 13.',
    wrong: '7 comes from a sign slip that produces 2w = 14; 26 stops at the value of 2w without dividing by 2.'
  },
  {
    id: 'Q247',
    section: 'Q',
    type: 'PS',
    domain: 'algebra',
    context: 'real',
    skill: 'q_alg',
    diff: 3,
    stem: 'A streaming service offers a basic plan for 8 dollars per month and a premium plan for 14 dollars per month, and every subscriber has exactly one plan. In April, its 500 subscribers paid a total of 5,200 dollars.\n\nHow many of the subscribers had the premium plan?',
    choices: ['150', '200', '250', '300', '350'],
    answer: 1,
    expl: 'If all 500 subscribers had the basic plan, revenue would be 500 x 8 = 4,000 dollars. The extra 1,200 dollars comes from premium subscribers at 14 - 8 = 6 extra dollars each, so there are 1,200 / 6 = 200 premium subscribers. Check: 300 x 8 + 200 x 14 = 2,400 + 2,800 = 5,200.',
    wrong: '300 is the number of basic subscribers, the wrong quantity; 250 assumes the two plans split evenly.'
  },
  {
    id: 'Q248',
    section: 'Q',
    type: 'PS',
    domain: 'algebra',
    context: 'pure',
    skill: 'q_alg',
    diff: 3,
    stem: 'If 3^(2n + 1) = 27^(n - 1), what is the value of n?',
    choices: ['1', '2', '3', '4', '5'],
    answer: 3,
    expl: 'Since 27 = 3^3, the right side is 3^(3n - 3). Setting the exponents equal gives 2n + 1 = 3n - 3, so n = 4. Check: 3^9 = 27^3.',
    wrong: '2 comes from distributing the exponent incorrectly as 3n - 1 instead of 3n - 3.'
  },
  {
    id: 'Q249',
    section: 'Q',
    type: 'PS',
    domain: 'algebra',
    context: 'pure',
    skill: 'q_alg',
    diff: 4,
    stem: 'If x + y = 7 and x^2 + y^2 = 29, what is the value of (x - y)^2?',
    choices: ['3', '9', '15', '20', '39'],
    answer: 1,
    expl: 'Squaring the first equation gives x^2 + 2xy + y^2 = 49, so 2xy = 49 - 29 = 20. Then (x - y)^2 = x^2 + y^2 - 2xy = 29 - 20 = 9. The shortcut is (x - y)^2 = 2(x^2 + y^2) - (x + y)^2 = 58 - 49 = 9.',
    wrong: '3 is the value of |x - y| rather than its square; 20 is the intermediate value 2xy.'
  },
  {
    id: 'Q250',
    section: 'Q',
    type: 'PS',
    domain: 'algebra',
    context: 'pure',
    skill: 'q_alg',
    diff: 5,
    stem: 'For all numbers a and b, the operation # is defined by a # b = ab - a - b.\n\nIf x # (x # 2) = 7, what is the sum of all possible values of x?',
    choices: ['-4', '-1', '4', '5', '6'],
    answer: 2,
    expl: 'First, x # 2 = 2x - x - 2 = x - 2. Then x # (x - 2) = x(x - 2) - x - (x - 2) = x^2 - 4x + 2, and setting this equal to 7 gives x^2 - 4x - 5 = 0, so (x - 5)(x + 1) = 0 and x = 5 or x = -1. By Vieta\'s formula the sum of the roots is 4 without solving at all.',
    wrong: '5 and -1 are the individual roots rather than their sum; -4 flips the sign in the sum of roots formula.'
  },
  {
    id: 'Q251',
    section: 'Q',
    type: 'PS',
    domain: 'number properties',
    context: 'pure',
    skill: 'q_vof',
    diff: 2,
    stem: 'What is the greatest integer n such that 2^n is a factor of 96?',
    choices: ['1', '2', '3', '4', '5'],
    answer: 4,
    expl: 'Factoring gives 96 = 32 x 3 = 2^5 x 3, so the largest power of 2 dividing 96 is 2^5. Therefore n = 5.',
    wrong: '4 comes from stopping the repeated division by 2 one step too early; 3 stops even earlier at 96 = 8 x 12 without factoring the 12.'
  },
  {
    id: 'Q252',
    section: 'Q',
    type: 'PS',
    domain: 'number properties',
    context: 'pure',
    skill: 'q_vof',
    diff: 3,
    stem: 'When the positive integer n is divided by 9, the remainder is 5. What is the remainder when 4n + 7 is divided by 9?',
    choices: ['0', '2', '3', '5', '7'],
    answer: 0,
    expl: 'Replace n by its remainder: 4 x 5 + 7 = 27, and 27 is a multiple of 9, so the remainder is 0. Testing n = 14 confirms it: 4 x 14 + 7 = 63 = 9 x 7 with remainder 0.',
    wrong: '5 assumes the remainder carries through the operations unchanged; 7 accounts only for the added 7 and ignores the effect of multiplying by 4.'
  },
  {
    id: 'Q253',
    section: 'Q',
    type: 'PS',
    domain: 'number properties',
    context: 'real',
    skill: 'q_vof',
    diff: 3,
    stem: 'At a school, a bell for regular classes rings every 40 minutes and a separate bell for lab sessions rings every 45 minutes. Both bells ring together at 9:00 am.\n\nAt what time will the two bells next ring together?',
    choices: ['10:30 am', '12:00 pm', '1:00 pm', '3:00 pm', '6:00 pm'],
    answer: 3,
    expl: 'The bells coincide every LCM(40, 45) minutes. Since 40 = 2^3 x 5 and 45 = 3^2 x 5, the LCM is 2^3 x 3^2 x 5 = 360 minutes, which is 6 hours, so they next coincide at 3:00 pm.',
    wrong: '10:30 am uses 90 minutes, which is not a multiple of 40; 12:00 pm uses 180 minutes, which 40 does not divide evenly either.'
  },
  {
    id: 'Q254',
    section: 'Q',
    type: 'PS',
    domain: 'number properties',
    context: 'pure',
    skill: 'q_vof',
    diff: 4,
    stem: 'If x and y are positive integers such that 3x + 5y = 60, how many different values of x are possible?',
    choices: ['3', '4', '5', '6', '11'],
    answer: 0,
    expl: 'Since 3x = 60 - 5y and both 60 and 5y must leave a multiple of 3, y must be a multiple of 3, and y < 12 to keep x positive. So y can be 3, 6, or 9, giving x = 15, 10, or 5, which is 3 possible values.',
    wrong: '4 wrongly counts x = 20, which forces y = 0 and violates the positive requirement; 11 counts every y from 1 to 11 while ignoring the divisibility condition.'
  },
  {
    id: 'Q255',
    section: 'Q',
    type: 'PS',
    domain: 'number properties',
    context: 'pure',
    skill: 'q_vof',
    diff: 5,
    stem: 'If -1 < x < 0, which of the following has the least value?',
    choices: ['x', 'x^2', 'x^3', '1/x', '1/x^2'],
    answer: 3,
    expl: 'Test x = -1/2: then x = -0.5, x^2 = 0.25, x^3 = -0.125, 1/x = -2, and 1/x^2 = 4. Taking the reciprocal of a negative fraction between -1 and 0 pushes it below -1, so 1/x is always the least.',
    wrong: 'x^3 is tempting because cubing feels more negative, but cubing a fraction between -1 and 0 actually moves it closer to zero; x itself is more negative than x^3 but still greater than 1/x.'
  },
  {
    id: 'Q256',
    section: 'Q',
    type: 'PS',
    domain: 'counting',
    context: 'real',
    skill: 'q_csp',
    diff: 2,
    stem: 'Two fair six sided dice are rolled. What is the probability that the sum of the two numbers rolled is 9?',
    choices: ['1/18', '1/12', '1/9', '5/36', '1/6'],
    answer: 2,
    expl: 'The ordered rolls that sum to 9 are (3,6), (4,5), (5,4), and (6,3), which is 4 outcomes out of 36. So the probability is 4/36 = 1/9.',
    wrong: '1/12 counts only three of the four ordered pairs; 1/18 counts the two unordered combinations without doubling them; 5/36 is the probability of a sum of 8.'
  },
  {
    id: 'Q257',
    section: 'Q',
    type: 'PS',
    domain: 'statistics',
    context: 'real',
    skill: 'q_csp',
    diff: 3,
    stem: 'The average of the daily high temperatures recorded in a city over 5 days was 70 degrees. After the high temperature for a sixth day was recorded, the average for all 6 days was 72 degrees.\n\nWhat was the high temperature on the sixth day?',
    choices: ['72', '74', '76', '80', '82'],
    answer: 4,
    expl: 'The six day total is 6 x 72 = 432 and the five day total was 5 x 70 = 350, so the sixth day was 432 - 350 = 82 degrees. Shortcut: the new value must equal the new average plus 2 degrees for each of the 5 earlier days, 72 + 10 = 82.',
    wrong: '74 adds the 2 degree rise to the new average only once instead of covering all five earlier days; 72 is just the new average itself.'
  },
  {
    id: 'Q258',
    section: 'Q',
    type: 'PS',
    domain: 'counting',
    context: 'real',
    skill: 'q_csp',
    diff: 3,
    stem: 'A parking permit code consists of 2 letters followed by 2 digits. The two letters must be different, the digits may repeat, and the first digit cannot be 0.\n\nHow many different permit codes are possible?',
    choices: ['52,650', '58,500', '60,840', '65,000', '67,600'],
    answer: 1,
    expl: 'The letters can be chosen in 26 x 25 = 650 ways, the first digit in 9 ways, and the second digit in 10 ways. Multiplying gives 650 x 90 = 58,500 codes.',
    wrong: '60,840 lets the letters repeat; 65,000 ignores the restriction on the first digit; 52,650 wrongly bars 0 from both digit positions.'
  },
  {
    id: 'Q259',
    section: 'Q',
    type: 'PS',
    domain: 'counting',
    context: 'real',
    skill: 'q_csp',
    diff: 4,
    stem: 'Two cards are drawn at random, without replacement, from a standard deck of 52 cards, of which 13 belong to each of 4 suits.\n\nWhat is the probability that the two cards drawn are of the same suit?',
    choices: ['1/17', '3/17', '4/17', '1/4', '13/51'],
    answer: 2,
    expl: 'Whatever the first card is, 12 of the remaining 51 cards share its suit, so the probability is 12/51 = 4/17. Conditioning on the first card avoids adding four separate suit cases.',
    wrong: '1/4 treats the second draw as if the first card were replaced; 1/17 is the probability that both cards come from one particular named suit, such as both hearts.'
  },
  {
    id: 'Q260',
    section: 'Q',
    type: 'PS',
    domain: 'statistics',
    context: 'pure',
    skill: 'q_csp',
    diff: 5,
    stem: 'A data set consists of the five numbers 4, 6, x, 10, and 14, where x is an integer.\n\nIf the median of the set equals the mean of the set, what is the sum of all possible values of x?',
    choices: ['-4', '8', '12', '16', '20'],
    answer: 2,
    expl: 'The mean is (34 + x)/5, and the median depends on where x falls. If x <= 6 the median is 6, so 34 + x = 30 and x = -4, which fits. If 6 <= x <= 10 the median is x, so 34 + x = 5x gives x = 8.5, rejected because x is an integer. If x >= 10 the median is 10, so 34 + x = 50 and x = 16, which fits, making the sum -4 + 16 = 12.',
    wrong: '16 and -4 each capture only one of the two valid cases; 20 comes from also accepting the middle case even though it yields the non integer 8.5.'
  }
];
