// bank_gre_verbal.js - Original GRE Verbal Reasoning items GV001-GV042.
// Three official question types: Reading Comprehension, Text Completion, Sentence
// Equivalence. Text Completion with one blank carries five choices; Sentence Equivalence
// carries six and asks for exactly two that produce sentences alike in meaning, which is
// why those items use answerType 'se' and an answer array.
const BANK_GRE_VERBAL = [
// ---------- Text Completion ----------
{id:'GV001',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:1,
 stem:'Although the committee had been assembled to review the proposal impartially, its report was so uniformly favorable that critics dismissed it as ______.',
 choices:['partisan','tentative','belated','technical','exhaustive'],answer:0,
 expl:'The sentence sets up a contrast with "impartially" and reports a uniformly favorable outcome, so critics would accuse the report of taking a side. Partisan means biased toward one party.',
 wrong:'Exhaustive and technical describe thoroughness or register, not bias. Tentative contradicts "uniformly favorable." Belated addresses timing, which the sentence never raises.'},
{id:'GV002',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:2,
 stem:'Far from being the solitary genius of legend, the inventor relied on a workshop of assistants whose contributions the historical record has largely ______.',
 choices:['preserved','effaced','contested','anticipated','magnified'],answer:1,
 expl:'The clause corrects a legend of solitary genius by noting assistants existed, and the record has hidden them. Effaced means erased or rubbed out.',
 wrong:'Magnified and preserved reverse the meaning. Contested implies a dispute the sentence does not describe. Anticipated is about time, not erasure.'},
{id:'GV003',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:2,
 stem:'The novel resists summary not because its plot is complicated but because its meaning is so thoroughly ______ its digressions, which a synopsis would discard.',
 choices:['borrowed from','obscured by','lodged in','opposed to','independent of'],answer:2,
 expl:'The meaning lives inside the digressions, so a summary that discards them loses it. Lodged in captures that the meaning is embedded there.',
 wrong:'Obscured by would mean the digressions hide the meaning, but then discarding them would help. Independent of and opposed to reverse the logic.'},
{id:'GV004',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:3,
 stem:'Her prose style is deceptively plain: sentences that appear ______ on first reading reveal, on a second, a carefully engineered rhythm.',
 choices:['archaic','deliberate','ornate','artless','turgid'],answer:3,
 expl:'Deceptively plain sets up an appearance that proves false. The sentences look unstudied at first but turn out engineered, so the blank needs a word meaning without artifice. Artless fits.',
 wrong:'Deliberate is what the second reading reveals, not the first impression. Ornate and turgid contradict "plain."'},
{id:'GV005',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:3,
 stem:'The field has been slow to adopt the method, less from any principled objection than from simple ______: the older technique works, and retraining is expensive.',
 choices:['hostility','rigor','curiosity','skepticism','inertia'],answer:4,
 expl:'The colon explains the cause: the old way works and change costs money. That is inertia, a tendency to stay as things are, explicitly distinguished from a principled objection.',
 wrong:'Skepticism and hostility are the principled or emotional objections the sentence rules out. Rigor and curiosity would not slow adoption.'},
{id:'GV006',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:4,
 stem:'What makes the archive valuable is precisely what makes it difficult: its compiler collected ______, preserving trivia alongside treaties with no indication of which he thought mattered.',
 choices:['indiscriminately','reluctantly','covertly','methodically','selectively'],answer:0,
 expl:'Preserving trivia alongside treaties with no ranking is collecting without discrimination, which is both the value (nothing lost) and the difficulty (no guidance).',
 wrong:'Selectively and methodically are the opposite of what the second half describes. Reluctantly and covertly speak to motive and secrecy, not to criteria.'},
{id:'GV007',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:4,
 stem:'The treaty was hailed as a breakthrough, though its terms were sufficiently ______ that both governments could return home claiming to have won.',
 choices:['stringent','equivocal','onerous','transparent','novel'],answer:1,
 expl:'Terms that let both sides claim victory must be open to more than one reading. Equivocal means ambiguous or capable of two interpretations.',
 wrong:'Transparent would make the outcome unmistakable. Stringent and onerous describe severity, which does not explain competing claims of victory.'},
{id:'GV008',section:'V',type:'TC',sub:'Text Completion, one blank',skill:'gre_tc',diff:5,
 stem:'Critics who fault the study for its small sample miss the point: it was designed not to establish a general result but to ______ one, by producing a single case the prevailing model cannot accommodate.',
 choices:['corroborate','generalize','unsettle','replicate','quantify'],answer:2,
 expl:'A single case that the prevailing model cannot accommodate works as a counterexample, which disturbs an accepted result rather than proving one. Unsettle fits, and it contrasts with "establish."',
 wrong:'Corroborate and replicate would support the model. Generalize contradicts "not to establish a general result."'},
// ---------- Sentence Equivalence: six choices, select exactly two ----------
{id:'GV009',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:1,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nDespite its reputation for difficulty, the course turned out to be surprisingly ______, requiring steady effort rather than brilliance.',
 choices:['manageable','abstruse','tractable','punishing','esoteric','inventive'],answer:[0,2],
 expl:'The second clause explains that steady effort suffices, so the blank means capable of being handled. Manageable and tractable are the pair that produce the same sentence.',
 wrong:'Abstruse and esoteric are a synonym pair, but they mean hard to understand, which contradicts the sentence. A matching pair is not enough; it has to fit the meaning.'},
{id:'GV010',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:2,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nThe biography is admiring without being ______: it records its subject\'s failures as carefully as his triumphs.',
 choices:['hagiographic','exhaustive','fawning','accurate','tedious','partisan'],answer:[0,2],
 expl:'The colon explains that failures are recorded too, so the blank names uncritical praise. Hagiographic and fawning both mean excessively adoring.',
 wrong:'Partisan is close but means taking a side generally, and it has no synonym among the choices. Exhaustive and tedious form no meaningful pair here.'},
{id:'GV011',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:3,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nHer argument is ______ at its center but ornamented at the edges, so readers who skim the elaborate opening often miss how simple the claim actually is.',
 choices:['spare','convoluted','austere','fanciful','rigorous','derivative'],answer:[0,2],
 expl:'The contrast with "ornamented" and the note that the claim is simple both point to plainness. Spare and austere both mean stripped of decoration.',
 wrong:'Rigorous is a compliment but does not pair with anything and does not contrast with ornamented. Convoluted and fanciful reverse the meaning.'},
{id:'GV012',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:3,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nThe policy was ______ from the start: it promised savings that its own cost projections showed to be impossible.',
 choices:['ambitious','untenable','contentious','indefensible','expensive','provisional'],answer:[1,3],
 expl:'Its own projections contradicted its promise, so the position could not be held. Untenable and indefensible both mean impossible to sustain under scrutiny.',
 wrong:'Contentious means disputed, which is weaker and has no partner. Ambitious and expensive miss the self-contradiction the colon describes.'},
{id:'GV013',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:4,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nFar from being ______, the reforms were the product of decades of quiet negotiation, which is exactly why they proved durable.',
 choices:['precipitate','deliberate','impromptu','contested','incremental','popular'],answer:[0,2],
 expl:'"Far from being" reverses the blank against decades of quiet negotiation, so the blank means sudden and unplanned. Precipitate and impromptu both carry that sense.',
 wrong:'Deliberate and incremental describe what the reforms actually were, so they fail the reversal. Contested and popular have no partner.'},
{id:'GV014',section:'V',type:'SE',sub:'Sentence Equivalence',skill:'gre_se',diff:5,answerType:'se',
 stem:'Select the TWO answer choices that, when used to complete the sentence, fit the meaning as a whole and produce completed sentences alike in meaning.\n\nThe committee\'s praise was so ______ that it read less as endorsement than as a warning to look elsewhere.',
 choices:['tepid','effusive','perfunctory','scathing','unanimous','belated'],answer:[0,2],
 expl:'Praise that functions as a warning must be weak and going through the motions. Tepid and perfunctory both describe that lack of real enthusiasm.',
 wrong:'Effusive is the opposite. Scathing is open attack rather than faint praise, which is what the sentence describes.'},
// ---------- Reading Comprehension ----------
{id:'GV015',section:'V',type:'RC',sub:'Main idea',skill:'gre_rc',diff:2,
 passage:'For a century, the standard account held that the city declined because its harbor silted up, cutting it off from trade. Recent sediment cores complicate that story. They show the silting was gradual and largely complete two centuries before the population fell, and that shipping volumes actually rose during the intervening period as merchants shifted to shallower vessels. The decline coincides instead with a documented collapse in the inland grain supply on which the city depended for both food and export revenue.',
 stem:'The primary purpose of the passage is to',
 choices:['describe the technical difficulties of dating harbor sediment','defend merchants against the charge of abandoning the city','propose that sediment cores are the most reliable evidence for urban history','revise a long-standing explanation in light of new evidence','argue that the city never declined as sharply as historians claim'],answer:3,
 expl:'The passage states the standard account, says new cores complicate it, shows why the timing fails, and offers a different cause. That is a revision of an accepted explanation.',
 wrong:'The cores are evidence, not the subject. The passage accepts that a decline happened and never discusses dating difficulties.'},
{id:'GV016',section:'V',type:'RC',sub:'Inference',skill:'gre_rc',diff:3,
 passage:'For a century, the standard account held that the city declined because its harbor silted up, cutting it off from trade. Recent sediment cores complicate that story. They show the silting was gradual and largely complete two centuries before the population fell, and that shipping volumes actually rose during the intervening period as merchants shifted to shallower vessels. The decline coincides instead with a documented collapse in the inland grain supply on which the city depended for both food and export revenue.',
 stem:'The passage suggests that the shift to shallower vessels',
 choices:['was the principal cause of the harbor silting','had been proposed a century earlier and rejected','was prompted by the collapse of the inland grain supply','proved more expensive than the merchants had anticipated','allowed trade to continue despite the condition of the harbor'],answer:4,
 expl:'Shipping volumes rose during the silted period because merchants switched to shallower vessels, so the switch let trade carry on despite the harbor.',
 wrong:'The grain collapse came later and is offered as the cause of decline, not of the vessel shift. Nothing addresses cost or a rejected earlier proposal.'},
{id:'GV017',section:'V',type:'RC',sub:'Function of a sentence',skill:'gre_rc',diff:3,
 passage:'For a century, the standard account held that the city declined because its harbor silted up, cutting it off from trade. Recent sediment cores complicate that story. They show the silting was gradual and largely complete two centuries before the population fell, and that shipping volumes actually rose during the intervening period as merchants shifted to shallower vessels. The decline coincides instead with a documented collapse in the inland grain supply on which the city depended for both food and export revenue.',
 stem:'The reference to shipping volumes serves primarily to',
 choices:['undercut the assumption that silting cut the city off from trade','quantify the scale of the eventual population decline','identify the merchants as the cause of the grain collapse','show that written records agree with the sediment evidence','establish that the harbor remained navigable for large vessels'],answer:0,
 expl:'The standard account depends on silting severing trade. Rising volumes during the silted period show trade was not severed, which is what breaks the old explanation.',
 wrong:'The passage says merchants moved to shallower vessels, so large ones were not still passing. Volumes measure trade, not population.'},
{id:'GV018',section:'V',type:'RC',sub:'Strengthen and weaken',skill:'gre_rc',diff:4,
 passage:'For a century, the standard account held that the city declined because its harbor silted up, cutting it off from trade. Recent sediment cores complicate that story. They show the silting was gradual and largely complete two centuries before the population fell, and that shipping volumes actually rose during the intervening period as merchants shifted to shallower vessels. The decline coincides instead with a documented collapse in the inland grain supply on which the city depended for both food and export revenue.',
 stem:'Which of the following, if true, would most weaken the explanation the passage favors?',
 choices:['Several nearby cities without harbors declined during the same period','A second city equally dependent on the same inland grain supply grew steadily through the collapse','Sediment cores from other harbors show similar patterns of gradual silting','The surviving records of shipping volumes are incomplete for the earliest decades','Grain prices in the region rose sharply during the century before the decline'],answer:1,
 expl:'The favored explanation is that the grain collapse caused the decline. A city equally dependent on the same supply that grew through the collapse shows the collapse was not sufficient to cause decline, which directly undercuts it.',
 wrong:'Incomplete early records and silting elsewhere do not bear on the grain claim. Nearby cities without harbors declining would if anything support a non-harbor cause.'},
{id:'GV019',section:'V',type:'RC',sub:'Main idea',skill:'gre_rc',diff:2,
 passage:'Conservation programs have long assumed that protecting a species means protecting its habitat, and in most cases this holds. Migratory species complicate the assumption. A bird that breeds in one country, refuels in a second and winters in a third is protected only as well as the weakest link in that chain, and the weakest link is often the refueling site, which is small, unglamorous and rarely the subject of a campaign. Protecting the breeding ground alone can produce healthy nesting counts and a population that still falls.',
 stem:'The passage is primarily concerned with',
 choices:['explaining why refueling sites attract little public attention','arguing that habitat protection is generally ineffective','identifying a limitation of a widely held conservation principle','comparing the costs of protecting different kinds of habitat','urging that migratory species be given priority over resident ones'],answer:2,
 expl:'The passage grants that the principle usually holds, then shows a class of cases where it fails. That is identifying a limitation rather than rejecting the principle.',
 wrong:'It explicitly says the assumption holds in most cases, so it does not argue habitat protection is generally ineffective. Cost and priority are never compared.'},
{id:'GV020',section:'V',type:'RC',sub:'Inference',skill:'gre_rc',diff:3,
 passage:'Conservation programs have long assumed that protecting a species means protecting its habitat, and in most cases this holds. Migratory species complicate the assumption. A bird that breeds in one country, refuels in a second and winters in a third is protected only as well as the weakest link in that chain, and the weakest link is often the refueling site, which is small, unglamorous and rarely the subject of a campaign. Protecting the breeding ground alone can produce healthy nesting counts and a population that still falls.',
 stem:'The passage implies that nesting counts',
 choices:['have been falling across most migratory species','overstate the importance of wintering grounds','are the most accurate available measure of population health','can remain high even as the overall population declines','are rarely collected at refueling sites'],answer:3,
 expl:'The final sentence says protecting the breeding ground alone can produce healthy nesting counts and a population that still falls, which is exactly the inference.',
 wrong:'The passage treats nesting counts as potentially misleading rather than most accurate, and it never says counts are falling across species.'},
];
