// bank_quant3.js : original GMAT Focus Quant practice items Q201 to Q220 for the Start From Nowhere trainer
const BANK_QUANT3 = [
{id:'Q201',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:2,
stem:'A retailer buys a jacket at a wholesale cost of $60 and marks it up by 40 percent. During a sale, the marked price is discounted by 25 percent. What is the sale price of the jacket?',
choices:['$60','$63','$66','$69','$84'],answer:1,
expl:'The marked price is 60 x 1.4 = 84 dollars, and the sale price is 84 x 0.75 = 63 dollars. Successive percent changes multiply, so a quick check is 60 x 1.4 x 0.75 = 60 x 1.05 = 63.',
wrong:'$69 adds the percents (40 - 25 = 15) and takes 60 x 1.15 instead of applying the changes in sequence. $84 stops after the markup and forgets the discount.'},
{id:'Q202',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
stem:'Pump A can fill an empty tank in 6 hours and pump B can fill the same tank in 12 hours. An open drain can empty the full tank in 8 hours. If both pumps run while the drain is open, how many hours will it take to fill the empty tank?',
choices:['4','6','8','10','12'],answer:2,
expl:'Add the fill rates and subtract the drain rate: 1/6 + 1/12 - 1/8 = 4/24 + 2/24 - 3/24 = 1/8 of the tank per hour. At 1/8 tank per hour, the tank fills in 8 hours.',
wrong:'4 comes from ignoring the drain entirely (1/6 + 1/12 = 1/4). Choices built by averaging the given times confuse times with rates; only rates can be added.'},
{id:'Q203',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:3,
stem:'A chemist has 30 liters of a solution that is 10 percent acid. How many liters of pure acid must be added so that the resulting solution is 25 percent acid?',
choices:['4.5','5','6','7.5','9'],answer:2,
expl:'The solution starts with 3 liters of acid. If x liters are added, (3 + x)/(30 + x) = 1/4, so 12 + 4x = 30 + x and x = 6. Back-solving is also fast: adding 6 gives 9 liters of acid in 36 liters total, exactly 25 percent.',
wrong:'4.5 takes 25 percent of the original 30 liters and subtracts the 3 liters already present, ignoring that the added acid also increases the total volume.'},
{id:'Q204',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:4,
stem:'Ana drives 90 miles from her office to a client site at a constant speed of 45 miles per hour. At what constant speed, in miles per hour, must she make the return trip along the same route so that her average speed for the entire round trip is 60 miles per hour?',
choices:['65','72','75','80','90'],answer:4,
expl:'The round trip is 180 miles, so an average of 60 miles per hour requires 180/60 = 3 hours in total. The outbound leg takes 90/45 = 2 hours, leaving 1 hour for the 90 mile return, so she must drive 90 miles per hour.',
wrong:'75 averages the two speeds, but average speed is total distance over total time, not the mean of the leg speeds. Because the slow leg takes longer, the return speed must be much higher than 75.'},
{id:'Q205',section:'Q',type:'PS',domain:'arithmetic',context:'real',skill:'q_rrp',diff:5,
stem:'A radiator holds 20 liters of a coolant mixture that is 30 percent antifreeze. How many liters of the mixture must be drained and replaced with pure antifreeze so that the radiator holds a mixture that is 58 percent antifreeze?',
choices:['5.6','6.4','8','9.6','11.6'],answer:2,
expl:'Draining x liters removes 0.3x liters of antifreeze and the replacement adds x liters, so the final amount of antifreeze is 6 + 0.7x. Setting 6 + 0.7x = 0.58 x 20 = 11.6 gives 0.7x = 5.6, so x = 8. Back-solving also works: draining 8 leaves 3.6 liters of antifreeze in 12 liters, and adding 8 pure liters gives 11.6 out of 20.',
wrong:'5.6 is just the extra antifreeze needed (11.6 - 6) and forgets that the drained liquid carries antifreeze out with it. 11.6 is the final amount of antifreeze, not the amount replaced.'},
{id:'Q206',section:'Q',type:'PS',domain:'number properties',context:'pure',skill:'q_vof',diff:2,
stem:'What is the units digit of 7^35?',
choices:['0','1','3','7','9'],answer:2,
expl:'Units digits of powers of 7 cycle with period 4: 7, 9, 3, 1. Since 35 = 4 x 8 + 3, 7^35 ends in the third digit of the cycle, which is 3.',
wrong:'9 comes from miscounting the position in the cycle, and 1 assumes 35 is a multiple of 4.'},
{id:'Q207',section:'Q',type:'PS',domain:'number properties',context:'pure',skill:'q_vof',diff:3,
stem:'When the positive integer n is divided by 12, the remainder is 7. What is the remainder when 3n is divided by 12?',
choices:['1','3','7','9','11'],answer:3,
expl:'Pick the smallest case n = 7: then 3n = 21 = 12 + 9, so the remainder is 9. In general 3n = 3(12k + 7) = 36k + 21, and 21 leaves remainder 9 when divided by 12.',
wrong:'7 assumes the remainder is unchanged by multiplication; you must multiply the remainder by 3 and then reduce 21 by another 12.'},
{id:'Q208',section:'Q',type:'PS',domain:'number properties',context:'pure',skill:'q_vof',diff:3,
stem:'How many positive divisors does 360 have?',
choices:['6','16','20','24','30'],answer:3,
expl:'Factor 360 = 2^3 x 3^2 x 5. The number of divisors is the product of each exponent plus 1: 4 x 3 x 2 = 24.',
wrong:'6 multiplies the exponents 3 x 2 x 1 without first adding 1 to each.'},
{id:'Q209',section:'Q',type:'PS',domain:'number properties',context:'pure',skill:'q_vof',diff:4,
stem:'If 3^(2x) x 9 = 27^(x - 1), what is the value of x?',
choices:['-5','1','3','5','7'],answer:3,
expl:'Rewrite everything in base 3: the left side is 3^(2x) x 3^2 = 3^(2x + 2) and the right side is 3^(3x - 3). Equating exponents gives 2x + 2 = 3x - 3, so x = 5.',
wrong:'-5 comes from a sign slip when moving terms across the equation, and 1 comes from dropping one of the constant exponents before equating.'},
{id:'Q210',section:'Q',type:'PS',domain:'number properties',context:'pure',skill:'q_vof',diff:5,
stem:'When the positive integer k is divided by 9, the remainder is 4, and when k is divided by 5, the remainder is 2. What is the second smallest positive integer that satisfies both conditions?',
choices:['22','44','58','67','89'],answer:3,
expl:'List numbers that leave remainder 4 when divided by 9: 4, 13, 22, 31, and check remainders on division by 5. The smallest match is 22, and solutions repeat every 45, the least common multiple of 9 and 5, so the second smallest is 22 + 45 = 67.',
wrong:'22 is the smallest such integer, not the second smallest. 44 doubles 22, but doubling does not preserve the remainders: 44 divided by 9 leaves 8, not 4.'},
{id:'Q211',section:'Q',type:'PS',domain:'algebra',context:'real',skill:'q_alg',diff:2,
stem:'A gym charges a one-time enrollment fee of $25 plus $35 per month of membership. If a member has paid $305 in total, for how many months has she been a member?',
choices:['6','7','8','9','10'],answer:2,
expl:'Subtract the fee first: 305 - 25 = 280, and 280/35 = 8 months. Back-solving confirms it: 25 + 35 x 8 = 305.',
wrong:'9 comes from dividing 305 by 35 and rounding up, which ignores the one-time enrollment fee.'},
{id:'Q212',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
stem:'How many integers x satisfy |2x - 5| < 7?',
choices:['4','5','6','7','8'],answer:2,
expl:'The inequality means -7 < 2x - 5 < 7, so -2 < 2x < 12 and -1 < x < 6. The integers strictly between -1 and 6 are 0, 1, 2, 3, 4, 5, a total of 6.',
wrong:'8 treats the strict inequality as inclusive and counts -1 and 6 as solutions. 5 comes from starting the count at 1 and missing x = 0.'},
{id:'Q213',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:3,
stem:'If f(x) = x^2 - 3x, what is the value of f(f(2))?',
choices:['-2','0','4','10','18'],answer:3,
expl:'Work from the inside out: f(2) = 4 - 6 = -2. Then f(-2) = (-2)^2 - 3(-2) = 4 + 6 = 10.',
wrong:'-2 stops after the inner evaluation, and a sign slip on -3(-2) also lands at 4 - 6 = -2; the outer step must add 6, not subtract it.'},
{id:'Q214',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:4,
stem:'Which of the following describes all values of x for which x^2 < 4x?',
choices:['x < 4','x > 0','0 < x < 4','-4 < x < 0','x > 4'],answer:2,
expl:'Bring everything to one side: x^2 - 4x < 0, so x(x - 4) < 0, which holds exactly when the two factors have opposite signs, that is 0 < x < 4. Testing x = -1 confirms negatives fail, since 1 < -4 is false.',
wrong:'x < 4 comes from dividing both sides by x, which is invalid because x could be zero or negative, and the inequality direction flips for negative x.'},
{id:'Q215',section:'Q',type:'PS',domain:'algebra',context:'pure',skill:'q_alg',diff:5,
stem:'If x is a positive number and x + 1/x = 5, what is the value of x^3 + 1/x^3?',
choices:['100','105','110','115','125'],answer:2,
expl:'Cube the given equation: (x + 1/x)^3 = x^3 + 1/x^3 + 3(x + 1/x). So 125 = x^3 + 1/x^3 + 15, giving x^3 + 1/x^3 = 110. There is no need to solve for x itself.',
wrong:'125 cubes the 5 but forgets the cross terms of the expansion, which contribute 3(x + 1/x) = 15.'},
{id:'Q216',section:'Q',type:'PS',domain:'statistics',context:'real',skill:'q_csp',diff:2,
stem:'Over five trading days, a broker averaged 12 client calls per day. On four of the days she made 9, 11, 14, and 16 calls. How many calls did she make on the fifth day?',
choices:['8','9','10','11','12'],answer:2,
expl:'The five-day total is 5 x 12 = 60 calls, and the four known days sum to 9 + 11 + 14 + 16 = 50, so the fifth day had 60 - 50 = 10 calls.',
wrong:'12 assumes the fifth day simply equals the average; work with the total, not the average itself.'},
{id:'Q217',section:'Q',type:'PS',domain:'counting',context:'real',skill:'q_csp',diff:3,
stem:'A pouch contains 4 red chips and 6 blue chips. If two chips are drawn at random without replacement, what is the probability that both chips are blue?',
choices:['1/5','3/10','1/3','9/25','3/5'],answer:2,
expl:'Multiply along the branch: 6/10 for the first blue chip and 5/9 for the second, giving 30/90 = 1/3.',
wrong:'9/25 squares 6/10, which assumes the first chip is replaced before the second draw.'},
{id:'Q218',section:'Q',type:'PS',domain:'counting',context:'real',skill:'q_csp',diff:3,
stem:'A wealth manager surveys 80 clients. Exactly 45 hold stock funds, 38 hold bond funds, and 12 hold neither type of fund. How many of the clients hold both types?',
choices:['3','12','15','23','27'],answer:2,
expl:'Clients holding at least one type: 80 - 12 = 68. By inclusion and exclusion, both = 45 + 38 - 68 = 15.',
wrong:'3 comes from 45 + 38 - 80, which forgets to remove the 12 clients who hold neither type before applying inclusion and exclusion.'},
{id:'Q219',section:'Q',type:'PS',domain:'counting',context:'real',skill:'q_csp',diff:4,
stem:'A project team of 4 people is to be formed from a group of 6 analysts and 3 managers. If the team must include at least one manager, how many different teams are possible?',
choices:['15','111','120','126','168'],answer:1,
expl:'Count the complement: total teams C(9,4) = 126, and all-analyst teams C(6,4) = 15, so 126 - 15 = 111 teams include at least one manager.',
wrong:'168 picks one of the 3 managers first and then any 3 of the remaining 8 people, which double counts teams with more than one manager. 126 ignores the restriction entirely.'},
{id:'Q220',section:'Q',type:'PS',domain:'counting',context:'pure',skill:'q_csp',diff:5,
stem:'Three fair coins are tossed. Given that at least one coin shows heads, what is the probability that exactly two coins show heads?',
choices:['1/4','3/8','3/7','1/2','2/3'],answer:2,
expl:'Of the 8 equally likely outcomes, the condition removes only TTT, leaving 7 outcomes. Exactly two heads occurs in 3 of them (HHT, HTH, THH), so the probability is 3/7.',
wrong:'3/8 is the unconditional probability and ignores the given condition; conditioning shrinks the sample space from 8 outcomes to 7.'}
];
if (typeof globalThis !== 'undefined') { globalThis.BANK_QUANT3 = BANK_QUANT3; }
