// SAT flashcard deck: formulas, rules and method prompts. front = prompt, back = answer.
// sec: RW | M | G (general/pacing). Keyed to the same eight content domains the engine tracks.
const CARDS = [
// ---------- Math: Algebra ----------
{id:'s001',sec:'M',skill:'m_alg',front:'Slope from two points',back:'Slope = (y2 - y1)/(x2 - x1). Subtract in the same order on top and bottom. A negative slope falls left to right; a zero slope is horizontal and an undefined slope is vertical.'},
{id:'s002',sec:'M',skill:'m_alg',front:'The three forms of a line, and when to use each',back:'Slope-intercept y = mx + b reads off slope and intercept. Point-slope y - y1 = m(x - x1) is fastest from a point. Standard Ax + By = C is best for finding intercepts: set x = 0, then y = 0.'},
{id:'s003',sec:'M',skill:'m_alg',front:'When does a system of two linear equations have no solution?',back:'When the lines are parallel: the x and y coefficients are proportional but the constants are not. Same coefficients and same constant ratio instead means infinitely many solutions, because it is one line written twice.'},
{id:'s004',sec:'M',skill:'m_alg',front:'The one rule that breaks inequalities',back:'Multiplying or dividing both sides by a negative number reverses the inequality sign. Nothing else does. Test one number from your answer back in the original to confirm.'},
{id:'s005',sec:'M',skill:'m_alg',front:'Reading a linear model such as C = 45 + 72h',back:'The constant is the starting value at h = 0; the coefficient is the rate of change per unit. Interpretation questions almost always offer the other number as a trap.'},
{id:'s006',sec:'M',skill:'m_alg',front:'Perpendicular and parallel slopes',back:'Parallel lines share a slope. Perpendicular slopes are negative reciprocals: flip the fraction and change the sign, so 2/3 becomes -3/2. Their product is always -1.'},
{id:'s007',sec:'M',skill:'m_alg',front:'Fastest way to solve a system on the SAT',back:'If a variable has matching or opposite coefficients, add or subtract the equations. If one equation is already solved for a variable, substitute. Then check what the question asked for, which is often x + y rather than x.'},
// ---------- Math: Advanced Math ----------
{id:'s008',sec:'M',skill:'m_adv',front:'Three factoring patterns to recognize instantly',back:'a^2 - b^2 = (a + b)(a - b); a^2 + 2ab + b^2 = (a + b)^2; a^2 - 2ab + b^2 = (a - b)^2. Difference of squares hides inside expressions like x^4 - 16 and inside rational expressions waiting to cancel.'},
{id:'s009',sec:'M',skill:'m_adv',front:'What the discriminant tells you',back:'For ax^2 + bx + c = 0, b^2 - 4ac positive means two real solutions, zero means exactly one, negative means none. Questions that say exactly one solution are asking you to set the discriminant to zero.'},
{id:'s010',sec:'M',skill:'m_adv',front:'Sum and product of the roots',back:'For x^2 + bx + c = 0 the roots sum to -b and multiply to c. It is a fast check after factoring and sometimes answers the question without factoring at all.'},
{id:'s011',sec:'M',skill:'m_adv',front:'Finding the vertex of a parabola',back:'The vertex x-value is -b/(2a); substitute it back for the y-value. In vertex form y = a(x - h)^2 + k the vertex is (h, k), and note the sign flip: x - 3 means h = 3.'},
{id:'s012',sec:'M',skill:'m_adv',front:'Solving an absolute value equation',back:'Split |expression| = k into expression = k and expression = -k, then solve both. Two branches unless k is zero. If the question asks for a sum or a count, you need both.'},
{id:'s013',sec:'M',skill:'m_adv',front:'Exponent rules in one line',back:'Same base multiplied: add exponents. Divided: subtract. Power of a power: multiply. a^(1/n) is the nth root, and a^(m/n) is that root raised to m. A negative exponent means take the reciprocal.'},
{id:'s014',sec:'M',skill:'m_adv',front:'Building an exponential model',back:'y = a(b)^(t/p), where a is the starting amount, b is the growth factor (2 for doubling, 0.5 for halving), and p is the time for one such change. Test the model at one known time before trusting it.'},
{id:'s015',sec:'M',skill:'m_adv',front:'Solving an equation with a square root',back:'Isolate the radical, then square both sides, then check every answer in the original equation. Squaring can introduce a solution that does not actually work.'},
// ---------- Math: Problem-Solving and Data Analysis ----------
{id:'s016',sec:'M',skill:'m_psda',front:'Percent change, and the base it uses',back:'(new - old)/old. The denominator is always the original value. Percent increase then decrease by the same percent never returns to the start: 1.2 x 0.8 = 0.96, a 4 percent loss.'},
{id:'s017',sec:'M',skill:'m_psda',front:'Undoing a percent discount',back:'A 25 percent discount leaves 75 percent, so divide the sale price by 0.75 to recover the original. Never add the percent back to the sale price.'},
{id:'s018',sec:'M',skill:'m_psda',front:'Ratio problems without guessing',back:'Write the parts as 3k and 5k, then use the total or the difference to solve for k. The multiplier k keeps the parts consistent and makes the total easy to set up.'},
{id:'s019',sec:'M',skill:'m_psda',front:'Mean versus median when a set is skewed',back:'Convert a mean to a sum before adding or removing any value, because sums are what change. The median resists outliers; the mean is pulled toward the long tail, so one extreme value lifts the mean above the median.'},
{id:'s020',sec:'M',skill:'m_psda',front:'Conditional probability from a two-way table',back:'When a question says given that or from those who, the named group becomes the denominator, not the table total. Find the row or column first, then the cell inside it.'},
{id:'s021',sec:'M',skill:'m_psda',front:'What a margin of error lets you say',back:'The sample statistic plus and minus the margin gives a plausible interval for the population value, and only for the population that was actually sampled. It never makes the sample figure exact and never reaches a different population.'},
{id:'s022',sec:'M',skill:'m_psda',front:'Reading a line of best fit',back:'The slope is the predicted change in y for each one-unit increase in x; the y-intercept is the predicted value at x = 0. Interpretation traps swap the two or turn a rate into a total.'},
// ---------- Math: Geometry and Trigonometry ----------
{id:'s023',sec:'M',skill:'m_geo',front:'The two special right triangles',back:'45-45-90 sides are 1, 1, and the square root of 2. 30-60-90 sides are 1, the square root of 3, and 2, with the shortest side opposite the 30 degree angle. The larger angle always faces the longer side.'},
{id:'s024',sec:'M',skill:'m_geo',front:'Circle equation in the xy-plane',back:'(x - h)^2 + (y - k)^2 = r^2 has center (h, k) and radius r. The right side is r squared, so take a square root before reporting the radius, and watch the sign: y + 2 means k = -2.'},
{id:'s025',sec:'M',skill:'m_geo',front:'Arc length and sector area',back:'Both are fractions of the whole circle set by the central angle over 360. Arc = (angle/360) x 2 pi r; sector area = (angle/360) x pi r^2.'},
{id:'s026',sec:'M',skill:'m_geo',front:'How scale factors act on length, area and volume',back:'Multiply every length by k and areas multiply by k squared, volumes by k cubed. Tripling the edge of a cube multiplies its volume by 27, not by 3.'},
{id:'s027',sec:'M',skill:'m_geo',front:'SOH CAH TOA, and the cofunction shortcut',back:'Sine is opposite over hypotenuse, cosine adjacent over hypotenuse, tangent opposite over adjacent. For acute angles, sin x = cos(90 - x), which is the identity most complement questions turn on.'},
{id:'s028',sec:'M',skill:'m_geo',front:'Pythagorean triples worth memorizing',back:'3-4-5, 5-12-13, 8-15-17, 7-24-25 and all their multiples. Spotting 9-12-15 as a scaled 3-4-5 saves the arithmetic entirely.'},
// ---------- Reading and Writing: Craft and Structure ----------
{id:'s029',sec:'RW',skill:'rw_cs',front:'Method for a Words in Context blank',back:'Cover the choices, read the sentence, and write your own word in the blank from the surrounding text. Then pick the choice closest to yours. Watch for a signal word such as but, yet, or because that tells you which direction the blank runs.'},
{id:'s030',sec:'RW',skill:'rw_cs',front:'What a Text Structure and Purpose question is really asking',back:'What that sentence does for the text, not what it says. Common jobs: name a problem, introduce a counterexample, set up a contrast, or supply evidence for the claim before it.'},
{id:'s031',sec:'RW',skill:'rw_cs',front:'Method for Cross-Text Connections',back:'Before reading the choices, state in your own words where the two texts disagree and how far Text 2 goes. Most wrong answers either agree with the wrong text or push the disagreement further than the author did.'},
{id:'s032',sec:'RW',skill:'rw_cs',front:'Why the most dramatic word is usually wrong',back:'Precision questions reward the word the evidence actually supports. Choices like abandoned, proved, and never overshoot passages that say complicated, suggests, and rarely.'},
// ---------- Reading and Writing: Information and Ideas ----------
{id:'s033',sec:'RW',skill:'rw_ii',front:'Finding a main idea in a short SAT text',back:'The main idea covers the whole text, not one sentence of it. A choice that is true but only describes a detail is the most common trap; a choice that adds a claim the text never makes is the next.'},
{id:'s034',sec:'RW',skill:'rw_ii',front:'How to attack a Command of Evidence question',back:'Break the claim into its parts and require the choice to hit every part. A choice that supports half the claim is not support, however true it is.'},
{id:'s035',sec:'RW',skill:'rw_ii',front:'Quantitative evidence questions',back:'Read the axis labels, the units, and the row or column headers before the choices. Then check that the choice both reads the data correctly and serves the claim the text is making.'},
{id:'s036',sec:'RW',skill:'rw_ii',front:'Completing an Inferences blank',back:'The blank is the conclusion the text has already built. Finish the thought yourself from the evidence given, and pay attention to the words right before the blank, such as cannot be explained by, which flip what belongs there.'},
{id:'s037',sec:'RW',skill:'rw_ii',front:'The boundary an inference cannot cross',back:'Stay inside the evidence: same population, same time frame, same strength of claim. Words like always, every, and proves rarely survive a passage built on one study.'},
// ---------- Reading and Writing: Standard English Conventions ----------
{id:'s038',sec:'RW',skill:'rw_sec',front:'The test for a comma splice',back:'Cover the punctuation and read each side alone. If both sides are complete sentences, a comma by itself cannot join them. Use a period, a semicolon, or a comma plus and, but, or, so, for, nor, yet.'},
{id:'s039',sec:'RW',skill:'rw_sec',front:'Words that cannot join two sentences',back:'However, therefore, moreover, nevertheless, and in fact are adverbs, not conjunctions. Across two independent clauses they need a semicolon before and a comma after.'},
{id:'s040',sec:'RW',skill:'rw_sec',front:'When a colon is correct',back:'Only after a complete sentence, and only to introduce what explains or lists what came before. If the words before the colon cannot stand alone, the colon is wrong.'},
{id:'s041',sec:'RW',skill:'rw_sec',front:'Restrictive versus nonrestrictive',back:'If removing the element would leave the sentence unable to identify what it means, it is restrictive and takes no commas. If the sentence still identifies its subject without it, set it off with commas on both sides.'},
{id:'s042',sec:'RW',skill:'rw_sec',front:'Never put punctuation here',back:'Between a subject and its verb, and between a verb and its object, no matter how long the subject runs. Strip the modifiers and read the bare sentence to hear it.'},
{id:'s043',sec:'RW',skill:'rw_sec',front:'Subject-verb agreement traps',back:'Cross out prepositional phrases between the subject and the verb. Each, every, either and neither are singular. In an inverted sentence beginning with a phrase, the subject comes after the verb.'},
{id:'s044',sec:'RW',skill:'rw_sec',front:'Its, it is, and the possessive rule',back:'Its is possessive; it is is a contraction. Substitute it is into the sentence: if it does not work, the possessive is correct. The same test settles their, they are, whose and who is.'},
{id:'s045',sec:'RW',skill:'rw_sec',front:'Fixing a dangling modifier',back:'An opening descriptive phrase attaches to whatever subject follows the comma. Ask who or what performed that action, then make that the subject of the main clause.'},
// ---------- Reading and Writing: Expression of Ideas ----------
{id:'s046',sec:'RW',skill:'rw_eoi',front:'Method for a Transitions question',back:'Cover the choices and name the relationship between the two sentences yourself: result, contrast, example, restatement, or sequence. Then take the choice that matches. The sentences decide, never the sound of the word.'},
{id:'s047',sec:'RW',skill:'rw_eoi',front:'The four transition families',back:'Result: therefore, as a result, consequently. Contrast: however, by contrast, nevertheless. Addition or example: moreover, for example, in particular. Restatement: in other words, that is.'},
{id:'s048',sec:'RW',skill:'rw_eoi',front:'How Rhetorical Synthesis is scored',back:'On the stated goal, not on truth. Every choice usually reports something accurate from the notes; only one does the job the goal names. Underline the goal before reading the choices.'},
{id:'s049',sec:'RW',skill:'rw_eoi',front:'Goal words that tell you what to include',back:'Compare needs both sides on the same property. Emphasize significance needs the later outcome. Introduce needs identification for a reader who knows nothing. Explain why needs a cause and its effect together.'},
// ---------- General: pacing and test-day mechanics ----------
{id:'s050',sec:'G',skill:'pacing',front:'Per-question pace on each SAT section',back:'Reading and Writing gives 32 minutes for 27 questions, about 71 seconds each. Math gives 35 minutes for 22 questions, about 95 seconds each. Conventions questions should run well under pace so the longer passages can run over.'},
{id:'s051',sec:'G',skill:'pacing',front:'How the digital SAT adapts',back:'It adapts by module, not by question. Each section has two modules, and your performance on the first decides whether the second is the harder or the easier form. Within a module you can move freely, so answer everything and flag what you want to revisit.'},
{id:'s052',sec:'G',skill:'pacing',front:'Why you should never leave a question blank',back:'There is no penalty for a wrong answer. Eliminate what you can, choose, flag it, and move on. An unanswered question and a wrong one cost the same, but a guess can score.'},
{id:'s053',sec:'G',skill:'pacing',front:'Entering a student-produced response',back:'Grid-ins accept any equivalent form, so 1/2, 0.5 and .5 all count. Negative answers are allowed. Do not enter a percent sign or units, and if the answer repeats, give enough digits to fill the entry.'},
{id:'s054',sec:'G',skill:'pacing',front:'Checkpoint pacing inside a module',back:'Split each module in half and check the clock at the midpoint: about 14 questions of Reading and Writing by 16 minutes, about 11 Math questions by 17 minutes. If you are behind, guess once and keep moving rather than rescuing one question.'}
];
