// LSAT flashcard deck: reasoning patterns, reading method and pacing. front = prompt, back = answer.
// sec: LR | RC | G (general/pacing). Keyed to the twelve skills the engine tracks for the LSAT.
const CARDS = [
// ---------- Logical Reasoning ----------
{id:'l001',sec:'LR',skill:'lsat_lr_struct',front:'How do you tell a premise from a conclusion?',back:'Ask which claim the other one is offered to support. Conclusion indicators are so, therefore, thus, hence, it follows that. Premise indicators are because, since, for, given that. The conclusion is often not the last sentence.'},
{id:'l002',sec:'LR',skill:'lsat_lr_struct',front:'A role of a claim question asks what?',back:'What job the sentence does in the argument, not whether it is true. The usual jobs: the main conclusion, a premise supporting it, an intermediate conclusion, a rival view being rejected, or evidence against a rival view.'},
{id:'l003',sec:'LR',skill:'lsat_lr_struct',front:'What is an intermediate conclusion?',back:'A claim that is supported by a premise and in turn supports the main conclusion. Test it by asking whether anything else in the argument is offered as a reason to believe it. If so, it is not the main conclusion.'},
{id:'l004',sec:'LR',skill:'lsat_lr_concl',front:'Must be true versus most strongly supported',back:'Must be true admits only what the statements guarantee. Most strongly supported admits the best-evidenced choice even if not guaranteed. Read the stem first; the same choices can be right under one and wrong under the other.'},
{id:'l005',sec:'LR',skill:'lsat_lr_concl',front:'Why do quantity words decide inference questions?',back:'All, most, some and none combine in fixed ways. Some is at least one and does not mean not all. Most means more than half. Two most statements about the same group overlap; two some statements need not.'},
{id:'l006',sec:'LR',skill:'lsat_lr_concl',front:'The commonest wrong answer on an inference question',back:'A choice that reverses a conditional. If all A are B, that does not make all B into A. Check the direction of every arrow before you accept a choice.'},
{id:'l007',sec:'LR',skill:'lsat_lr_assum',front:'Necessary versus sufficient assumption',back:'A necessary assumption must hold or the argument collapses; negate it and the argument fails. A sufficient assumption, added to the premises, makes the conclusion follow. Sufficient assumptions are usually much stronger statements.'},
{id:'l008',sec:'LR',skill:'lsat_lr_assum',front:'The negation test',back:'For a necessary assumption, negate each choice. The one whose negation destroys the argument is the answer. If the argument survives the negation, that choice was never required.'},
{id:'l009',sec:'LR',skill:'lsat_lr_assum',front:'Where do assumption gaps usually sit?',back:'Between a premise about one thing and a conclusion about another: bought versus consumed, reported versus occurred, one measure versus overall effect. Name both terms and the gap is the assumption.'},
{id:'l010',sec:'LR',skill:'lsat_lr_flaw',front:'Name the five flaws that recur most',back:'Confusing correlation with causation; sampling that is not representative; treating a necessary condition as sufficient; attacking the person instead of the claim; and presenting two options as the only ones available.'},
{id:'l011',sec:'LR',skill:'lsat_lr_flaw',front:'Why is naming the flaw better than disagreeing?',back:'Flaw answers describe a defect in the reasoning, not a false premise. A choice that says the conclusion is wrong, or that a premise is untrue, is almost always a trap. The answer describes the move, not the content.'},
{id:'l012',sec:'LR',skill:'lsat_lr_flaw',front:'The averaging flaw',back:'Evidence about an average is used to draw a conclusion about a particular group or member. A minority can behave very differently while the average stays put, so the average never impeaches the subgroup.'},
{id:'l013',sec:'LR',skill:'lsat_lr_evid',front:'How do you weaken a causal argument?',back:'Offer an alternative cause, show the effect occurs without the cause, show the cause occurs without the effect, or reverse the direction. Attacking the data collection also works if the data are the whole support.'},
{id:'l014',sec:'LR',skill:'lsat_lr_evid',front:'What makes a strengthener strong?',back:'It closes the specific gap the argument depends on, usually by ruling out the most obvious rival explanation. A choice that supports the topic generally, without touching the link, does nothing.'},
{id:'l015',sec:'LR',skill:'lsat_lr_evid',front:'Watch for the comparison that changed',back:'Before and after arguments assume the two measurements are alike. If the test, the sample, the season or the conditions changed between them, the comparison carries no weight, whatever the numbers say.'},
{id:'l016',sec:'LR',skill:'lsat_lr_prin',front:'How do you apply a principle?',back:'Treat the principle as a conditional. Check that every condition it names is actually satisfied by the case in the answer. A choice that satisfies most of the conditions but not all of them is wrong.'},
{id:'l017',sec:'LR',skill:'lsat_lr_prin',front:'How do you match parallel reasoning?',back:'Match the logical form, not the subject. Diagram the original: what is conditional, what is denied, what is concluded. Valid arguments pair with valid; a flawed original pairs with the same flaw.'},
{id:'l018',sec:'LR',skill:'lsat_lr_expl',front:'What does an explain the discrepancy question want?',back:'A fact consistent with both halves of the puzzle that shows why they can both be true. It does not challenge either half. If a choice denies one of the stated facts, it is not the answer.'},
{id:'l019',sec:'LR',skill:'lsat_lr_expl',front:'Point at issue questions',back:'Find the claim one speaker asserts and the other denies. Both must have a view on it. A claim only one speaker addresses, however central it feels, cannot be the point at issue.'},
// ---------- Reading Comprehension ----------
{id:'l020',sec:'RC',skill:'lsat_rc_main',front:'What should you have after one read of a passage?',back:'The claim, who disagrees, and where the author stands. Detail can be found again; structure cannot be reconstructed without rereading. Read for the shape and let the specifics go.'},
{id:'l021',sec:'RC',skill:'lsat_rc_main',front:'How do you test a main point answer?',back:'It must cover the whole passage and match the author\'s attitude. A choice true of one paragraph is the commonest trap, and a choice stronger than the author\'s own hedging is the second commonest.'},
{id:'l022',sec:'RC',skill:'lsat_rc_stated',front:'What settles a stated information question?',back:'A specific line in the passage. If you cannot point to it, the choice is wrong however reasonable it sounds. Reasonableness is not the standard; the text is.'},
{id:'l023',sec:'RC',skill:'lsat_rc_inf',front:'How far can an inference go?',back:'Only as far as the passage supports. Implied means the passage commits to it; plausible means you supplied a step. Extreme words such as never, only and cannot usually take a choice past what the text will bear.'},
{id:'l024',sec:'RC',skill:'lsat_rc_struct',front:'How do you answer a function question?',back:'Ask what the sentence does for the argument around it. Usually it introduces a rival view, supports a claim, qualifies one, or supplies the example the next claim generalises from.'},
{id:'l025',sec:'RC',skill:'lsat_rc_struct',front:'How do you read tone?',back:'From the modifiers, not the subject. Words such as merely, so far, has yet to, and overstates place the author. An author reporting a dispute at length is often neutral, and neutral is an available answer.'},
{id:'l026',sec:'RC',skill:'lsat_rc_app',front:'What does an application question ask?',back:'You take a principle or pattern from the passage and apply it to a new case. Identify the rule in the passage first, in your own words, and then test each case against it.'},
{id:'l027',sec:'RC',skill:'lsat_rc_app',front:'Comparative reading: what gets tested?',back:'The relationship between the two passages. Whether one generalises and the other instantiates, whether they agree on facts but differ on significance, and what each would say about the other\'s central claim.'},
// ---------- General and pacing ----------
{id:'l028',sec:'G',front:'What is the LSAT scored out of?',back:'120 to 180. Your raw score is the number of questions you answer correctly, with no deduction for wrong answers, so never leave a question blank.'},
{id:'l029',sec:'G',front:'How is the test laid out?',back:'Four 35-minute multiple-choice sections: one Reading Comprehension, two Logical Reasoning, and one unscored variable section that can be either type and can appear anywhere. A 10-minute intermission falls between the second and third sections.'},
{id:'l030',sec:'G',front:'Why does the unscored section matter for strategy?',back:'You cannot identify it, so you must work every section as though it counts. Saving effort for later sections on a guess about which one is experimental is how people lose scored points.'},
{id:'l031',sec:'G',front:'How long is a Reading Comprehension set?',back:'The section holds four sets, each a selection followed by five to eight questions, with three or four single passages and one or no comparative pair. Budget about eight and a half minutes per set including the reading.'},
{id:'l032',sec:'G',front:'What should you do when you are stuck?',back:'Mark it, pick the best remaining choice, and move. A Logical Reasoning question is worth exactly as much as any other, and two minutes spent on a hard one costs you two easier ones at the end of the section.'},
{id:'l033',sec:'G',front:'Is there an essay?',back:'LSAT Argumentative Writing is administered separately online and is unscored. You get 50 minutes in total, 15 for prewriting analysis and 35 for the essay. Law schools read it; no number is attached to it.'}
];
