// ACT flashcard deck: grammar rules, math facts, reading and science method, pacing.
// front = prompt, back = answer. sec: E | M | R | S | G (general/pacing).
// Keyed to the fifteen reporting categories the engine tracks for the ACT.
const CARDS = [
// ---------- English ----------
{id:'a001',sec:'E',skill:'act_e_cse',front:'When do you use a comma before and?',back:'When and joins two independent clauses. If what follows and cannot stand alone as a sentence, leave the comma out: two verbs sharing one subject take no comma between them.'},
{id:'a002',sec:'E',skill:'act_e_cse',front:'Semicolon, colon or dash: which joins what?',back:'A semicolon joins two independent clauses of equal weight. A colon introduces an explanation, list or example and needs an independent clause before it. The ACT tests the semicolon and colon far more often than any other join.'},
{id:'a003',sec:'E',skill:'act_e_cse',front:'How do you punctuate a nonessential phrase?',back:'Commas on both sides, or dashes on both sides, or parentheses on both sides. Never one comma and nothing else, and never a comma paired with a dash. Matching the pair is half the punctuation questions on the section.'},
{id:'a004',sec:'E',skill:'act_e_cse',front:'Its versus it is',back:'Its is possessive and takes no apostrophe. It is always means it is or it has. If you cannot substitute it is, the apostrophe is wrong.'},
{id:'a005',sec:'E',skill:'act_e_cse',front:'How do you find the subject for verb agreement?',back:'Cross out every prepositional phrase between the subject and the verb. A list of factors is singular; the plural noun nearest the verb is usually the trap.'},
{id:'a006',sec:'E',skill:'act_e_cse',front:'What is a dangling modifier?',back:'An opening phrase whose implied subject is not the subject of the main clause. Walking to the station, the rain began puts the rain on the walk. The noun right after the comma must be the one doing the action.'},
{id:'a007',sec:'E',skill:'act_e_cse',front:'When is the past perfect right?',back:'When one past action finished before another past action. Otherwise use the simple past. On the ACT, had is wrong far more often than it is right.'},
{id:'a008',sec:'E',skill:'act_e_kol',front:'The default rule for wordiness',back:'Shortest choice that keeps the meaning and is grammatical. Redundancy is the most tested error of all: annual yearly report, in the year of 1931, both of the two.'},
{id:'a009',sec:'E',skill:'act_e_kol',front:'How do you judge tone?',back:'Match the passage, not your taste. A plain reported narrative rejects choices that praise, dramatise or use inflated vocabulary, and it also rejects choices so clipped that they drop information the sentence needs.'},
{id:'a010',sec:'E',skill:'act_e_kol',front:'What does a precise word choice question want?',back:'The word whose exact meaning fits the sentence, not a near synonym. Opaque, obscure and dense are not interchangeable. Read the sentence for what is actually being claimed.'},
{id:'a011',sec:'E',skill:'act_e_pow',front:'How do you pick a transition?',back:'Work out the relationship between the two sentences first, then choose. However needs a contrast, therefore needs a consequence, for example needs an instance. If the sentences simply continue, no transition may be the answer.'},
{id:'a012',sec:'E',skill:'act_e_pow',front:'Answering a should this sentence be added question',back:'Answer the question the choice asks, not whether the sentence is interesting. Keep it if it supports the paragraph point; delete it if it repeats, digresses or names something the passage never develops.'},
{id:'a013',sec:'E',skill:'act_e_pow',front:'How do you place a sentence?',back:'Find its pronouns and its transitions. A sentence beginning with this rule or with that change must follow the thing it refers to, which usually settles the placement by itself.'},
{id:'a014',sec:'E',skill:'act_e_pow',front:'Questions that state a goal',back:'When the stem says the writer wants to emphasise, introduce or conclude with something, the correct choice does that job even if another choice is more elegant. The stated goal outranks style.'},
// ---------- Mathematics ----------
{id:'a015',sec:'M',skill:'act_m_alg',front:'Slope from two points',back:'Rise over run: the difference of the y values over the difference of the x values, taken in the same order. Parallel lines share a slope; perpendicular slopes multiply to negative one.'},
{id:'a016',sec:'M',skill:'act_m_alg',front:'How do you solve a system fastest?',back:'Substitute when one variable is already isolated, eliminate when coefficients line up. Check the answer choices first: on the ACT it is often quicker to test them than to solve.'},
{id:'a017',sec:'M',skill:'act_m_fun',front:'What does f(g(x)) mean?',back:'Apply g first, then feed the result into f. Composition is not multiplication and is not commutative, so f(g(2)) and g(f(2)) generally differ.'},
{id:'a018',sec:'M',skill:'act_m_fun',front:'Vertex form of a parabola',back:'y = a(x - h)^2 + k has its vertex at (h, k). The sign of a says which way it opens, and the axis of symmetry is x = h.'},
{id:'a019',sec:'M',skill:'act_m_geo',front:'SOHCAHTOA',back:'Sine is opposite over hypotenuse, cosine is adjacent over hypotenuse, tangent is opposite over adjacent. These apply only in a right triangle.'},
{id:'a020',sec:'M',skill:'act_m_geo',front:'The two special right triangles',back:'A 30-60-90 has sides in the ratio 1, root 3, 2. A 45-45-90 has sides in the ratio 1, 1, root 2. Recognising them saves the whole calculation.'},
{id:'a021',sec:'M',skill:'act_m_geo',front:'Circle equation',back:'(x - h)^2 + (y - k)^2 = r^2 gives centre (h, k) and radius r. Note the sign flip: x + 3 means the centre is at negative 3.'},
{id:'a022',sec:'M',skill:'act_m_nq',front:'Exponent rules worth knowing cold',back:'Same base multiplied adds exponents; divided subtracts. A power of a power multiplies. A negative exponent is a reciprocal, and a fractional exponent is a root.'},
{id:'a023',sec:'M',skill:'act_m_nq',front:'What is the imaginary unit?',back:'i is the square root of negative one, so i squared is negative one. Powers of i cycle every four: i, minus one, minus i, one.'},
{id:'a024',sec:'M',skill:'act_m_sp',front:'Mean, median and mode',back:'Mean is the total over the count, median is the middle value in order, mode is the most frequent. Outliers move the mean far more than the median, which is what most questions test.'},
{id:'a025',sec:'M',skill:'act_m_sp',front:'Probability of A or B',back:'Add the probabilities and subtract the overlap. For independent events happening together, multiply. Drawing without replacement changes the denominator on the second draw.'},
{id:'a026',sec:'M',skill:'act_m_ies',front:'Percent change',back:'Difference over original, times one hundred. A rise of 20 percent then a fall of 20 percent does not return you to the start, because the base changed.'},
{id:'a027',sec:'M',skill:'act_m_ies',front:'Pacing on the Math section',back:'45 questions in 50 minutes is about 67 seconds each. The questions run roughly easiest to hardest, so protect the early ones and do not spend three minutes on question 40 while question 12 sits unchecked.'},
// ---------- Reading ----------
{id:'a028',sec:'R',skill:'act_r_kid',front:'What should a first read give you?',back:'Main idea, structure and where the specifics live. Do not try to hold the details; you can return to them. The section gives you about eight and a half minutes per part including reading.'},
{id:'a029',sec:'R',skill:'act_r_kid',front:'How do you handle an EXCEPT question?',back:'Three choices are supported by the passage and one is not. Find each of the three in the text and the remaining one is the answer. This is slow by design, so do it last within the part.'},
{id:'a030',sec:'R',skill:'act_r_cs',front:'How do you answer a word in context question?',back:'Go back and read the sentence with the word blanked out, predict a replacement, then choose. The tested word usually has a common meaning that is wrong here and a secondary meaning that is right.'},
{id:'a031',sec:'R',skill:'act_r_cs',front:'What gives away the author perspective?',back:'Adjectives and qualifiers, not the subject matter. An author can explain a view at length and still signal doubt with a single word such as supposedly, claimed, or as yet unproven.'},
{id:'a032',sec:'R',skill:'act_r_iki',front:'What do paired passages ask?',back:'How the two texts relate: whether one qualifies, extends or contradicts the other, and what each author would say about the other claim. Read each passage separately before answering anything that compares them.'},
// ---------- Science ----------
{id:'a033',sec:'S',skill:'act_s_iod',front:'Where should you start on a Science part?',back:'With the questions, not the introduction. Most items point you to a specific table or figure. Read axis labels, units and column headings before reading a single data value.'},
{id:'a034',sec:'S',skill:'act_s_iod',front:'What does a trend question need?',back:'Direction only, usually. Check the first and last values and one in the middle to catch a rise then fall. Exact numbers are rarely needed for a trend.'},
{id:'a035',sec:'S',skill:'act_s_iod',front:'Interpolation versus extrapolation',back:'Interpolation reads between measured points and is safe. Extrapolation goes beyond them and is only as good as the assumption that the trend continues, which some questions deliberately test.'},
{id:'a036',sec:'S',skill:'act_s_si',front:'How do you spot the controlled variable?',back:'Compare the experiments and find what stayed the same. Whatever differs between two experiments is what they were designed to test, and everything held constant is there to keep that comparison clean.'},
{id:'a037',sec:'S',skill:'act_s_si',front:'What is the control group for?',back:'A baseline showing what happens with no treatment. Without it there is nothing to measure the treated groups against, which is why questions about why a condition was included usually have this answer.'},
{id:'a038',sec:'S',skill:'act_s_esa',front:'How do you handle conflicting viewpoints?',back:'Note what both scientists accept and where exactly they part. Most questions turn on the single point of disagreement, and common ground is the most reliable source of the agree with both answer.'},
{id:'a039',sec:'S',skill:'act_s_esa',front:'What makes new evidence support one viewpoint?',back:'It has to bear on the point in dispute, not on the shared background. The strongest evidence is a comparison in which one proposed cause is present and the other absent.'},
// ---------- General and pacing ----------
{id:'a040',sec:'G',front:'How is the ACT laid out?',back:'English 50 questions in 35 minutes, Mathematics 45 in 50, Reading 36 in 40, and an optional Science section of 40 in 40. That is 171 multiple-choice questions and 2 hours 45 minutes of timed testing.'},
{id:'a041',sec:'G',front:'How many answer choices does the ACT give?',back:'Four, in every section including Mathematics. The older ACT gave five on Math; the enhanced test gives four throughout, so eliminating two choices leaves you a coin flip.'},
{id:'a042',sec:'G',front:'What goes into the Composite score?',back:'The average of English, Mathematics and Reading, rounded to the nearest whole number. Science is scored 1 to 36 and reported, but ACT removed it from the Composite for all testing modes in September 2025.'},
{id:'a043',sec:'G',front:'Are all the questions you see scored?',back:'No. Every section carries embedded unscored field-test questions: 40 of the 50 English count, 41 of 45 Math, 27 of 36 Reading and 34 of 40 Science. You cannot tell which, so answer all of them.'},
{id:'a044',sec:'G',front:'Is there a guessing penalty?',back:'No. Nothing is deducted for a wrong answer, so every blank is a wasted chance. Fill in every bubble, including the ones you never read.'},
{id:'a045',sec:'G',front:'How is the optional Writing test scored?',back:'2 to 12, as the rounded average of four domain scores: Ideas and Analysis, Development and Support, Organization, and Language Use and Conventions. It does not affect the Composite.'}
];
