// Flashcard deck: formulas, rules and strategy prompts. front = prompt, back = answer. sec: Q | V | DI | G (general/pacing)
const CARDS = [
{id:'c001',sec:'Q',skill:'q_rrp',front:'Percent change formula',back:'(new - old) / old x 100%. The base is always the ORIGINAL value.'},
{id:'c002',sec:'Q',skill:'q_rrp',front:'Successive percent changes of +a% then -b%',back:'Multiply the factors: (1 + a/100)(1 - b/100). +20% then -20% = 1.2 x 0.8 = 0.96, a 4% net decrease.'},
{id:'c003',sec:'Q',skill:'q_rrp',front:'Combined work rate for two machines taking a and b hours alone',back:'Add rates: 1/a + 1/b = 1/T, so T = ab/(a + b). Always less than the faster time.'},
{id:'c004',sec:'Q',skill:'q_rrp',front:'Average speed over a trip',back:'Total distance / total time. Never the average of the two speeds unless the times are equal.'},
{id:'c005',sec:'Q',skill:'q_rrp',front:'Ratio multiplier method',back:'If a:b = 3:4, write a = 3k and b = 4k. Any total, difference, or single value pins down k.'},
{id:'c006',sec:'Q',skill:'q_rrp',front:'Mixture setup (concentrations)',back:'Track the pure ingredient: (pure before + pure added) / (total before + total added) = target concentration.'},
{id:'c007',sec:'Q',skill:'q_rrp',front:'Simple vs compound interest',back:'Simple: I = P x r x t. Compound: A = P(1 + r/n)^(nt). Compound exceeds simple after the first period.'},
{id:'c008',sec:'Q',skill:'q_rrp',front:'"x is what percent greater than y" vs "x is what percent of y"',back:'Greater than: (x - y)/y. Of: x/y. Different questions, different answers.'},
{id:'c009',sec:'Q',skill:'q_vof',front:'Number of positive divisors of N',back:'Prime factorize N = p^a x q^b x ... The count is (a+1)(b+1)... For 72 = 2^3 x 3^2: 4 x 3 = 12.'},
{id:'c010',sec:'Q',skill:'q_vof',front:'LCM and GCF from prime factorizations',back:'LCM takes the highest power of each prime; GCF takes the lowest. LCM x GCF = a x b.'},
{id:'c011',sec:'Q',skill:'q_vof',front:'Remainder of a^n divided by m',back:'Reduce a mod m, then find the cycle of powers mod m. 7^25 mod 5: 7 = 2 mod 5; 2, 4, 3, 1 repeats every 4; 25 = 24 + 1, remainder 2.'},
{id:'c012',sec:'Q',skill:'q_vof',front:'When does a fraction terminate as a decimal?',back:'In lowest terms, only if the denominator has no prime factors other than 2 and 5.'},
{id:'c013',sec:'Q',skill:'q_vof',front:'If n^2 is divisible by p^k, what must divide n?',back:'p^(ceil(k/2)). n^2 divisible by 2^3 forces n divisible by 2^2.'},
{id:'c014',sec:'Q',skill:'q_vof',front:'Even/odd rules',back:'even +- even = even; odd +- odd = even; even +- odd = odd; product is odd only if all factors are odd.'},
{id:'c015',sec:'Q',skill:'q_vof',front:'Comparing fractions quickly',back:'Cross-multiply pairs, or convert to decimals to 3 places. Do not eyeball.'},
{id:'c016',sec:'Q',skill:'q_alg',front:'Translate: "3 more than twice a number"',back:'2x + 3. Order of the words matters: "twice (3 more than a number)" is 2(x + 3).'},
{id:'c017',sec:'Q',skill:'q_alg',front:'When does an inequality flip?',back:'When you multiply or divide both sides by a negative. Never multiply by a variable of unknown sign.'},
{id:'c018',sec:'Q',skill:'q_alg',front:'|expression| < k and |expression| > k',back:'< k: -k < expr < k (a band). > k: expr > k OR expr < -k (two rays).'},
{id:'c019',sec:'Q',skill:'q_alg',front:'Discriminant b^2 - 4ac tells you...',back:'> 0: two real roots; = 0: one real root (perfect square); < 0: no real roots.'},
{id:'c020',sec:'Q',skill:'q_alg',front:'Three special products to recognize on sight',back:'(a+b)^2 = a^2 + 2ab + b^2; (a-b)^2 = a^2 - 2ab + b^2; (a+b)(a-b) = a^2 - b^2.'},
{id:'c021',sec:'Q',skill:'q_alg',front:'x + 1/x = 3. What is x^2 + 1/x^2?',back:'Square both sides: x^2 + 2 + 1/x^2 = 9, so x^2 + 1/x^2 = 7. Do not forget the cross term.'},
{id:'c022',sec:'Q',skill:'q_alg',front:'Two equations, two unknowns: when is there NO unique solution?',back:'When one equation is a multiple of the other (same line) or they are parallel. Check independence before trusting "two equations".'},
{id:'c023',sec:'Q',skill:'q_alg',front:'Exponent rules',back:'a^m x a^n = a^(m+n); (a^m)^n = a^(mn); a^m / a^n = a^(m-n); a^0 = 1; a^(-n) = 1/a^n.'},
{id:'c024',sec:'Q',skill:'q_alg',front:'Back-solving: where to start?',back:'Start with B or D (choices are usually ascending). The result tells you which direction to move, so you test at most two more.'},
{id:'c025',sec:'Q',skill:'q_csp',front:'Permutations vs combinations',back:'Order matters: nPr = n!/(n-r)!. Order does not matter: nCr = n!/(r!(n-r)!). Committees are combinations; rankings are permutations.'},
{id:'c026',sec:'Q',skill:'q_csp',front:'"A and B must sit together" in a row of n',back:'Glue A and B into one unit: (n-1)! arrangements x 2 for their internal order.'},
{id:'c027',sec:'Q',skill:'q_csp',front:'P(at least one)',back:'1 - P(none). Almost always faster than adding cases.'},
{id:'c028',sec:'Q',skill:'q_csp',front:'Two overlapping sets formula',back:'Total = A + B - Both + Neither. Subtract "neither" first when it is given.'},
{id:'c029',sec:'Q',skill:'q_csp',front:'Sum of an arithmetic sequence',back:'n x (first + last) / 2. The n-th term is a1 + (n-1)d.'},
{id:'c030',sec:'Q',skill:'q_csp',front:'Mean vs median in a skewed set',back:'The mean is pulled toward the tail (outliers); the median resists. Evenly spaced sets: mean = median = (first + last)/2.'},
{id:'c031',sec:'Q',skill:'q_csp',front:'Standard deviation: what changes it?',back:'Adding a constant to every term: unchanged. Multiplying every term by c: SD multiplies by |c|. Values closer to the mean lower it.'},
{id:'c032',sec:'Q',skill:'q_csp',front:'Averages: first move',back:'Convert to sums. Sum = average x count. Then add, remove, or replace terms with sums.'},
{id:'c033',sec:'V',skill:'v_ac',front:'First step on every Critical Reasoning item',back:'Find the conclusion (therefore, thus, clearly, should). Then the evidence. The gap between them is where the answer lives.'},
{id:'c034',sec:'V',skill:'v_ac',front:'Assumption negation test',back:'Negate the choice. If the argument collapses, that choice is a necessary assumption. If the argument survives, it is not.'},
{id:'c035',sec:'V',skill:'v_ac',front:'Three classic weakeners for a causal claim',back:'Reverse causation, a third factor causing both, or an unrepresentative sample / coincidence.'},
{id:'c036',sec:'V',skill:'v_ac',front:'Evaluate questions: what does the right answer look like?',back:'A question whose YES and NO answers push the conclusion in opposite directions. If both answers leave the argument unchanged, eliminate.'},
{id:'c037',sec:'V',skill:'v_ac',front:'Boldface method',back:'Label every sentence (conclusion, premise, opposing view, background) BEFORE reading the choices. Then match roles, not content.'},
{id:'c038',sec:'V',skill:'v_pc',front:'Paradox / resolve the discrepancy',back:'The right answer makes both facts true at once. Never pick a choice that denies one of the facts.'},
{id:'c039',sec:'V',skill:'v_pc',front:'Plan questions: two things to separate',back:'The goal and the mechanism. A plan fails when the mechanism does not reach the goal or when people respond in ways that defeat it.'},
{id:'c040',sec:'V',skill:'v_pc',front:'Inference / must-be-true standard',back:'Must follow from the text, not merely be likely. Prefer the modest answer over the interesting one. Extreme words are red flags.'},
{id:'c041',sec:'V',skill:'v_st',front:'RC passage map',back:'One phrase per paragraph stating its JOB (raises a view, rejects it, offers an alternative, handles an objection). Read for structure, not memory.'},
{id:'c042',sec:'V',skill:'v_st',front:'Main idea traps',back:'Too narrow (one paragraph), too broad, or the author\'s stance reversed. The answer covers the whole map.'},
{id:'c043',sec:'V',skill:'v_st',front:'Detail questions: correct vs trap',back:'Correct answers paraphrase the text. Traps reuse the passage\'s exact words with a twisted meaning.'},
{id:'c044',sec:'V',skill:'v_inf',front:'"In order to" (function) questions',back:'Describe the ROLE the sentence plays in the argument (concede then rebut, illustrate, qualify), not its content.'},
{id:'c045',sec:'V',skill:'v_st',front:'RC time budget',back:'3 to 4 minutes to read and map, then about 1 minute per question. Long passage set: 6 to 8 minutes total.'},
{id:'c046',sec:'DI',skill:'di_ds',front:'Data Sufficiency answer choices',back:'A: (1) alone. B: (2) alone. C: together only. D: each alone. E: neither, even together.'},
{id:'c047',sec:'DI',skill:'di_ds',front:'AD / BCE grid',back:'Test (1) alone. Sufficient: answer is A or D. Not: B, C, or E. Then test (2) alone. Combine only if both fail alone.'},
{id:'c048',sec:'DI',skill:'di_ds',front:'What does "sufficient" mean for a value question vs a yes/no question?',back:'Value: exactly one value. Yes/no: a definite answer either way; a consistent NO is sufficient.'},
{id:'c049',sec:'DI',skill:'di_ds',front:'Numbers to test in DS',back:'0, 1, negatives, fractions between 0 and 1. Squares hide negatives; products hide zero.'},
{id:'c050',sec:'DI',skill:'di_ds',front:'The two cardinal DS sins',back:'Carrying information from statement (1) into (2), and solving fully instead of testing sufficiency.'},
{id:'c051',sec:'DI',skill:'di_gt',front:'Graphs and tables: first 10 seconds',back:'Title, axes, units, legend, footnotes. Most misses are unit misses (thousands vs units, percent vs percentage points).'},
{id:'c052',sec:'DI',skill:'di_gt',front:'Largest increase vs largest percent increase',back:'Different questions. The tallest bar is not necessarily the largest percent change; divide by the starting value.'},
{id:'c053',sec:'DI',skill:'di_gt',front:'Table Analysis method',back:'Sort by the column the statement is about, verify each statement independently, and watch for totals rows and rounding.'},
{id:'c054',sec:'DI',skill:'di_gt',front:'Graphics Interpretation dropdowns',back:'Read every option before choosing; the options tell you what the statement is testing (percent vs number, slope vs value).'},
{id:'c055',sec:'DI',skill:'di_msr',front:'Multi-Source Reasoning approach',back:'Skim each tab for what it contains, then answer-driven reading. Test each request against every condition; do not stop at the first satisfied rule.'},
{id:'c056',sec:'DI',skill:'di_tpa',front:'Two-Part Analysis: linked vs independent columns',back:'Linked: one system of equations, solve once, place both answers. Independent: solve each column separately. The same value can appear in both.'},
{id:'c057',sec:'DI',skill:'di_gt',front:'When to use the on-screen calculator',back:'Only in Data Insights, only for the final arithmetic. Estimate first; the answer choices are usually spread.'},
{id:'c058',sec:'G',skill:'pacing',front:'Section pace per question',back:'Quant 2:08 (21 Q / 45 min). Verbal 1:57 (23 Q / 45 min). Data Insights 2:15 (20 Q / 45 min).'},
{id:'c059',sec:'G',skill:'pacing',front:'Bail rule',back:'No method after 60 to 75 seconds: pick the best remaining choice, bookmark, move on. Slow-and-wrong costs twice.'},
{id:'c060',sec:'G',skill:'pacing',front:'Review and edit rules (Focus Edition)',back:'Bookmark any question; at the end of each section change up to 3 answers if time remains. Reserve 3 to 5 minutes; do not re-solve from scratch.'},
{id:'c061',sec:'G',skill:'pacing',front:'Score scale',back:'Total 205 to 805 in 10-point steps. Each section 60 to 90. Sections weighted equally. Focus 645 is roughly the old 700.'},
{id:'c062',sec:'G',skill:'pacing',front:'Never leave a question blank because...',back:'Unanswered questions hurt more than wrong ones in the adaptive scoring. Guess and move.'}
];
