# -*- coding: utf-8 -*-
"""Every bank that says it is generated is exactly what its generator writes (INC-0193).

A bank whose header says "Generated by src/mk_bank_X.py" is written by that script, and
the header tells the next person to edit the script rather than the bank. Nothing checked
that anyone did. src/bank_lsat_rc2.js was generated on September 21, 2026 by a script that
stamped no such line, was corrected in place four times over the following week because
nothing said it was generated, and by September 28 its script wrote a bank that differed
on 25 lines. Running the script as its docstring said would have put back garbled choices,
misdirected notes and uneven answer lengths, and the tests would have caught only some.

Two rules, both about a bank having one source:

1. Every bank whose header names a generator is regenerated into a temporary directory and
   compared with the committed file. Any difference fails, whichever side is wrong: an edit
   made to the bank belongs in the generator, and an edit made to the generator that was
   never run has not reached the site.
2. A generator whose default output is a bank that does not name it fails, because that is
   a bank edited by hand with a script beside it that would write over the edits.

Run: python3 src/check_bank_sources.py   (build.py runs it on every build)
"""
import io, os, re, subprocess, sys, tempfile

SRC = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SRC)

# The line bank_emit.write puts in the header each generator hands it. Read from the first
# lines only, so a passage or note that quotes the phrase cannot make a bank look generated.
HEADER = re.compile(r'^// Generated by (src/mk_bank_\w+\.py)\. Edit that file, not this one\.$',
                    re.M)
HEAD_LINES = 5
# How each generator names the bank it writes when run with no argument.
DEFAULT_DEST = re.compile(r"""sys\.argv\[1\] if len\(sys\.argv\) > 1 else ['"](src/bank_\w+\.js)['"]""")


def generated_banks():
    """{bank path: generator path} for every src/bank_*.js whose header names a generator."""
    out = {}
    for name in sorted(os.listdir(SRC)):
        if not (name.startswith('bank_') and name.endswith('.js')):
            continue
        with io.open(os.path.join(SRC, name), encoding='utf-8') as f:
            head = ''.join(f.readline() for _ in range(HEAD_LINES))
        m = HEADER.search(head)
        if m:
            out['src/' + name] = m.group(1)
    return out


def _differing_lines(a, b):
    la, lb = a.split('\n'), b.split('\n')
    return sum(1 for x, y in zip(la, lb) if x != y) + abs(len(la) - len(lb))


def problems():
    """One line per bank with two sources. Empty when every bank has one."""
    out = []
    named = generated_banks()
    for name in sorted(os.listdir(SRC)):
        if not (name.startswith('mk_bank_') and name.endswith('.py')):
            continue
        gen = 'src/' + name
        with io.open(os.path.join(SRC, name), encoding='utf-8') as f:
            text = f.read()
        for dest in DEFAULT_DEST.findall(text):
            if named.get(dest) != gen:
                out.append('%s writes %s when run with no path, and that bank does not say it '
                           'is generated by it, so running the script would write over whatever '
                           'was edited into the bank. Either give the bank the header or make '
                           'the script refuse it.' % (gen, dest))
    if not named:
        out.append('no bank names a generator, so the comparison below would pass vacuously; '
                   'the header pattern in src/check_bank_sources.py no longer matches '
                   'bank_emit.write')
    with tempfile.TemporaryDirectory() as tmp:
        for bank, gen in sorted(named.items()):
            if not os.path.exists(os.path.join(ROOT, gen)):
                out.append('%s names %s, which does not exist' % (bank, gen))
                continue
            dest = os.path.join(tmp, os.path.basename(bank))
            r = subprocess.run([sys.executable, os.path.join(ROOT, gen), dest], cwd=ROOT,
                               capture_output=True, text=True)
            if r.returncode != 0 or not os.path.exists(dest):
                out.append('%s did not run: %s' % (gen, (r.stderr or r.stdout).strip()[-600:]))
                continue
            with io.open(dest, encoding='utf-8') as f:
                made = f.read()
            with io.open(os.path.join(ROOT, bank), encoding='utf-8') as f:
                committed = f.read()
            if made != committed:
                out.append('%s is not what %s writes: %d line(s) differ. Make the change in the '
                           'generator and run it (python3 %s), rather than editing the bank.'
                           % (bank, gen, _differing_lines(made, committed), gen))
    return out


def main():
    bad = problems()
    for line in bad:
        print('ERROR: ' + line, file=sys.stderr)
    if bad:
        return 1
    print('  %d generated banks are exactly what their generators write' % len(generated_banks()))
    return 0


if __name__ == '__main__':
    sys.exit(main())
