// GMAT Focus playbook: the methods behind every skill the engine tracks.
const PLAYBOOK=[
 {skill:'q_rrp',sec:'Q',title:'Rates, ratios, percent',items:['Rate x Time = Distance (or Work). Build an RTD table with one row per mover; fill two cells, solve the third.','Combined work: add rates, never times. Two machines together are always faster than the faster one alone.','Percent change = (new - old)/old. Successive changes multiply: +20% then -20% is x1.2 x 0.8 = 0.96.','Ratio multiplier: if a:b = 3:4, write a = 3k, b = 4k, then use any total or difference to find k.','Mixtures: track the pure ingredient. (acid before + acid added)/(total before + total added).','Average speed = total distance / total time. Never average the speeds.']},
 {skill:'q_vof',sec:'Q',title:'Value, order, factors',items:['Prime factorize first. Divisor count = product of (exponent + 1).','LCM takes the highest power of each prime; GCF takes the lowest. LCM x GCF = product of the two numbers.','Remainder cycles: reduce the base mod n, then find the cycle of powers.','If n^2 is divisible by p^k, n needs p^(ceil(k/2)).','Comparing fractions and decimals: convert everything to decimals to 3 places, or cross-multiply pairs.','Consecutive integers: the average equals the middle term (or the average of the two middle terms).']},
 {skill:'q_alg',sec:'Q',title:'Equalities, inequalities, algebra',items:['Word problems: define variables in words first ("a = number of adult tickets"), translate one sentence at a time, then solve.','"3 more than twice x" = 2x + 3. "Twice (3 more than x)" = 2(x + 3). Word order matters.','Inequalities flip when multiplying or dividing by a negative. Never multiply by a variable of unknown sign.','|expr| < k means -k < expr < k. |expr| > k means expr > k or expr < -k.','Discriminant b^2 - 4ac: zero means one solution, positive two, negative none.','Back-solve from the middle answer choice when the algebra looks messy; plug in numbers when answers contain variables.','Age problems: anchor every phrase to "now" before writing the equation.']},
 {skill:'q_csp',sec:'Q',title:'Counting, sets, series, probability, statistics',items:['Order matters: permutations (slots). Order does not matter: combinations (divide by k!).','"Must sit together": glue them into one unit, arrange units, multiply by internal arrangements.','Probability without replacement: multiply the changing fractions. "At least one" = 1 - P(none).','Two-set overlap: Total = A + B - Both + Neither. Subtract "neither" first.','Averages: always convert to sums. Sum = average x count.','Arithmetic sequence sum = n x (first + last)/2.','Mean vs median: median resists outliers; a skewed set has its mean pulled toward the tail.']},
 {skill:'v_ac',sec:'V',title:'Analysis and critique (critical reasoning)',items:['Find the conclusion first (after "therefore", "thus", "clearly"). Then the evidence. The gap between them is where every question lives.','Assumption: negate the choice; if the argument collapses, that is the assumption.','Strengthen / weaken: attack or defend the gap, not the evidence. Alternative causes, unrepresentative samples, and shifted terms are the big three.','Correlation-to-cause arguments: weaken with reverse causation, third factor, or coincidence.','Evaluate: the right answer is a question whose two possible answers pull the conclusion in opposite directions.','Paradox: the answer makes both facts true at once; never pick something that denies a fact.','Boldface: label each sentence as conclusion, premise, opposing view, or background before reading choices.','Predict the answer before reading the choices. Extreme words ("all", "never", "only") are usually wrong on assumption questions.']},
 {skill:'v_pc',sec:'V',title:'Plan and construct',items:['Identify the goal and the mechanism separately. A plan fails when the mechanism does not lead to the goal, or when people respond in a way that defeats it.','"Most seriously calls into question the plan": look for unintended responses (displacement, substitution, gaming).','"Required for the prediction": often a quantitative threshold hidden in the numbers.','Answers about cost, popularity, or other plans rarely bear on whether this plan works.']},
 {skill:'v_inf',sec:'V',title:'Identify inferred idea',items:['An inference must be true given the text, not merely likely. Prefer the modest answer over the interesting one.','For "complete the argument", the blank is a conclusion the facts already force; not a recommendation.','RC inference: locate the lines, then ask "what follows if this is true?" Reject anything requiring outside knowledge.','Extreme language ("never", "always", "no role") is a red flag unless the passage is equally extreme.']},
 {skill:'v_st',sec:'V',title:'Identify stated idea (RC detail and main idea)',items:['Map the passage: one phrase per paragraph stating its job (raises view, rejects it, offers alternative, addresses objection).','Main idea = the whole map, not the most interesting paragraph. Eliminate answers that are too narrow or misstate the author\'s stance.','Detail questions: find the exact lines and match meaning, not wording. Correct answers paraphrase; traps reuse words.','Function questions ("in order to"): describe the role in the argument, not the content.','Budget: 3 to 4 minutes reading, then about 1 minute per question. Read for structure, not memory.']},
 {skill:'di_ds',sec:'DI',title:'Data sufficiency',items:['Rephrase the question before touching the statements. "Is x > 5?" with x^2 in play means think about negatives.','AD / BCE grid: test (1) alone. If sufficient, answer is A or D; if not, B, C, or E. Then test (2) alone. Only combine if both fail alone.','Never solve completely. Ask only: does this pin down one value (or one yes/no)?','Two equations may be the same line (E). Check independence.','Use the stem\'s constraints (positive, integer) inside each statement.','Value questions: "sufficient" means exactly one value. Yes/no questions: a definite NO is also sufficient.']},
 {skill:'di_gt',sec:'DI',title:'Graphs and tables',items:['Read titles, axes, units, and footnotes before the question. Most misses are unit misses (thousands vs units, percent vs points).','Percent change vs absolute change: the largest bar is not the largest percent.','Sort mentally for medians; compute means only when asked.','Estimate first; choices are usually spread enough that rough arithmetic suffices. Use the calculator only for the final step.']},
 {skill:'di_msr',sec:'DI',title:'Multi-source reasoning',items:['Skim each tab for what it contains (rules vs data vs narrative). Do not read everything up front.','Answer-driven reading: go back to the tab that holds the relevant rule and check each condition in order.','List conditions as a checklist and test each request against all of them; the trap is stopping at the first satisfied rule.']},
 {skill:'di_tpa',sec:'DI',title:'Two-part analysis',items:['Decide if the two parts are independent or linked. Linked parts are one system of equations; solve once, place both answers.','The same value may be correct for both columns; do not assume they must differ.','Confirm both selections against the stem before submitting; a half-right TPA scores zero.']},
 {skill:'pacing',sec:'G',title:'Pacing and review-and-edit',items:['Section pace: Quant 2:08 per question, Verbal 1:57, DI 2:15. Check the clock every 5 questions.','Bail rule: if you have no method after 60 to 75 seconds, choose the best remaining option and bookmark it.','Focus Edition lets you bookmark and change up to 3 answers per section. Reserve 3 to 5 minutes at the end for that pass; do not re-solve from scratch.','Your Dec 2025 pattern: 5 of 6 Quant misses were slow-and-wrong. Time cost more than concepts on those. Practice letting go.']}
];
