// Hostname canonicalisation. The one piece of dynamic code in front of an otherwise
// static site, kept deliberately small.
//
// Why it exists: the apex and www both resolve to this Worker and both served 200 with
// identical content. That split the ranking signal across two hostnames, and because
// localStorage is per origin it meant a consent choice stored on one hostname was
// invisible to the other, which is why the cookie dialog kept reappearing for anyone who
// arrived on www.
//
// Two settings in wrangler.jsonc are load bearing. Removing either one makes this file
// dead code that still looks correct:
//
//   assets.binding "ASSETS"   gives this script env.ASSETS. Requests passed through it
//                             keep html_handling and not_found_handling, so /terms.html
//                             still redirects to /terms and an unknown path still serves
//                             404.html with a 404.
//
//   assets.run_worker_first   true. Without it the asset router answers first and this
//                             script never runs for a path that matches a file, which is
//                             every page on the site. Worse, from compatibility_date
//                             2025-04-01 onward a browser navigation request, the ones
//                             carrying Sec-Fetch-Mode: navigate, is sent straight to
//                             assets as a billing optimisation. A person opening
//                             www.startfromnowhere.com in a browser is exactly the case
//                             this redirect exists to catch, so assets first would have
//                             shipped a redirect that passes a curl test and does nothing
//                             for actual visitors.

// The security headers from _headers, restated here on purpose.
//
// _headers stays the human readable source and still covers the asset path. But
// Cloudflare documents that custom headers from _headers are "not applied to responses
// generated by your Worker code", and names assets.run_worker_first as a case where you
// "will likely need to attach any custom headers you wish to apply directly within that
// Worker script". That is hedged, and the cost of it being true is the whole site losing
// its CSP, HSTS and framing protection silently, which is a far worse outcome than the
// redirect this file exists for. So the worker sets them itself and the result is correct
// whichever way that sentence reads.
//
// Restating a value in two files is normally how the two drift apart. The guard against
// that is src/smoke_redirect.js, which parses the /* block out of _headers and fails if
// this object does not match it exactly. Edit one and the build tells you about the other.
const SECURITY_HEADERS = {
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Cache-Control": "public, max-age=300",
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "Permissions-Policy": "geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()",
  "Content-Security-Policy": "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob:; connect-src 'self' https://ftsqwbzhkzuudogkvoqa.supabase.co; form-action 'self' https://checkout.stripe.com https://billing.stripe.com; frame-ancestors 'none'; base-uri 'self'; object-src 'none'; upgrade-insecure-requests",
};

// Copying a response to edit its headers fails for the null body statuses (204, 304 and
// friends) in some runtimes, and a 304 is the normal answer to a revalidation request on a
// site that sets max-age. Losing those would break caching for everyone, so a failure here
// returns the original response untouched rather than throwing.
function withSecurityHeaders(response) {
  try {
    const out = new Response(response.body, response);
    for (const name of Object.keys(SECURITY_HEADERS)) out.headers.set(name, SECURITY_HEADERS[name]);
    return out;
  } catch (err) {
    return response;
  }
}

const CANONICAL_HOST = "startfromnowhere.com";
const REDIRECT_FROM = "www." + CANONICAL_HOST;

// Pages that existed, were indexed, and were withdrawn. The MCAT and Executive Assessment
// guides came down on 2026-09-18 because their official sources could not be reached to
// re-verify them, but Search Console still showed 302 impressions for the two URLs in the
// following five weeks, the Executive Assessment one at an average position of 9.6. A
// searcher who clicked got the 404 page, which is the whole GMAT trainer. The exams hub
// says which exams are covered and links the rest, which is an honest answer to anyone
// who arrives looking for one we have withdrawn. Remove an entry when its page returns.
const RETIRED = {
  "/exams/mcat/": "/exams/",
  "/exams/executive-assessment/": "/exams/",
};

// Pure, so src/smoke_redirect.js can assert the whole table with no network and no
// runtime. Returns the absolute URL to redirect to, or null to serve normally.
//
// Only the single hostname being consolidated is touched. Previews, workers.dev and any
// future custom domain pass through rather than being pointed at the apex, and the
// comparison is a full equality check on the parsed hostname rather than a prefix or
// substring test, so a lookalike host cannot be used to bounce a visitor off this site.
export function canonicalTarget(requestUrl) {
  let url;
  try {
    url = new URL(requestUrl);
  } catch (err) {
    return null;
  }
  const host = url.hostname.toLowerCase();
  if (host !== REDIRECT_FROM && host !== CANONICAL_HOST) return null;
  const path = url.pathname.endsWith("/") ? url.pathname : url.pathname + "/";
  if (Object.prototype.hasOwnProperty.call(RETIRED, path)) {
    return "https://" + CANONICAL_HOST + RETIRED[path] + url.search;
  }
  if (host !== REDIRECT_FROM) return null;
  url.protocol = "https:";
  url.hostname = CANONICAL_HOST;
  url.port = "";
  // href carries pathname and search through unchanged, which is what preserves deep
  // links and utm parameters. A fragment never reaches the server, so there is none to
  // preserve here; the browser reattaches it after the redirect.
  return url.href;
}

export default {
  async fetch(request, env) {
    const target = canonicalTarget(request.url);
    // 301 and not 302. The move is permanent, and only a permanent redirect consolidates
    // the ranking signal onto the apex.
    if (target !== null) {
      return withSecurityHeaders(
        new Response(null, { status: 301, headers: { Location: target } })
      );
    }
    return withSecurityHeaders(await env.ASSETS.fetch(request));
  },
};

export { SECURITY_HEADERS };
